# Runs graphics_class_names.m in R2025b and writes the tables the MATLAB dialect reads a graphics
# object's names (open item 82) and set(h)'s words (open item 41) from: JgsGraphicsProperties.R2025bNames.cs.
param(
    [string]$Matlab = "C:\Program Files\MATLAB\R2025b\bin\matlab.exe",
    [string]$Recorded = ""
)

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$repo = Resolve-Path (Join-Path $here "..\..\..")
$out = Join-Path $repo "src\JGraph.Scripting\Jgs\JgsGraphicsProperties.R2025bNames.cs"

if ($Recorded -eq "") {
    $Recorded = Join-Path $env:TEMP "graphics_class_names.txt"
    & $Matlab -noFigureWindows -sd $here -batch graphics_class_names 2>&1 > $Recorded
}

$byClass = [ordered]@{}
$words = New-Object System.Collections.Generic.List[string]
foreach ($row in Get-Content $Recorded) {
    # At most four fields: a word can be a bar (the | marker).
    $parts = $row -split '\|', 4
    if ($parts.Count -ne 4) { continue }
    if ($parts[0] -eq "SET") {
        $text = $parts[3].Replace('\', '\\').Replace('"', '\"').Replace("`t", '\t')
        $words.Add("        (""$($parts[1])"", ""$($parts[2])"", ""$text""),")
        continue
    }
    # The _I twins are the classes' internal storage; no model property is named like one.
    if ($parts[2].EndsWith('_I')) { continue }
    if (-not $byClass.Contains($parts[0])) { $byClass[$parts[0]] = New-Object System.Collections.Generic.List[string] }
    # A hidden property answers when named and is left out of get(h): marked with a leading ~.
    $byClass[$parts[0]].Add($(if ($parts[3] -eq "1") { "~" + $parts[2] } else { $parts[2] }))
}

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// <auto-generated>")
$lines.Add("// Written by tools/matlab-checklist/graphics-probes/gen_graphics_class_names.ps1 from R2025b's")
$lines.Add("// metaclass of each graphics class: every property with public get access; a hidden one starts with ~.")
$lines.Add("// </auto-generated>")
$lines.Add("")
$lines.Add("namespace JGraph.Scripting.Jgs;")
$lines.Add("")
$lines.Add("internal static partial class JgsGraphicsProperties")
$lines.Add("{")
$lines.Add("    private static (string Class, string Names)[] R2025bNameRows =>")
$lines.Add("    [")
foreach ($class in ($byClass.Keys | Sort-Object)) {
    $names = ($byClass[$class] | Sort-Object { $_.TrimStart('~') } -Unique) -join ' '
    $lines.Add("        (""$class"",")
    # Wrap the names to keep the lines short.
    $chunk = ""
    $pieces = New-Object System.Collections.Generic.List[string]
    foreach ($name in ($names -split ' ')) {
        if (($chunk.Length + $name.Length + 1) -gt 88) { $pieces.Add($chunk); $chunk = "" }
        $chunk = if ($chunk -eq "") { $name } else { "$chunk $name" }
    }
    if ($chunk -ne "") { $pieces.Add($chunk) }
    for ($i = 0; $i -lt $pieces.Count; $i++) {
        $tail = if ($i -lt $pieces.Count - 1) { " "" +" } else { """)," }
        $lines.Add("            """ + $pieces[$i] + $tail)
    }
}
$lines.Add("    ];")
$lines.Add("")
$lines.Add("    /// <summary>The words R2025b's set(h) gives each property that takes some, tab-separated.</summary>")
$lines.Add("    private static (string Class, string Property, string Words)[] R2025bSetWordRows =>")
$lines.Add("    [")
foreach ($row in $words) { $lines.Add($row) }
$lines.Add("    ];")
$lines.Add("}")

$utf8 = New-Object System.Text.UTF8Encoding $true
[IO.File]::WriteAllText($out, ($lines -join "`n") + "`n", $utf8)
"wrote $out ($($byClass.Count) classes, $($words.Count) word rows)"
