"""Writes JgsGraphicsProperties.R2025bDefaults.cs from recorded/graphics_missing_defaults.txt.

Each recorded row is kind|name|class|size|value: R2025b's value of a name its get(h) lists and this
build's model lacked (open item 88). A row becomes a default the MATLAB dialect answers for that
name until a script writes one. Left out: a value that is an object or a table (rendered '?'), a
value that depends on the data or the layout rather than being the class's own (a title's Position
and Extent, a ruler's MinorTickValues, a quiver's ScaleFactor), and an integer class.
"""

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
OUT = REPO / "src" / "JGraph.Scripting" / "Jgs" / "JgsGraphicsProperties.R2025bDefaults.cs"

PRIMITIVE = "matlab.graphics.primitive."
CHART = "matlab.graphics.chart.primitive."
SHAPE = "matlab.graphics.shape."

CLASS_OF = {
    "figure": "matlab.ui.Figure",
    "axes": "matlab.graphics.axis.Axes",
    "line": CHART + "Line",
    "text": PRIMITIVE + "Text",
    "title": PRIMITIVE + "Text",
    "patch": PRIMITIVE + "Patch",
    "image": PRIMITIVE + "Image",
    "scatter": CHART + "Scatter",
    "bar": CHART + "Bar",
    "hggroup": PRIMITIVE + "Group",
    "hgtransform": PRIMITIVE + "Transform",
    "stem": CHART + "Stem",
    "stairs": CHART + "Stair",
    "quiver": CHART + "Quiver",
    "contour": CHART + "Contour",
    "rectangle": PRIMITIVE + "Rectangle",
    "xline": "matlab.graphics.chart.decoration.ConstantLine",
    "animatedline": "matlab.graphics.animation.AnimatedLine",
    "legend": "matlab.graphics.illustration.Legend",
    "ruler": "matlab.graphics.axis.decorator.NumericRuler",
    "histogram2": CHART + "Histogram2",
    "bubblechart": CHART + "BubbleChart",
    "boxchart": CHART + "BoxChart",
    "heatmap": "matlab.graphics.chart.HeatmapChart",
    "polaraxes": "matlab.graphics.axis.PolarAxes",
    "textbox": SHAPE + "TextBox",
    "arrow": SHAPE + "Arrow",
    "annline": SHAPE + "Line",
    "ellipse": SHAPE + "Ellipse",
    "doublearrow": SHAPE + "DoubleEndArrow",
    "textarrow": SHAPE + "TextArrow",
    "uiaxes": "matlab.ui.control.UIAxes",
}

COMPUTED = {
    ("title", "Position"), ("title", "Extent"), ("ruler", "MinorTickValues"), ("quiver", "ScaleFactor"),
}


def literal(cls, size, value):
    """The C# expression for a recorded value, or None for one this table does not hold."""
    if value == "?" or cls not in ("char", "double", "logical", "string", "matlab.lang.OnOffSwitchState"):
        return None
    if cls in ("char", "matlab.lang.OnOffSwitchState"):
        return 'JgsValue.Str("' + value.replace("\\", "\\\\").replace('"', '\\"') + '")'
    if cls == "string":
        return "EmptyStringRow()" if size == "[1 0]" else None
    if size == "[0 0]":
        return "JgsEmpty.Zero()"
    numbers = value.strip("[]").split()
    if len(numbers) == 1:
        return f"JgsValue.Number({numbers[0]})"
    return "Row(" + ", ".join(numbers) + ")"


def main():
    rows = []
    recorded = HERE / "recorded" / "graphics_missing_defaults.txt"
    for line in recorded.read_text(encoding="utf-8-sig").splitlines():
        parts = line.split("|", 4)
        if len(parts) != 5 or parts[2] == "ERR" or (parts[0], parts[1]) in COMPUTED:
            continue
        kind, name, cls, size, value = parts
        expression = literal(cls, size, value)
        if expression is None:
            continue
        row = (CLASS_OF[kind], name, expression)
        if all((r[0], r[1]) != row[:2] for r in rows):
            rows.append(row)

    lines = [
        "// <auto-generated>",
        "// Written by tools/matlab-checklist/graphics-probes/gen_graphics_defaults.py from R2025b's value of",
        "// each name get(h) lists that this build's model lacked (open item 88).",
        "// </auto-generated>",
        "",
        "namespace JGraph.Scripting.Jgs;",
        "",
        "internal static partial class JgsGraphicsProperties",
        "{",
        "    /// <summary>R2025b's own value of a name the model lacks, by class: answered until a script writes one.</summary>",
        "    private static (string Class, string Name, Func<JgsValue> Value)[] R2025bDefaultRows =>",
        "    [",
    ]
    for cls, name, expression in sorted(rows):
        lines.append(f'        ("{cls}", "{name}", () => {expression}),')
    lines += ["    ];", "}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8-sig")
    print(f"wrote {OUT} ({len(rows)} defaults)")


if __name__ == "__main__":
    sys.exit(main())
