// <auto-generated> tools/devices/gen-gatt-names.py from R2025b's blelib name tables; do not edit. </auto-generated>
namespace JGraph.Devices.Bluetooth;

public static partial class GattNames
{
    /// <summary>The standard services and their characteristics, in R2025b's order.</summary>
    private static readonly GattService[] StandardServices =
    [
        new("Alert Notification Service", "1811", [new("Supported New Alert Category", "2A47"), new("New Alert", "2A46"), new("Supported Unread Alert Category", "2A48"), new("Unread Alert Status", "2A45"), new("Alert Notification Control Point", "2A44")]),
        new("Automation IO", "1815", [new("Digital", "2A56"), new("Analog", "2A58"), new("Aggregate", "2A5A")]),
        new("Battery Service", "180F", [new("Battery Level", "2A19")]),
        new("Blood Pressure", "1810", [new("Blood Pressure Measurement", "2A35"), new("Intermediate Cuff Pressure", "2A36"), new("Blood Pressure Feature", "2A49")]),
        new("Body Composition", "181B", [new("Body Composition Feature", "2A9B"), new("Body Composition Measurement", "2A9C")]),
        new("Bond Management Service", "181E", [new("Bond Management Control Point", "2AA4"), new("Bond Management Features", "2AA5")]),
        new("Continuous Glucose Monitoring", "181F", [new("CGM Measurement", "2AA7"), new("CGM Feature", "2AA8"), new("CGM Status", "2AA9"), new("CGM Session Start Time", "2AAA"), new("CGM Session Run Time", "2AAB"), new("Record Access Control Point", "2A52"), new("CGM Specific Ops Control Point", "2AAC")]),
        new("Current Time Service", "1805", [new("Current Time", "2A2B"), new("Local Time Information", "2A0F"), new("Reference Time Information", "2A14")]),
        new("Cycling Power", "1818", [new("Cycling Power Measurement", "2A63"), new("Cycling Power Feature", "2A65"), new("Sensor Location", "2A5D"), new("Cycling Power Vector", "2A64"), new("Cycling Power Control Point", "2A66")]),
        new("Cycling Speed and Cadence", "1816", [new("CSC Measurement", "2A5B"), new("CSC Feature", "2A5C"), new("Sensor Location", "2A5D"), new("SC Control Point", "2A55")]),
        new("Device Information", "180A", [new("Manufacturer Name String", "2A29"), new("Model Number String", "2A24"), new("Serial Number String", "2A25"), new("Hardware Revision String", "2A27"), new("Firmware Revision String", "2A26"), new("Software Revision String", "2A28"), new("System ID", "2A23"), new("IEEE 11073-20601 Regulatory Certification Data List", "2A2A"), new("PnP ID", "2A50")]),
        new("Environmental Sensing", "181A", [new("Descriptor Value Changed", "2A7D"), new("Apparent Wind Direction", "2A73"), new("Apparent Wind Speed", "2A72"), new("Dew Point", "2A7B"), new("Elevation", "2A6C"), new("Gust Factor", "2A74"), new("Heat Index", "2A7A"), new("Humidity", "2A6F"), new("Irradiance", "2A77"), new("Pollen Concentration", "2A75"), new("Rainfall", "2A78"), new("Pressure", "2A6D"), new("Temperature", "2A6E"), new("True Wind Direction", "2A71"), new("True Wind Speed", "2A70"), new("UV Index", "2A76"), new("Wind Chill", "2A79"), new("Barometric Pressure Trend", "2AA3"), new("Magnetic Declination", "2A2C"), new("Magnetic Flux Density - 2D", "2AA0"), new("Magnetic Flux Density - 3D", "2AA1")]),
        new("Fitness Machine", "1826", [new("Fitness Machine Feature", "2ACC"), new("Treadmill Data", "2ACD"), new("Cross Trainer Data", "2ACE"), new("Step Climber Data", "2ACF"), new("Stair Climber Data", "2AD0"), new("Rower Data", "2AD1"), new("Indoor Bike Data", "2AD2"), new("Training Status", "2AD3"), new("Supported Speed Range", "2AD4"), new("Supported Inclination Range", "2AD5"), new("Supported Resistance Level Range", "2AD6"), new("Supported Power Range", "2AD8"), new("Supported Heart Rate Range", "2AD7"), new("Fitness Machine Control Point", "2AD9"), new("Fitness Machine Status", "2ADA")]),
        new("Generic Access", "1800", [new("Device Name", "2A00"), new("Appearance", "2A01"), new("Peripheral Privacy Flag", "2A02"), new("Reconnection Address", "2A03"), new("Peripheral Preferred Connection Parameters", "2A04"), new("Central Address Resolution", "2AA6")]),
        new("Generic Attribute", "1801", [new("Service Changed", "2A05")]),
        new("Glucose", "1808", [new("Glucose Measurement", "2A18"), new("Glucose Measurement Context", "2A34"), new("Glucose Feature", "2A51"), new("Record Access Control Point", "2A52")]),
        new("Health Thermometer", "1809", [new("Temperature Measurement", "2A1C"), new("Temperature Type", "2A1D"), new("Intermediate Temperature", "2A1E"), new("Measurement Interval", "2A21")]),
        new("Heart Rate", "180D", [new("Heart Rate Measurement", "2A37"), new("Body Sensor Location", "2A38"), new("Heart Rate Control Point", "2A39")]),
        new("HTTP Proxy", "1823", [new("URI", "2AB6"), new("HTTP Headers", "2AB7"), new("HTTP Entity Body", "2AB9"), new("HTTP Control Point", "2ABA"), new("HTTP Status Code", "2AB8"), new("HTTPS Security", "2ABB")]),
        new("Human Interface Device", "1812", [new("Protocol Mode", "2A4E"), new("Report", "2A4D"), new("Report Map", "2A4B"), new("Boot Keyboard Input Report", "2A22"), new("Boot Keyboard Output Report", "2A32"), new("Boot Mouse Input Report", "2A33"), new("HID Information", "2A4A"), new("HID Control Point", "2A4C")]),
        new("Immediate Alert", "1802", [new("Alert Level", "2A06")]),
        new("Indoor Positioning", "1821", [new("Indoor Positioning Configuration", "2AAD"), new("Latitude", "2AAE"), new("Longitude", "2AAF"), new("Local North Coordinate", "2AB0"), new("Local East Coordinate", "2AB1"), new("Floor Number", "2AB2"), new("Altitude", "2AB3"), new("Uncertainty", "2AB4"), new("Location Name", "2AB5")]),
        new("Insulin Delivery", "183A", [new("IDD Status Changed", "2B20"), new("IDD Status", "2B21"), new("IDD Annunciation Status", "2B22"), new("IDD Features", "2B23"), new("IDD Status Reader Control Point", "2B24"), new("IDD Command Control Point", "2B25"), new("IDD Command Data", "2B26"), new("IDD Record Access Control Point", "2B27"), new("IDD History Data", "2B28")]),
        new("Internet Protocol Support Service", "1820", []),
        new("Link Loss", "1803", [new("Alert Level", "2A06")]),
        new("Location and Navigation", "1819", [new("LN Feature", "2A6A"), new("Location and Speed Characteristic", "2A67"), new("Position Quality", "2A69"), new("LN Control Point", "2A6B"), new("Navigation", "2A68")]),
        new("Mesh Provisioning Service", "1827", [new("Mesh Provisioning Data In", "2ADB"), new("Mesh Provisioning Data Out", "2ADC")]),
        new("Mesh Proxy Service", "1828", [new("Mesh Proxy Data In", "2ADD"), new("Mesh Proxy Data Out", "2ADE")]),
        new("Next DST Change Service", "1807", [new("Time with DST", "2A11")]),
        new("Object Transfer Service", "1825", [new("OTS Feature", "2ABD"), new("Object Name", "2ABE"), new("Object Type", "2ABF"), new("Object Size", "2AC0"), new("Object First-Created", "2AC1"), new("Object Last-Modified", "2AC2"), new("Object ID", "2AC3"), new("Object Properties", "2AC4"), new("Object Action Control Point", "2AC5"), new("Object List Control Point", "2AC6"), new("Object List Filter", "2AC7"), new("Object Changed", "2AC8")]),
        new("Phone Alert Status Service", "180E", [new("Alert Status", "2A3F"), new("Ringer Setting", "2A41"), new("Ringer Control point", "2A40")]),
        new("Pulse Oximeter Service", "1822", [new("PLX Spot-Check Measurement", "2A5E"), new("PLX Continuous Measurement Characteristic", "2A5F"), new("PLX Features", "2A60"), new("Record Access Control Point", "2A52")]),
        new("Reconnection Configuration", "1829", [new("RC Feature", "2B1D"), new("RC Settings", "2B1E"), new("Reconnection Configuration Control Point", "2B1F")]),
        new("Reference Time Update Service", "1806", [new("Time Update Control Point", "2A16"), new("Time Update State", "2A17")]),
        new("Running Speed and Cadence", "1814", [new("RSC Measurement", "2A53"), new("RSC Feature", "2A54"), new("Sensor Location", "2A5D"), new("SC Control Point", "2A55")]),
        new("Scan Parameters", "1813", [new("Scan Interval Window", "2A4F"), new("Scan Refresh", "2A31")]),
        new("Transport Discovery", "1824", [new("TDS Control Point", "2ABC")]),
        new("Tx Power", "1804", [new("Tx Power Level", "2A07")]),
        new("User Data", "181C", [new("First Name", "2A8A"), new("Last Name", "2A90"), new("Email Address", "2A87"), new("Age", "2A80"), new("Date of Birth", "2A85"), new("Gender", "2A8C"), new("Weight", "2A98"), new("Height", "2A8E"), new("VO2 Max", "2A96"), new("Heart Rate Max", "2A8D"), new("Resting Heart Rate", "2A92"), new("Maximum Recommended Heart Rate", "2A91"), new("Aerobic Threshold", "2A7F"), new("Anaerobic Threshold", "2A83"), new("Sport Type for Aerobic and Anaerobic Thresholds", "2A93"), new("Date of Threshold Assessment", "2A86"), new("Waist Circumference", "2A97"), new("Hip Circumference", "2A8F"), new("Fat Burn Heart Rate Lower Limit", "2A88"), new("Fat Burn Heart Rate Upper Limit", "2A89"), new("Aerobic Heart Rate Lower Limit", "2A7E"), new("Aerobic Heart Rate Upper Limit", "2A84"), new("Anaerobic Heart Rate Lower Limit", "2A81"), new("Anaerobic Heart Rate Upper Limit", "2A82"), new("Five Zone Heart Rate Limits", "2A8B"), new("Three Zone Heart Rate Limits", "2A94"), new("Two Zone Heart Rate Limit", "2A95"), new("Database Change Increment", "2A99"), new("User Index", "2A9A"), new("User Control Point", "2A9F"), new("Language", "2AA2")]),
        new("Weight Scale", "181D", [new("Weight Scale Feature", "2A9E"), new("Weight Measurement", "2A9D")]),
    ];

    /// <summary>The vendor services R2025b names.</summary>
    private static readonly GattService[] CustomServices =
    [
        new("Thingy Configuration Service", "EF680100-9B35-4933-9B10-52FFA9740042", [new("Device Name", "EF680101-9B35-4933-9B10-52FFA9740042"), new("Advertising Parameters", "EF680102-9B35-4933-9B10-52FFA9740042"), new("Connection Parameters", "EF680104-9B35-4933-9B10-52FFA9740042"), new("Eddystone URL", "EF680105-9B35-4933-9B10-52FFA9740042"), new("Cloud Token", "EF680106-9B35-4933-9B10-52FFA9740042"), new("Firmware Version", "EF680107-9B35-4933-9B10-52FFA9740042"), new("MTU Request", "EF680108-9B35-4933-9B10-52FFA9740042"), new("NFC Tag Content", "EF680109-9B35-4933-9B10-52FFA9740042")]),
        new("Weather Station Service", "EF680200-9B35-4933-9B10-52FFA9740042", [new("Temperature", "EF680201-9B35-4933-9B10-52FFA9740042"), new("Pressure", "EF680202-9B35-4933-9B10-52FFA9740042"), new("Humidity", "EF680203-9B35-4933-9B10-52FFA9740042"), new("Air Quality", "EF680204-9B35-4933-9B10-52FFA9740042"), new("Color", "EF680205-9B35-4933-9B10-52FFA9740042"), new("Configuration", "EF680206-9B35-4933-9B10-52FFA9740042")]),
        new("User Interface Service", "EF680300-9B35-4933-9B10-52FFA9740042", [new("LED", "EF680301-9B35-4933-9B10-52FFA9740042"), new("Button", "EF680302-9B35-4933-9B10-52FFA9740042"), new("EXT Pin", "EF680303-9B35-4933-9B10-52FFA9740042")]),
        new("Motion Service", "EF680400-9B35-4933-9B10-52FFA9740042", [new("Configuration", "EF680401-9B35-4933-9B10-52FFA9740042"), new("Tap", "EF680402-9B35-4933-9B10-52FFA9740042"), new("Orientation", "EF680403-9B35-4933-9B10-52FFA9740042"), new("Quaternion", "EF680404-9B35-4933-9B10-52FFA9740042"), new("Step Counter", "EF680405-9B35-4933-9B10-52FFA9740042"), new("Raw Data", "EF680406-9B35-4933-9B10-52FFA9740042"), new("Euler", "EF680407-9B35-4933-9B10-52FFA9740042"), new("Rotation Matrix", "EF680408-9B35-4933-9B10-52FFA9740042"), new("Heading", "EF680409-9B35-4933-9B10-52FFA9740042"), new("Gravity", "EF68040A-9B35-4933-9B10-52FFA9740042")]),
        new("Sound Service", "EF680500-9B35-4933-9B10-52FFA9740042", [new("Configuration", "EF680501-9B35-4933-9B10-52FFA9740042"), new("Speaker Data", "EF680502-9B35-4933-9B10-52FFA9740042"), new("Speaker Status", "EF680503-9B35-4933-9B10-52FFA9740042"), new("Microphone", "EF680504-9B35-4933-9B10-52FFA9740042")]),
        new("Secure DFU Service", "FE59", [new("DFU Control Point", "8EC90003-F315-4F60-9FB8-838830DAEA50")]),
    ];

    /// <summary>The standard descriptors, in R2025b's order.</summary>
    private static readonly GattName[] StandardDescriptors =
    [
        new("Characteristic Aggregate Format", "2905"),
        new("Characteristic Extended Properties", "2900"),
        new("Characteristic Presentation Format", "2904"),
        new("Characteristic User Description", "2901"),
        new("Client Characteristic Configuration", "2902"),
        new("Environmental Sensing Configuration", "290B"),
        new("Environmental Sensing Measurement", "290C"),
        new("Environmental Sensing Trigger Setting", "290D"),
        new("External Report Reference", "2907"),
        new("Number of Digitals", "2909"),
        new("Report Reference", "2908"),
        new("Server Characteristic Configuration", "2903"),
        new("Time Trigger Setting", "290E"),
        new("Valid Range", "2906"),
        new("Value Trigger Setting", "290A"),
    ];
}
