using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using JGraph.Core.Model;
using JGraph.Core.Undo;
using JGraph.Interaction.Editing;

namespace JGraph.Controls.Inspector;

/// <summary>
/// A VS-style property inspector for <see cref="GraphObject"/>s. Rows are generated by reflection
/// through <see cref="EditablePropertyFactory"/> and grouped by category; every committed edit is
/// recorded on the attached <see cref="Core.Undo.UndoStack"/> so property changes are undoable.
/// </summary>
public partial class PropertyInspectorControl : UserControl
{
    /// <summary>Identifies the <see cref="Target"/> dependency property.</summary>
    public static readonly DependencyProperty TargetProperty = DependencyProperty.Register(
        nameof(Target),
        typeof(GraphObject),
        typeof(PropertyInspectorControl),
        new PropertyMetadata(null, OnTargetChanged));

    private List<PropertyRowViewModel> _rows = new();

    public PropertyInspectorControl()
    {
        InitializeComponent();
    }

    /// <summary>The object being inspected, or null for the empty state.</summary>
    public GraphObject? Target
    {
        get => (GraphObject?)GetValue(TargetProperty);
        set => SetValue(TargetProperty, value);
    }

    /// <summary>The undo stack committed edits are recorded on (typically the figure control's).</summary>
    public UndoStack? UndoStack { get; set; }

    private static void OnTargetChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) =>
        ((PropertyInspectorControl)d).Rebuild();

    private void Rebuild()
    {
        foreach (PropertyRowViewModel row in _rows)
        {
            row.Dispose();
        }

        _rows = new List<PropertyRowViewModel>();

        GraphObject? target = Target;
        if (target is null)
        {
            HeaderType.Text = "Properties";
            HeaderName.Text = string.Empty;
            EmptyHint.Visibility = Visibility.Visible;
            Rows.ItemsSource = null;
            return;
        }

        foreach (EditableProperty property in EditablePropertyFactory.Describe(target))
        {
            _rows.Add(new PropertyRowViewModel(target, property, UndoStack));
        }

        HeaderType.Text = target.GetType().Name;
        HeaderName.Text = target.Name;
        EmptyHint.Visibility = Visibility.Collapsed;

        var view = new ListCollectionView(_rows);
        view.GroupDescriptions.Add(new PropertyGroupDescription(nameof(PropertyRowViewModel.Category)));
        Rows.ItemsSource = view;
    }

    /// <summary>Commits a text editor on Enter and reverts it on Escape.</summary>
    private void OnEditorTextBoxKeyDown(object sender, KeyEventArgs e)
    {
        if (sender is not TextBox box)
        {
            return;
        }

        if (e.Key == Key.Enter)
        {
            box.GetBindingExpression(TextBox.TextProperty)?.UpdateSource();
            e.Handled = true;
        }
        else if (e.Key == Key.Escape)
        {
            box.GetBindingExpression(TextBox.TextProperty)?.UpdateTarget();
            e.Handled = true;
        }
    }
}
