using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Input;
using JGraph.Core.Model;
using JGraph.Core.Undo;
using JGraph.Interaction.Editing;

namespace JGraph.Controls.Inspector;

/// <summary>
/// A VS-style property inspector for <see cref="GraphObject"/>s. Rows are generated by reflection
/// through <see cref="EditablePropertyFactory"/> and grouped by category; every committed edit is
/// recorded on the attached <see cref="Core.Undo.UndoStack"/> so property changes are undoable.
/// </summary>
public partial class PropertyInspectorControl : UserControl
{
    /// <summary>Identifies the <see cref="Target"/> dependency property.</summary>
    public static readonly DependencyProperty TargetProperty = DependencyProperty.Register(
        nameof(Target),
        typeof(GraphObject),
        typeof(PropertyInspectorControl),
        new PropertyMetadata(null, OnTargetChanged));

    private List<PropertyRowViewModel> _rows = new();

    /// <summary>The header row of each composite, keyed by the group name its children carry.</summary>
    private Dictionary<string, PropertyRowViewModel> _headers = new(StringComparer.Ordinal);

    private ListCollectionView? _view;

    public PropertyInspectorControl()
    {
        InitializeComponent();
    }

    /// <summary>The object being inspected, or null for the empty state.</summary>
    public GraphObject? Target
    {
        get => (GraphObject?)GetValue(TargetProperty);
        set => SetValue(TargetProperty, value);
    }

    /// <summary>The undo stack committed edits are recorded on (typically the figure control's).</summary>
    public UndoStack? UndoStack { get; set; }

    private static void OnTargetChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) =>
        ((PropertyInspectorControl)d).Rebuild();

    private void Rebuild()
    {
        foreach (PropertyRowViewModel header in _headers.Values)
        {
            header.PropertyChanged -= OnHeaderPropertyChanged;
        }

        foreach (PropertyRowViewModel row in _rows)
        {
            row.Dispose();
        }

        _rows = new List<PropertyRowViewModel>();
        _headers = new Dictionary<string, PropertyRowViewModel>(StringComparer.Ordinal);
        _view = null;

        GraphObject? target = Target;
        if (target is null)
        {
            HeaderType.Text = "Properties";
            HeaderName.Text = string.Empty;
            EmptyHint.Visibility = Visibility.Visible;
            Rows.ItemsSource = null;
            return;
        }

        foreach (EditableProperty property in EditablePropertyFactory.Describe(target))
        {
            var row = new PropertyRowViewModel(target, property, UndoStack);
            _rows.Add(row);

            if (row.IsHeader)
            {
                _headers[row.DisplayName] = row;
                row.PropertyChanged += OnHeaderPropertyChanged;
            }
        }

        HeaderType.Text = target.GetType().Name;
        HeaderName.Text = target.Name;
        EmptyHint.Visibility = Visibility.Collapsed;

        _view = new ListCollectionView(_rows);
        _view.GroupDescriptions.Add(new PropertyGroupDescription(nameof(PropertyRowViewModel.Category)));

        // Children of a composite are hidden until their header is expanded. Filtering (rather than a
        // nested items control) keeps the single flat, category-grouped list the inspector already is.
        _view.Filter = item => item is not PropertyRowViewModel row
            || row.Group is null
            || (_headers.TryGetValue(row.Group, out PropertyRowViewModel? header) && header.IsExpanded);

        Rows.ItemsSource = _view;
    }

    private void OnHeaderPropertyChanged(object? sender, System.ComponentModel.PropertyChangedEventArgs e)
    {
        if (e.PropertyName == nameof(PropertyRowViewModel.IsExpanded))
        {
            _view?.Refresh();
        }
    }

    /// <summary>Commits a text editor on Enter and reverts it on Escape.</summary>
    private void OnEditorTextBoxKeyDown(object sender, KeyEventArgs e)
    {
        if (sender is not TextBox box)
        {
            return;
        }

        if (e.Key == Key.Enter)
        {
            box.GetBindingExpression(TextBox.TextProperty)?.UpdateSource();
            e.Handled = true;
        }
        else if (e.Key == Key.Escape)
        {
            box.GetBindingExpression(TextBox.TextProperty)?.UpdateTarget();
            e.Handled = true;
        }
    }
}
