% probe_net_types: modifiers (ref/out/params/optional), arrays, generics, enums, misc types.
dotnetenv("core", Version="8");
a = ip_assets();
NET.addAssembly(a.assembly);

% ---- ref / out / params / optional
ip_pr('ref.double', 'JGTest.Modifiers.Double(2)');
ip_px('ref.double.two', '[r1, r2] = JGTest.Modifiers.Double(2)');
ip_px('ref.nooutput', 'JGTest.Modifiers.Double(2)');
ip_px('out.split', '[w, f] = JGTest.Modifiers.Split(2.75)');
ip_px('out.split.one', 'w = JGTest.Modifiers.Split(2.75)');
ip_px('out.tryhalf', '[ok, h] = JGTest.Modifiers.TryHalf(int32(8))');
ip_px('out.tryhalf.odd', '[ok, h] = JGTest.Modifiers.TryHalf(int32(7))');
ip_px('refoutret', '[r, a1, lbl] = JGTest.Modifiers.RefOutReturn(1)');
ip_px('ref.array', 'v = JGTest.Modifiers.Grow([1 2 3])');
ip_px('out.name', 'n = JGTest.Modifiers.MakeName()');
ip_px('out.name.nooutput', 'JGTest.Modifiers.MakeName()');
ip_px('methods.modifiers', 'methods(''JGTest.Modifiers'', ''-full'')');
ip_pr('params.none', 'JGTest.Modifiers.Sum()');
ip_pr('params.scalars', 'JGTest.Modifiers.Sum(1, 2, 3)');
ip_pr('params.array', 'JGTest.Modifiers.Sum([1 2 3])');
ip_pr('params.netarray', 'JGTest.Modifiers.Sum(NET.convertArray([1 2 3]))');
ip_pr('params.join', 'JGTest.Modifiers.Join(''-'', ''a'', ''b'')');
ip_pr('params.join.cell', 'JGTest.Modifiers.Join(''-'', {''a'', ''b''})');
ip_pr('optional.one', 'JGTest.Modifiers.Optional(int32(1))');
ip_pr('optional.two', 'JGTest.Modifiers.Optional(int32(1), int32(2))');
ip_pr('optional.three', 'JGTest.Modifiers.Optional(int32(1), int32(2), int32(3))');
ip_pr('optional.missing', 'JGTest.Modifiers.Optional(int32(1), System.Reflection.Missing.Value, int32(3))');
ip_pr('void.output', 'JGTest.Modifiers.Void()');
ip_px('void.call', 'JGTest.Modifiers.Void()');
ip_px('value.echo', 'JGTest.Modifiers.Value()');

% ---- arrays
ip_pr('arr.Ramp', 'JGTest.ArrayMaker.Ramp(int32(3))');
ip_px('arr.Ramp.disp', 'r = JGTest.ArrayMaker.Ramp(int32(3))');
r = JGTest.ArrayMaker.Ramp(int32(3));
ip_pr('arr.class', 'class(r)');
ip_pr('arr.size', 'size(r)');
ip_pr('arr.Length', 'r.Length');
ip_pr('arr.Rank', 'r.Rank');
ip_pr('arr.index1', 'r(1)');
ip_pr('arr.index0', 'r(0)');
ip_pr('arr.index.end', 'r(end)');
ip_pr('arr.index.range', 'r(1:2)');
ip_pr('arr.index.colon', 'r(:)');
ip_pr('arr.GetValue', 'r.GetValue(0)');
r(1) = 50;
ip_pr('arr.set', 'r.GetValue(0)');
ip_px('arr.set.oob', 'r(10) = 1;');
ip_pr('arr.double', 'double(r)');
ip_pr('arr.plus', 'r + 1');
ip_pr('arr.sum', 'sum(r)');
ip_pr('arr.numel', 'numel(r)');
ip_pr('arr.isempty.empty', 'isempty(JGTest.ArrayMaker.Empty())');
ip_pr('arr.Empty.double', 'double(JGTest.ArrayMaker.Empty())');
g = JGTest.ArrayMaker.Grid(int32(2), int32(3));
ip_pr('arr2d.class', 'class(g)');
ip_pr('arr2d.size', 'size(g)');
ip_pr('arr2d.index', 'g(2, 3)');
ip_pr('arr2d.linear', 'g(4)');
ip_pr('arr2d.double', 'double(g)');
ip_pr('arr2d.GetLength', 'g.GetLength(1)');
j = JGTest.ArrayMaker.Jagged();
ip_pr('jagged.class', 'class(j)');
ip_pr('jagged.outer', 'j(2)');
ip_pr('jagged.inner', 'j(2)(2)');
ip_pr('jagged.double', 'double(j(3))');
ip_pr('jagged.cell', 'cell(j)');
ip_pr('jagged.double.all', 'double(j)');
ip_pr('ints', 'int32(JGTest.ArrayMaker.Ints())');
ip_pr('ints.raw', 'JGTest.ArrayMaker.Ints()');
ip_pr('bools', 'logical(JGTest.ArrayMaker.Bools())');
ip_pr('chars', 'char(JGTest.ArrayMaker.Chars())');
ip_pr('bytes', 'uint8(JGTest.ArrayMaker.Bytes())');
w = JGTest.ArrayMaker.Words();
ip_pr('words.class', 'class(w)');
ip_pr('words.index', 'w(2)');
ip_pr('words.string', 'string(w)');
ip_pr('words.cellstr', 'cellstr(w)');
ip_pr('words.cell', 'cell(w)');
ip_pr('words.char', 'char(w)');
mx = JGTest.ArrayMaker.Mixed();
ip_pr('mixed.class', 'class(mx)');
ip_pr('mixed.cell', 'cell(mx)');
ip_pr('mixed.index1', 'mx(1)');
ip_pr('mixed.index5', 'mx(5)');
ip_pr('sum.double', 'JGTest.ArrayMaker.Sum([1 2 3])');
ip_pr('sum.col', 'JGTest.ArrayMaker.Sum([1; 2; 3])');
ip_pr('sum.int32', 'JGTest.ArrayMaker.Sum(int32([1 2 3]))');
ip_pr('sum.scalar', 'JGTest.ArrayMaker.Sum(5)');
ip_pr('sum.empty', 'JGTest.ArrayMaker.Sum([])');
ip_pr('sum2.mat', 'JGTest.ArrayMaker.Sum2([1 2 3; 4 5 6])');
ip_pr('shape.mat', 'JGTest.ArrayMaker.Shape([1 2 3; 4 5 6])');
ip_pr('shape.row', 'JGTest.ArrayMaker.Shape([1 2 3])');
ip_pr('count.cellstr', 'JGTest.ArrayMaker.Count({''a'', ''b''})');
ip_pr('count.string', 'JGTest.ArrayMaker.Count(["a" "b" "c"])');
ip_pr('count.charmat', 'JGTest.ArrayMaker.Count([''ab''; ''cd''])');
ip_pr('kinds.cell', 'JGTest.ArrayMaker.Kinds({1, ''a'', int8(2), true, "s", [1 2], {3}})');
ip_pr('kinds.cell.empty', 'JGTest.ArrayMaker.Kinds({[]})');

% ---- NET.createArray and NET.convertArray
ip_pr('createArray.1d', 'NET.createArray(''System.Double'', 3)');
ip_pr('createArray.2d', 'size(NET.createArray(''System.Int32'', 2, 3))');
ip_pr('createArray.class', 'class(NET.createArray(''System.String'', 2))');
ip_pr('createArray.jagged', 'class(NET.createArray(''System.Double[]'', 2))');
ip_pr('createArray.typeobj', 'class(NET.createArray(System.Type.GetType(''System.Double''), 2))');
ip_pr('createArray.bad', 'NET.createArray(''No.Such.Type'', 2)');
ip_pr('convertArray.row', 'class(NET.convertArray([1 2 3]))');
ip_pr('convertArray.mat', 'size(NET.convertArray([1 2; 3 4]))');
ip_pr('convertArray.type', 'class(NET.convertArray([1 2 3], ''System.Int32''))');
ip_pr('convertArray.dims', 'size(NET.convertArray([1 2 3], ''System.Double'', [1 3]))');
ip_pr('convertArray.col', 'size(NET.convertArray([1; 2; 3]))');
ip_pr('convertArray.char', 'NET.convertArray(''abc'')');

% ---- generics
b = NET.createGeneric('JGTest.Box', {'System.Double'}, 2.5);
ip_pr('gen.class', 'class(b)');
ip_pr('gen.value', 'b.Value');
ip_pr('gen.typename', 'b.TypeName');
ip_px('gen.disp', 'b');
b2 = NET.createGeneric('JGTest.Box', {'System.String'});
ip_pr('gen.nothing', 'b2.Value');
b2.Value = 'hi';
ip_pr('gen.string.value', 'b2.Value');
pr = NET.createGeneric('JGTest.Pair', {'System.Int32', 'System.String'}, int32(1), 'one');
ip_pr('gen.pair.class', 'class(pr)');
ip_pr('gen.pair.first', 'pr.First');
ip_pr('gen.pair.second', 'pr.Second');
ip_pr('gen.nested.typearg', 'class(NET.createGeneric(''JGTest.Box'', {''System.Collections.Generic.List<System.Double>''}))');
ip_pr('gen.nested.createGeneric', 'class(NET.createGeneric(''JGTest.Box'', {NET.GenericClass(''System.Collections.Generic.List'', ''System.Double'')}))');
ip_pr('gen.constraint.bad', 'NET.createGeneric(''JGTest.Constrained'', {''System.String''})');
ip_pr('gen.constraint.ok', 'class(NET.createGeneric(''JGTest.Constrained'', {''System.Int32''}))');
ip_pr('gen.method.Echo', 'NET.invokeGenericMethod(''JGTest.GenericTools'', ''Echo'', {''System.Int32''}, int32(5))');
ip_pr('gen.method.TypeOf', 'NET.invokeGenericMethod(''JGTest.GenericTools'', ''TypeOf'', {''System.String''})');
ip_pr('gen.method.direct', 'JGTest.GenericTools.Echo(5)');
ip_pr('gen.GenericClass', 'NET.GenericClass(''System.Collections.Generic.List'', ''System.Double'')');
lst = JGTest.GenericTools.Range(int32(3));
ip_pr('list.class', 'class(lst)');
ip_pr('list.Count', 'lst.Count');
ip_pr('list.Item', 'lst.Item(1)');
ip_pr('list.ToArray', 'double(lst.ToArray())');
ip_px('list.disp', 'lst');
ip_pr('list.index', 'lst(1)');
nb = JGTest.GenericTools.NestedBox(int32(2));
ip_pr('nested.class', 'class(nb)');
ip_pr('nested.value.class', 'class(nb.Value)');
t = JGTest.GenericTools.Table();
ip_pr('dict.class', 'class(t)');
ip_pr('dict.Item', 't.Item(''two'')');
ip_pr('dict.ContainsKey', 't.ContainsKey(''one'')');
ip_pr('dict.Keys', 'class(t.Keys)');
ip_px('dict.disp', 't');
ip_pr('ienumerable.list', 'JGTest.GenericTools.Total(lst)');
ip_pr('ienumerable.double', 'JGTest.GenericTools.Total([1 2 3])');
ip_pr('dictionary.convert', 'dictionary(t)');

% ---- enums
c = JGTest.Color.Green;
ip_pr('enum.class', 'class(c)');
ip_px('enum.disp', 'c');
ip_pr('enum.char', 'char(c)');
ip_pr('enum.string', 'string(c)');
ip_pr('enum.int32', 'int32(c)');
ip_pr('enum.double', 'double(c)');
ip_pr('enum.eq', 'c == JGTest.Color.Green');
ip_pr('enum.eq.char', 'c == ''Green''');
ip_pr('enum.isa', 'isa(c, ''System.Enum'')');
ip_pr('enum.Next', 'JGTest.EnumTools.Next(c)');
ip_pr('enum.Name', 'JGTest.EnumTools.Name(c)');
ip_pr('enum.Name.char', 'JGTest.EnumTools.Name(''Blue'')');
ip_pr('enum.Name.int', 'JGTest.EnumTools.Name(int32(2))');
ip_pr('enum.Name.double', 'JGTest.EnumTools.Name(2)');
ip_pr('enum.bad.name', 'JGTest.Color.Purple');
ip_pr('enum.enumeration', 'enumeration(''JGTest.Color'')');
ip_px('enum.enumeration.disp', 'enumeration(''JGTest.Color'')');
ip_pr('enum.GetNames', 'string(System.Enum.GetNames(c.GetType()))');
ip_pr('enum.methods', 'methods(c)');
f1 = JGTest.EnumTools.Combine(JGTest.Access.Read, JGTest.Access.Write);
ip_px('flags.disp', 'f1');
ip_pr('flags.char', 'char(f1)');
ip_pr('flags.int32', 'int32(f1)');
ip_pr('flags.bitor', 'bitor(JGTest.Access.Read, JGTest.Access.Execute)');
ip_pr('flags.or', 'JGTest.Access.Read | JGTest.Access.Execute');
ip_pr('flags.HasFlag', 'f1.HasFlag(JGTest.Access.Write)');
ip_pr('flags.CanWrite', 'JGTest.EnumTools.CanWrite(f1)');
ip_pr('flags.bitand', 'bitand(f1, JGTest.Access.Write)');
ip_pr('enum.byte.value', 'uint8(JGTest.EnumTools.SmallHigh())');
ip_pr('enum.byte.int32', 'int32(JGTest.EnumTools.SmallHigh())');
ip_pr('enum.long.value', 'int64(JGTest.EnumTools.BigLarge())');
ip_pr('enum.long.double', 'double(JGTest.Big.Negative)');
ip_pr('enum.ulong.value', 'sprintf(''%d'', uint64(JGTest.EnumTools.HugeHigh()))');
ip_pr('enum.ulong.HugeValue', 'sprintf(''%d'', JGTest.EnumTools.HugeValue(JGTest.Huge.High))');
ip_px('enum.ulong.disp', 'h = JGTest.Huge.High');
ip_pr('enum.dow', 'System.DayOfWeek.Friday');

% ---- misc types
ip_pr('disposable', 'isa(JGTest.Resource(), ''System.IDisposable'')');
JGTest.Resource.ResetCount();
rs = JGTest.Resource();
rs.Dispose();
ip_pr('disposable.after', 'JGTest.Resource.Disposed');
rs2 = JGTest.Resource();
delete(rs2);
ip_pr('disposable.delete', 'JGTest.Resource.Disposed');
v1 = JGTest.Vector2(1, 2);
v2 = JGTest.Vector2(3, 4);
ip_pr('op.plus', 'v1 + v2');
ip_pr('op.minus', 'v1 - v2');
ip_pr('op.times', 'v1 * 2');
ip_pr('op.mtimes.scalar.first', '2 * v1');
ip_pr('op.eq', 'v1 == JGTest.Vector2(1, 2)');
ip_pr('op.ne', 'v1 ~= v2');
ip_pr('op.op_Addition', 'JGTest.Vector2.op_Addition(v1, v2)');
gr = JGTest.Greeter();
ip_pr('iface.public', 'gr.Public()');
ip_pr('iface.explicit', 'gr.Greet()');
ip_pr('iface.cast', 'NET.explicitCast(gr, ''JGTest.IGreeter'').Greet()');
ip_pr('iface.cast.class', 'class(NET.explicitCast(gr, ''JGTest.IGreeter''))');
ip_pr('nested.class.name', 'class(JGTest.Outer.MakeInner())');
ip_pr('nested.class.call', 'JGTest.Outer.MakeInner().Where()');
ip_pr('nested.ctor.plus', 'JGTest.Outer+Inner()');
ip_pr('nested.ctor.dot', 'JGTest.Outer.Inner()');
sq = JGTest.Sequence(int32(3));
ip_pr('ienum.class', 'class(sq)');
ip_px('ienum.loop', 'e = sq.GetEnumerator(); while e.MoveNext(), disp(e.Current); end');
ip_px('ienum.for', 'for x = sq, disp(x); end');
