function probe_which(outdir)
names = {'uicontrol','uipanel','uibuttongroup','uitable','uitabgroup','uitab','uimenu', ...
 'uicontextmenu','uitoolbar','uipushtool','uitoggletool','uisplittool','uitogglesplittool', ...
 'uicontainer','uiflowcontainer','uigridcontainer','uifigure','uibutton','uilabel', ...
 'uieditfield','uitextarea','uidropdown','uilistbox','uicheckbox','uiradiobutton', ...
 'uitogglebutton','uislider','uirangeslider','uispinner','uiknob','uiswitch','uigauge', ...
 'uilamp','uidatepicker','uicolorpicker','uihyperlink','uiimage','uihtml','uitree', ...
 'uitreenode','uiaxes','uigridlayout','uistyle','addStyle','removeStyle','uialert', ...
 'uiconfirm','uiprogressdlg','uigetfile','uiputfile','uigetdir','uisetcolor','uisetfont', ...
 'msgbox','errordlg','warndlg','helpdlg','questdlg','inputdlg','listdlg','waitbar', ...
 'uiopen','uisave','uiload','uiimport','uiwait','uiresume','waitfor','waitforbuttonpress', ...
 'guidata','guihandles','setappdata','getappdata','isappdata','rmappdata','focus', ...
 'scroll','isInScrollView','appdesigner','drawnow','figure','gcf','gcbo','gcbf','gco','ginput', ...
 'uistack','movegui','dialog','openfig','savefig','guide','javacomponent','actxcontrol', ...
 'actxserver','uitoolfactory','uiprintdlg','uiexportdlg','expand','collapse','move', ...
 'sendEventToHTMLSource','openmlapp','uigetpref','uisetpref','inspect','theme', ...
 'getpixelposition','setpixelposition','findall','findobj','allchild','ancestor', ...
 'uisuspend','uirestore','textwrap','listfonts','clipboard','export2wsdlg','menu', ...
 'tabdlg','wizard','btngroup','uiundo','uitimescope','matlab.apps.AppBase', ...
 'matlab.ui.componentcontainer.ComponentContainer','appdesigner.appmigration.migrateGUIDEApp', ...
 'imageSource','uiimport','selectmoveresize','refreshdata','linkdata','brush','datacursormode', ...
 'zoom','pan','rotate3d','closereq','close','delete','isvalid','ishghandle','isgraphics', ...
 'createCallbackFcn','matlab.apps.createCallbackFcn','uifigureOnBeforeAppStart', ...
 'uisetpref','getframe','exportapp','matlab.ui.internal.isUIFigure','isUIFigure', ...
 'startup','registerApp','runningApp','uiopen','uitable','addcats','qeinbatch', ...
 'matlab.ui.style.Style','uiprogressdlg','uicolorpicker','uispinner','uipagination', ...
 'uibreadcrumb','uitooltip','uicarousel','uinavigation','uipasswordfield','uirating', ...
 'uiprogressbar','uiaccordion','uitimer','timer','uiaccordionpanel','uiseparator'};
names = unique(names, 'stable');
fid = fopen(fullfile(outdir, 'which.txt'), 'w');
for i = 1:numel(names)
    n = names{i};
    try, e = exist(n); catch, e = -1; end %#ok<EXIST>
    try, w = which(n); catch ex, w = ['<which error ' ex.message '>']; end
    if isempty(w), w = '<not found>'; end
    w = strrep(w, matlabroot, '$ML');
    fprintf(fid, '%-45s exist=%2d  %s\n', n, e, w);
end
fclose(fid);
end
