"""Writes src/JGraph.Scripting/Jgs/JgsGraphicsClasses.Table.cs from u7_classes.out.txt.

u7_classes.m records R2025b's class and superclasses for each kind of graphics object JGraph
makes. Names under an .internal. package are left out: nothing a script asks isa about.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
rows = []
extra = {}
for line in open(os.path.join(HERE, "u7_classes.out.txt"), encoding="utf-8", errors="replace"):
    line = line.strip()
    if line.startswith("I|"):
        # The bases superclasses() does not list and isa() answers to, asked about one by one.
        _, key, found = line.split("|")
        extra[key] = [s for s in found.split(",") if s and ".internal." not in s]
        continue
    if not line.startswith("K|") or "|ERR " in line:
        continue
    _, key, cls, supers = line.split("|")
    supers = [s for s in supers.split(",") if s and ".internal." not in s]
    rows.append((key, cls, supers))
rows = [(key, cls, supers + [s for s in extra.get(key, []) if s != cls and s not in supers]) for key, cls, supers in rows]

# Most classes share long runs of superclasses, so each distinct name is written once.
names = []
index = {}
for _, cls, supers in rows:
    for n in [cls] + supers:
        if n not in index:
            index[n] = len(names)
            names.append(n)

out = []
out.append("// Generated by tools/matlab-checklist/ui-probes/u7/gen_classes.py from u7_classes.out.txt (R2025b). Do not edit.")
out.append("namespace JGraph.Scripting.Jgs;")
out.append("")
out.append("internal static partial class JgsGraphicsClasses")
out.append("{")
out.append("    private static readonly string[] Names =")
out.append("    [")
for n in names:
    out.append('        "%s",' % n)
out.append("    ];")
out.append("")
out.append("    /// <summary>Each kind of object: its key, then the indices of its class and of each superclass, as R2025b lists them.</summary>")
out.append("    private static readonly (string Key, int[] Chain)[] Rows =")
out.append("    [")
for key, cls, supers in rows:
    chain = ", ".join(str(index[n]) for n in [cls] + supers)
    out.append('        ("%s", [%s]),' % (key, chain))
out.append("    ];")
out.append("}")
path = os.path.join(REPO, "src", "JGraph.Scripting", "Jgs", "JgsGraphicsClasses.Table.cs")
with open(path, "w", encoding="utf-8", newline="\r\n") as f:
    f.write("\n".join(out) + "\n")
print(len(rows), "kinds,", len(names), "names")
