% value_isolation_gen_overlap.m -- GENERATED by tools/parity/gen-value-isolation.py; do not edit.
% The overlap matrix of the value-ownership plan (rule M10): an indexed write whose right-hand
% side, subscript, or both are the target's own storage -- permuted, shifted, grown from itself,
% promoted to complex or demoted to char through a self-subscript -- for every element type and
% every target kind (a variable, a field, a cell element, a global, a persistent).

run_case('o_permute_rhs_same_double_variable', @o_permute_rhs_same_double_variable);
run_case('o_permute_rhs_same_double_field', @o_permute_rhs_same_double_field);
run_case('o_permute_rhs_same_double_cellelem', @o_permute_rhs_same_double_cellelem);
run_case('o_permute_rhs_same_double_global', @o_permute_rhs_same_double_global);
run_case('o_permute_rhs_same_double_persistent', @o_permute_rhs_same_double_persistent);
run_case('o_permute_rhs_same_single_variable', @o_permute_rhs_same_single_variable);
run_case('o_permute_rhs_same_single_field', @o_permute_rhs_same_single_field);
run_case('o_permute_rhs_same_single_cellelem', @o_permute_rhs_same_single_cellelem);
run_case('o_permute_rhs_same_single_global', @o_permute_rhs_same_single_global);
run_case('o_permute_rhs_same_single_persistent', @o_permute_rhs_same_single_persistent);
run_case('o_permute_rhs_same_int8_variable', @o_permute_rhs_same_int8_variable);
run_case('o_permute_rhs_same_int8_field', @o_permute_rhs_same_int8_field);
run_case('o_permute_rhs_same_int8_cellelem', @o_permute_rhs_same_int8_cellelem);
run_case('o_permute_rhs_same_int8_global', @o_permute_rhs_same_int8_global);
run_case('o_permute_rhs_same_int8_persistent', @o_permute_rhs_same_int8_persistent);
run_case('o_permute_rhs_same_logical_variable', @o_permute_rhs_same_logical_variable);
run_case('o_permute_rhs_same_logical_field', @o_permute_rhs_same_logical_field);
run_case('o_permute_rhs_same_logical_cellelem', @o_permute_rhs_same_logical_cellelem);
run_case('o_permute_rhs_same_logical_global', @o_permute_rhs_same_logical_global);
run_case('o_permute_rhs_same_logical_persistent', @o_permute_rhs_same_logical_persistent);
run_case('o_permute_rhs_same_char_variable', @o_permute_rhs_same_char_variable);
run_case('o_permute_rhs_same_char_field', @o_permute_rhs_same_char_field);
run_case('o_permute_rhs_same_char_cellelem', @o_permute_rhs_same_char_cellelem);
run_case('o_permute_rhs_same_char_global', @o_permute_rhs_same_char_global);
run_case('o_permute_rhs_same_char_persistent', @o_permute_rhs_same_char_persistent);
run_case('o_permute_rhs_same_string_variable', @o_permute_rhs_same_string_variable);
run_case('o_permute_rhs_same_string_field', @o_permute_rhs_same_string_field);
run_case('o_permute_rhs_same_string_cellelem', @o_permute_rhs_same_string_cellelem);
run_case('o_permute_rhs_same_string_global', @o_permute_rhs_same_string_global);
run_case('o_permute_rhs_same_string_persistent', @o_permute_rhs_same_string_persistent);
run_case('o_permute_rhs_same_complex_variable', @o_permute_rhs_same_complex_variable);
run_case('o_permute_rhs_same_complex_field', @o_permute_rhs_same_complex_field);
run_case('o_permute_rhs_same_complex_cellelem', @o_permute_rhs_same_complex_cellelem);
run_case('o_permute_rhs_same_complex_global', @o_permute_rhs_same_complex_global);
run_case('o_permute_rhs_same_complex_persistent', @o_permute_rhs_same_complex_persistent);
run_case('o_permute_rhs_same_cell_variable', @o_permute_rhs_same_cell_variable);
run_case('o_permute_rhs_same_cell_field', @o_permute_rhs_same_cell_field);
run_case('o_permute_rhs_same_cell_cellelem', @o_permute_rhs_same_cell_cellelem);
run_case('o_permute_rhs_same_cell_global', @o_permute_rhs_same_cell_global);
run_case('o_permute_rhs_same_cell_persistent', @o_permute_rhs_same_cell_persistent);
run_case('o_permute_rhs_same_structarr_variable', @o_permute_rhs_same_structarr_variable);
run_case('o_permute_rhs_same_structarr_field', @o_permute_rhs_same_structarr_field);
run_case('o_permute_rhs_same_structarr_cellelem', @o_permute_rhs_same_structarr_cellelem);
run_case('o_permute_rhs_same_structarr_global', @o_permute_rhs_same_structarr_global);
run_case('o_permute_rhs_same_structarr_persistent', @o_permute_rhs_same_structarr_persistent);
run_case('o_permute_rhs_fresh_double_variable', @o_permute_rhs_fresh_double_variable);
run_case('o_permute_rhs_fresh_double_field', @o_permute_rhs_fresh_double_field);
run_case('o_permute_rhs_fresh_double_cellelem', @o_permute_rhs_fresh_double_cellelem);
run_case('o_permute_rhs_fresh_double_global', @o_permute_rhs_fresh_double_global);
run_case('o_permute_rhs_fresh_double_persistent', @o_permute_rhs_fresh_double_persistent);
run_case('o_permute_rhs_fresh_single_variable', @o_permute_rhs_fresh_single_variable);
run_case('o_permute_rhs_fresh_single_field', @o_permute_rhs_fresh_single_field);
run_case('o_permute_rhs_fresh_single_cellelem', @o_permute_rhs_fresh_single_cellelem);
run_case('o_permute_rhs_fresh_single_global', @o_permute_rhs_fresh_single_global);
run_case('o_permute_rhs_fresh_single_persistent', @o_permute_rhs_fresh_single_persistent);
run_case('o_permute_rhs_fresh_int8_variable', @o_permute_rhs_fresh_int8_variable);
run_case('o_permute_rhs_fresh_int8_field', @o_permute_rhs_fresh_int8_field);
run_case('o_permute_rhs_fresh_int8_cellelem', @o_permute_rhs_fresh_int8_cellelem);
run_case('o_permute_rhs_fresh_int8_global', @o_permute_rhs_fresh_int8_global);
run_case('o_permute_rhs_fresh_int8_persistent', @o_permute_rhs_fresh_int8_persistent);
run_case('o_permute_rhs_fresh_logical_variable', @o_permute_rhs_fresh_logical_variable);
run_case('o_permute_rhs_fresh_logical_field', @o_permute_rhs_fresh_logical_field);
run_case('o_permute_rhs_fresh_logical_cellelem', @o_permute_rhs_fresh_logical_cellelem);
run_case('o_permute_rhs_fresh_logical_global', @o_permute_rhs_fresh_logical_global);
run_case('o_permute_rhs_fresh_logical_persistent', @o_permute_rhs_fresh_logical_persistent);
run_case('o_permute_rhs_fresh_char_variable', @o_permute_rhs_fresh_char_variable);
run_case('o_permute_rhs_fresh_char_field', @o_permute_rhs_fresh_char_field);
run_case('o_permute_rhs_fresh_char_cellelem', @o_permute_rhs_fresh_char_cellelem);
run_case('o_permute_rhs_fresh_char_global', @o_permute_rhs_fresh_char_global);
run_case('o_permute_rhs_fresh_char_persistent', @o_permute_rhs_fresh_char_persistent);
run_case('o_permute_rhs_fresh_string_variable', @o_permute_rhs_fresh_string_variable);
run_case('o_permute_rhs_fresh_string_field', @o_permute_rhs_fresh_string_field);
run_case('o_permute_rhs_fresh_string_cellelem', @o_permute_rhs_fresh_string_cellelem);
run_case('o_permute_rhs_fresh_string_global', @o_permute_rhs_fresh_string_global);
run_case('o_permute_rhs_fresh_string_persistent', @o_permute_rhs_fresh_string_persistent);
run_case('o_permute_rhs_fresh_complex_variable', @o_permute_rhs_fresh_complex_variable);
run_case('o_permute_rhs_fresh_complex_field', @o_permute_rhs_fresh_complex_field);
run_case('o_permute_rhs_fresh_complex_cellelem', @o_permute_rhs_fresh_complex_cellelem);
run_case('o_permute_rhs_fresh_complex_global', @o_permute_rhs_fresh_complex_global);
run_case('o_permute_rhs_fresh_complex_persistent', @o_permute_rhs_fresh_complex_persistent);
run_case('o_permute_rhs_fresh_cell_variable', @o_permute_rhs_fresh_cell_variable);
run_case('o_permute_rhs_fresh_cell_field', @o_permute_rhs_fresh_cell_field);
run_case('o_permute_rhs_fresh_cell_cellelem', @o_permute_rhs_fresh_cell_cellelem);
run_case('o_permute_rhs_fresh_cell_global', @o_permute_rhs_fresh_cell_global);
run_case('o_permute_rhs_fresh_cell_persistent', @o_permute_rhs_fresh_cell_persistent);
run_case('o_permute_rhs_fresh_structarr_variable', @o_permute_rhs_fresh_structarr_variable);
run_case('o_permute_rhs_fresh_structarr_field', @o_permute_rhs_fresh_structarr_field);
run_case('o_permute_rhs_fresh_structarr_cellelem', @o_permute_rhs_fresh_structarr_cellelem);
run_case('o_permute_rhs_fresh_structarr_global', @o_permute_rhs_fresh_structarr_global);
run_case('o_permute_rhs_fresh_structarr_persistent', @o_permute_rhs_fresh_structarr_persistent);
run_case('o_shift_rhs_fresh_double_variable', @o_shift_rhs_fresh_double_variable);
run_case('o_shift_rhs_fresh_double_field', @o_shift_rhs_fresh_double_field);
run_case('o_shift_rhs_fresh_double_cellelem', @o_shift_rhs_fresh_double_cellelem);
run_case('o_shift_rhs_fresh_double_global', @o_shift_rhs_fresh_double_global);
run_case('o_shift_rhs_fresh_double_persistent', @o_shift_rhs_fresh_double_persistent);
run_case('o_shift_rhs_fresh_single_variable', @o_shift_rhs_fresh_single_variable);
run_case('o_shift_rhs_fresh_single_field', @o_shift_rhs_fresh_single_field);
run_case('o_shift_rhs_fresh_single_cellelem', @o_shift_rhs_fresh_single_cellelem);
run_case('o_shift_rhs_fresh_single_global', @o_shift_rhs_fresh_single_global);
run_case('o_shift_rhs_fresh_single_persistent', @o_shift_rhs_fresh_single_persistent);
run_case('o_shift_rhs_fresh_int8_variable', @o_shift_rhs_fresh_int8_variable);
run_case('o_shift_rhs_fresh_int8_field', @o_shift_rhs_fresh_int8_field);
run_case('o_shift_rhs_fresh_int8_cellelem', @o_shift_rhs_fresh_int8_cellelem);
run_case('o_shift_rhs_fresh_int8_global', @o_shift_rhs_fresh_int8_global);
run_case('o_shift_rhs_fresh_int8_persistent', @o_shift_rhs_fresh_int8_persistent);
run_case('o_shift_rhs_fresh_logical_variable', @o_shift_rhs_fresh_logical_variable);
run_case('o_shift_rhs_fresh_logical_field', @o_shift_rhs_fresh_logical_field);
run_case('o_shift_rhs_fresh_logical_cellelem', @o_shift_rhs_fresh_logical_cellelem);
run_case('o_shift_rhs_fresh_logical_global', @o_shift_rhs_fresh_logical_global);
run_case('o_shift_rhs_fresh_logical_persistent', @o_shift_rhs_fresh_logical_persistent);
run_case('o_shift_rhs_fresh_char_variable', @o_shift_rhs_fresh_char_variable);
run_case('o_shift_rhs_fresh_char_field', @o_shift_rhs_fresh_char_field);
run_case('o_shift_rhs_fresh_char_cellelem', @o_shift_rhs_fresh_char_cellelem);
run_case('o_shift_rhs_fresh_char_global', @o_shift_rhs_fresh_char_global);
run_case('o_shift_rhs_fresh_char_persistent', @o_shift_rhs_fresh_char_persistent);
run_case('o_shift_rhs_fresh_string_variable', @o_shift_rhs_fresh_string_variable);
run_case('o_shift_rhs_fresh_string_field', @o_shift_rhs_fresh_string_field);
run_case('o_shift_rhs_fresh_string_cellelem', @o_shift_rhs_fresh_string_cellelem);
run_case('o_shift_rhs_fresh_string_global', @o_shift_rhs_fresh_string_global);
run_case('o_shift_rhs_fresh_string_persistent', @o_shift_rhs_fresh_string_persistent);
run_case('o_shift_rhs_fresh_complex_variable', @o_shift_rhs_fresh_complex_variable);
run_case('o_shift_rhs_fresh_complex_field', @o_shift_rhs_fresh_complex_field);
run_case('o_shift_rhs_fresh_complex_cellelem', @o_shift_rhs_fresh_complex_cellelem);
run_case('o_shift_rhs_fresh_complex_global', @o_shift_rhs_fresh_complex_global);
run_case('o_shift_rhs_fresh_complex_persistent', @o_shift_rhs_fresh_complex_persistent);
run_case('o_shift_rhs_fresh_cell_variable', @o_shift_rhs_fresh_cell_variable);
run_case('o_shift_rhs_fresh_cell_field', @o_shift_rhs_fresh_cell_field);
run_case('o_shift_rhs_fresh_cell_cellelem', @o_shift_rhs_fresh_cell_cellelem);
run_case('o_shift_rhs_fresh_cell_global', @o_shift_rhs_fresh_cell_global);
run_case('o_shift_rhs_fresh_cell_persistent', @o_shift_rhs_fresh_cell_persistent);
run_case('o_shift_rhs_fresh_structarr_variable', @o_shift_rhs_fresh_structarr_variable);
run_case('o_shift_rhs_fresh_structarr_field', @o_shift_rhs_fresh_structarr_field);
run_case('o_shift_rhs_fresh_structarr_cellelem', @o_shift_rhs_fresh_structarr_cellelem);
run_case('o_shift_rhs_fresh_structarr_global', @o_shift_rhs_fresh_structarr_global);
run_case('o_shift_rhs_fresh_structarr_persistent', @o_shift_rhs_fresh_structarr_persistent);
run_case('o_grow_rhs_same_double_variable', @o_grow_rhs_same_double_variable);
run_case('o_grow_rhs_same_double_field', @o_grow_rhs_same_double_field);
run_case('o_grow_rhs_same_double_cellelem', @o_grow_rhs_same_double_cellelem);
run_case('o_grow_rhs_same_double_global', @o_grow_rhs_same_double_global);
run_case('o_grow_rhs_same_double_persistent', @o_grow_rhs_same_double_persistent);
run_case('o_grow_rhs_same_single_variable', @o_grow_rhs_same_single_variable);
run_case('o_grow_rhs_same_single_field', @o_grow_rhs_same_single_field);
run_case('o_grow_rhs_same_single_cellelem', @o_grow_rhs_same_single_cellelem);
run_case('o_grow_rhs_same_single_global', @o_grow_rhs_same_single_global);
run_case('o_grow_rhs_same_single_persistent', @o_grow_rhs_same_single_persistent);
run_case('o_grow_rhs_same_int8_variable', @o_grow_rhs_same_int8_variable);
run_case('o_grow_rhs_same_int8_field', @o_grow_rhs_same_int8_field);
run_case('o_grow_rhs_same_int8_cellelem', @o_grow_rhs_same_int8_cellelem);
run_case('o_grow_rhs_same_int8_global', @o_grow_rhs_same_int8_global);
run_case('o_grow_rhs_same_int8_persistent', @o_grow_rhs_same_int8_persistent);
run_case('o_grow_rhs_same_logical_variable', @o_grow_rhs_same_logical_variable);
run_case('o_grow_rhs_same_logical_field', @o_grow_rhs_same_logical_field);
run_case('o_grow_rhs_same_logical_cellelem', @o_grow_rhs_same_logical_cellelem);
run_case('o_grow_rhs_same_logical_global', @o_grow_rhs_same_logical_global);
run_case('o_grow_rhs_same_logical_persistent', @o_grow_rhs_same_logical_persistent);
run_case('o_grow_rhs_same_char_variable', @o_grow_rhs_same_char_variable);
run_case('o_grow_rhs_same_char_field', @o_grow_rhs_same_char_field);
run_case('o_grow_rhs_same_char_cellelem', @o_grow_rhs_same_char_cellelem);
run_case('o_grow_rhs_same_char_global', @o_grow_rhs_same_char_global);
run_case('o_grow_rhs_same_char_persistent', @o_grow_rhs_same_char_persistent);
run_case('o_grow_rhs_same_string_variable', @o_grow_rhs_same_string_variable);
run_case('o_grow_rhs_same_string_field', @o_grow_rhs_same_string_field);
run_case('o_grow_rhs_same_string_cellelem', @o_grow_rhs_same_string_cellelem);
run_case('o_grow_rhs_same_string_global', @o_grow_rhs_same_string_global);
run_case('o_grow_rhs_same_string_persistent', @o_grow_rhs_same_string_persistent);
run_case('o_grow_rhs_same_complex_variable', @o_grow_rhs_same_complex_variable);
run_case('o_grow_rhs_same_complex_field', @o_grow_rhs_same_complex_field);
run_case('o_grow_rhs_same_complex_cellelem', @o_grow_rhs_same_complex_cellelem);
run_case('o_grow_rhs_same_complex_global', @o_grow_rhs_same_complex_global);
run_case('o_grow_rhs_same_complex_persistent', @o_grow_rhs_same_complex_persistent);
run_case('o_grow_rhs_same_cell_variable', @o_grow_rhs_same_cell_variable);
run_case('o_grow_rhs_same_cell_field', @o_grow_rhs_same_cell_field);
run_case('o_grow_rhs_same_cell_cellelem', @o_grow_rhs_same_cell_cellelem);
run_case('o_grow_rhs_same_cell_global', @o_grow_rhs_same_cell_global);
run_case('o_grow_rhs_same_cell_persistent', @o_grow_rhs_same_cell_persistent);
run_case('o_grow_rhs_same_structarr_variable', @o_grow_rhs_same_structarr_variable);
run_case('o_grow_rhs_same_structarr_field', @o_grow_rhs_same_structarr_field);
run_case('o_grow_rhs_same_structarr_cellelem', @o_grow_rhs_same_structarr_cellelem);
run_case('o_grow_rhs_same_structarr_global', @o_grow_rhs_same_structarr_global);
run_case('o_grow_rhs_same_structarr_persistent', @o_grow_rhs_same_structarr_persistent);
run_case('o_grow_end_rhs_same_double_variable', @o_grow_end_rhs_same_double_variable);
run_case('o_grow_end_rhs_same_double_field', @o_grow_end_rhs_same_double_field);
run_case('o_grow_end_rhs_same_double_cellelem', @o_grow_end_rhs_same_double_cellelem);
run_case('o_grow_end_rhs_same_double_global', @o_grow_end_rhs_same_double_global);
run_case('o_grow_end_rhs_same_double_persistent', @o_grow_end_rhs_same_double_persistent);
run_case('o_grow_end_rhs_same_single_variable', @o_grow_end_rhs_same_single_variable);
run_case('o_grow_end_rhs_same_single_field', @o_grow_end_rhs_same_single_field);
run_case('o_grow_end_rhs_same_single_cellelem', @o_grow_end_rhs_same_single_cellelem);
run_case('o_grow_end_rhs_same_single_global', @o_grow_end_rhs_same_single_global);
run_case('o_grow_end_rhs_same_single_persistent', @o_grow_end_rhs_same_single_persistent);
run_case('o_grow_end_rhs_same_int8_variable', @o_grow_end_rhs_same_int8_variable);
run_case('o_grow_end_rhs_same_int8_field', @o_grow_end_rhs_same_int8_field);
run_case('o_grow_end_rhs_same_int8_cellelem', @o_grow_end_rhs_same_int8_cellelem);
run_case('o_grow_end_rhs_same_int8_global', @o_grow_end_rhs_same_int8_global);
run_case('o_grow_end_rhs_same_int8_persistent', @o_grow_end_rhs_same_int8_persistent);
run_case('o_grow_end_rhs_same_logical_variable', @o_grow_end_rhs_same_logical_variable);
run_case('o_grow_end_rhs_same_logical_field', @o_grow_end_rhs_same_logical_field);
run_case('o_grow_end_rhs_same_logical_cellelem', @o_grow_end_rhs_same_logical_cellelem);
run_case('o_grow_end_rhs_same_logical_global', @o_grow_end_rhs_same_logical_global);
run_case('o_grow_end_rhs_same_logical_persistent', @o_grow_end_rhs_same_logical_persistent);
run_case('o_grow_end_rhs_same_char_variable', @o_grow_end_rhs_same_char_variable);
run_case('o_grow_end_rhs_same_char_field', @o_grow_end_rhs_same_char_field);
run_case('o_grow_end_rhs_same_char_cellelem', @o_grow_end_rhs_same_char_cellelem);
run_case('o_grow_end_rhs_same_char_global', @o_grow_end_rhs_same_char_global);
run_case('o_grow_end_rhs_same_char_persistent', @o_grow_end_rhs_same_char_persistent);
run_case('o_grow_end_rhs_same_string_variable', @o_grow_end_rhs_same_string_variable);
run_case('o_grow_end_rhs_same_string_field', @o_grow_end_rhs_same_string_field);
run_case('o_grow_end_rhs_same_string_cellelem', @o_grow_end_rhs_same_string_cellelem);
run_case('o_grow_end_rhs_same_string_global', @o_grow_end_rhs_same_string_global);
run_case('o_grow_end_rhs_same_string_persistent', @o_grow_end_rhs_same_string_persistent);
run_case('o_grow_end_rhs_same_complex_variable', @o_grow_end_rhs_same_complex_variable);
run_case('o_grow_end_rhs_same_complex_field', @o_grow_end_rhs_same_complex_field);
run_case('o_grow_end_rhs_same_complex_cellelem', @o_grow_end_rhs_same_complex_cellelem);
run_case('o_grow_end_rhs_same_complex_global', @o_grow_end_rhs_same_complex_global);
run_case('o_grow_end_rhs_same_complex_persistent', @o_grow_end_rhs_same_complex_persistent);
run_case('o_grow_end_rhs_same_cell_variable', @o_grow_end_rhs_same_cell_variable);
run_case('o_grow_end_rhs_same_cell_field', @o_grow_end_rhs_same_cell_field);
run_case('o_grow_end_rhs_same_cell_cellelem', @o_grow_end_rhs_same_cell_cellelem);
run_case('o_grow_end_rhs_same_cell_global', @o_grow_end_rhs_same_cell_global);
run_case('o_grow_end_rhs_same_cell_persistent', @o_grow_end_rhs_same_cell_persistent);
run_case('o_grow_end_rhs_same_structarr_variable', @o_grow_end_rhs_same_structarr_variable);
run_case('o_grow_end_rhs_same_structarr_field', @o_grow_end_rhs_same_structarr_field);
run_case('o_grow_end_rhs_same_structarr_cellelem', @o_grow_end_rhs_same_structarr_cellelem);
run_case('o_grow_end_rhs_same_structarr_global', @o_grow_end_rhs_same_structarr_global);
run_case('o_grow_end_rhs_same_structarr_persistent', @o_grow_end_rhs_same_structarr_persistent);
run_case('o_sub_same_double_variable', @o_sub_same_double_variable);
run_case('o_sub_same_double_field', @o_sub_same_double_field);
run_case('o_sub_same_double_cellelem', @o_sub_same_double_cellelem);
run_case('o_sub_same_double_global', @o_sub_same_double_global);
run_case('o_sub_same_double_persistent', @o_sub_same_double_persistent);
run_case('o_sub_same_single_variable', @o_sub_same_single_variable);
run_case('o_sub_same_single_field', @o_sub_same_single_field);
run_case('o_sub_same_single_cellelem', @o_sub_same_single_cellelem);
run_case('o_sub_same_single_global', @o_sub_same_single_global);
run_case('o_sub_same_single_persistent', @o_sub_same_single_persistent);
run_case('o_sub_same_int8_variable', @o_sub_same_int8_variable);
run_case('o_sub_same_int8_field', @o_sub_same_int8_field);
run_case('o_sub_same_int8_cellelem', @o_sub_same_int8_cellelem);
run_case('o_sub_same_int8_global', @o_sub_same_int8_global);
run_case('o_sub_same_int8_persistent', @o_sub_same_int8_persistent);
run_case('o_sub_same_mask_logical_variable', @o_sub_same_mask_logical_variable);
run_case('o_sub_same_mask_logical_field', @o_sub_same_mask_logical_field);
run_case('o_sub_same_mask_logical_cellelem', @o_sub_same_mask_logical_cellelem);
run_case('o_sub_same_mask_logical_global', @o_sub_same_mask_logical_global);
run_case('o_sub_same_mask_logical_persistent', @o_sub_same_mask_logical_persistent);
run_case('o_both_same_double_variable', @o_both_same_double_variable);
run_case('o_both_same_double_field', @o_both_same_double_field);
run_case('o_both_same_double_cellelem', @o_both_same_double_cellelem);
run_case('o_both_same_double_global', @o_both_same_double_global);
run_case('o_both_same_double_persistent', @o_both_same_double_persistent);
run_case('o_both_same_single_variable', @o_both_same_single_variable);
run_case('o_both_same_single_field', @o_both_same_single_field);
run_case('o_both_same_single_cellelem', @o_both_same_single_cellelem);
run_case('o_both_same_single_global', @o_both_same_single_global);
run_case('o_both_same_single_persistent', @o_both_same_single_persistent);
run_case('o_both_same_int8_variable', @o_both_same_int8_variable);
run_case('o_both_same_int8_field', @o_both_same_int8_field);
run_case('o_both_same_int8_cellelem', @o_both_same_int8_cellelem);
run_case('o_both_same_int8_global', @o_both_same_int8_global);
run_case('o_both_same_int8_persistent', @o_both_same_int8_persistent);
run_case('o_sub_same_promote_double_variable', @o_sub_same_promote_double_variable);
run_case('o_sub_same_promote_double_field', @o_sub_same_promote_double_field);
run_case('o_sub_same_promote_double_cellelem', @o_sub_same_promote_double_cellelem);
run_case('o_sub_same_promote_double_global', @o_sub_same_promote_double_global);
run_case('o_sub_same_promote_double_persistent', @o_sub_same_promote_double_persistent);
run_case('o_sub_same_promote_single_variable', @o_sub_same_promote_single_variable);
run_case('o_sub_same_promote_single_field', @o_sub_same_promote_single_field);
run_case('o_sub_same_promote_single_cellelem', @o_sub_same_promote_single_cellelem);
run_case('o_sub_same_promote_single_global', @o_sub_same_promote_single_global);
run_case('o_sub_same_promote_single_persistent', @o_sub_same_promote_single_persistent);
run_case('o_sub_same_demote_double_variable', @o_sub_same_demote_double_variable);
run_case('o_sub_same_demote_double_field', @o_sub_same_demote_double_field);
run_case('o_sub_same_demote_double_cellelem', @o_sub_same_demote_double_cellelem);
run_case('o_sub_same_demote_double_global', @o_sub_same_demote_double_global);
run_case('o_sub_same_demote_double_persistent', @o_sub_same_demote_double_persistent);
run_case('o_both_same_grow_double_variable', @o_both_same_grow_double_variable);
run_case('o_both_same_grow_double_field', @o_both_same_grow_double_field);
run_case('o_both_same_grow_double_cellelem', @o_both_same_grow_double_cellelem);
run_case('o_both_same_grow_double_global', @o_both_same_grow_double_global);
run_case('o_both_same_grow_double_persistent', @o_both_same_grow_double_persistent);
run_case('o_both_same_grow_single_variable', @o_both_same_grow_single_variable);
run_case('o_both_same_grow_single_field', @o_both_same_grow_single_field);
run_case('o_both_same_grow_single_cellelem', @o_both_same_grow_single_cellelem);
run_case('o_both_same_grow_single_global', @o_both_same_grow_single_global);
run_case('o_both_same_grow_single_persistent', @o_both_same_grow_single_persistent);
run_case('o_both_same_grow_int8_variable', @o_both_same_grow_int8_variable);
run_case('o_both_same_grow_int8_field', @o_both_same_grow_int8_field);
run_case('o_both_same_grow_int8_cellelem', @o_both_same_grow_int8_cellelem);
run_case('o_both_same_grow_int8_global', @o_both_same_grow_int8_global);
run_case('o_both_same_grow_int8_persistent', @o_both_same_grow_int8_persistent);

function run_case(name, fn)
global vlog_text
vlog_text = '';
try
    fprintf('CHK|%s|%s|exact\n', name, clean(fn()));
catch err
    fprintf('CHK|%s|ERR %s|exact\n', name, clean(err.message));
end
end

function s = clean(s)
if isnumeric(s) || islogical(s)
    s = mat2str(s);
end
s = char(s);
s = strrep(s, char(13), '');
s = strrep(s, char(10), ' ');
s = strrep(s, '|', '/');
end

function s = show(x)
% class, size and contents as text; a large array by its first two elements, its last and its sum.
sz = mat2str(size(x));
if isa(x, 'dictionary')
    ks = keys(x);
    parts = cell(1, numel(ks));
    for k = 1:numel(ks)
        parts{k} = sprintf('%s=%s', show(ks(k)), show(x(ks(k))));
    end
    s = sprintf('dictionary %d {%s}', numEntries(x), strjoin(parts, ' '));
elseif isa(x, 'ValueBox')
    s = sprintf('ValueBox p=%s', show(x.p));
elseif isstruct(x)
    if isscalar(x)
        fn = fieldnames(x);
        parts = cell(1, numel(fn));
        for k = 1:numel(fn)
            parts{k} = sprintf('%s=%s', fn{k}, show(x.(fn{k})));
        end
        s = sprintf('struct %s {%s}', sz, strjoin(parts, ' '));
    else
        fn = strjoin(fieldnames(x)', ',');
        if numel(x) <= 8
            parts = arrayfun(@(e) show_fields(e), x, 'UniformOutput', false);
            s = sprintf('struct %s [%s] {%s}', sz, fn, strjoin(parts(:)', ' '));
        else
            s = sprintf('struct %s [%s] {%s %s .. %s}', sz, fn, show_fields(x(1)), show_fields(x(2)), show_fields(x(end)));
        end
    end
elseif iscell(x)
    if numel(x) <= 8
        parts = cellfun(@show, x, 'UniformOutput', false);
        s = sprintf('cell %s {%s}', sz, strjoin(parts(:)', ' '));
    else
        s = sprintf('cell %s {%s %s .. %s}', sz, show(x{1}), show(x{2}), show(x{end}));
    end
elseif isstring(x)
    if numel(x) <= 8
        s = sprintf('string %s {%s}', sz, strjoin(cellstr(x(:)'), ' '));
    else
        s = sprintf('string %s {%s %s .. %s}', sz, x(1), x(2), x(end));
    end
elseif ischar(x)
    if numel(x) <= 16
        s = sprintf('char %s {%s}', sz, x(:)');
    else
        s = sprintf('char %s {%s%s..%s}', sz, x(1), x(2), x(end));
    end
elseif islogical(x)
    if numel(x) <= 8
        s = sprintf('logical %s %s', sz, mat2str(x));
    else
        d = double(x(:));
        s = sprintf('logical %s [%s %s .. %s] sum=%s', sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
elseif isnumeric(x) && ~isreal(x)
    % real and imaginary planes apart: mat2str's spelling of a complex array is its own line (#61)
    if numel(x) <= 8
        s = sprintf('%s %s re=%s im=%s', class(x), sz, mat2str(double(real(x))), mat2str(double(imag(x))));
    else
        d = double(real(x(:))); e = double(imag(x(:)));
        s = sprintf('%s %s re=[%s %s .. %s] sum=%s im=[%s %s .. %s] sum=%s', class(x), sz, ...
            mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)), ...
            mat2str(e(1)), mat2str(e(2)), mat2str(e(end)), mat2str(sum(e)));
    end
elseif isnumeric(x)
    if numel(x) <= 8
        s = sprintf('%s %s %s', class(x), sz, mat2str(double(x)));
    else
        d = double(x(:));
        s = sprintf('%s %s [%s %s .. %s] sum=%s', class(x), sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
else
    s = sprintf('%s %s', class(x), sz);
end
end

function s = show_fields(e)
fn = fieldnames(e);
parts = cell(1, numel(fn));
for k = 1:numel(fn)
    parts{k} = show(e.(fn{k}));
end
s = strjoin(parts, ',');
end

function s = o_permute_rhs_same_double_variable()
x = [3 1 2];
x([2 3 1]) = x;
s = show(x);
end

function s = o_permute_rhs_same_double_field()
st = struct(); st.v = [3 1 2];
st.v([2 3 1]) = st.v;
s = show(st.v);
end

function s = o_permute_rhs_same_double_cellelem()
c = {[3 1 2]};
c{1}([2 3 1]) = c{1};
s = show(c{1});
end

function s = o_permute_rhs_same_double_global()
global gO_4; gO_4 = [3 1 2];
gO_4([2 3 1]) = gO_4;
s = show(gO_4);
end

function s = o_permute_rhs_same_double_persistent()
persistent p; p = [3 1 2];
p([2 3 1]) = p;
s = show(p);
end

function s = o_permute_rhs_same_single_variable()
x = single([3 1 2]);
x([2 3 1]) = x;
s = show(x);
end

function s = o_permute_rhs_same_single_field()
st = struct(); st.v = single([3 1 2]);
st.v([2 3 1]) = st.v;
s = show(st.v);
end

function s = o_permute_rhs_same_single_cellelem()
c = {single([3 1 2])};
c{1}([2 3 1]) = c{1};
s = show(c{1});
end

function s = o_permute_rhs_same_single_global()
global gO_9; gO_9 = single([3 1 2]);
gO_9([2 3 1]) = gO_9;
s = show(gO_9);
end

function s = o_permute_rhs_same_single_persistent()
persistent p; p = single([3 1 2]);
p([2 3 1]) = p;
s = show(p);
end

function s = o_permute_rhs_same_int8_variable()
x = int8([3 1 2]);
x([2 3 1]) = x;
s = show(x);
end

function s = o_permute_rhs_same_int8_field()
st = struct(); st.v = int8([3 1 2]);
st.v([2 3 1]) = st.v;
s = show(st.v);
end

function s = o_permute_rhs_same_int8_cellelem()
c = {int8([3 1 2])};
c{1}([2 3 1]) = c{1};
s = show(c{1});
end

function s = o_permute_rhs_same_int8_global()
global gO_14; gO_14 = int8([3 1 2]);
gO_14([2 3 1]) = gO_14;
s = show(gO_14);
end

function s = o_permute_rhs_same_int8_persistent()
persistent p; p = int8([3 1 2]);
p([2 3 1]) = p;
s = show(p);
end

function s = o_permute_rhs_same_logical_variable()
x = [true false true];
x([2 3 1]) = x;
s = show(x);
end

function s = o_permute_rhs_same_logical_field()
st = struct(); st.v = [true false true];
st.v([2 3 1]) = st.v;
s = show(st.v);
end

function s = o_permute_rhs_same_logical_cellelem()
c = {[true false true]};
c{1}([2 3 1]) = c{1};
s = show(c{1});
end

function s = o_permute_rhs_same_logical_global()
global gO_19; gO_19 = [true false true];
gO_19([2 3 1]) = gO_19;
s = show(gO_19);
end

function s = o_permute_rhs_same_logical_persistent()
persistent p; p = [true false true];
p([2 3 1]) = p;
s = show(p);
end

function s = o_permute_rhs_same_char_variable()
x = 'cab';
x([2 3 1]) = x;
s = show(x);
end

function s = o_permute_rhs_same_char_field()
st = struct(); st.v = 'cab';
st.v([2 3 1]) = st.v;
s = show(st.v);
end

function s = o_permute_rhs_same_char_cellelem()
c = {'cab'};
c{1}([2 3 1]) = c{1};
s = show(c{1});
end

function s = o_permute_rhs_same_char_global()
global gO_24; gO_24 = 'cab';
gO_24([2 3 1]) = gO_24;
s = show(gO_24);
end

function s = o_permute_rhs_same_char_persistent()
persistent p; p = 'cab';
p([2 3 1]) = p;
s = show(p);
end

function s = o_permute_rhs_same_string_variable()
x = ["c" "a" "b"];
x([2 3 1]) = x;
s = show(x);
end

function s = o_permute_rhs_same_string_field()
st = struct(); st.v = ["c" "a" "b"];
st.v([2 3 1]) = st.v;
s = show(st.v);
end

function s = o_permute_rhs_same_string_cellelem()
c = {["c" "a" "b"]};
c{1}([2 3 1]) = c{1};
s = show(c{1});
end

function s = o_permute_rhs_same_string_global()
global gO_29; gO_29 = ["c" "a" "b"];
gO_29([2 3 1]) = gO_29;
s = show(gO_29);
end

function s = o_permute_rhs_same_string_persistent()
persistent p; p = ["c" "a" "b"];
p([2 3 1]) = p;
s = show(p);
end

function s = o_permute_rhs_same_complex_variable()
x = [3+1i 1 2];
x([2 3 1]) = x;
s = show(x);
end

function s = o_permute_rhs_same_complex_field()
st = struct(); st.v = [3+1i 1 2];
st.v([2 3 1]) = st.v;
s = show(st.v);
end

function s = o_permute_rhs_same_complex_cellelem()
c = {[3+1i 1 2]};
c{1}([2 3 1]) = c{1};
s = show(c{1});
end

function s = o_permute_rhs_same_complex_global()
global gO_34; gO_34 = [3+1i 1 2];
gO_34([2 3 1]) = gO_34;
s = show(gO_34);
end

function s = o_permute_rhs_same_complex_persistent()
persistent p; p = [3+1i 1 2];
p([2 3 1]) = p;
s = show(p);
end

function s = o_permute_rhs_same_cell_variable()
x = {3, 'a', 2};
x([2 3 1]) = x;
s = show(x);
end

function s = o_permute_rhs_same_cell_field()
st = struct(); st.v = {3, 'a', 2};
st.v([2 3 1]) = st.v;
s = show(st.v);
end

function s = o_permute_rhs_same_cell_cellelem()
c = {{3, 'a', 2}};
c{1}([2 3 1]) = c{1};
s = show(c{1});
end

function s = o_permute_rhs_same_cell_global()
global gO_39; gO_39 = {3, 'a', 2};
gO_39([2 3 1]) = gO_39;
s = show(gO_39);
end

function s = o_permute_rhs_same_cell_persistent()
persistent p; p = {3, 'a', 2};
p([2 3 1]) = p;
s = show(p);
end

function s = o_permute_rhs_same_structarr_variable()
x = struct('f', {3, 1, 2});
x([2 3 1]) = x;
s = show(x);
end

function s = o_permute_rhs_same_structarr_field()
st = struct(); st.v = struct('f', {3, 1, 2});
st.v([2 3 1]) = st.v;
s = show(st.v);
end

function s = o_permute_rhs_same_structarr_cellelem()
c = {struct('f', {3, 1, 2})};
c{1}([2 3 1]) = c{1};
s = show(c{1});
end

function s = o_permute_rhs_same_structarr_global()
global gO_44; gO_44 = struct('f', {3, 1, 2});
gO_44([2 3 1]) = gO_44;
s = show(gO_44);
end

function s = o_permute_rhs_same_structarr_persistent()
persistent p; p = struct('f', {3, 1, 2});
p([2 3 1]) = p;
s = show(p);
end

function s = o_permute_rhs_fresh_double_variable()
x = [3 1 2];
x([2 3 1]) = x([1 2 3]);
s = show(x);
end

function s = o_permute_rhs_fresh_double_field()
st = struct(); st.v = [3 1 2];
st.v([2 3 1]) = st.v([1 2 3]);
s = show(st.v);
end

function s = o_permute_rhs_fresh_double_cellelem()
c = {[3 1 2]};
c{1}([2 3 1]) = c{1}([1 2 3]);
s = show(c{1});
end

function s = o_permute_rhs_fresh_double_global()
global gO_49; gO_49 = [3 1 2];
gO_49([2 3 1]) = gO_49([1 2 3]);
s = show(gO_49);
end

function s = o_permute_rhs_fresh_double_persistent()
persistent p; p = [3 1 2];
p([2 3 1]) = p([1 2 3]);
s = show(p);
end

function s = o_permute_rhs_fresh_single_variable()
x = single([3 1 2]);
x([2 3 1]) = x([1 2 3]);
s = show(x);
end

function s = o_permute_rhs_fresh_single_field()
st = struct(); st.v = single([3 1 2]);
st.v([2 3 1]) = st.v([1 2 3]);
s = show(st.v);
end

function s = o_permute_rhs_fresh_single_cellelem()
c = {single([3 1 2])};
c{1}([2 3 1]) = c{1}([1 2 3]);
s = show(c{1});
end

function s = o_permute_rhs_fresh_single_global()
global gO_54; gO_54 = single([3 1 2]);
gO_54([2 3 1]) = gO_54([1 2 3]);
s = show(gO_54);
end

function s = o_permute_rhs_fresh_single_persistent()
persistent p; p = single([3 1 2]);
p([2 3 1]) = p([1 2 3]);
s = show(p);
end

function s = o_permute_rhs_fresh_int8_variable()
x = int8([3 1 2]);
x([2 3 1]) = x([1 2 3]);
s = show(x);
end

function s = o_permute_rhs_fresh_int8_field()
st = struct(); st.v = int8([3 1 2]);
st.v([2 3 1]) = st.v([1 2 3]);
s = show(st.v);
end

function s = o_permute_rhs_fresh_int8_cellelem()
c = {int8([3 1 2])};
c{1}([2 3 1]) = c{1}([1 2 3]);
s = show(c{1});
end

function s = o_permute_rhs_fresh_int8_global()
global gO_59; gO_59 = int8([3 1 2]);
gO_59([2 3 1]) = gO_59([1 2 3]);
s = show(gO_59);
end

function s = o_permute_rhs_fresh_int8_persistent()
persistent p; p = int8([3 1 2]);
p([2 3 1]) = p([1 2 3]);
s = show(p);
end

function s = o_permute_rhs_fresh_logical_variable()
x = [true false true];
x([2 3 1]) = x([1 2 3]);
s = show(x);
end

function s = o_permute_rhs_fresh_logical_field()
st = struct(); st.v = [true false true];
st.v([2 3 1]) = st.v([1 2 3]);
s = show(st.v);
end

function s = o_permute_rhs_fresh_logical_cellelem()
c = {[true false true]};
c{1}([2 3 1]) = c{1}([1 2 3]);
s = show(c{1});
end

function s = o_permute_rhs_fresh_logical_global()
global gO_64; gO_64 = [true false true];
gO_64([2 3 1]) = gO_64([1 2 3]);
s = show(gO_64);
end

function s = o_permute_rhs_fresh_logical_persistent()
persistent p; p = [true false true];
p([2 3 1]) = p([1 2 3]);
s = show(p);
end

function s = o_permute_rhs_fresh_char_variable()
x = 'cab';
x([2 3 1]) = x([1 2 3]);
s = show(x);
end

function s = o_permute_rhs_fresh_char_field()
st = struct(); st.v = 'cab';
st.v([2 3 1]) = st.v([1 2 3]);
s = show(st.v);
end

function s = o_permute_rhs_fresh_char_cellelem()
c = {'cab'};
c{1}([2 3 1]) = c{1}([1 2 3]);
s = show(c{1});
end

function s = o_permute_rhs_fresh_char_global()
global gO_69; gO_69 = 'cab';
gO_69([2 3 1]) = gO_69([1 2 3]);
s = show(gO_69);
end

function s = o_permute_rhs_fresh_char_persistent()
persistent p; p = 'cab';
p([2 3 1]) = p([1 2 3]);
s = show(p);
end

function s = o_permute_rhs_fresh_string_variable()
x = ["c" "a" "b"];
x([2 3 1]) = x([1 2 3]);
s = show(x);
end

function s = o_permute_rhs_fresh_string_field()
st = struct(); st.v = ["c" "a" "b"];
st.v([2 3 1]) = st.v([1 2 3]);
s = show(st.v);
end

function s = o_permute_rhs_fresh_string_cellelem()
c = {["c" "a" "b"]};
c{1}([2 3 1]) = c{1}([1 2 3]);
s = show(c{1});
end

function s = o_permute_rhs_fresh_string_global()
global gO_74; gO_74 = ["c" "a" "b"];
gO_74([2 3 1]) = gO_74([1 2 3]);
s = show(gO_74);
end

function s = o_permute_rhs_fresh_string_persistent()
persistent p; p = ["c" "a" "b"];
p([2 3 1]) = p([1 2 3]);
s = show(p);
end

function s = o_permute_rhs_fresh_complex_variable()
x = [3+1i 1 2];
x([2 3 1]) = x([1 2 3]);
s = show(x);
end

function s = o_permute_rhs_fresh_complex_field()
st = struct(); st.v = [3+1i 1 2];
st.v([2 3 1]) = st.v([1 2 3]);
s = show(st.v);
end

function s = o_permute_rhs_fresh_complex_cellelem()
c = {[3+1i 1 2]};
c{1}([2 3 1]) = c{1}([1 2 3]);
s = show(c{1});
end

function s = o_permute_rhs_fresh_complex_global()
global gO_79; gO_79 = [3+1i 1 2];
gO_79([2 3 1]) = gO_79([1 2 3]);
s = show(gO_79);
end

function s = o_permute_rhs_fresh_complex_persistent()
persistent p; p = [3+1i 1 2];
p([2 3 1]) = p([1 2 3]);
s = show(p);
end

function s = o_permute_rhs_fresh_cell_variable()
x = {3, 'a', 2};
x([2 3 1]) = x([1 2 3]);
s = show(x);
end

function s = o_permute_rhs_fresh_cell_field()
st = struct(); st.v = {3, 'a', 2};
st.v([2 3 1]) = st.v([1 2 3]);
s = show(st.v);
end

function s = o_permute_rhs_fresh_cell_cellelem()
c = {{3, 'a', 2}};
c{1}([2 3 1]) = c{1}([1 2 3]);
s = show(c{1});
end

function s = o_permute_rhs_fresh_cell_global()
global gO_84; gO_84 = {3, 'a', 2};
gO_84([2 3 1]) = gO_84([1 2 3]);
s = show(gO_84);
end

function s = o_permute_rhs_fresh_cell_persistent()
persistent p; p = {3, 'a', 2};
p([2 3 1]) = p([1 2 3]);
s = show(p);
end

function s = o_permute_rhs_fresh_structarr_variable()
x = struct('f', {3, 1, 2});
x([2 3 1]) = x([1 2 3]);
s = show(x);
end

function s = o_permute_rhs_fresh_structarr_field()
st = struct(); st.v = struct('f', {3, 1, 2});
st.v([2 3 1]) = st.v([1 2 3]);
s = show(st.v);
end

function s = o_permute_rhs_fresh_structarr_cellelem()
c = {struct('f', {3, 1, 2})};
c{1}([2 3 1]) = c{1}([1 2 3]);
s = show(c{1});
end

function s = o_permute_rhs_fresh_structarr_global()
global gO_89; gO_89 = struct('f', {3, 1, 2});
gO_89([2 3 1]) = gO_89([1 2 3]);
s = show(gO_89);
end

function s = o_permute_rhs_fresh_structarr_persistent()
persistent p; p = struct('f', {3, 1, 2});
p([2 3 1]) = p([1 2 3]);
s = show(p);
end

function s = o_shift_rhs_fresh_double_variable()
x = [3 1 2];
x(2:3) = x(1:2);
s = show(x);
end

function s = o_shift_rhs_fresh_double_field()
st = struct(); st.v = [3 1 2];
st.v(2:3) = st.v(1:2);
s = show(st.v);
end

function s = o_shift_rhs_fresh_double_cellelem()
c = {[3 1 2]};
c{1}(2:3) = c{1}(1:2);
s = show(c{1});
end

function s = o_shift_rhs_fresh_double_global()
global gO_94; gO_94 = [3 1 2];
gO_94(2:3) = gO_94(1:2);
s = show(gO_94);
end

function s = o_shift_rhs_fresh_double_persistent()
persistent p; p = [3 1 2];
p(2:3) = p(1:2);
s = show(p);
end

function s = o_shift_rhs_fresh_single_variable()
x = single([3 1 2]);
x(2:3) = x(1:2);
s = show(x);
end

function s = o_shift_rhs_fresh_single_field()
st = struct(); st.v = single([3 1 2]);
st.v(2:3) = st.v(1:2);
s = show(st.v);
end

function s = o_shift_rhs_fresh_single_cellelem()
c = {single([3 1 2])};
c{1}(2:3) = c{1}(1:2);
s = show(c{1});
end

function s = o_shift_rhs_fresh_single_global()
global gO_99; gO_99 = single([3 1 2]);
gO_99(2:3) = gO_99(1:2);
s = show(gO_99);
end

function s = o_shift_rhs_fresh_single_persistent()
persistent p; p = single([3 1 2]);
p(2:3) = p(1:2);
s = show(p);
end

function s = o_shift_rhs_fresh_int8_variable()
x = int8([3 1 2]);
x(2:3) = x(1:2);
s = show(x);
end

function s = o_shift_rhs_fresh_int8_field()
st = struct(); st.v = int8([3 1 2]);
st.v(2:3) = st.v(1:2);
s = show(st.v);
end

function s = o_shift_rhs_fresh_int8_cellelem()
c = {int8([3 1 2])};
c{1}(2:3) = c{1}(1:2);
s = show(c{1});
end

function s = o_shift_rhs_fresh_int8_global()
global gO_104; gO_104 = int8([3 1 2]);
gO_104(2:3) = gO_104(1:2);
s = show(gO_104);
end

function s = o_shift_rhs_fresh_int8_persistent()
persistent p; p = int8([3 1 2]);
p(2:3) = p(1:2);
s = show(p);
end

function s = o_shift_rhs_fresh_logical_variable()
x = [true false true];
x(2:3) = x(1:2);
s = show(x);
end

function s = o_shift_rhs_fresh_logical_field()
st = struct(); st.v = [true false true];
st.v(2:3) = st.v(1:2);
s = show(st.v);
end

function s = o_shift_rhs_fresh_logical_cellelem()
c = {[true false true]};
c{1}(2:3) = c{1}(1:2);
s = show(c{1});
end

function s = o_shift_rhs_fresh_logical_global()
global gO_109; gO_109 = [true false true];
gO_109(2:3) = gO_109(1:2);
s = show(gO_109);
end

function s = o_shift_rhs_fresh_logical_persistent()
persistent p; p = [true false true];
p(2:3) = p(1:2);
s = show(p);
end

function s = o_shift_rhs_fresh_char_variable()
x = 'cab';
x(2:3) = x(1:2);
s = show(x);
end

function s = o_shift_rhs_fresh_char_field()
st = struct(); st.v = 'cab';
st.v(2:3) = st.v(1:2);
s = show(st.v);
end

function s = o_shift_rhs_fresh_char_cellelem()
c = {'cab'};
c{1}(2:3) = c{1}(1:2);
s = show(c{1});
end

function s = o_shift_rhs_fresh_char_global()
global gO_114; gO_114 = 'cab';
gO_114(2:3) = gO_114(1:2);
s = show(gO_114);
end

function s = o_shift_rhs_fresh_char_persistent()
persistent p; p = 'cab';
p(2:3) = p(1:2);
s = show(p);
end

function s = o_shift_rhs_fresh_string_variable()
x = ["c" "a" "b"];
x(2:3) = x(1:2);
s = show(x);
end

function s = o_shift_rhs_fresh_string_field()
st = struct(); st.v = ["c" "a" "b"];
st.v(2:3) = st.v(1:2);
s = show(st.v);
end

function s = o_shift_rhs_fresh_string_cellelem()
c = {["c" "a" "b"]};
c{1}(2:3) = c{1}(1:2);
s = show(c{1});
end

function s = o_shift_rhs_fresh_string_global()
global gO_119; gO_119 = ["c" "a" "b"];
gO_119(2:3) = gO_119(1:2);
s = show(gO_119);
end

function s = o_shift_rhs_fresh_string_persistent()
persistent p; p = ["c" "a" "b"];
p(2:3) = p(1:2);
s = show(p);
end

function s = o_shift_rhs_fresh_complex_variable()
x = [3+1i 1 2];
x(2:3) = x(1:2);
s = show(x);
end

function s = o_shift_rhs_fresh_complex_field()
st = struct(); st.v = [3+1i 1 2];
st.v(2:3) = st.v(1:2);
s = show(st.v);
end

function s = o_shift_rhs_fresh_complex_cellelem()
c = {[3+1i 1 2]};
c{1}(2:3) = c{1}(1:2);
s = show(c{1});
end

function s = o_shift_rhs_fresh_complex_global()
global gO_124; gO_124 = [3+1i 1 2];
gO_124(2:3) = gO_124(1:2);
s = show(gO_124);
end

function s = o_shift_rhs_fresh_complex_persistent()
persistent p; p = [3+1i 1 2];
p(2:3) = p(1:2);
s = show(p);
end

function s = o_shift_rhs_fresh_cell_variable()
x = {3, 'a', 2};
x(2:3) = x(1:2);
s = show(x);
end

function s = o_shift_rhs_fresh_cell_field()
st = struct(); st.v = {3, 'a', 2};
st.v(2:3) = st.v(1:2);
s = show(st.v);
end

function s = o_shift_rhs_fresh_cell_cellelem()
c = {{3, 'a', 2}};
c{1}(2:3) = c{1}(1:2);
s = show(c{1});
end

function s = o_shift_rhs_fresh_cell_global()
global gO_129; gO_129 = {3, 'a', 2};
gO_129(2:3) = gO_129(1:2);
s = show(gO_129);
end

function s = o_shift_rhs_fresh_cell_persistent()
persistent p; p = {3, 'a', 2};
p(2:3) = p(1:2);
s = show(p);
end

function s = o_shift_rhs_fresh_structarr_variable()
x = struct('f', {3, 1, 2});
x(2:3) = x(1:2);
s = show(x);
end

function s = o_shift_rhs_fresh_structarr_field()
st = struct(); st.v = struct('f', {3, 1, 2});
st.v(2:3) = st.v(1:2);
s = show(st.v);
end

function s = o_shift_rhs_fresh_structarr_cellelem()
c = {struct('f', {3, 1, 2})};
c{1}(2:3) = c{1}(1:2);
s = show(c{1});
end

function s = o_shift_rhs_fresh_structarr_global()
global gO_134; gO_134 = struct('f', {3, 1, 2});
gO_134(2:3) = gO_134(1:2);
s = show(gO_134);
end

function s = o_shift_rhs_fresh_structarr_persistent()
persistent p; p = struct('f', {3, 1, 2});
p(2:3) = p(1:2);
s = show(p);
end

function s = o_grow_rhs_same_double_variable()
x = [3 1 2];
x(4:6) = x;
s = show(x);
end

function s = o_grow_rhs_same_double_field()
st = struct(); st.v = [3 1 2];
st.v(4:6) = st.v;
s = show(st.v);
end

function s = o_grow_rhs_same_double_cellelem()
c = {[3 1 2]};
c{1}(4:6) = c{1};
s = show(c{1});
end

function s = o_grow_rhs_same_double_global()
global gO_139; gO_139 = [3 1 2];
gO_139(4:6) = gO_139;
s = show(gO_139);
end

function s = o_grow_rhs_same_double_persistent()
persistent p; p = [3 1 2];
p(4:6) = p;
s = show(p);
end

function s = o_grow_rhs_same_single_variable()
x = single([3 1 2]);
x(4:6) = x;
s = show(x);
end

function s = o_grow_rhs_same_single_field()
st = struct(); st.v = single([3 1 2]);
st.v(4:6) = st.v;
s = show(st.v);
end

function s = o_grow_rhs_same_single_cellelem()
c = {single([3 1 2])};
c{1}(4:6) = c{1};
s = show(c{1});
end

function s = o_grow_rhs_same_single_global()
global gO_144; gO_144 = single([3 1 2]);
gO_144(4:6) = gO_144;
s = show(gO_144);
end

function s = o_grow_rhs_same_single_persistent()
persistent p; p = single([3 1 2]);
p(4:6) = p;
s = show(p);
end

function s = o_grow_rhs_same_int8_variable()
x = int8([3 1 2]);
x(4:6) = x;
s = show(x);
end

function s = o_grow_rhs_same_int8_field()
st = struct(); st.v = int8([3 1 2]);
st.v(4:6) = st.v;
s = show(st.v);
end

function s = o_grow_rhs_same_int8_cellelem()
c = {int8([3 1 2])};
c{1}(4:6) = c{1};
s = show(c{1});
end

function s = o_grow_rhs_same_int8_global()
global gO_149; gO_149 = int8([3 1 2]);
gO_149(4:6) = gO_149;
s = show(gO_149);
end

function s = o_grow_rhs_same_int8_persistent()
persistent p; p = int8([3 1 2]);
p(4:6) = p;
s = show(p);
end

function s = o_grow_rhs_same_logical_variable()
x = [true false true];
x(4:6) = x;
s = show(x);
end

function s = o_grow_rhs_same_logical_field()
st = struct(); st.v = [true false true];
st.v(4:6) = st.v;
s = show(st.v);
end

function s = o_grow_rhs_same_logical_cellelem()
c = {[true false true]};
c{1}(4:6) = c{1};
s = show(c{1});
end

function s = o_grow_rhs_same_logical_global()
global gO_154; gO_154 = [true false true];
gO_154(4:6) = gO_154;
s = show(gO_154);
end

function s = o_grow_rhs_same_logical_persistent()
persistent p; p = [true false true];
p(4:6) = p;
s = show(p);
end

function s = o_grow_rhs_same_char_variable()
x = 'cab';
x(4:6) = x;
s = show(x);
end

function s = o_grow_rhs_same_char_field()
st = struct(); st.v = 'cab';
st.v(4:6) = st.v;
s = show(st.v);
end

function s = o_grow_rhs_same_char_cellelem()
c = {'cab'};
c{1}(4:6) = c{1};
s = show(c{1});
end

function s = o_grow_rhs_same_char_global()
global gO_159; gO_159 = 'cab';
gO_159(4:6) = gO_159;
s = show(gO_159);
end

function s = o_grow_rhs_same_char_persistent()
persistent p; p = 'cab';
p(4:6) = p;
s = show(p);
end

function s = o_grow_rhs_same_string_variable()
x = ["c" "a" "b"];
x(4:6) = x;
s = show(x);
end

function s = o_grow_rhs_same_string_field()
st = struct(); st.v = ["c" "a" "b"];
st.v(4:6) = st.v;
s = show(st.v);
end

function s = o_grow_rhs_same_string_cellelem()
c = {["c" "a" "b"]};
c{1}(4:6) = c{1};
s = show(c{1});
end

function s = o_grow_rhs_same_string_global()
global gO_164; gO_164 = ["c" "a" "b"];
gO_164(4:6) = gO_164;
s = show(gO_164);
end

function s = o_grow_rhs_same_string_persistent()
persistent p; p = ["c" "a" "b"];
p(4:6) = p;
s = show(p);
end

function s = o_grow_rhs_same_complex_variable()
x = [3+1i 1 2];
x(4:6) = x;
s = show(x);
end

function s = o_grow_rhs_same_complex_field()
st = struct(); st.v = [3+1i 1 2];
st.v(4:6) = st.v;
s = show(st.v);
end

function s = o_grow_rhs_same_complex_cellelem()
c = {[3+1i 1 2]};
c{1}(4:6) = c{1};
s = show(c{1});
end

function s = o_grow_rhs_same_complex_global()
global gO_169; gO_169 = [3+1i 1 2];
gO_169(4:6) = gO_169;
s = show(gO_169);
end

function s = o_grow_rhs_same_complex_persistent()
persistent p; p = [3+1i 1 2];
p(4:6) = p;
s = show(p);
end

function s = o_grow_rhs_same_cell_variable()
x = {3, 'a', 2};
x(4:6) = x;
s = show(x);
end

function s = o_grow_rhs_same_cell_field()
st = struct(); st.v = {3, 'a', 2};
st.v(4:6) = st.v;
s = show(st.v);
end

function s = o_grow_rhs_same_cell_cellelem()
c = {{3, 'a', 2}};
c{1}(4:6) = c{1};
s = show(c{1});
end

function s = o_grow_rhs_same_cell_global()
global gO_174; gO_174 = {3, 'a', 2};
gO_174(4:6) = gO_174;
s = show(gO_174);
end

function s = o_grow_rhs_same_cell_persistent()
persistent p; p = {3, 'a', 2};
p(4:6) = p;
s = show(p);
end

function s = o_grow_rhs_same_structarr_variable()
x = struct('f', {3, 1, 2});
x(4:6) = x;
s = show(x);
end

function s = o_grow_rhs_same_structarr_field()
st = struct(); st.v = struct('f', {3, 1, 2});
st.v(4:6) = st.v;
s = show(st.v);
end

function s = o_grow_rhs_same_structarr_cellelem()
c = {struct('f', {3, 1, 2})};
c{1}(4:6) = c{1};
s = show(c{1});
end

function s = o_grow_rhs_same_structarr_global()
global gO_179; gO_179 = struct('f', {3, 1, 2});
gO_179(4:6) = gO_179;
s = show(gO_179);
end

function s = o_grow_rhs_same_structarr_persistent()
persistent p; p = struct('f', {3, 1, 2});
p(4:6) = p;
s = show(p);
end

function s = o_grow_end_rhs_same_double_variable()
x = [3 1 2];
x(end + 1:end + 3) = x;
s = show(x);
end

function s = o_grow_end_rhs_same_double_field()
st = struct(); st.v = [3 1 2];
st.v(end + 1:end + 3) = st.v;
s = show(st.v);
end

function s = o_grow_end_rhs_same_double_cellelem()
c = {[3 1 2]};
c{1}(end + 1:end + 3) = c{1};
s = show(c{1});
end

function s = o_grow_end_rhs_same_double_global()
global gO_184; gO_184 = [3 1 2];
gO_184(end + 1:end + 3) = gO_184;
s = show(gO_184);
end

function s = o_grow_end_rhs_same_double_persistent()
persistent p; p = [3 1 2];
p(end + 1:end + 3) = p;
s = show(p);
end

function s = o_grow_end_rhs_same_single_variable()
x = single([3 1 2]);
x(end + 1:end + 3) = x;
s = show(x);
end

function s = o_grow_end_rhs_same_single_field()
st = struct(); st.v = single([3 1 2]);
st.v(end + 1:end + 3) = st.v;
s = show(st.v);
end

function s = o_grow_end_rhs_same_single_cellelem()
c = {single([3 1 2])};
c{1}(end + 1:end + 3) = c{1};
s = show(c{1});
end

function s = o_grow_end_rhs_same_single_global()
global gO_189; gO_189 = single([3 1 2]);
gO_189(end + 1:end + 3) = gO_189;
s = show(gO_189);
end

function s = o_grow_end_rhs_same_single_persistent()
persistent p; p = single([3 1 2]);
p(end + 1:end + 3) = p;
s = show(p);
end

function s = o_grow_end_rhs_same_int8_variable()
x = int8([3 1 2]);
x(end + 1:end + 3) = x;
s = show(x);
end

function s = o_grow_end_rhs_same_int8_field()
st = struct(); st.v = int8([3 1 2]);
st.v(end + 1:end + 3) = st.v;
s = show(st.v);
end

function s = o_grow_end_rhs_same_int8_cellelem()
c = {int8([3 1 2])};
c{1}(end + 1:end + 3) = c{1};
s = show(c{1});
end

function s = o_grow_end_rhs_same_int8_global()
global gO_194; gO_194 = int8([3 1 2]);
gO_194(end + 1:end + 3) = gO_194;
s = show(gO_194);
end

function s = o_grow_end_rhs_same_int8_persistent()
persistent p; p = int8([3 1 2]);
p(end + 1:end + 3) = p;
s = show(p);
end

function s = o_grow_end_rhs_same_logical_variable()
x = [true false true];
x(end + 1:end + 3) = x;
s = show(x);
end

function s = o_grow_end_rhs_same_logical_field()
st = struct(); st.v = [true false true];
st.v(end + 1:end + 3) = st.v;
s = show(st.v);
end

function s = o_grow_end_rhs_same_logical_cellelem()
c = {[true false true]};
c{1}(end + 1:end + 3) = c{1};
s = show(c{1});
end

function s = o_grow_end_rhs_same_logical_global()
global gO_199; gO_199 = [true false true];
gO_199(end + 1:end + 3) = gO_199;
s = show(gO_199);
end

function s = o_grow_end_rhs_same_logical_persistent()
persistent p; p = [true false true];
p(end + 1:end + 3) = p;
s = show(p);
end

function s = o_grow_end_rhs_same_char_variable()
x = 'cab';
x(end + 1:end + 3) = x;
s = show(x);
end

function s = o_grow_end_rhs_same_char_field()
st = struct(); st.v = 'cab';
st.v(end + 1:end + 3) = st.v;
s = show(st.v);
end

function s = o_grow_end_rhs_same_char_cellelem()
c = {'cab'};
c{1}(end + 1:end + 3) = c{1};
s = show(c{1});
end

function s = o_grow_end_rhs_same_char_global()
global gO_204; gO_204 = 'cab';
gO_204(end + 1:end + 3) = gO_204;
s = show(gO_204);
end

function s = o_grow_end_rhs_same_char_persistent()
persistent p; p = 'cab';
p(end + 1:end + 3) = p;
s = show(p);
end

function s = o_grow_end_rhs_same_string_variable()
x = ["c" "a" "b"];
x(end + 1:end + 3) = x;
s = show(x);
end

function s = o_grow_end_rhs_same_string_field()
st = struct(); st.v = ["c" "a" "b"];
st.v(end + 1:end + 3) = st.v;
s = show(st.v);
end

function s = o_grow_end_rhs_same_string_cellelem()
c = {["c" "a" "b"]};
c{1}(end + 1:end + 3) = c{1};
s = show(c{1});
end

function s = o_grow_end_rhs_same_string_global()
global gO_209; gO_209 = ["c" "a" "b"];
gO_209(end + 1:end + 3) = gO_209;
s = show(gO_209);
end

function s = o_grow_end_rhs_same_string_persistent()
persistent p; p = ["c" "a" "b"];
p(end + 1:end + 3) = p;
s = show(p);
end

function s = o_grow_end_rhs_same_complex_variable()
x = [3+1i 1 2];
x(end + 1:end + 3) = x;
s = show(x);
end

function s = o_grow_end_rhs_same_complex_field()
st = struct(); st.v = [3+1i 1 2];
st.v(end + 1:end + 3) = st.v;
s = show(st.v);
end

function s = o_grow_end_rhs_same_complex_cellelem()
c = {[3+1i 1 2]};
c{1}(end + 1:end + 3) = c{1};
s = show(c{1});
end

function s = o_grow_end_rhs_same_complex_global()
global gO_214; gO_214 = [3+1i 1 2];
gO_214(end + 1:end + 3) = gO_214;
s = show(gO_214);
end

function s = o_grow_end_rhs_same_complex_persistent()
persistent p; p = [3+1i 1 2];
p(end + 1:end + 3) = p;
s = show(p);
end

function s = o_grow_end_rhs_same_cell_variable()
x = {3, 'a', 2};
x(end + 1:end + 3) = x;
s = show(x);
end

function s = o_grow_end_rhs_same_cell_field()
st = struct(); st.v = {3, 'a', 2};
st.v(end + 1:end + 3) = st.v;
s = show(st.v);
end

function s = o_grow_end_rhs_same_cell_cellelem()
c = {{3, 'a', 2}};
c{1}(end + 1:end + 3) = c{1};
s = show(c{1});
end

function s = o_grow_end_rhs_same_cell_global()
global gO_219; gO_219 = {3, 'a', 2};
gO_219(end + 1:end + 3) = gO_219;
s = show(gO_219);
end

function s = o_grow_end_rhs_same_cell_persistent()
persistent p; p = {3, 'a', 2};
p(end + 1:end + 3) = p;
s = show(p);
end

function s = o_grow_end_rhs_same_structarr_variable()
x = struct('f', {3, 1, 2});
x(end + 1:end + 3) = x;
s = show(x);
end

function s = o_grow_end_rhs_same_structarr_field()
st = struct(); st.v = struct('f', {3, 1, 2});
st.v(end + 1:end + 3) = st.v;
s = show(st.v);
end

function s = o_grow_end_rhs_same_structarr_cellelem()
c = {struct('f', {3, 1, 2})};
c{1}(end + 1:end + 3) = c{1};
s = show(c{1});
end

function s = o_grow_end_rhs_same_structarr_global()
global gO_224; gO_224 = struct('f', {3, 1, 2});
gO_224(end + 1:end + 3) = gO_224;
s = show(gO_224);
end

function s = o_grow_end_rhs_same_structarr_persistent()
persistent p; p = struct('f', {3, 1, 2});
p(end + 1:end + 3) = p;
s = show(p);
end

function s = o_sub_same_double_variable()
x = [3 1 2];
x(x) = 9;
s = show(x);
end

function s = o_sub_same_double_field()
st = struct(); st.v = [3 1 2];
st.v(st.v) = 9;
s = show(st.v);
end

function s = o_sub_same_double_cellelem()
c = {[3 1 2]};
c{1}(c{1}) = 9;
s = show(c{1});
end

function s = o_sub_same_double_global()
global gO_229; gO_229 = [3 1 2];
gO_229(gO_229) = 9;
s = show(gO_229);
end

function s = o_sub_same_double_persistent()
persistent p; p = [3 1 2];
p(p) = 9;
s = show(p);
end

function s = o_sub_same_single_variable()
x = single([3 1 2]);
x(x) = 9;
s = show(x);
end

function s = o_sub_same_single_field()
st = struct(); st.v = single([3 1 2]);
st.v(st.v) = 9;
s = show(st.v);
end

function s = o_sub_same_single_cellelem()
c = {single([3 1 2])};
c{1}(c{1}) = 9;
s = show(c{1});
end

function s = o_sub_same_single_global()
global gO_234; gO_234 = single([3 1 2]);
gO_234(gO_234) = 9;
s = show(gO_234);
end

function s = o_sub_same_single_persistent()
persistent p; p = single([3 1 2]);
p(p) = 9;
s = show(p);
end

function s = o_sub_same_int8_variable()
x = int8([3 1 2]);
x(x) = 9;
s = show(x);
end

function s = o_sub_same_int8_field()
st = struct(); st.v = int8([3 1 2]);
st.v(st.v) = 9;
s = show(st.v);
end

function s = o_sub_same_int8_cellelem()
c = {int8([3 1 2])};
c{1}(c{1}) = 9;
s = show(c{1});
end

function s = o_sub_same_int8_global()
global gO_239; gO_239 = int8([3 1 2]);
gO_239(gO_239) = 9;
s = show(gO_239);
end

function s = o_sub_same_int8_persistent()
persistent p; p = int8([3 1 2]);
p(p) = 9;
s = show(p);
end

function s = o_sub_same_mask_logical_variable()
x = [true false true];
x(x) = false;
s = show(x);
end

function s = o_sub_same_mask_logical_field()
st = struct(); st.v = [true false true];
st.v(st.v) = false;
s = show(st.v);
end

function s = o_sub_same_mask_logical_cellelem()
c = {[true false true]};
c{1}(c{1}) = false;
s = show(c{1});
end

function s = o_sub_same_mask_logical_global()
global gO_244; gO_244 = [true false true];
gO_244(gO_244) = false;
s = show(gO_244);
end

function s = o_sub_same_mask_logical_persistent()
persistent p; p = [true false true];
p(p) = false;
s = show(p);
end

function s = o_both_same_double_variable()
x = [3 1 2];
x(x) = x;
s = show(x);
end

function s = o_both_same_double_field()
st = struct(); st.v = [3 1 2];
st.v(st.v) = st.v;
s = show(st.v);
end

function s = o_both_same_double_cellelem()
c = {[3 1 2]};
c{1}(c{1}) = c{1};
s = show(c{1});
end

function s = o_both_same_double_global()
global gO_249; gO_249 = [3 1 2];
gO_249(gO_249) = gO_249;
s = show(gO_249);
end

function s = o_both_same_double_persistent()
persistent p; p = [3 1 2];
p(p) = p;
s = show(p);
end

function s = o_both_same_single_variable()
x = single([3 1 2]);
x(x) = x;
s = show(x);
end

function s = o_both_same_single_field()
st = struct(); st.v = single([3 1 2]);
st.v(st.v) = st.v;
s = show(st.v);
end

function s = o_both_same_single_cellelem()
c = {single([3 1 2])};
c{1}(c{1}) = c{1};
s = show(c{1});
end

function s = o_both_same_single_global()
global gO_254; gO_254 = single([3 1 2]);
gO_254(gO_254) = gO_254;
s = show(gO_254);
end

function s = o_both_same_single_persistent()
persistent p; p = single([3 1 2]);
p(p) = p;
s = show(p);
end

function s = o_both_same_int8_variable()
x = int8([3 1 2]);
x(x) = x;
s = show(x);
end

function s = o_both_same_int8_field()
st = struct(); st.v = int8([3 1 2]);
st.v(st.v) = st.v;
s = show(st.v);
end

function s = o_both_same_int8_cellelem()
c = {int8([3 1 2])};
c{1}(c{1}) = c{1};
s = show(c{1});
end

function s = o_both_same_int8_global()
global gO_259; gO_259 = int8([3 1 2]);
gO_259(gO_259) = gO_259;
s = show(gO_259);
end

function s = o_both_same_int8_persistent()
persistent p; p = int8([3 1 2]);
p(p) = p;
s = show(p);
end

function s = o_sub_same_promote_double_variable()
x = [3 1 2];
x(x) = 1i;
s = show(x);
end

function s = o_sub_same_promote_double_field()
st = struct(); st.v = [3 1 2];
st.v(st.v) = 1i;
s = show(st.v);
end

function s = o_sub_same_promote_double_cellelem()
c = {[3 1 2]};
c{1}(c{1}) = 1i;
s = show(c{1});
end

function s = o_sub_same_promote_double_global()
global gO_264; gO_264 = [3 1 2];
gO_264(gO_264) = 1i;
s = show(gO_264);
end

function s = o_sub_same_promote_double_persistent()
persistent p; p = [3 1 2];
p(p) = 1i;
s = show(p);
end

function s = o_sub_same_promote_single_variable()
x = single([3 1 2]);
x(x) = 1i;
s = show(x);
end

function s = o_sub_same_promote_single_field()
st = struct(); st.v = single([3 1 2]);
st.v(st.v) = 1i;
s = show(st.v);
end

function s = o_sub_same_promote_single_cellelem()
c = {single([3 1 2])};
c{1}(c{1}) = 1i;
s = show(c{1});
end

function s = o_sub_same_promote_single_global()
global gO_269; gO_269 = single([3 1 2]);
gO_269(gO_269) = 1i;
s = show(gO_269);
end

function s = o_sub_same_promote_single_persistent()
persistent p; p = single([3 1 2]);
p(p) = 1i;
s = show(p);
end

function s = o_sub_same_demote_double_variable()
x = [3 1 2];
x(x) = 'a';
s = show(x);
end

function s = o_sub_same_demote_double_field()
st = struct(); st.v = [3 1 2];
st.v(st.v) = 'a';
s = show(st.v);
end

function s = o_sub_same_demote_double_cellelem()
c = {[3 1 2]};
c{1}(c{1}) = 'a';
s = show(c{1});
end

function s = o_sub_same_demote_double_global()
global gO_274; gO_274 = [3 1 2];
gO_274(gO_274) = 'a';
s = show(gO_274);
end

function s = o_sub_same_demote_double_persistent()
persistent p; p = [3 1 2];
p(p) = 'a';
s = show(p);
end

function s = o_both_same_grow_double_variable()
x = [3 1 2];
x(x + 3) = x;
s = show(x);
end

function s = o_both_same_grow_double_field()
st = struct(); st.v = [3 1 2];
st.v(st.v + 3) = st.v;
s = show(st.v);
end

function s = o_both_same_grow_double_cellelem()
c = {[3 1 2]};
c{1}(c{1} + 3) = c{1};
s = show(c{1});
end

function s = o_both_same_grow_double_global()
global gO_279; gO_279 = [3 1 2];
gO_279(gO_279 + 3) = gO_279;
s = show(gO_279);
end

function s = o_both_same_grow_double_persistent()
persistent p; p = [3 1 2];
p(p + 3) = p;
s = show(p);
end

function s = o_both_same_grow_single_variable()
x = single([3 1 2]);
x(x + 3) = x;
s = show(x);
end

function s = o_both_same_grow_single_field()
st = struct(); st.v = single([3 1 2]);
st.v(st.v + 3) = st.v;
s = show(st.v);
end

function s = o_both_same_grow_single_cellelem()
c = {single([3 1 2])};
c{1}(c{1} + 3) = c{1};
s = show(c{1});
end

function s = o_both_same_grow_single_global()
global gO_284; gO_284 = single([3 1 2]);
gO_284(gO_284 + 3) = gO_284;
s = show(gO_284);
end

function s = o_both_same_grow_single_persistent()
persistent p; p = single([3 1 2]);
p(p + 3) = p;
s = show(p);
end

function s = o_both_same_grow_int8_variable()
x = int8([3 1 2]);
x(x + 3) = x;
s = show(x);
end

function s = o_both_same_grow_int8_field()
st = struct(); st.v = int8([3 1 2]);
st.v(st.v + 3) = st.v;
s = show(st.v);
end

function s = o_both_same_grow_int8_cellelem()
c = {int8([3 1 2])};
c{1}(c{1} + 3) = c{1};
s = show(c{1});
end

function s = o_both_same_grow_int8_global()
global gO_289; gO_289 = int8([3 1 2]);
gO_289(gO_289 + 3) = gO_289;
s = show(gO_289);
end

function s = o_both_same_grow_int8_persistent()
persistent p; p = int8([3 1 2]);
p(p + 3) = p;
s = show(p);
end
