% value_isolation_gen_multi.m -- GENERATED by tools/parity/gen-value-isolation.py; do not edit.
% The multiple-assignment matrix of the value-ownership plan (rule M11): every output form --
% deal, named outputs, varargout, a cell's and a struct array's comma list, three outputs --
% whose first target is an element of the value a later output is bound to, for a numeric, a
% cell, a string and a struct array, and through a cell element as the target.

run_case('m_deal_real', @m_deal_real);
run_case('m_named_real', @m_named_real);
run_case('m_varargout_real', @m_varargout_real);
run_case('m_cslist_real', @m_cslist_real);
run_case('m_fieldlist_real', @m_fieldlist_real);
run_case('m_three_real', @m_three_real);
run_case('m_deal_container_real', @m_deal_container_real);
run_case('m_deal_cell', @m_deal_cell);
run_case('m_named_cell', @m_named_cell);
run_case('m_varargout_cell', @m_varargout_cell);
run_case('m_cslist_cell', @m_cslist_cell);
run_case('m_fieldlist_cell', @m_fieldlist_cell);
run_case('m_three_cell', @m_three_cell);
run_case('m_deal_container_cell', @m_deal_container_cell);
run_case('m_deal_string', @m_deal_string);
run_case('m_named_string', @m_named_string);
run_case('m_varargout_string', @m_varargout_string);
run_case('m_cslist_string', @m_cslist_string);
run_case('m_fieldlist_string', @m_fieldlist_string);
run_case('m_three_string', @m_three_string);
run_case('m_deal_container_string', @m_deal_container_string);
run_case('m_deal_structarr', @m_deal_structarr);
run_case('m_named_structarr', @m_named_structarr);
run_case('m_varargout_structarr', @m_varargout_structarr);
run_case('m_cslist_structarr', @m_cslist_structarr);
run_case('m_fieldlist_structarr', @m_fieldlist_structarr);
run_case('m_three_structarr', @m_three_structarr);
run_case('m_deal_container_structarr', @m_deal_container_structarr);

function run_case(name, fn)
global vlog_text
vlog_text = '';
try
    fprintf('CHK|%s|%s|exact\n', name, clean(fn()));
catch err
    fprintf('CHK|%s|ERR %s|exact\n', name, clean(err.message));
end
end

function s = clean(s)
if isnumeric(s) || islogical(s)
    s = mat2str(s);
end
s = char(s);
s = strrep(s, char(13), '');
s = strrep(s, char(10), ' ');
s = strrep(s, '|', '/');
end

function s = show(x)
% class, size and contents as text; a large array by its first two elements, its last and its sum.
sz = mat2str(size(x));
if isa(x, 'dictionary')
    ks = keys(x);
    parts = cell(1, numel(ks));
    for k = 1:numel(ks)
        parts{k} = sprintf('%s=%s', show(ks(k)), show(x(ks(k))));
    end
    s = sprintf('dictionary %d {%s}', numEntries(x), strjoin(parts, ' '));
elseif isa(x, 'ValueBox')
    s = sprintf('ValueBox p=%s', show(x.p));
elseif isstruct(x)
    if isscalar(x)
        fn = fieldnames(x);
        parts = cell(1, numel(fn));
        for k = 1:numel(fn)
            parts{k} = sprintf('%s=%s', fn{k}, show(x.(fn{k})));
        end
        s = sprintf('struct %s {%s}', sz, strjoin(parts, ' '));
    else
        fn = strjoin(fieldnames(x)', ',');
        if numel(x) <= 8
            parts = arrayfun(@(e) show_fields(e), x, 'UniformOutput', false);
            s = sprintf('struct %s [%s] {%s}', sz, fn, strjoin(parts(:)', ' '));
        else
            s = sprintf('struct %s [%s] {%s %s .. %s}', sz, fn, show_fields(x(1)), show_fields(x(2)), show_fields(x(end)));
        end
    end
elseif iscell(x)
    if numel(x) <= 8
        parts = cellfun(@show, x, 'UniformOutput', false);
        s = sprintf('cell %s {%s}', sz, strjoin(parts(:)', ' '));
    else
        s = sprintf('cell %s {%s %s .. %s}', sz, show(x{1}), show(x{2}), show(x{end}));
    end
elseif isstring(x)
    if numel(x) <= 8
        s = sprintf('string %s {%s}', sz, strjoin(cellstr(x(:)'), ' '));
    else
        s = sprintf('string %s {%s %s .. %s}', sz, x(1), x(2), x(end));
    end
elseif ischar(x)
    if numel(x) <= 16
        s = sprintf('char %s {%s}', sz, x(:)');
    else
        s = sprintf('char %s {%s%s..%s}', sz, x(1), x(2), x(end));
    end
elseif islogical(x)
    if numel(x) <= 8
        s = sprintf('logical %s %s', sz, mat2str(x));
    else
        d = double(x(:));
        s = sprintf('logical %s [%s %s .. %s] sum=%s', sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
elseif isnumeric(x) && ~isreal(x)
    % real and imaginary planes apart: mat2str's spelling of a complex array is its own line (#61)
    if numel(x) <= 8
        s = sprintf('%s %s re=%s im=%s', class(x), sz, mat2str(double(real(x))), mat2str(double(imag(x))));
    else
        d = double(real(x(:))); e = double(imag(x(:)));
        s = sprintf('%s %s re=[%s %s .. %s] sum=%s im=[%s %s .. %s] sum=%s', class(x), sz, ...
            mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)), ...
            mat2str(e(1)), mat2str(e(2)), mat2str(e(end)), mat2str(sum(e)));
    end
elseif isnumeric(x)
    if numel(x) <= 8
        s = sprintf('%s %s %s', class(x), sz, mat2str(double(x)));
    else
        d = double(x(:));
        s = sprintf('%s %s [%s %s .. %s] sum=%s', class(x), sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
else
    s = sprintf('%s %s', class(x), sz);
end
end

function s = show_fields(e)
fn = fieldnames(e);
parts = cell(1, numel(fn));
for k = 1:numel(fn)
    parts{k} = show(e.(fn{k}));
end
s = strjoin(parts, ',');
end

function [a, b] = two_out(a, b)
end

function varargout = va_out(varargin)
varargout = varargin;
end

function s = m_deal_real()
v = [1 2 3];
[v(1), b] = deal(7, v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_named_real()
v = [1 2 3];
[v(1), b] = two_out(7, v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_varargout_real()
v = [1 2 3];
[v(1), b] = va_out(7, v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_cslist_real()
v = [1 2 3];
C = {7, v}; [v(1), b] = C{:};
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_fieldlist_real()
v = [1 2 3];
st = struct('f', {7, v}); [v(1), b] = st.f;
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_three_real()
v = [1 2 3];
[v(1), b, c] = deal(7, v, v);
s = sprintf('v=%s b=%s c=%s', show(v), show(b), show(c));
end

function s = m_deal_container_real()
v = [1 2 3];
c = {v};
[c{1}, b] = deal(7, c{1});
s = sprintf('c1=%s b=%s', show(c{1}), show(b));
end

function s = m_deal_cell()
v = {1, 2, 3};
[v{1}, b] = deal(7, v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_named_cell()
v = {1, 2, 3};
[v{1}, b] = two_out(7, v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_varargout_cell()
v = {1, 2, 3};
[v{1}, b] = va_out(7, v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_cslist_cell()
v = {1, 2, 3};
C = {7, v}; [v{1}, b] = C{:};
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_fieldlist_cell()
v = {1, 2, 3};
st = struct('f', {7, v}); [v{1}, b] = st.f;
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_three_cell()
v = {1, 2, 3};
[v{1}, b, c] = deal(7, v, v);
s = sprintf('v=%s b=%s c=%s', show(v), show(b), show(c));
end

function s = m_deal_container_cell()
v = {1, 2, 3};
c = {v};
[c{1}, b] = deal(7, c{1});
s = sprintf('c1=%s b=%s', show(c{1}), show(b));
end

function s = m_deal_string()
v = ["a" "b" "c"];
[v(1), b] = deal("z", v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_named_string()
v = ["a" "b" "c"];
[v(1), b] = two_out("z", v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_varargout_string()
v = ["a" "b" "c"];
[v(1), b] = va_out("z", v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_cslist_string()
v = ["a" "b" "c"];
C = {"z", v}; [v(1), b] = C{:};
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_fieldlist_string()
v = ["a" "b" "c"];
st = struct('f', {"z", v}); [v(1), b] = st.f;
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_three_string()
v = ["a" "b" "c"];
[v(1), b, c] = deal("z", v, v);
s = sprintf('v=%s b=%s c=%s', show(v), show(b), show(c));
end

function s = m_deal_container_string()
v = ["a" "b" "c"];
c = {v};
[c{1}, b] = deal("z", c{1});
s = sprintf('c1=%s b=%s', show(c{1}), show(b));
end

function s = m_deal_structarr()
v = struct('f', {1, 2, 3});
[v(1).f, b] = deal(7, v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_named_structarr()
v = struct('f', {1, 2, 3});
[v(1).f, b] = two_out(7, v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_varargout_structarr()
v = struct('f', {1, 2, 3});
[v(1).f, b] = va_out(7, v);
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_cslist_structarr()
v = struct('f', {1, 2, 3});
C = {7, v}; [v(1).f, b] = C{:};
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_fieldlist_structarr()
v = struct('f', {1, 2, 3});
st = struct('f', {7, v}); [v(1).f, b] = st.f;
s = sprintf('v=%s b=%s', show(v), show(b));
end

function s = m_three_structarr()
v = struct('f', {1, 2, 3});
[v(1).f, b, c] = deal(7, v, v);
s = sprintf('v=%s b=%s c=%s', show(v), show(b), show(c));
end

function s = m_deal_container_structarr()
v = struct('f', {1, 2, 3});
c = {v};
[c{1}, b] = deal(7, c{1});
s = sprintf('c1=%s b=%s', show(c{1}), show(b));
end
