% value_isolation_gen_refusal.m -- GENERATED by tools/parity/gen-value-isolation.py; do not edit.
% The refusal matrix of the value-ownership plan (rule M14): every write form failing on a count
% mismatch, a bad subscript or an unconvertible value, on a variable, an alias, a field, a cell
% element and a global; each line shows whether the write was refused and what the target and
% its aliases hold afterwards. Growth past an allocation limit is left out on purpose.

run_case('r_range_count_variable', @r_range_count_variable);
run_case('r_range_count_alias', @r_range_count_alias);
run_case('r_range_count_field', @r_range_count_field);
run_case('r_range_count_cellelem', @r_range_count_cellelem);
run_case('r_range_count_global', @r_range_count_global);
run_case('r_range_subscript_variable', @r_range_subscript_variable);
run_case('r_range_subscript_alias', @r_range_subscript_alias);
run_case('r_range_subscript_field', @r_range_subscript_field);
run_case('r_range_subscript_cellelem', @r_range_subscript_cellelem);
run_case('r_range_subscript_global', @r_range_subscript_global);
run_case('r_range_convert_variable', @r_range_convert_variable);
run_case('r_range_convert_alias', @r_range_convert_alias);
run_case('r_range_convert_field', @r_range_convert_field);
run_case('r_range_convert_cellelem', @r_range_convert_cellelem);
run_case('r_range_convert_global', @r_range_convert_global);
run_case('r_range2d_count_variable', @r_range2d_count_variable);
run_case('r_range2d_count_alias', @r_range2d_count_alias);
run_case('r_range2d_count_field', @r_range2d_count_field);
run_case('r_range2d_count_cellelem', @r_range2d_count_cellelem);
run_case('r_range2d_count_global', @r_range2d_count_global);
run_case('r_range2d_subscript_variable', @r_range2d_subscript_variable);
run_case('r_range2d_subscript_alias', @r_range2d_subscript_alias);
run_case('r_range2d_subscript_field', @r_range2d_subscript_field);
run_case('r_range2d_subscript_cellelem', @r_range2d_subscript_cellelem);
run_case('r_range2d_subscript_global', @r_range2d_subscript_global);
run_case('r_range2d_convert_variable', @r_range2d_convert_variable);
run_case('r_range2d_convert_alias', @r_range2d_convert_alias);
run_case('r_range2d_convert_field', @r_range2d_convert_field);
run_case('r_range2d_convert_cellelem', @r_range2d_convert_cellelem);
run_case('r_range2d_convert_global', @r_range2d_convert_global);
run_case('r_mask_count_variable', @r_mask_count_variable);
run_case('r_mask_count_alias', @r_mask_count_alias);
run_case('r_mask_count_field', @r_mask_count_field);
run_case('r_mask_count_cellelem', @r_mask_count_cellelem);
run_case('r_mask_count_global', @r_mask_count_global);
run_case('r_mask_convert_variable', @r_mask_convert_variable);
run_case('r_mask_convert_alias', @r_mask_convert_alias);
run_case('r_mask_convert_field', @r_mask_convert_field);
run_case('r_mask_convert_cellelem', @r_mask_convert_cellelem);
run_case('r_mask_convert_global', @r_mask_convert_global);
run_case('r_cellparen_count_variable', @r_cellparen_count_variable);
run_case('r_cellparen_count_alias', @r_cellparen_count_alias);
run_case('r_cellparen_count_field', @r_cellparen_count_field);
run_case('r_cellparen_count_cellelem', @r_cellparen_count_cellelem);
run_case('r_cellparen_count_global', @r_cellparen_count_global);
run_case('r_cellparen_subscript_variable', @r_cellparen_subscript_variable);
run_case('r_cellparen_subscript_alias', @r_cellparen_subscript_alias);
run_case('r_cellparen_subscript_field', @r_cellparen_subscript_field);
run_case('r_cellparen_subscript_cellelem', @r_cellparen_subscript_cellelem);
run_case('r_cellparen_subscript_global', @r_cellparen_subscript_global);
run_case('r_cellparen_convert_variable', @r_cellparen_convert_variable);
run_case('r_cellparen_convert_alias', @r_cellparen_convert_alias);
run_case('r_cellparen_convert_field', @r_cellparen_convert_field);
run_case('r_cellparen_convert_cellelem', @r_cellparen_convert_cellelem);
run_case('r_cellparen_convert_global', @r_cellparen_convert_global);
run_case('r_cellbrace_count_variable', @r_cellbrace_count_variable);
run_case('r_cellbrace_count_alias', @r_cellbrace_count_alias);
run_case('r_cellbrace_count_field', @r_cellbrace_count_field);
run_case('r_cellbrace_count_cellelem', @r_cellbrace_count_cellelem);
run_case('r_cellbrace_count_global', @r_cellbrace_count_global);
run_case('r_cellbrace_subscript_variable', @r_cellbrace_subscript_variable);
run_case('r_cellbrace_subscript_alias', @r_cellbrace_subscript_alias);
run_case('r_cellbrace_subscript_field', @r_cellbrace_subscript_field);
run_case('r_cellbrace_subscript_cellelem', @r_cellbrace_subscript_cellelem);
run_case('r_cellbrace_subscript_global', @r_cellbrace_subscript_global);
run_case('r_cellbrace_multi_variable', @r_cellbrace_multi_variable);
run_case('r_cellbrace_multi_alias', @r_cellbrace_multi_alias);
run_case('r_cellbrace_multi_field', @r_cellbrace_multi_field);
run_case('r_cellbrace_multi_cellelem', @r_cellbrace_multi_cellelem);
run_case('r_cellbrace_multi_global', @r_cellbrace_multi_global);
run_case('r_structelem_count_variable', @r_structelem_count_variable);
run_case('r_structelem_count_alias', @r_structelem_count_alias);
run_case('r_structelem_count_field', @r_structelem_count_field);
run_case('r_structelem_count_cellelem', @r_structelem_count_cellelem);
run_case('r_structelem_count_global', @r_structelem_count_global);
run_case('r_structelem_subscript_variable', @r_structelem_subscript_variable);
run_case('r_structelem_subscript_alias', @r_structelem_subscript_alias);
run_case('r_structelem_subscript_field', @r_structelem_subscript_field);
run_case('r_structelem_subscript_cellelem', @r_structelem_subscript_cellelem);
run_case('r_structelem_subscript_global', @r_structelem_subscript_global);
run_case('r_structelem_convert_variable', @r_structelem_convert_variable);
run_case('r_structelem_convert_alias', @r_structelem_convert_alias);
run_case('r_structelem_convert_field', @r_structelem_convert_field);
run_case('r_structelem_convert_cellelem', @r_structelem_convert_cellelem);
run_case('r_structelem_convert_global', @r_structelem_convert_global);
run_case('r_stringelem_count_variable', @r_stringelem_count_variable);
run_case('r_stringelem_count_alias', @r_stringelem_count_alias);
run_case('r_stringelem_count_field', @r_stringelem_count_field);
run_case('r_stringelem_count_cellelem', @r_stringelem_count_cellelem);
run_case('r_stringelem_count_global', @r_stringelem_count_global);
run_case('r_stringelem_subscript_variable', @r_stringelem_subscript_variable);
run_case('r_stringelem_subscript_alias', @r_stringelem_subscript_alias);
run_case('r_stringelem_subscript_field', @r_stringelem_subscript_field);
run_case('r_stringelem_subscript_cellelem', @r_stringelem_subscript_cellelem);
run_case('r_stringelem_subscript_global', @r_stringelem_subscript_global);
run_case('r_stringelem_convert_variable', @r_stringelem_convert_variable);
run_case('r_stringelem_convert_alias', @r_stringelem_convert_alias);
run_case('r_stringelem_convert_field', @r_stringelem_convert_field);
run_case('r_stringelem_convert_cellelem', @r_stringelem_convert_cellelem);
run_case('r_stringelem_convert_global', @r_stringelem_convert_global);

function run_case(name, fn)
global vlog_text
vlog_text = '';
try
    fprintf('CHK|%s|%s|exact\n', name, clean(fn()));
catch err
    fprintf('CHK|%s|ERR %s|exact\n', name, clean(err.message));
end
end

function s = clean(s)
if isnumeric(s) || islogical(s)
    s = mat2str(s);
end
s = char(s);
s = strrep(s, char(13), '');
s = strrep(s, char(10), ' ');
s = strrep(s, '|', '/');
end

function s = show(x)
% class, size and contents as text; a large array by its first two elements, its last and its sum.
sz = mat2str(size(x));
if isa(x, 'dictionary')
    ks = keys(x);
    parts = cell(1, numel(ks));
    for k = 1:numel(ks)
        parts{k} = sprintf('%s=%s', show(ks(k)), show(x(ks(k))));
    end
    s = sprintf('dictionary %d {%s}', numEntries(x), strjoin(parts, ' '));
elseif isa(x, 'ValueBox')
    s = sprintf('ValueBox p=%s', show(x.p));
elseif isstruct(x)
    if isscalar(x)
        fn = fieldnames(x);
        parts = cell(1, numel(fn));
        for k = 1:numel(fn)
            parts{k} = sprintf('%s=%s', fn{k}, show(x.(fn{k})));
        end
        s = sprintf('struct %s {%s}', sz, strjoin(parts, ' '));
    else
        fn = strjoin(fieldnames(x)', ',');
        if numel(x) <= 8
            parts = arrayfun(@(e) show_fields(e), x, 'UniformOutput', false);
            s = sprintf('struct %s [%s] {%s}', sz, fn, strjoin(parts(:)', ' '));
        else
            s = sprintf('struct %s [%s] {%s %s .. %s}', sz, fn, show_fields(x(1)), show_fields(x(2)), show_fields(x(end)));
        end
    end
elseif iscell(x)
    if numel(x) <= 8
        parts = cellfun(@show, x, 'UniformOutput', false);
        s = sprintf('cell %s {%s}', sz, strjoin(parts(:)', ' '));
    else
        s = sprintf('cell %s {%s %s .. %s}', sz, show(x{1}), show(x{2}), show(x{end}));
    end
elseif isstring(x)
    if numel(x) <= 8
        s = sprintf('string %s {%s}', sz, strjoin(cellstr(x(:)'), ' '));
    else
        s = sprintf('string %s {%s %s .. %s}', sz, x(1), x(2), x(end));
    end
elseif ischar(x)
    if numel(x) <= 16
        s = sprintf('char %s {%s}', sz, x(:)');
    else
        s = sprintf('char %s {%s%s..%s}', sz, x(1), x(2), x(end));
    end
elseif islogical(x)
    if numel(x) <= 8
        s = sprintf('logical %s %s', sz, mat2str(x));
    else
        d = double(x(:));
        s = sprintf('logical %s [%s %s .. %s] sum=%s', sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
elseif isnumeric(x) && ~isreal(x)
    % real and imaginary planes apart: mat2str's spelling of a complex array is its own line (#61)
    if numel(x) <= 8
        s = sprintf('%s %s re=%s im=%s', class(x), sz, mat2str(double(real(x))), mat2str(double(imag(x))));
    else
        d = double(real(x(:))); e = double(imag(x(:)));
        s = sprintf('%s %s re=[%s %s .. %s] sum=%s im=[%s %s .. %s] sum=%s', class(x), sz, ...
            mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)), ...
            mat2str(e(1)), mat2str(e(2)), mat2str(e(end)), mat2str(sum(e)));
    end
elseif isnumeric(x)
    if numel(x) <= 8
        s = sprintf('%s %s %s', class(x), sz, mat2str(double(x)));
    else
        d = double(x(:));
        s = sprintf('%s %s [%s %s .. %s] sum=%s', class(x), sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
else
    s = sprintf('%s %s', class(x), sz);
end
end

function s = show_fields(e)
fn = fieldnames(e);
parts = cell(1, numel(fn));
for k = 1:numel(fn)
    parts{k} = show(e.(fn{k}));
end
s = strjoin(parts, ',');
end

function s = r_range_count_variable()
x = [1 2];
refused = 0;
try
    x(4:5) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_range_count_alias()
x = [1 2]; y = x;
refused = 0;
try
    x(4:5) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_range_count_field()
st = struct(); st.v = [1 2]; t = st;
refused = 0;
try
    st.v(4:5) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_range_count_cellelem()
c = {[1 2]}; d = c;
refused = 0;
try
    c{1}(4:5) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_range_count_global()
global gR_5; gR_5 = [1 2]; y = gR_5;
refused = 0;
try
    gR_5(4:5) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d gR_5=%s y=%s', refused, show(gR_5), show(y));
end

function s = r_range_subscript_variable()
x = [1 2];
refused = 0;
try
    x(0) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_range_subscript_alias()
x = [1 2]; y = x;
refused = 0;
try
    x(0) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_range_subscript_field()
st = struct(); st.v = [1 2]; t = st;
refused = 0;
try
    st.v(0) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_range_subscript_cellelem()
c = {[1 2]}; d = c;
refused = 0;
try
    c{1}(0) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_range_subscript_global()
global gR_10; gR_10 = [1 2]; y = gR_10;
refused = 0;
try
    gR_10(0) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d gR_10=%s y=%s', refused, show(gR_10), show(y));
end

function s = r_range_convert_variable()
x = [1 2];
refused = 0;
try
    x(2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_range_convert_alias()
x = [1 2]; y = x;
refused = 0;
try
    x(2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_range_convert_field()
st = struct(); st.v = [1 2]; t = st;
refused = 0;
try
    st.v(2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_range_convert_cellelem()
c = {[1 2]}; d = c;
refused = 0;
try
    c{1}(2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_range_convert_global()
global gR_15; gR_15 = [1 2]; y = gR_15;
refused = 0;
try
    gR_15(2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d gR_15=%s y=%s', refused, show(gR_15), show(y));
end

function s = r_range2d_count_variable()
x = [1 2; 3 4];
refused = 0;
try
    x(3:4, 1) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_range2d_count_alias()
x = [1 2; 3 4]; y = x;
refused = 0;
try
    x(3:4, 1) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_range2d_count_field()
st = struct(); st.v = [1 2; 3 4]; t = st;
refused = 0;
try
    st.v(3:4, 1) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_range2d_count_cellelem()
c = {[1 2; 3 4]}; d = c;
refused = 0;
try
    c{1}(3:4, 1) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_range2d_count_global()
global gR_20; gR_20 = [1 2; 3 4]; y = gR_20;
refused = 0;
try
    gR_20(3:4, 1) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d gR_20=%s y=%s', refused, show(gR_20), show(y));
end

function s = r_range2d_subscript_variable()
x = [1 2; 3 4];
refused = 0;
try
    x(0, 1) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_range2d_subscript_alias()
x = [1 2; 3 4]; y = x;
refused = 0;
try
    x(0, 1) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_range2d_subscript_field()
st = struct(); st.v = [1 2; 3 4]; t = st;
refused = 0;
try
    st.v(0, 1) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_range2d_subscript_cellelem()
c = {[1 2; 3 4]}; d = c;
refused = 0;
try
    c{1}(0, 1) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_range2d_subscript_global()
global gR_25; gR_25 = [1 2; 3 4]; y = gR_25;
refused = 0;
try
    gR_25(0, 1) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d gR_25=%s y=%s', refused, show(gR_25), show(y));
end

function s = r_range2d_convert_variable()
x = [1 2; 3 4];
refused = 0;
try
    x(1, 2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_range2d_convert_alias()
x = [1 2; 3 4]; y = x;
refused = 0;
try
    x(1, 2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_range2d_convert_field()
st = struct(); st.v = [1 2; 3 4]; t = st;
refused = 0;
try
    st.v(1, 2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_range2d_convert_cellelem()
c = {[1 2; 3 4]}; d = c;
refused = 0;
try
    c{1}(1, 2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_range2d_convert_global()
global gR_30; gR_30 = [1 2; 3 4]; y = gR_30;
refused = 0;
try
    gR_30(1, 2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d gR_30=%s y=%s', refused, show(gR_30), show(y));
end

function s = r_mask_count_variable()
x = [1 2 3];
refused = 0;
try
    x(logical([1 0 1])) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_mask_count_alias()
x = [1 2 3]; y = x;
refused = 0;
try
    x(logical([1 0 1])) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_mask_count_field()
st = struct(); st.v = [1 2 3]; t = st;
refused = 0;
try
    st.v(logical([1 0 1])) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_mask_count_cellelem()
c = {[1 2 3]}; d = c;
refused = 0;
try
    c{1}(logical([1 0 1])) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_mask_count_global()
global gR_35; gR_35 = [1 2 3]; y = gR_35;
refused = 0;
try
    gR_35(logical([1 0 1])) = [7 8 9];
catch
    refused = 1;
end
s = sprintf('refused=%d gR_35=%s y=%s', refused, show(gR_35), show(y));
end

function s = r_mask_convert_variable()
x = [1 2 3];
refused = 0;
try
    x(logical([1 0 1])) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_mask_convert_alias()
x = [1 2 3]; y = x;
refused = 0;
try
    x(logical([1 0 1])) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_mask_convert_field()
st = struct(); st.v = [1 2 3]; t = st;
refused = 0;
try
    st.v(logical([1 0 1])) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_mask_convert_cellelem()
c = {[1 2 3]}; d = c;
refused = 0;
try
    c{1}(logical([1 0 1])) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_mask_convert_global()
global gR_40; gR_40 = [1 2 3]; y = gR_40;
refused = 0;
try
    gR_40(logical([1 0 1])) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d gR_40=%s y=%s', refused, show(gR_40), show(y));
end

function s = r_cellparen_count_variable()
x = {1, 2};
refused = 0;
try
    x(4:5) = {7, 8, 9};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_cellparen_count_alias()
x = {1, 2}; y = x;
refused = 0;
try
    x(4:5) = {7, 8, 9};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_cellparen_count_field()
st = struct(); st.v = {1, 2}; t = st;
refused = 0;
try
    st.v(4:5) = {7, 8, 9};
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_cellparen_count_cellelem()
c = {{1, 2}}; d = c;
refused = 0;
try
    c{1}(4:5) = {7, 8, 9};
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_cellparen_count_global()
global gR_45; gR_45 = {1, 2}; y = gR_45;
refused = 0;
try
    gR_45(4:5) = {7, 8, 9};
catch
    refused = 1;
end
s = sprintf('refused=%d gR_45=%s y=%s', refused, show(gR_45), show(y));
end

function s = r_cellparen_subscript_variable()
x = {1, 2};
refused = 0;
try
    x(0) = {7};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_cellparen_subscript_alias()
x = {1, 2}; y = x;
refused = 0;
try
    x(0) = {7};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_cellparen_subscript_field()
st = struct(); st.v = {1, 2}; t = st;
refused = 0;
try
    st.v(0) = {7};
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_cellparen_subscript_cellelem()
c = {{1, 2}}; d = c;
refused = 0;
try
    c{1}(0) = {7};
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_cellparen_subscript_global()
global gR_50; gR_50 = {1, 2}; y = gR_50;
refused = 0;
try
    gR_50(0) = {7};
catch
    refused = 1;
end
s = sprintf('refused=%d gR_50=%s y=%s', refused, show(gR_50), show(y));
end

function s = r_cellparen_convert_variable()
x = {1, 2};
refused = 0;
try
    x(4:5) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_cellparen_convert_alias()
x = {1, 2}; y = x;
refused = 0;
try
    x(4:5) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_cellparen_convert_field()
st = struct(); st.v = {1, 2}; t = st;
refused = 0;
try
    st.v(4:5) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_cellparen_convert_cellelem()
c = {{1, 2}}; d = c;
refused = 0;
try
    c{1}(4:5) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_cellparen_convert_global()
global gR_55; gR_55 = {1, 2}; y = gR_55;
refused = 0;
try
    gR_55(4:5) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d gR_55=%s y=%s', refused, show(gR_55), show(y));
end

function s = r_cellbrace_count_variable()
x = {1, 2};
refused = 0;
try
    [x{4:5}] = deal(7, 8, 9);
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_cellbrace_count_alias()
x = {1, 2}; y = x;
refused = 0;
try
    [x{4:5}] = deal(7, 8, 9);
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_cellbrace_count_field()
st = struct(); st.v = {1, 2}; t = st;
refused = 0;
try
    [st.v{4:5}] = deal(7, 8, 9);
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_cellbrace_count_cellelem()
c = {{1, 2}}; d = c;
refused = 0;
try
    [c{1}{4:5}] = deal(7, 8, 9);
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_cellbrace_count_global()
global gR_60; gR_60 = {1, 2}; y = gR_60;
refused = 0;
try
    [gR_60{4:5}] = deal(7, 8, 9);
catch
    refused = 1;
end
s = sprintf('refused=%d gR_60=%s y=%s', refused, show(gR_60), show(y));
end

function s = r_cellbrace_subscript_variable()
x = {1, 2};
refused = 0;
try
    x{0} = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_cellbrace_subscript_alias()
x = {1, 2}; y = x;
refused = 0;
try
    x{0} = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_cellbrace_subscript_field()
st = struct(); st.v = {1, 2}; t = st;
refused = 0;
try
    st.v{0} = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_cellbrace_subscript_cellelem()
c = {{1, 2}}; d = c;
refused = 0;
try
    c{1}{0} = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_cellbrace_subscript_global()
global gR_65; gR_65 = {1, 2}; y = gR_65;
refused = 0;
try
    gR_65{0} = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d gR_65=%s y=%s', refused, show(gR_65), show(y));
end

function s = r_cellbrace_multi_variable()
x = {1, 2};
refused = 0;
try
    x{[1 2]} = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_cellbrace_multi_alias()
x = {1, 2}; y = x;
refused = 0;
try
    x{[1 2]} = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_cellbrace_multi_field()
st = struct(); st.v = {1, 2}; t = st;
refused = 0;
try
    st.v{[1 2]} = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_cellbrace_multi_cellelem()
c = {{1, 2}}; d = c;
refused = 0;
try
    c{1}{[1 2]} = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_cellbrace_multi_global()
global gR_70; gR_70 = {1, 2}; y = gR_70;
refused = 0;
try
    gR_70{[1 2]} = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d gR_70=%s y=%s', refused, show(gR_70), show(y));
end

function s = r_structelem_count_variable()
x = struct('a', {1, 2});
refused = 0;
try
    x(4:6) = x(1:2);
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_structelem_count_alias()
x = struct('a', {1, 2}); y = x;
refused = 0;
try
    x(4:6) = x(1:2);
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_structelem_count_field()
st = struct(); st.v = struct('a', {1, 2}); t = st;
refused = 0;
try
    st.v(4:6) = st.v(1:2);
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_structelem_count_cellelem()
c = {struct('a', {1, 2})}; d = c;
refused = 0;
try
    c{1}(4:6) = c{1}(1:2);
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_structelem_count_global()
global gR_75; gR_75 = struct('a', {1, 2}); y = gR_75;
refused = 0;
try
    gR_75(4:6) = gR_75(1:2);
catch
    refused = 1;
end
s = sprintf('refused=%d gR_75=%s y=%s', refused, show(gR_75), show(y));
end

function s = r_structelem_subscript_variable()
x = struct('a', {1, 2});
refused = 0;
try
    x(0) = x(1);
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_structelem_subscript_alias()
x = struct('a', {1, 2}); y = x;
refused = 0;
try
    x(0) = x(1);
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_structelem_subscript_field()
st = struct(); st.v = struct('a', {1, 2}); t = st;
refused = 0;
try
    st.v(0) = st.v(1);
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_structelem_subscript_cellelem()
c = {struct('a', {1, 2})}; d = c;
refused = 0;
try
    c{1}(0) = c{1}(1);
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_structelem_subscript_global()
global gR_80; gR_80 = struct('a', {1, 2}); y = gR_80;
refused = 0;
try
    gR_80(0) = gR_80(1);
catch
    refused = 1;
end
s = sprintf('refused=%d gR_80=%s y=%s', refused, show(gR_80), show(y));
end

function s = r_structelem_convert_variable()
x = struct('a', {1, 2});
refused = 0;
try
    x(3) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_structelem_convert_alias()
x = struct('a', {1, 2}); y = x;
refused = 0;
try
    x(3) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_structelem_convert_field()
st = struct(); st.v = struct('a', {1, 2}); t = st;
refused = 0;
try
    st.v(3) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_structelem_convert_cellelem()
c = {struct('a', {1, 2})}; d = c;
refused = 0;
try
    c{1}(3) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_structelem_convert_global()
global gR_85; gR_85 = struct('a', {1, 2}); y = gR_85;
refused = 0;
try
    gR_85(3) = 7;
catch
    refused = 1;
end
s = sprintf('refused=%d gR_85=%s y=%s', refused, show(gR_85), show(y));
end

function s = r_stringelem_count_variable()
x = ["a" "b"];
refused = 0;
try
    x(4:5) = ["x" "y" "z"];
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_stringelem_count_alias()
x = ["a" "b"]; y = x;
refused = 0;
try
    x(4:5) = ["x" "y" "z"];
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_stringelem_count_field()
st = struct(); st.v = ["a" "b"]; t = st;
refused = 0;
try
    st.v(4:5) = ["x" "y" "z"];
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_stringelem_count_cellelem()
c = {["a" "b"]}; d = c;
refused = 0;
try
    c{1}(4:5) = ["x" "y" "z"];
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_stringelem_count_global()
global gR_90; gR_90 = ["a" "b"]; y = gR_90;
refused = 0;
try
    gR_90(4:5) = ["x" "y" "z"];
catch
    refused = 1;
end
s = sprintf('refused=%d gR_90=%s y=%s', refused, show(gR_90), show(y));
end

function s = r_stringelem_subscript_variable()
x = ["a" "b"];
refused = 0;
try
    x(0) = "x";
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_stringelem_subscript_alias()
x = ["a" "b"]; y = x;
refused = 0;
try
    x(0) = "x";
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_stringelem_subscript_field()
st = struct(); st.v = ["a" "b"]; t = st;
refused = 0;
try
    st.v(0) = "x";
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_stringelem_subscript_cellelem()
c = {["a" "b"]}; d = c;
refused = 0;
try
    c{1}(0) = "x";
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_stringelem_subscript_global()
global gR_95; gR_95 = ["a" "b"]; y = gR_95;
refused = 0;
try
    gR_95(0) = "x";
catch
    refused = 1;
end
s = sprintf('refused=%d gR_95=%s y=%s', refused, show(gR_95), show(y));
end

function s = r_stringelem_convert_variable()
x = ["a" "b"];
refused = 0;
try
    x(2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s', refused, show(x));
end

function s = r_stringelem_convert_alias()
x = ["a" "b"]; y = x;
refused = 0;
try
    x(2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d x=%s y=%s', refused, show(x), show(y));
end

function s = r_stringelem_convert_field()
st = struct(); st.v = ["a" "b"]; t = st;
refused = 0;
try
    st.v(2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d st.v=%s t.v=%s', refused, show(st.v), show(t.v));
end

function s = r_stringelem_convert_cellelem()
c = {["a" "b"]}; d = c;
refused = 0;
try
    c{1}(2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d c{1}=%s d{1}=%s', refused, show(c{1}), show(d{1}));
end

function s = r_stringelem_convert_global()
global gR_100; gR_100 = ["a" "b"]; y = gR_100;
refused = 0;
try
    gR_100(2) = {5};
catch
    refused = 1;
end
s = sprintf('refused=%d gR_100=%s y=%s', refused, show(gR_100), show(y));
end
