% value_isolation_gen_builtins.m -- GENERATED by tools/parity/gen-value-isolation.py; do not edit.
% The builtin matrix of the value-ownership plan (rule M8): every value-transforming builtin with
% its result discarded, kept and failing midway, showing the source afterwards; and the handle-type
% controls (a containers.Map verb, a handle method) that must still mutate.

run_case('b_insert_discarded', @b_insert_discarded);
run_case('b_insert_kept', @b_insert_kept);
run_case('b_insert_failing', @b_insert_failing);
run_case('b_remove_discarded', @b_remove_discarded);
run_case('b_remove_kept', @b_remove_kept);
run_case('b_remove_failing', @b_remove_failing);
run_case('b_setfield_discarded', @b_setfield_discarded);
run_case('b_setfield_kept', @b_setfield_kept);
run_case('b_setfield_failing', @b_setfield_failing);
run_case('b_rmfield_discarded', @b_rmfield_discarded);
run_case('b_rmfield_kept', @b_rmfield_kept);
run_case('b_rmfield_failing', @b_rmfield_failing);
run_case('b_orderfields_discarded', @b_orderfields_discarded);
run_case('b_orderfields_kept', @b_orderfields_kept);
run_case('b_orderfields_failing', @b_orderfields_failing);
run_case('b_horzcat_discarded', @b_horzcat_discarded);
run_case('b_horzcat_kept', @b_horzcat_kept);
run_case('b_horzcat_failing', @b_horzcat_failing);
run_case('b_sort_cell_discarded', @b_sort_cell_discarded);
run_case('b_sort_cell_kept', @b_sort_cell_kept);
run_case('b_sort_cell_failing', @b_sort_cell_failing);
run_case('b_strrep_cell_discarded', @b_strrep_cell_discarded);
run_case('b_strrep_cell_kept', @b_strrep_cell_kept);
run_case('b_strrep_cell_failing', @b_strrep_cell_failing);
run_case('b_unique_discarded', @b_unique_discarded);
run_case('b_unique_kept', @b_unique_kept);
run_case('b_unique_failing', @b_unique_failing);
run_case('b_num2cell_discarded', @b_num2cell_discarded);
run_case('b_num2cell_kept', @b_num2cell_kept);
run_case('b_num2cell_failing', @b_num2cell_failing);
run_case('b_control_map_remove', @b_control_map_remove);
run_case('b_control_handle_method', @b_control_handle_method);
run_case('b_control_map_assign', @b_control_map_assign);

function run_case(name, fn)
global vlog_text
vlog_text = '';
try
    fprintf('CHK|%s|%s|exact\n', name, clean(fn()));
catch err
    fprintf('CHK|%s|ERR %s|exact\n', name, clean(err.message));
end
end

function s = clean(s)
if isnumeric(s) || islogical(s)
    s = mat2str(s);
end
s = char(s);
s = strrep(s, char(13), '');
s = strrep(s, char(10), ' ');
s = strrep(s, '|', '/');
end

function s = show(x)
% class, size and contents as text; a large array by its first two elements, its last and its sum.
sz = mat2str(size(x));
if isa(x, 'dictionary')
    ks = keys(x);
    parts = cell(1, numel(ks));
    for k = 1:numel(ks)
        parts{k} = sprintf('%s=%s', show(ks(k)), show(x(ks(k))));
    end
    s = sprintf('dictionary %d {%s}', numEntries(x), strjoin(parts, ' '));
elseif isa(x, 'ValueBox')
    s = sprintf('ValueBox p=%s', show(x.p));
elseif isstruct(x)
    if isscalar(x)
        fn = fieldnames(x);
        parts = cell(1, numel(fn));
        for k = 1:numel(fn)
            parts{k} = sprintf('%s=%s', fn{k}, show(x.(fn{k})));
        end
        s = sprintf('struct %s {%s}', sz, strjoin(parts, ' '));
    else
        fn = strjoin(fieldnames(x)', ',');
        if numel(x) <= 8
            parts = arrayfun(@(e) show_fields(e), x, 'UniformOutput', false);
            s = sprintf('struct %s [%s] {%s}', sz, fn, strjoin(parts(:)', ' '));
        else
            s = sprintf('struct %s [%s] {%s %s .. %s}', sz, fn, show_fields(x(1)), show_fields(x(2)), show_fields(x(end)));
        end
    end
elseif iscell(x)
    if numel(x) <= 8
        parts = cellfun(@show, x, 'UniformOutput', false);
        s = sprintf('cell %s {%s}', sz, strjoin(parts(:)', ' '));
    else
        s = sprintf('cell %s {%s %s .. %s}', sz, show(x{1}), show(x{2}), show(x{end}));
    end
elseif isstring(x)
    if numel(x) <= 8
        s = sprintf('string %s {%s}', sz, strjoin(cellstr(x(:)'), ' '));
    else
        s = sprintf('string %s {%s %s .. %s}', sz, x(1), x(2), x(end));
    end
elseif ischar(x)
    if numel(x) <= 16
        s = sprintf('char %s {%s}', sz, x(:)');
    else
        s = sprintf('char %s {%s%s..%s}', sz, x(1), x(2), x(end));
    end
elseif islogical(x)
    if numel(x) <= 8
        s = sprintf('logical %s %s', sz, mat2str(x));
    else
        d = double(x(:));
        s = sprintf('logical %s [%s %s .. %s] sum=%s', sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
elseif isnumeric(x) && ~isreal(x)
    % real and imaginary planes apart: mat2str's spelling of a complex array is its own line (#61)
    if numel(x) <= 8
        s = sprintf('%s %s re=%s im=%s', class(x), sz, mat2str(double(real(x))), mat2str(double(imag(x))));
    else
        d = double(real(x(:))); e = double(imag(x(:)));
        s = sprintf('%s %s re=[%s %s .. %s] sum=%s im=[%s %s .. %s] sum=%s', class(x), sz, ...
            mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)), ...
            mat2str(e(1)), mat2str(e(2)), mat2str(e(end)), mat2str(sum(e)));
    end
elseif isnumeric(x)
    if numel(x) <= 8
        s = sprintf('%s %s %s', class(x), sz, mat2str(double(x)));
    else
        d = double(x(:));
        s = sprintf('%s %s [%s %s .. %s] sum=%s', class(x), sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
else
    s = sprintf('%s %s', class(x), sz);
end
end

function s = show_fields(e)
fn = fieldnames(e);
parts = cell(1, numel(fn));
for k = 1:numel(fn)
    parts{k} = show(e.(fn{k}));
end
s = strjoin(parts, ',');
end

function s = b_insert_discarded()
d = dictionary(1, 10);
insert(d, 1, 20);
s = show(d);
end

function s = b_insert_kept()
d = dictionary(1, 10);
r = insert(d, 1, 20);
s = show(d);
end

function s = b_insert_failing()
d = dictionary(1, 10);
try
    r = insert(d, [1 2], 20);
catch
end
s = show(d);
end

function s = b_remove_discarded()
d = dictionary([1 2], [10 20]);
remove(d, 2);
s = show(d);
end

function s = b_remove_kept()
d = dictionary([1 2], [10 20]);
r = remove(d, 2);
s = show(d);
end

function s = b_remove_failing()
d = dictionary([1 2], [10 20]);
try
    r = remove(d, {1});
catch
end
s = show(d);
end

function s = b_setfield_discarded()
st = struct('f', 1, 'g', 2);
setfield(st, 'f', 7);
s = show(st);
end

function s = b_setfield_kept()
st = struct('f', 1, 'g', 2);
r = setfield(st, 'f', 7);
s = show(st);
end

function s = b_setfield_failing()
st = struct('f', 1, 'g', 2);
try
    r = setfield(st, 3, 7);
catch
end
s = show(st);
end

function s = b_rmfield_discarded()
st = struct('f', 1, 'g', 2);
rmfield(st, 'g');
s = show(st);
end

function s = b_rmfield_kept()
st = struct('f', 1, 'g', 2);
r = rmfield(st, 'g');
s = show(st);
end

function s = b_rmfield_failing()
st = struct('f', 1, 'g', 2);
try
    r = rmfield(st, 'zz');
catch
end
s = show(st);
end

function s = b_orderfields_discarded()
st = struct('g', 2, 'f', 1);
orderfields(st);
s = show(st);
end

function s = b_orderfields_kept()
st = struct('g', 2, 'f', 1);
r = orderfields(st);
s = show(st);
end

function s = b_orderfields_failing()
st = struct('g', 2, 'f', 1);
try
    r = orderfields(st, {'f'});
catch
end
s = show(st);
end

function s = b_horzcat_discarded()
st = struct('f', 1);
[st, st];
s = show(st);
end

function s = b_horzcat_kept()
st = struct('f', 1);
r = [st, st];
s = show(st);
end

function s = b_horzcat_failing()
st = struct('f', 1);
try
    r = [st, struct('q', 1)];
catch
end
s = show(st);
end

function s = b_sort_cell_discarded()
c = {'b', 'a'};
sort(c);
s = show(c);
end

function s = b_sort_cell_kept()
c = {'b', 'a'};
r = sort(c);
s = show(c);
end

function s = b_sort_cell_failing()
c = {'b', 'a'};
try
    r = sort(c, 3);
catch
end
s = show(c);
end

function s = b_strrep_cell_discarded()
c = {'aa', 'ba'};
strrep(c, 'a', 'x');
s = show(c);
end

function s = b_strrep_cell_kept()
c = {'aa', 'ba'};
r = strrep(c, 'a', 'x');
s = show(c);
end

function s = b_strrep_cell_failing()
c = {'aa', 'ba'};
try
    r = strrep(c, 'a');
catch
end
s = show(c);
end

function s = b_unique_discarded()
x = [3 1 2 1];
unique(x);
s = show(x);
end

function s = b_unique_kept()
x = [3 1 2 1];
r = unique(x);
s = show(x);
end

function s = b_unique_failing()
x = [3 1 2 1];
try
    r = unique(x, 'nosuch');
catch
end
s = show(x);
end

function s = b_num2cell_discarded()
x = [1 2 3];
num2cell(x);
s = show(x);
end

function s = b_num2cell_kept()
x = [1 2 3];
r = num2cell(x);
s = show(x);
end

function s = b_num2cell_failing()
x = [1 2 3];
try
    r = num2cell(x, 3);
catch
end
s = show(x);
end

function s = b_control_map_remove()
m = containers.Map({'a', 'b'}, {1, 2});
remove(m, 'b');
s = show(m.Count);
end

function s = b_control_handle_method()
h = HandleHolder(); h.data = [1 2 3];
h.bump();
s = show(h.data);
end

function s = b_control_map_assign()
m = containers.Map(); m('k') = 1;
m('k') = 2;
s = show(m('k'));
end
