% value_isolation_gen_order.m -- GENERATED by tools/parity/gen-value-isolation.py; do not edit.
% The order matrix of the value-ownership plan (rules M15 and M16): for every target shape -- a
% paren index on a variable, a 2-D one, a brace, a field then paren, a brace then paren, a paren
% then field, two fields then paren, a dynamic field -- a subscript function and a right-hand-side
% function that each log their call and grow, shrink, rebind or clear the global target, in every
% combination, plus end against a right-hand side that acts; each line shows the call log and the
% target afterwards.

run_case('w_paren_sub_plain_rhs_plain', @w_paren_sub_plain_rhs_plain);
run_case('w_paren_sub_plain_rhs_grow', @w_paren_sub_plain_rhs_grow);
run_case('w_paren_sub_plain_rhs_shrink', @w_paren_sub_plain_rhs_shrink);
run_case('w_paren_sub_plain_rhs_rebind', @w_paren_sub_plain_rhs_rebind);
run_case('w_paren_sub_plain_rhs_clear', @w_paren_sub_plain_rhs_clear);
run_case('w_paren_sub_grow_rhs_plain', @w_paren_sub_grow_rhs_plain);
run_case('w_paren_sub_grow_rhs_grow', @w_paren_sub_grow_rhs_grow);
run_case('w_paren_sub_grow_rhs_shrink', @w_paren_sub_grow_rhs_shrink);
run_case('w_paren_sub_grow_rhs_rebind', @w_paren_sub_grow_rhs_rebind);
run_case('w_paren_sub_grow_rhs_clear', @w_paren_sub_grow_rhs_clear);
run_case('w_paren_sub_shrink_rhs_plain', @w_paren_sub_shrink_rhs_plain);
run_case('w_paren_sub_shrink_rhs_grow', @w_paren_sub_shrink_rhs_grow);
run_case('w_paren_sub_shrink_rhs_shrink', @w_paren_sub_shrink_rhs_shrink);
run_case('w_paren_sub_shrink_rhs_rebind', @w_paren_sub_shrink_rhs_rebind);
run_case('w_paren_sub_shrink_rhs_clear', @w_paren_sub_shrink_rhs_clear);
run_case('w_paren_sub_rebind_rhs_plain', @w_paren_sub_rebind_rhs_plain);
run_case('w_paren_sub_rebind_rhs_grow', @w_paren_sub_rebind_rhs_grow);
run_case('w_paren_sub_rebind_rhs_shrink', @w_paren_sub_rebind_rhs_shrink);
run_case('w_paren_sub_rebind_rhs_rebind', @w_paren_sub_rebind_rhs_rebind);
run_case('w_paren_sub_rebind_rhs_clear', @w_paren_sub_rebind_rhs_clear);
run_case('w_paren_sub_clear_rhs_plain', @w_paren_sub_clear_rhs_plain);
run_case('w_paren_sub_clear_rhs_grow', @w_paren_sub_clear_rhs_grow);
run_case('w_paren_sub_clear_rhs_shrink', @w_paren_sub_clear_rhs_shrink);
run_case('w_paren_sub_clear_rhs_rebind', @w_paren_sub_clear_rhs_rebind);
run_case('w_paren_sub_clear_rhs_clear', @w_paren_sub_clear_rhs_clear);
run_case('w_paren_end_rhs_grow', @w_paren_end_rhs_grow);
run_case('w_paren_end_rhs_shrink', @w_paren_end_rhs_shrink);
run_case('w_paren_end_rhs_rebind', @w_paren_end_rhs_rebind);
run_case('w_paren_end_rhs_clear', @w_paren_end_rhs_clear);
run_case('w_paren2d_sub_plain_rhs_plain', @w_paren2d_sub_plain_rhs_plain);
run_case('w_paren2d_sub_plain_rhs_grow', @w_paren2d_sub_plain_rhs_grow);
run_case('w_paren2d_sub_plain_rhs_shrink', @w_paren2d_sub_plain_rhs_shrink);
run_case('w_paren2d_sub_plain_rhs_rebind', @w_paren2d_sub_plain_rhs_rebind);
run_case('w_paren2d_sub_plain_rhs_clear', @w_paren2d_sub_plain_rhs_clear);
run_case('w_paren2d_sub_grow_rhs_plain', @w_paren2d_sub_grow_rhs_plain);
run_case('w_paren2d_sub_grow_rhs_grow', @w_paren2d_sub_grow_rhs_grow);
run_case('w_paren2d_sub_grow_rhs_shrink', @w_paren2d_sub_grow_rhs_shrink);
run_case('w_paren2d_sub_grow_rhs_rebind', @w_paren2d_sub_grow_rhs_rebind);
run_case('w_paren2d_sub_grow_rhs_clear', @w_paren2d_sub_grow_rhs_clear);
run_case('w_paren2d_sub_shrink_rhs_plain', @w_paren2d_sub_shrink_rhs_plain);
run_case('w_paren2d_sub_shrink_rhs_grow', @w_paren2d_sub_shrink_rhs_grow);
run_case('w_paren2d_sub_shrink_rhs_shrink', @w_paren2d_sub_shrink_rhs_shrink);
run_case('w_paren2d_sub_shrink_rhs_rebind', @w_paren2d_sub_shrink_rhs_rebind);
run_case('w_paren2d_sub_shrink_rhs_clear', @w_paren2d_sub_shrink_rhs_clear);
run_case('w_paren2d_sub_rebind_rhs_plain', @w_paren2d_sub_rebind_rhs_plain);
run_case('w_paren2d_sub_rebind_rhs_grow', @w_paren2d_sub_rebind_rhs_grow);
run_case('w_paren2d_sub_rebind_rhs_shrink', @w_paren2d_sub_rebind_rhs_shrink);
run_case('w_paren2d_sub_rebind_rhs_rebind', @w_paren2d_sub_rebind_rhs_rebind);
run_case('w_paren2d_sub_rebind_rhs_clear', @w_paren2d_sub_rebind_rhs_clear);
run_case('w_paren2d_sub_clear_rhs_plain', @w_paren2d_sub_clear_rhs_plain);
run_case('w_paren2d_sub_clear_rhs_grow', @w_paren2d_sub_clear_rhs_grow);
run_case('w_paren2d_sub_clear_rhs_shrink', @w_paren2d_sub_clear_rhs_shrink);
run_case('w_paren2d_sub_clear_rhs_rebind', @w_paren2d_sub_clear_rhs_rebind);
run_case('w_paren2d_sub_clear_rhs_clear', @w_paren2d_sub_clear_rhs_clear);
run_case('w_paren2d_end_rhs_grow', @w_paren2d_end_rhs_grow);
run_case('w_paren2d_end_rhs_shrink', @w_paren2d_end_rhs_shrink);
run_case('w_paren2d_end_rhs_rebind', @w_paren2d_end_rhs_rebind);
run_case('w_paren2d_end_rhs_clear', @w_paren2d_end_rhs_clear);
run_case('w_brace_sub_plain_rhs_plain', @w_brace_sub_plain_rhs_plain);
run_case('w_brace_sub_plain_rhs_grow', @w_brace_sub_plain_rhs_grow);
run_case('w_brace_sub_plain_rhs_shrink', @w_brace_sub_plain_rhs_shrink);
run_case('w_brace_sub_plain_rhs_rebind', @w_brace_sub_plain_rhs_rebind);
run_case('w_brace_sub_plain_rhs_clear', @w_brace_sub_plain_rhs_clear);
run_case('w_brace_sub_grow_rhs_plain', @w_brace_sub_grow_rhs_plain);
run_case('w_brace_sub_grow_rhs_grow', @w_brace_sub_grow_rhs_grow);
run_case('w_brace_sub_grow_rhs_shrink', @w_brace_sub_grow_rhs_shrink);
run_case('w_brace_sub_grow_rhs_rebind', @w_brace_sub_grow_rhs_rebind);
run_case('w_brace_sub_grow_rhs_clear', @w_brace_sub_grow_rhs_clear);
run_case('w_brace_sub_shrink_rhs_plain', @w_brace_sub_shrink_rhs_plain);
run_case('w_brace_sub_shrink_rhs_grow', @w_brace_sub_shrink_rhs_grow);
run_case('w_brace_sub_shrink_rhs_shrink', @w_brace_sub_shrink_rhs_shrink);
run_case('w_brace_sub_shrink_rhs_rebind', @w_brace_sub_shrink_rhs_rebind);
run_case('w_brace_sub_shrink_rhs_clear', @w_brace_sub_shrink_rhs_clear);
run_case('w_brace_sub_rebind_rhs_plain', @w_brace_sub_rebind_rhs_plain);
run_case('w_brace_sub_rebind_rhs_grow', @w_brace_sub_rebind_rhs_grow);
run_case('w_brace_sub_rebind_rhs_shrink', @w_brace_sub_rebind_rhs_shrink);
run_case('w_brace_sub_rebind_rhs_rebind', @w_brace_sub_rebind_rhs_rebind);
run_case('w_brace_sub_rebind_rhs_clear', @w_brace_sub_rebind_rhs_clear);
run_case('w_brace_sub_clear_rhs_plain', @w_brace_sub_clear_rhs_plain);
run_case('w_brace_sub_clear_rhs_grow', @w_brace_sub_clear_rhs_grow);
run_case('w_brace_sub_clear_rhs_shrink', @w_brace_sub_clear_rhs_shrink);
run_case('w_brace_sub_clear_rhs_rebind', @w_brace_sub_clear_rhs_rebind);
run_case('w_brace_sub_clear_rhs_clear', @w_brace_sub_clear_rhs_clear);
run_case('w_brace_end_rhs_grow', @w_brace_end_rhs_grow);
run_case('w_brace_end_rhs_shrink', @w_brace_end_rhs_shrink);
run_case('w_brace_end_rhs_rebind', @w_brace_end_rhs_rebind);
run_case('w_brace_end_rhs_clear', @w_brace_end_rhs_clear);
run_case('w_field_paren_sub_plain_rhs_plain', @w_field_paren_sub_plain_rhs_plain);
run_case('w_field_paren_sub_plain_rhs_grow', @w_field_paren_sub_plain_rhs_grow);
run_case('w_field_paren_sub_plain_rhs_shrink', @w_field_paren_sub_plain_rhs_shrink);
run_case('w_field_paren_sub_plain_rhs_rebind', @w_field_paren_sub_plain_rhs_rebind);
run_case('w_field_paren_sub_plain_rhs_clear', @w_field_paren_sub_plain_rhs_clear);
run_case('w_field_paren_sub_grow_rhs_plain', @w_field_paren_sub_grow_rhs_plain);
run_case('w_field_paren_sub_grow_rhs_grow', @w_field_paren_sub_grow_rhs_grow);
run_case('w_field_paren_sub_grow_rhs_shrink', @w_field_paren_sub_grow_rhs_shrink);
run_case('w_field_paren_sub_grow_rhs_rebind', @w_field_paren_sub_grow_rhs_rebind);
run_case('w_field_paren_sub_grow_rhs_clear', @w_field_paren_sub_grow_rhs_clear);
run_case('w_field_paren_sub_shrink_rhs_plain', @w_field_paren_sub_shrink_rhs_plain);
run_case('w_field_paren_sub_shrink_rhs_grow', @w_field_paren_sub_shrink_rhs_grow);
run_case('w_field_paren_sub_shrink_rhs_shrink', @w_field_paren_sub_shrink_rhs_shrink);
run_case('w_field_paren_sub_shrink_rhs_rebind', @w_field_paren_sub_shrink_rhs_rebind);
run_case('w_field_paren_sub_shrink_rhs_clear', @w_field_paren_sub_shrink_rhs_clear);
run_case('w_field_paren_sub_rebind_rhs_plain', @w_field_paren_sub_rebind_rhs_plain);
run_case('w_field_paren_sub_rebind_rhs_grow', @w_field_paren_sub_rebind_rhs_grow);
run_case('w_field_paren_sub_rebind_rhs_shrink', @w_field_paren_sub_rebind_rhs_shrink);
run_case('w_field_paren_sub_rebind_rhs_rebind', @w_field_paren_sub_rebind_rhs_rebind);
run_case('w_field_paren_sub_rebind_rhs_clear', @w_field_paren_sub_rebind_rhs_clear);
run_case('w_field_paren_sub_clear_rhs_plain', @w_field_paren_sub_clear_rhs_plain);
run_case('w_field_paren_sub_clear_rhs_grow', @w_field_paren_sub_clear_rhs_grow);
run_case('w_field_paren_sub_clear_rhs_shrink', @w_field_paren_sub_clear_rhs_shrink);
run_case('w_field_paren_sub_clear_rhs_rebind', @w_field_paren_sub_clear_rhs_rebind);
run_case('w_field_paren_sub_clear_rhs_clear', @w_field_paren_sub_clear_rhs_clear);
run_case('w_field_paren_end_rhs_grow', @w_field_paren_end_rhs_grow);
run_case('w_field_paren_end_rhs_shrink', @w_field_paren_end_rhs_shrink);
run_case('w_field_paren_end_rhs_rebind', @w_field_paren_end_rhs_rebind);
run_case('w_field_paren_end_rhs_clear', @w_field_paren_end_rhs_clear);
run_case('w_brace_paren_sub_plain_rhs_plain', @w_brace_paren_sub_plain_rhs_plain);
run_case('w_brace_paren_sub_plain_rhs_grow', @w_brace_paren_sub_plain_rhs_grow);
run_case('w_brace_paren_sub_plain_rhs_shrink', @w_brace_paren_sub_plain_rhs_shrink);
run_case('w_brace_paren_sub_plain_rhs_rebind', @w_brace_paren_sub_plain_rhs_rebind);
run_case('w_brace_paren_sub_plain_rhs_clear', @w_brace_paren_sub_plain_rhs_clear);
run_case('w_brace_paren_sub_grow_rhs_plain', @w_brace_paren_sub_grow_rhs_plain);
run_case('w_brace_paren_sub_grow_rhs_grow', @w_brace_paren_sub_grow_rhs_grow);
run_case('w_brace_paren_sub_grow_rhs_shrink', @w_brace_paren_sub_grow_rhs_shrink);
run_case('w_brace_paren_sub_grow_rhs_rebind', @w_brace_paren_sub_grow_rhs_rebind);
run_case('w_brace_paren_sub_grow_rhs_clear', @w_brace_paren_sub_grow_rhs_clear);
run_case('w_brace_paren_sub_shrink_rhs_plain', @w_brace_paren_sub_shrink_rhs_plain);
run_case('w_brace_paren_sub_shrink_rhs_grow', @w_brace_paren_sub_shrink_rhs_grow);
run_case('w_brace_paren_sub_shrink_rhs_shrink', @w_brace_paren_sub_shrink_rhs_shrink);
run_case('w_brace_paren_sub_shrink_rhs_rebind', @w_brace_paren_sub_shrink_rhs_rebind);
run_case('w_brace_paren_sub_shrink_rhs_clear', @w_brace_paren_sub_shrink_rhs_clear);
run_case('w_brace_paren_sub_rebind_rhs_plain', @w_brace_paren_sub_rebind_rhs_plain);
run_case('w_brace_paren_sub_rebind_rhs_grow', @w_brace_paren_sub_rebind_rhs_grow);
run_case('w_brace_paren_sub_rebind_rhs_shrink', @w_brace_paren_sub_rebind_rhs_shrink);
run_case('w_brace_paren_sub_rebind_rhs_rebind', @w_brace_paren_sub_rebind_rhs_rebind);
run_case('w_brace_paren_sub_rebind_rhs_clear', @w_brace_paren_sub_rebind_rhs_clear);
run_case('w_brace_paren_sub_clear_rhs_plain', @w_brace_paren_sub_clear_rhs_plain);
run_case('w_brace_paren_sub_clear_rhs_grow', @w_brace_paren_sub_clear_rhs_grow);
run_case('w_brace_paren_sub_clear_rhs_shrink', @w_brace_paren_sub_clear_rhs_shrink);
run_case('w_brace_paren_sub_clear_rhs_rebind', @w_brace_paren_sub_clear_rhs_rebind);
run_case('w_brace_paren_sub_clear_rhs_clear', @w_brace_paren_sub_clear_rhs_clear);
run_case('w_brace_paren_end_rhs_grow', @w_brace_paren_end_rhs_grow);
run_case('w_brace_paren_end_rhs_shrink', @w_brace_paren_end_rhs_shrink);
run_case('w_brace_paren_end_rhs_rebind', @w_brace_paren_end_rhs_rebind);
run_case('w_brace_paren_end_rhs_clear', @w_brace_paren_end_rhs_clear);
run_case('w_paren_field_sub_plain_rhs_plain', @w_paren_field_sub_plain_rhs_plain);
run_case('w_paren_field_sub_plain_rhs_grow', @w_paren_field_sub_plain_rhs_grow);
run_case('w_paren_field_sub_plain_rhs_shrink', @w_paren_field_sub_plain_rhs_shrink);
run_case('w_paren_field_sub_plain_rhs_rebind', @w_paren_field_sub_plain_rhs_rebind);
run_case('w_paren_field_sub_plain_rhs_clear', @w_paren_field_sub_plain_rhs_clear);
run_case('w_paren_field_sub_grow_rhs_plain', @w_paren_field_sub_grow_rhs_plain);
run_case('w_paren_field_sub_grow_rhs_grow', @w_paren_field_sub_grow_rhs_grow);
run_case('w_paren_field_sub_grow_rhs_shrink', @w_paren_field_sub_grow_rhs_shrink);
run_case('w_paren_field_sub_grow_rhs_rebind', @w_paren_field_sub_grow_rhs_rebind);
run_case('w_paren_field_sub_grow_rhs_clear', @w_paren_field_sub_grow_rhs_clear);
run_case('w_paren_field_sub_shrink_rhs_plain', @w_paren_field_sub_shrink_rhs_plain);
run_case('w_paren_field_sub_shrink_rhs_grow', @w_paren_field_sub_shrink_rhs_grow);
run_case('w_paren_field_sub_shrink_rhs_shrink', @w_paren_field_sub_shrink_rhs_shrink);
run_case('w_paren_field_sub_shrink_rhs_rebind', @w_paren_field_sub_shrink_rhs_rebind);
run_case('w_paren_field_sub_shrink_rhs_clear', @w_paren_field_sub_shrink_rhs_clear);
run_case('w_paren_field_sub_rebind_rhs_plain', @w_paren_field_sub_rebind_rhs_plain);
run_case('w_paren_field_sub_rebind_rhs_grow', @w_paren_field_sub_rebind_rhs_grow);
run_case('w_paren_field_sub_rebind_rhs_shrink', @w_paren_field_sub_rebind_rhs_shrink);
run_case('w_paren_field_sub_rebind_rhs_rebind', @w_paren_field_sub_rebind_rhs_rebind);
run_case('w_paren_field_sub_rebind_rhs_clear', @w_paren_field_sub_rebind_rhs_clear);
run_case('w_paren_field_sub_clear_rhs_plain', @w_paren_field_sub_clear_rhs_plain);
run_case('w_paren_field_sub_clear_rhs_grow', @w_paren_field_sub_clear_rhs_grow);
run_case('w_paren_field_sub_clear_rhs_shrink', @w_paren_field_sub_clear_rhs_shrink);
run_case('w_paren_field_sub_clear_rhs_rebind', @w_paren_field_sub_clear_rhs_rebind);
run_case('w_paren_field_sub_clear_rhs_clear', @w_paren_field_sub_clear_rhs_clear);
run_case('w_paren_field_end_rhs_grow', @w_paren_field_end_rhs_grow);
run_case('w_paren_field_end_rhs_shrink', @w_paren_field_end_rhs_shrink);
run_case('w_paren_field_end_rhs_rebind', @w_paren_field_end_rhs_rebind);
run_case('w_paren_field_end_rhs_clear', @w_paren_field_end_rhs_clear);
run_case('w_field_field_paren_sub_plain_rhs_plain', @w_field_field_paren_sub_plain_rhs_plain);
run_case('w_field_field_paren_sub_plain_rhs_grow', @w_field_field_paren_sub_plain_rhs_grow);
run_case('w_field_field_paren_sub_plain_rhs_shrink', @w_field_field_paren_sub_plain_rhs_shrink);
run_case('w_field_field_paren_sub_plain_rhs_rebind', @w_field_field_paren_sub_plain_rhs_rebind);
run_case('w_field_field_paren_sub_plain_rhs_clear', @w_field_field_paren_sub_plain_rhs_clear);
run_case('w_field_field_paren_sub_grow_rhs_plain', @w_field_field_paren_sub_grow_rhs_plain);
run_case('w_field_field_paren_sub_grow_rhs_grow', @w_field_field_paren_sub_grow_rhs_grow);
run_case('w_field_field_paren_sub_grow_rhs_shrink', @w_field_field_paren_sub_grow_rhs_shrink);
run_case('w_field_field_paren_sub_grow_rhs_rebind', @w_field_field_paren_sub_grow_rhs_rebind);
run_case('w_field_field_paren_sub_grow_rhs_clear', @w_field_field_paren_sub_grow_rhs_clear);
run_case('w_field_field_paren_sub_shrink_rhs_plain', @w_field_field_paren_sub_shrink_rhs_plain);
run_case('w_field_field_paren_sub_shrink_rhs_grow', @w_field_field_paren_sub_shrink_rhs_grow);
run_case('w_field_field_paren_sub_shrink_rhs_shrink', @w_field_field_paren_sub_shrink_rhs_shrink);
run_case('w_field_field_paren_sub_shrink_rhs_rebind', @w_field_field_paren_sub_shrink_rhs_rebind);
run_case('w_field_field_paren_sub_shrink_rhs_clear', @w_field_field_paren_sub_shrink_rhs_clear);
run_case('w_field_field_paren_sub_rebind_rhs_plain', @w_field_field_paren_sub_rebind_rhs_plain);
run_case('w_field_field_paren_sub_rebind_rhs_grow', @w_field_field_paren_sub_rebind_rhs_grow);
run_case('w_field_field_paren_sub_rebind_rhs_shrink', @w_field_field_paren_sub_rebind_rhs_shrink);
run_case('w_field_field_paren_sub_rebind_rhs_rebind', @w_field_field_paren_sub_rebind_rhs_rebind);
run_case('w_field_field_paren_sub_rebind_rhs_clear', @w_field_field_paren_sub_rebind_rhs_clear);
run_case('w_field_field_paren_sub_clear_rhs_plain', @w_field_field_paren_sub_clear_rhs_plain);
run_case('w_field_field_paren_sub_clear_rhs_grow', @w_field_field_paren_sub_clear_rhs_grow);
run_case('w_field_field_paren_sub_clear_rhs_shrink', @w_field_field_paren_sub_clear_rhs_shrink);
run_case('w_field_field_paren_sub_clear_rhs_rebind', @w_field_field_paren_sub_clear_rhs_rebind);
run_case('w_field_field_paren_sub_clear_rhs_clear', @w_field_field_paren_sub_clear_rhs_clear);
run_case('w_field_field_paren_end_rhs_grow', @w_field_field_paren_end_rhs_grow);
run_case('w_field_field_paren_end_rhs_shrink', @w_field_field_paren_end_rhs_shrink);
run_case('w_field_field_paren_end_rhs_rebind', @w_field_field_paren_end_rhs_rebind);
run_case('w_field_field_paren_end_rhs_clear', @w_field_field_paren_end_rhs_clear);
run_case('w_dynfield_sub_plain_rhs_plain', @w_dynfield_sub_plain_rhs_plain);
run_case('w_dynfield_sub_plain_rhs_grow', @w_dynfield_sub_plain_rhs_grow);
run_case('w_dynfield_sub_plain_rhs_shrink', @w_dynfield_sub_plain_rhs_shrink);
run_case('w_dynfield_sub_plain_rhs_rebind', @w_dynfield_sub_plain_rhs_rebind);
run_case('w_dynfield_sub_plain_rhs_clear', @w_dynfield_sub_plain_rhs_clear);
run_case('w_dynfield_sub_grow_rhs_plain', @w_dynfield_sub_grow_rhs_plain);
run_case('w_dynfield_sub_grow_rhs_grow', @w_dynfield_sub_grow_rhs_grow);
run_case('w_dynfield_sub_grow_rhs_shrink', @w_dynfield_sub_grow_rhs_shrink);
run_case('w_dynfield_sub_grow_rhs_rebind', @w_dynfield_sub_grow_rhs_rebind);
run_case('w_dynfield_sub_grow_rhs_clear', @w_dynfield_sub_grow_rhs_clear);
run_case('w_dynfield_sub_shrink_rhs_plain', @w_dynfield_sub_shrink_rhs_plain);
run_case('w_dynfield_sub_shrink_rhs_grow', @w_dynfield_sub_shrink_rhs_grow);
run_case('w_dynfield_sub_shrink_rhs_shrink', @w_dynfield_sub_shrink_rhs_shrink);
run_case('w_dynfield_sub_shrink_rhs_rebind', @w_dynfield_sub_shrink_rhs_rebind);
run_case('w_dynfield_sub_shrink_rhs_clear', @w_dynfield_sub_shrink_rhs_clear);
run_case('w_dynfield_sub_rebind_rhs_plain', @w_dynfield_sub_rebind_rhs_plain);
run_case('w_dynfield_sub_rebind_rhs_grow', @w_dynfield_sub_rebind_rhs_grow);
run_case('w_dynfield_sub_rebind_rhs_shrink', @w_dynfield_sub_rebind_rhs_shrink);
run_case('w_dynfield_sub_rebind_rhs_rebind', @w_dynfield_sub_rebind_rhs_rebind);
run_case('w_dynfield_sub_rebind_rhs_clear', @w_dynfield_sub_rebind_rhs_clear);
run_case('w_dynfield_sub_clear_rhs_plain', @w_dynfield_sub_clear_rhs_plain);
run_case('w_dynfield_sub_clear_rhs_grow', @w_dynfield_sub_clear_rhs_grow);
run_case('w_dynfield_sub_clear_rhs_shrink', @w_dynfield_sub_clear_rhs_shrink);
run_case('w_dynfield_sub_clear_rhs_rebind', @w_dynfield_sub_clear_rhs_rebind);
run_case('w_dynfield_sub_clear_rhs_clear', @w_dynfield_sub_clear_rhs_clear);

function run_case(name, fn)
global vlog_text
vlog_text = '';
try
    fprintf('CHK|%s|%s|exact\n', name, clean(fn()));
catch err
    fprintf('CHK|%s|ERR %s|exact\n', name, clean(err.message));
end
end

function s = clean(s)
if isnumeric(s) || islogical(s)
    s = mat2str(s);
end
s = char(s);
s = strrep(s, char(13), '');
s = strrep(s, char(10), ' ');
s = strrep(s, '|', '/');
end

function s = show(x)
% class, size and contents as text; a large array by its first two elements, its last and its sum.
sz = mat2str(size(x));
if isa(x, 'dictionary')
    ks = keys(x);
    parts = cell(1, numel(ks));
    for k = 1:numel(ks)
        parts{k} = sprintf('%s=%s', show(ks(k)), show(x(ks(k))));
    end
    s = sprintf('dictionary %d {%s}', numEntries(x), strjoin(parts, ' '));
elseif isa(x, 'ValueBox')
    s = sprintf('ValueBox p=%s', show(x.p));
elseif isstruct(x)
    if isscalar(x)
        fn = fieldnames(x);
        parts = cell(1, numel(fn));
        for k = 1:numel(fn)
            parts{k} = sprintf('%s=%s', fn{k}, show(x.(fn{k})));
        end
        s = sprintf('struct %s {%s}', sz, strjoin(parts, ' '));
    else
        fn = strjoin(fieldnames(x)', ',');
        if numel(x) <= 8
            parts = arrayfun(@(e) show_fields(e), x, 'UniformOutput', false);
            s = sprintf('struct %s [%s] {%s}', sz, fn, strjoin(parts(:)', ' '));
        else
            s = sprintf('struct %s [%s] {%s %s .. %s}', sz, fn, show_fields(x(1)), show_fields(x(2)), show_fields(x(end)));
        end
    end
elseif iscell(x)
    if numel(x) <= 8
        parts = cellfun(@show, x, 'UniformOutput', false);
        s = sprintf('cell %s {%s}', sz, strjoin(parts(:)', ' '));
    else
        s = sprintf('cell %s {%s %s .. %s}', sz, show(x{1}), show(x{2}), show(x{end}));
    end
elseif isstring(x)
    if numel(x) <= 8
        s = sprintf('string %s {%s}', sz, strjoin(cellstr(x(:)'), ' '));
    else
        s = sprintf('string %s {%s %s .. %s}', sz, x(1), x(2), x(end));
    end
elseif ischar(x)
    if numel(x) <= 16
        s = sprintf('char %s {%s}', sz, x(:)');
    else
        s = sprintf('char %s {%s%s..%s}', sz, x(1), x(2), x(end));
    end
elseif islogical(x)
    if numel(x) <= 8
        s = sprintf('logical %s %s', sz, mat2str(x));
    else
        d = double(x(:));
        s = sprintf('logical %s [%s %s .. %s] sum=%s', sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
elseif isnumeric(x) && ~isreal(x)
    % real and imaginary planes apart: mat2str's spelling of a complex array is its own line (#61)
    if numel(x) <= 8
        s = sprintf('%s %s re=%s im=%s', class(x), sz, mat2str(double(real(x))), mat2str(double(imag(x))));
    else
        d = double(real(x(:))); e = double(imag(x(:)));
        s = sprintf('%s %s re=[%s %s .. %s] sum=%s im=[%s %s .. %s] sum=%s', class(x), sz, ...
            mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)), ...
            mat2str(e(1)), mat2str(e(2)), mat2str(e(end)), mat2str(sum(e)));
    end
elseif isnumeric(x)
    if numel(x) <= 8
        s = sprintf('%s %s %s', class(x), sz, mat2str(double(x)));
    else
        d = double(x(:));
        s = sprintf('%s %s [%s %s .. %s] sum=%s', class(x), sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
else
    s = sprintf('%s %s', class(x), sz);
end
end

function s = show_fields(e)
fn = fieldnames(e);
parts = cell(1, numel(fn));
for k = 1:numel(fn)
    parts{k} = show(e.(fn{k}));
end
s = strjoin(parts, ',');
end

function s = logged(v)
global vlog_text
s = sprintf('%s / %s', vlog_text, v);
end

function k = idx_paren_plain()
global gT
vlog('idx');

k = 2;
end

function v = rhs_paren_plain()
global gT
vlog('rhs');

v = 9;
end

function k = idx_paren_grow()
global gT
vlog('idx');
gT(end + 1) = 50;
k = 2;
end

function v = rhs_paren_grow()
global gT
vlog('rhs');
gT(end + 1) = 50;
v = 9;
end

function k = idx_paren_shrink()
global gT
vlog('idx');
gT(end) = [];
k = 2;
end

function v = rhs_paren_shrink()
global gT
vlog('rhs');
gT(end) = [];
v = 9;
end

function k = idx_paren_rebind()
global gT
vlog('idx');
gT = [7 7 7 7];
k = 2;
end

function v = rhs_paren_rebind()
global gT
vlog('rhs');
gT = [7 7 7 7];
v = 9;
end

function k = idx_paren_clear()
global gT
vlog('idx');
clear global gT
k = 2;
end

function v = rhs_paren_clear()
global gT
vlog('rhs');
clear global gT
v = 9;
end

function k = idx_paren2d_plain()
global gT
vlog('idx');

k = 2;
end

function v = rhs_paren2d_plain()
global gT
vlog('rhs');

v = 9;
end

function k = idx_paren2d_grow()
global gT
vlog('idx');
gT(:, end + 1) = [50; 60];
k = 2;
end

function v = rhs_paren2d_grow()
global gT
vlog('rhs');
gT(:, end + 1) = [50; 60];
v = 9;
end

function k = idx_paren2d_shrink()
global gT
vlog('idx');
gT(:, end) = [];
k = 2;
end

function v = rhs_paren2d_shrink()
global gT
vlog('rhs');
gT(:, end) = [];
v = 9;
end

function k = idx_paren2d_rebind()
global gT
vlog('idx');
gT = [7 7 7 7; 7 7 7 7];
k = 2;
end

function v = rhs_paren2d_rebind()
global gT
vlog('rhs');
gT = [7 7 7 7; 7 7 7 7];
v = 9;
end

function k = idx_paren2d_clear()
global gT
vlog('idx');
clear global gT
k = 2;
end

function v = rhs_paren2d_clear()
global gT
vlog('rhs');
clear global gT
v = 9;
end

function k = idx_brace_plain()
global gT
vlog('idx');

k = 2;
end

function v = rhs_brace_plain()
global gT
vlog('rhs');

v = 9;
end

function k = idx_brace_grow()
global gT
vlog('idx');
gT{end + 1} = 50;
k = 2;
end

function v = rhs_brace_grow()
global gT
vlog('rhs');
gT{end + 1} = 50;
v = 9;
end

function k = idx_brace_shrink()
global gT
vlog('idx');
gT(end) = [];
k = 2;
end

function v = rhs_brace_shrink()
global gT
vlog('rhs');
gT(end) = [];
v = 9;
end

function k = idx_brace_rebind()
global gT
vlog('idx');
gT = {7, 7, 7, 7};
k = 2;
end

function v = rhs_brace_rebind()
global gT
vlog('rhs');
gT = {7, 7, 7, 7};
v = 9;
end

function k = idx_brace_clear()
global gT
vlog('idx');
clear global gT
k = 2;
end

function v = rhs_brace_clear()
global gT
vlog('rhs');
clear global gT
v = 9;
end

function k = idx_field_paren_plain()
global gT
vlog('idx');

k = 2;
end

function v = rhs_field_paren_plain()
global gT
vlog('rhs');

v = 9;
end

function k = idx_field_paren_grow()
global gT
vlog('idx');
gT.f(end + 1) = 50;
k = 2;
end

function v = rhs_field_paren_grow()
global gT
vlog('rhs');
gT.f(end + 1) = 50;
v = 9;
end

function k = idx_field_paren_shrink()
global gT
vlog('idx');
gT.f(end) = [];
k = 2;
end

function v = rhs_field_paren_shrink()
global gT
vlog('rhs');
gT.f(end) = [];
v = 9;
end

function k = idx_field_paren_rebind()
global gT
vlog('idx');
gT = struct('f', [7 7 7 7]);
k = 2;
end

function v = rhs_field_paren_rebind()
global gT
vlog('rhs');
gT = struct('f', [7 7 7 7]);
v = 9;
end

function k = idx_field_paren_clear()
global gT
vlog('idx');
clear global gT
k = 2;
end

function v = rhs_field_paren_clear()
global gT
vlog('rhs');
clear global gT
v = 9;
end

function k = idx_brace_paren_plain()
global gT
vlog('idx');

k = 2;
end

function v = rhs_brace_paren_plain()
global gT
vlog('rhs');

v = 9;
end

function k = idx_brace_paren_grow()
global gT
vlog('idx');
gT{1}(end + 1) = 50;
k = 2;
end

function v = rhs_brace_paren_grow()
global gT
vlog('rhs');
gT{1}(end + 1) = 50;
v = 9;
end

function k = idx_brace_paren_shrink()
global gT
vlog('idx');
gT{1}(end) = [];
k = 2;
end

function v = rhs_brace_paren_shrink()
global gT
vlog('rhs');
gT{1}(end) = [];
v = 9;
end

function k = idx_brace_paren_rebind()
global gT
vlog('idx');
gT = {[7 7 7 7]};
k = 2;
end

function v = rhs_brace_paren_rebind()
global gT
vlog('rhs');
gT = {[7 7 7 7]};
v = 9;
end

function k = idx_brace_paren_clear()
global gT
vlog('idx');
clear global gT
k = 2;
end

function v = rhs_brace_paren_clear()
global gT
vlog('rhs');
clear global gT
v = 9;
end

function k = idx_paren_field_plain()
global gT
vlog('idx');

k = 2;
end

function v = rhs_paren_field_plain()
global gT
vlog('rhs');

v = 9;
end

function k = idx_paren_field_grow()
global gT
vlog('idx');
gT(end + 1).f = 50;
k = 2;
end

function v = rhs_paren_field_grow()
global gT
vlog('rhs');
gT(end + 1).f = 50;
v = 9;
end

function k = idx_paren_field_shrink()
global gT
vlog('idx');
gT(end) = [];
k = 2;
end

function v = rhs_paren_field_shrink()
global gT
vlog('rhs');
gT(end) = [];
v = 9;
end

function k = idx_paren_field_rebind()
global gT
vlog('idx');
gT = struct('f', {7, 7, 7, 7});
k = 2;
end

function v = rhs_paren_field_rebind()
global gT
vlog('rhs');
gT = struct('f', {7, 7, 7, 7});
v = 9;
end

function k = idx_paren_field_clear()
global gT
vlog('idx');
clear global gT
k = 2;
end

function v = rhs_paren_field_clear()
global gT
vlog('rhs');
clear global gT
v = 9;
end

function k = idx_field_field_paren_plain()
global gT
vlog('idx');

k = 2;
end

function v = rhs_field_field_paren_plain()
global gT
vlog('rhs');

v = 9;
end

function k = idx_field_field_paren_grow()
global gT
vlog('idx');
gT.a.b(end + 1) = 50;
k = 2;
end

function v = rhs_field_field_paren_grow()
global gT
vlog('rhs');
gT.a.b(end + 1) = 50;
v = 9;
end

function k = idx_field_field_paren_shrink()
global gT
vlog('idx');
gT.a.b(end) = [];
k = 2;
end

function v = rhs_field_field_paren_shrink()
global gT
vlog('rhs');
gT.a.b(end) = [];
v = 9;
end

function k = idx_field_field_paren_rebind()
global gT
vlog('idx');
gT = struct('a', struct('b', [7 7 7 7]));
k = 2;
end

function v = rhs_field_field_paren_rebind()
global gT
vlog('rhs');
gT = struct('a', struct('b', [7 7 7 7]));
v = 9;
end

function k = idx_field_field_paren_clear()
global gT
vlog('idx');
clear global gT
k = 2;
end

function v = rhs_field_field_paren_clear()
global gT
vlog('rhs');
clear global gT
v = 9;
end

function k = idx_dynfield_plain()
global gT
vlog('idx');

k = 'g';
end

function v = rhs_dynfield_plain()
global gT
vlog('rhs');

v = 9;
end

function k = idx_dynfield_grow()
global gT
vlog('idx');
gT.h = 50;
k = 'g';
end

function v = rhs_dynfield_grow()
global gT
vlog('rhs');
gT.h = 50;
v = 9;
end

function k = idx_dynfield_shrink()
global gT
vlog('idx');
gT = rmfield(gT, 'f');
k = 'g';
end

function v = rhs_dynfield_shrink()
global gT
vlog('rhs');
gT = rmfield(gT, 'f');
v = 9;
end

function k = idx_dynfield_rebind()
global gT
vlog('idx');
gT = struct('f', 7);
k = 'g';
end

function v = rhs_dynfield_rebind()
global gT
vlog('rhs');
gT = struct('f', 7);
v = 9;
end

function k = idx_dynfield_clear()
global gT
vlog('idx');
clear global gT
k = 'g';
end

function v = rhs_dynfield_clear()
global gT
vlog('rhs');
clear global gT
v = 9;
end

function s = w_paren_sub_plain_rhs_plain()
global gT
gT = [1 2 3];
gT(idx_paren_plain()) = rhs_paren_plain();
s = logged(show(gT));
end

function s = w_paren_sub_plain_rhs_grow()
global gT
gT = [1 2 3];
gT(idx_paren_plain()) = rhs_paren_grow();
s = logged(show(gT));
end

function s = w_paren_sub_plain_rhs_shrink()
global gT
gT = [1 2 3];
gT(idx_paren_plain()) = rhs_paren_shrink();
s = logged(show(gT));
end

function s = w_paren_sub_plain_rhs_rebind()
global gT
gT = [1 2 3];
gT(idx_paren_plain()) = rhs_paren_rebind();
s = logged(show(gT));
end

function s = w_paren_sub_plain_rhs_clear()
global gT
gT = [1 2 3];
gT(idx_paren_plain()) = rhs_paren_clear();
s = logged(show(gT));
end

function s = w_paren_sub_grow_rhs_plain()
global gT
gT = [1 2 3];
gT(idx_paren_grow()) = rhs_paren_plain();
s = logged(show(gT));
end

function s = w_paren_sub_grow_rhs_grow()
global gT
gT = [1 2 3];
gT(idx_paren_grow()) = rhs_paren_grow();
s = logged(show(gT));
end

function s = w_paren_sub_grow_rhs_shrink()
global gT
gT = [1 2 3];
gT(idx_paren_grow()) = rhs_paren_shrink();
s = logged(show(gT));
end

function s = w_paren_sub_grow_rhs_rebind()
global gT
gT = [1 2 3];
gT(idx_paren_grow()) = rhs_paren_rebind();
s = logged(show(gT));
end

function s = w_paren_sub_grow_rhs_clear()
global gT
gT = [1 2 3];
gT(idx_paren_grow()) = rhs_paren_clear();
s = logged(show(gT));
end

function s = w_paren_sub_shrink_rhs_plain()
global gT
gT = [1 2 3];
gT(idx_paren_shrink()) = rhs_paren_plain();
s = logged(show(gT));
end

function s = w_paren_sub_shrink_rhs_grow()
global gT
gT = [1 2 3];
gT(idx_paren_shrink()) = rhs_paren_grow();
s = logged(show(gT));
end

function s = w_paren_sub_shrink_rhs_shrink()
global gT
gT = [1 2 3];
gT(idx_paren_shrink()) = rhs_paren_shrink();
s = logged(show(gT));
end

function s = w_paren_sub_shrink_rhs_rebind()
global gT
gT = [1 2 3];
gT(idx_paren_shrink()) = rhs_paren_rebind();
s = logged(show(gT));
end

function s = w_paren_sub_shrink_rhs_clear()
global gT
gT = [1 2 3];
gT(idx_paren_shrink()) = rhs_paren_clear();
s = logged(show(gT));
end

function s = w_paren_sub_rebind_rhs_plain()
global gT
gT = [1 2 3];
gT(idx_paren_rebind()) = rhs_paren_plain();
s = logged(show(gT));
end

function s = w_paren_sub_rebind_rhs_grow()
global gT
gT = [1 2 3];
gT(idx_paren_rebind()) = rhs_paren_grow();
s = logged(show(gT));
end

function s = w_paren_sub_rebind_rhs_shrink()
global gT
gT = [1 2 3];
gT(idx_paren_rebind()) = rhs_paren_shrink();
s = logged(show(gT));
end

function s = w_paren_sub_rebind_rhs_rebind()
global gT
gT = [1 2 3];
gT(idx_paren_rebind()) = rhs_paren_rebind();
s = logged(show(gT));
end

function s = w_paren_sub_rebind_rhs_clear()
global gT
gT = [1 2 3];
gT(idx_paren_rebind()) = rhs_paren_clear();
s = logged(show(gT));
end

function s = w_paren_sub_clear_rhs_plain()
global gT
gT = [1 2 3];
gT(idx_paren_clear()) = rhs_paren_plain();
s = logged(show(gT));
end

function s = w_paren_sub_clear_rhs_grow()
global gT
gT = [1 2 3];
gT(idx_paren_clear()) = rhs_paren_grow();
s = logged(show(gT));
end

function s = w_paren_sub_clear_rhs_shrink()
global gT
gT = [1 2 3];
gT(idx_paren_clear()) = rhs_paren_shrink();
s = logged(show(gT));
end

function s = w_paren_sub_clear_rhs_rebind()
global gT
gT = [1 2 3];
gT(idx_paren_clear()) = rhs_paren_rebind();
s = logged(show(gT));
end

function s = w_paren_sub_clear_rhs_clear()
global gT
gT = [1 2 3];
gT(idx_paren_clear()) = rhs_paren_clear();
s = logged(show(gT));
end

function s = w_paren_end_rhs_grow()
global gT
gT = [1 2 3];
gT(end) = rhs_paren_grow();
s = logged(show(gT));
end

function s = w_paren_end_rhs_shrink()
global gT
gT = [1 2 3];
gT(end) = rhs_paren_shrink();
s = logged(show(gT));
end

function s = w_paren_end_rhs_rebind()
global gT
gT = [1 2 3];
gT(end) = rhs_paren_rebind();
s = logged(show(gT));
end

function s = w_paren_end_rhs_clear()
global gT
gT = [1 2 3];
gT(end) = rhs_paren_clear();
s = logged(show(gT));
end

function s = w_paren2d_sub_plain_rhs_plain()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_plain()) = rhs_paren2d_plain();
s = logged(show(gT));
end

function s = w_paren2d_sub_plain_rhs_grow()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_plain()) = rhs_paren2d_grow();
s = logged(show(gT));
end

function s = w_paren2d_sub_plain_rhs_shrink()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_plain()) = rhs_paren2d_shrink();
s = logged(show(gT));
end

function s = w_paren2d_sub_plain_rhs_rebind()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_plain()) = rhs_paren2d_rebind();
s = logged(show(gT));
end

function s = w_paren2d_sub_plain_rhs_clear()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_plain()) = rhs_paren2d_clear();
s = logged(show(gT));
end

function s = w_paren2d_sub_grow_rhs_plain()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_grow()) = rhs_paren2d_plain();
s = logged(show(gT));
end

function s = w_paren2d_sub_grow_rhs_grow()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_grow()) = rhs_paren2d_grow();
s = logged(show(gT));
end

function s = w_paren2d_sub_grow_rhs_shrink()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_grow()) = rhs_paren2d_shrink();
s = logged(show(gT));
end

function s = w_paren2d_sub_grow_rhs_rebind()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_grow()) = rhs_paren2d_rebind();
s = logged(show(gT));
end

function s = w_paren2d_sub_grow_rhs_clear()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_grow()) = rhs_paren2d_clear();
s = logged(show(gT));
end

function s = w_paren2d_sub_shrink_rhs_plain()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_shrink()) = rhs_paren2d_plain();
s = logged(show(gT));
end

function s = w_paren2d_sub_shrink_rhs_grow()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_shrink()) = rhs_paren2d_grow();
s = logged(show(gT));
end

function s = w_paren2d_sub_shrink_rhs_shrink()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_shrink()) = rhs_paren2d_shrink();
s = logged(show(gT));
end

function s = w_paren2d_sub_shrink_rhs_rebind()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_shrink()) = rhs_paren2d_rebind();
s = logged(show(gT));
end

function s = w_paren2d_sub_shrink_rhs_clear()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_shrink()) = rhs_paren2d_clear();
s = logged(show(gT));
end

function s = w_paren2d_sub_rebind_rhs_plain()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_rebind()) = rhs_paren2d_plain();
s = logged(show(gT));
end

function s = w_paren2d_sub_rebind_rhs_grow()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_rebind()) = rhs_paren2d_grow();
s = logged(show(gT));
end

function s = w_paren2d_sub_rebind_rhs_shrink()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_rebind()) = rhs_paren2d_shrink();
s = logged(show(gT));
end

function s = w_paren2d_sub_rebind_rhs_rebind()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_rebind()) = rhs_paren2d_rebind();
s = logged(show(gT));
end

function s = w_paren2d_sub_rebind_rhs_clear()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_rebind()) = rhs_paren2d_clear();
s = logged(show(gT));
end

function s = w_paren2d_sub_clear_rhs_plain()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_clear()) = rhs_paren2d_plain();
s = logged(show(gT));
end

function s = w_paren2d_sub_clear_rhs_grow()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_clear()) = rhs_paren2d_grow();
s = logged(show(gT));
end

function s = w_paren2d_sub_clear_rhs_shrink()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_clear()) = rhs_paren2d_shrink();
s = logged(show(gT));
end

function s = w_paren2d_sub_clear_rhs_rebind()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_clear()) = rhs_paren2d_rebind();
s = logged(show(gT));
end

function s = w_paren2d_sub_clear_rhs_clear()
global gT
gT = [1 2 3; 4 5 6];
gT(1, idx_paren2d_clear()) = rhs_paren2d_clear();
s = logged(show(gT));
end

function s = w_paren2d_end_rhs_grow()
global gT
gT = [1 2 3; 4 5 6];
gT(1, end) = rhs_paren2d_grow();
s = logged(show(gT));
end

function s = w_paren2d_end_rhs_shrink()
global gT
gT = [1 2 3; 4 5 6];
gT(1, end) = rhs_paren2d_shrink();
s = logged(show(gT));
end

function s = w_paren2d_end_rhs_rebind()
global gT
gT = [1 2 3; 4 5 6];
gT(1, end) = rhs_paren2d_rebind();
s = logged(show(gT));
end

function s = w_paren2d_end_rhs_clear()
global gT
gT = [1 2 3; 4 5 6];
gT(1, end) = rhs_paren2d_clear();
s = logged(show(gT));
end

function s = w_brace_sub_plain_rhs_plain()
global gT
gT = {1, 2, 3};
gT{idx_brace_plain()} = rhs_brace_plain();
s = logged(show(gT));
end

function s = w_brace_sub_plain_rhs_grow()
global gT
gT = {1, 2, 3};
gT{idx_brace_plain()} = rhs_brace_grow();
s = logged(show(gT));
end

function s = w_brace_sub_plain_rhs_shrink()
global gT
gT = {1, 2, 3};
gT{idx_brace_plain()} = rhs_brace_shrink();
s = logged(show(gT));
end

function s = w_brace_sub_plain_rhs_rebind()
global gT
gT = {1, 2, 3};
gT{idx_brace_plain()} = rhs_brace_rebind();
s = logged(show(gT));
end

function s = w_brace_sub_plain_rhs_clear()
global gT
gT = {1, 2, 3};
gT{idx_brace_plain()} = rhs_brace_clear();
s = logged(show(gT));
end

function s = w_brace_sub_grow_rhs_plain()
global gT
gT = {1, 2, 3};
gT{idx_brace_grow()} = rhs_brace_plain();
s = logged(show(gT));
end

function s = w_brace_sub_grow_rhs_grow()
global gT
gT = {1, 2, 3};
gT{idx_brace_grow()} = rhs_brace_grow();
s = logged(show(gT));
end

function s = w_brace_sub_grow_rhs_shrink()
global gT
gT = {1, 2, 3};
gT{idx_brace_grow()} = rhs_brace_shrink();
s = logged(show(gT));
end

function s = w_brace_sub_grow_rhs_rebind()
global gT
gT = {1, 2, 3};
gT{idx_brace_grow()} = rhs_brace_rebind();
s = logged(show(gT));
end

function s = w_brace_sub_grow_rhs_clear()
global gT
gT = {1, 2, 3};
gT{idx_brace_grow()} = rhs_brace_clear();
s = logged(show(gT));
end

function s = w_brace_sub_shrink_rhs_plain()
global gT
gT = {1, 2, 3};
gT{idx_brace_shrink()} = rhs_brace_plain();
s = logged(show(gT));
end

function s = w_brace_sub_shrink_rhs_grow()
global gT
gT = {1, 2, 3};
gT{idx_brace_shrink()} = rhs_brace_grow();
s = logged(show(gT));
end

function s = w_brace_sub_shrink_rhs_shrink()
global gT
gT = {1, 2, 3};
gT{idx_brace_shrink()} = rhs_brace_shrink();
s = logged(show(gT));
end

function s = w_brace_sub_shrink_rhs_rebind()
global gT
gT = {1, 2, 3};
gT{idx_brace_shrink()} = rhs_brace_rebind();
s = logged(show(gT));
end

function s = w_brace_sub_shrink_rhs_clear()
global gT
gT = {1, 2, 3};
gT{idx_brace_shrink()} = rhs_brace_clear();
s = logged(show(gT));
end

function s = w_brace_sub_rebind_rhs_plain()
global gT
gT = {1, 2, 3};
gT{idx_brace_rebind()} = rhs_brace_plain();
s = logged(show(gT));
end

function s = w_brace_sub_rebind_rhs_grow()
global gT
gT = {1, 2, 3};
gT{idx_brace_rebind()} = rhs_brace_grow();
s = logged(show(gT));
end

function s = w_brace_sub_rebind_rhs_shrink()
global gT
gT = {1, 2, 3};
gT{idx_brace_rebind()} = rhs_brace_shrink();
s = logged(show(gT));
end

function s = w_brace_sub_rebind_rhs_rebind()
global gT
gT = {1, 2, 3};
gT{idx_brace_rebind()} = rhs_brace_rebind();
s = logged(show(gT));
end

function s = w_brace_sub_rebind_rhs_clear()
global gT
gT = {1, 2, 3};
gT{idx_brace_rebind()} = rhs_brace_clear();
s = logged(show(gT));
end

function s = w_brace_sub_clear_rhs_plain()
global gT
gT = {1, 2, 3};
gT{idx_brace_clear()} = rhs_brace_plain();
s = logged(show(gT));
end

function s = w_brace_sub_clear_rhs_grow()
global gT
gT = {1, 2, 3};
gT{idx_brace_clear()} = rhs_brace_grow();
s = logged(show(gT));
end

function s = w_brace_sub_clear_rhs_shrink()
global gT
gT = {1, 2, 3};
gT{idx_brace_clear()} = rhs_brace_shrink();
s = logged(show(gT));
end

function s = w_brace_sub_clear_rhs_rebind()
global gT
gT = {1, 2, 3};
gT{idx_brace_clear()} = rhs_brace_rebind();
s = logged(show(gT));
end

function s = w_brace_sub_clear_rhs_clear()
global gT
gT = {1, 2, 3};
gT{idx_brace_clear()} = rhs_brace_clear();
s = logged(show(gT));
end

function s = w_brace_end_rhs_grow()
global gT
gT = {1, 2, 3};
gT{end} = rhs_brace_grow();
s = logged(show(gT));
end

function s = w_brace_end_rhs_shrink()
global gT
gT = {1, 2, 3};
gT{end} = rhs_brace_shrink();
s = logged(show(gT));
end

function s = w_brace_end_rhs_rebind()
global gT
gT = {1, 2, 3};
gT{end} = rhs_brace_rebind();
s = logged(show(gT));
end

function s = w_brace_end_rhs_clear()
global gT
gT = {1, 2, 3};
gT{end} = rhs_brace_clear();
s = logged(show(gT));
end

function s = w_field_paren_sub_plain_rhs_plain()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_plain()) = rhs_field_paren_plain();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_plain_rhs_grow()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_plain()) = rhs_field_paren_grow();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_plain_rhs_shrink()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_plain()) = rhs_field_paren_shrink();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_plain_rhs_rebind()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_plain()) = rhs_field_paren_rebind();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_plain_rhs_clear()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_plain()) = rhs_field_paren_clear();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_grow_rhs_plain()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_grow()) = rhs_field_paren_plain();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_grow_rhs_grow()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_grow()) = rhs_field_paren_grow();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_grow_rhs_shrink()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_grow()) = rhs_field_paren_shrink();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_grow_rhs_rebind()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_grow()) = rhs_field_paren_rebind();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_grow_rhs_clear()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_grow()) = rhs_field_paren_clear();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_shrink_rhs_plain()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_shrink()) = rhs_field_paren_plain();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_shrink_rhs_grow()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_shrink()) = rhs_field_paren_grow();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_shrink_rhs_shrink()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_shrink()) = rhs_field_paren_shrink();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_shrink_rhs_rebind()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_shrink()) = rhs_field_paren_rebind();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_shrink_rhs_clear()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_shrink()) = rhs_field_paren_clear();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_rebind_rhs_plain()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_rebind()) = rhs_field_paren_plain();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_rebind_rhs_grow()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_rebind()) = rhs_field_paren_grow();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_rebind_rhs_shrink()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_rebind()) = rhs_field_paren_shrink();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_rebind_rhs_rebind()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_rebind()) = rhs_field_paren_rebind();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_rebind_rhs_clear()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_rebind()) = rhs_field_paren_clear();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_clear_rhs_plain()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_clear()) = rhs_field_paren_plain();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_clear_rhs_grow()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_clear()) = rhs_field_paren_grow();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_clear_rhs_shrink()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_clear()) = rhs_field_paren_shrink();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_clear_rhs_rebind()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_clear()) = rhs_field_paren_rebind();
s = logged(show(gT.f));
end

function s = w_field_paren_sub_clear_rhs_clear()
global gT
gT = struct('f', [1 2 3]);
gT.f(idx_field_paren_clear()) = rhs_field_paren_clear();
s = logged(show(gT.f));
end

function s = w_field_paren_end_rhs_grow()
global gT
gT = struct('f', [1 2 3]);
gT.f(end) = rhs_field_paren_grow();
s = logged(show(gT.f));
end

function s = w_field_paren_end_rhs_shrink()
global gT
gT = struct('f', [1 2 3]);
gT.f(end) = rhs_field_paren_shrink();
s = logged(show(gT.f));
end

function s = w_field_paren_end_rhs_rebind()
global gT
gT = struct('f', [1 2 3]);
gT.f(end) = rhs_field_paren_rebind();
s = logged(show(gT.f));
end

function s = w_field_paren_end_rhs_clear()
global gT
gT = struct('f', [1 2 3]);
gT.f(end) = rhs_field_paren_clear();
s = logged(show(gT.f));
end

function s = w_brace_paren_sub_plain_rhs_plain()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_plain()) = rhs_brace_paren_plain();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_plain_rhs_grow()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_plain()) = rhs_brace_paren_grow();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_plain_rhs_shrink()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_plain()) = rhs_brace_paren_shrink();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_plain_rhs_rebind()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_plain()) = rhs_brace_paren_rebind();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_plain_rhs_clear()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_plain()) = rhs_brace_paren_clear();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_grow_rhs_plain()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_grow()) = rhs_brace_paren_plain();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_grow_rhs_grow()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_grow()) = rhs_brace_paren_grow();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_grow_rhs_shrink()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_grow()) = rhs_brace_paren_shrink();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_grow_rhs_rebind()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_grow()) = rhs_brace_paren_rebind();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_grow_rhs_clear()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_grow()) = rhs_brace_paren_clear();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_shrink_rhs_plain()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_shrink()) = rhs_brace_paren_plain();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_shrink_rhs_grow()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_shrink()) = rhs_brace_paren_grow();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_shrink_rhs_shrink()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_shrink()) = rhs_brace_paren_shrink();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_shrink_rhs_rebind()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_shrink()) = rhs_brace_paren_rebind();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_shrink_rhs_clear()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_shrink()) = rhs_brace_paren_clear();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_rebind_rhs_plain()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_rebind()) = rhs_brace_paren_plain();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_rebind_rhs_grow()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_rebind()) = rhs_brace_paren_grow();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_rebind_rhs_shrink()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_rebind()) = rhs_brace_paren_shrink();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_rebind_rhs_rebind()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_rebind()) = rhs_brace_paren_rebind();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_rebind_rhs_clear()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_rebind()) = rhs_brace_paren_clear();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_clear_rhs_plain()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_clear()) = rhs_brace_paren_plain();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_clear_rhs_grow()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_clear()) = rhs_brace_paren_grow();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_clear_rhs_shrink()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_clear()) = rhs_brace_paren_shrink();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_clear_rhs_rebind()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_clear()) = rhs_brace_paren_rebind();
s = logged(show(gT{1}));
end

function s = w_brace_paren_sub_clear_rhs_clear()
global gT
gT = {[1 2 3]};
gT{1}(idx_brace_paren_clear()) = rhs_brace_paren_clear();
s = logged(show(gT{1}));
end

function s = w_brace_paren_end_rhs_grow()
global gT
gT = {[1 2 3]};
gT{1}(end) = rhs_brace_paren_grow();
s = logged(show(gT{1}));
end

function s = w_brace_paren_end_rhs_shrink()
global gT
gT = {[1 2 3]};
gT{1}(end) = rhs_brace_paren_shrink();
s = logged(show(gT{1}));
end

function s = w_brace_paren_end_rhs_rebind()
global gT
gT = {[1 2 3]};
gT{1}(end) = rhs_brace_paren_rebind();
s = logged(show(gT{1}));
end

function s = w_brace_paren_end_rhs_clear()
global gT
gT = {[1 2 3]};
gT{1}(end) = rhs_brace_paren_clear();
s = logged(show(gT{1}));
end

function s = w_paren_field_sub_plain_rhs_plain()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_plain()).f = rhs_paren_field_plain();
s = logged(show(gT));
end

function s = w_paren_field_sub_plain_rhs_grow()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_plain()).f = rhs_paren_field_grow();
s = logged(show(gT));
end

function s = w_paren_field_sub_plain_rhs_shrink()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_plain()).f = rhs_paren_field_shrink();
s = logged(show(gT));
end

function s = w_paren_field_sub_plain_rhs_rebind()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_plain()).f = rhs_paren_field_rebind();
s = logged(show(gT));
end

function s = w_paren_field_sub_plain_rhs_clear()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_plain()).f = rhs_paren_field_clear();
s = logged(show(gT));
end

function s = w_paren_field_sub_grow_rhs_plain()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_grow()).f = rhs_paren_field_plain();
s = logged(show(gT));
end

function s = w_paren_field_sub_grow_rhs_grow()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_grow()).f = rhs_paren_field_grow();
s = logged(show(gT));
end

function s = w_paren_field_sub_grow_rhs_shrink()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_grow()).f = rhs_paren_field_shrink();
s = logged(show(gT));
end

function s = w_paren_field_sub_grow_rhs_rebind()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_grow()).f = rhs_paren_field_rebind();
s = logged(show(gT));
end

function s = w_paren_field_sub_grow_rhs_clear()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_grow()).f = rhs_paren_field_clear();
s = logged(show(gT));
end

function s = w_paren_field_sub_shrink_rhs_plain()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_shrink()).f = rhs_paren_field_plain();
s = logged(show(gT));
end

function s = w_paren_field_sub_shrink_rhs_grow()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_shrink()).f = rhs_paren_field_grow();
s = logged(show(gT));
end

function s = w_paren_field_sub_shrink_rhs_shrink()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_shrink()).f = rhs_paren_field_shrink();
s = logged(show(gT));
end

function s = w_paren_field_sub_shrink_rhs_rebind()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_shrink()).f = rhs_paren_field_rebind();
s = logged(show(gT));
end

function s = w_paren_field_sub_shrink_rhs_clear()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_shrink()).f = rhs_paren_field_clear();
s = logged(show(gT));
end

function s = w_paren_field_sub_rebind_rhs_plain()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_rebind()).f = rhs_paren_field_plain();
s = logged(show(gT));
end

function s = w_paren_field_sub_rebind_rhs_grow()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_rebind()).f = rhs_paren_field_grow();
s = logged(show(gT));
end

function s = w_paren_field_sub_rebind_rhs_shrink()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_rebind()).f = rhs_paren_field_shrink();
s = logged(show(gT));
end

function s = w_paren_field_sub_rebind_rhs_rebind()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_rebind()).f = rhs_paren_field_rebind();
s = logged(show(gT));
end

function s = w_paren_field_sub_rebind_rhs_clear()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_rebind()).f = rhs_paren_field_clear();
s = logged(show(gT));
end

function s = w_paren_field_sub_clear_rhs_plain()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_clear()).f = rhs_paren_field_plain();
s = logged(show(gT));
end

function s = w_paren_field_sub_clear_rhs_grow()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_clear()).f = rhs_paren_field_grow();
s = logged(show(gT));
end

function s = w_paren_field_sub_clear_rhs_shrink()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_clear()).f = rhs_paren_field_shrink();
s = logged(show(gT));
end

function s = w_paren_field_sub_clear_rhs_rebind()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_clear()).f = rhs_paren_field_rebind();
s = logged(show(gT));
end

function s = w_paren_field_sub_clear_rhs_clear()
global gT
gT = struct('f', {1, 2, 3});
gT(idx_paren_field_clear()).f = rhs_paren_field_clear();
s = logged(show(gT));
end

function s = w_paren_field_end_rhs_grow()
global gT
gT = struct('f', {1, 2, 3});
gT(end).f = rhs_paren_field_grow();
s = logged(show(gT));
end

function s = w_paren_field_end_rhs_shrink()
global gT
gT = struct('f', {1, 2, 3});
gT(end).f = rhs_paren_field_shrink();
s = logged(show(gT));
end

function s = w_paren_field_end_rhs_rebind()
global gT
gT = struct('f', {1, 2, 3});
gT(end).f = rhs_paren_field_rebind();
s = logged(show(gT));
end

function s = w_paren_field_end_rhs_clear()
global gT
gT = struct('f', {1, 2, 3});
gT(end).f = rhs_paren_field_clear();
s = logged(show(gT));
end

function s = w_field_field_paren_sub_plain_rhs_plain()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_plain()) = rhs_field_field_paren_plain();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_plain_rhs_grow()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_plain()) = rhs_field_field_paren_grow();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_plain_rhs_shrink()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_plain()) = rhs_field_field_paren_shrink();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_plain_rhs_rebind()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_plain()) = rhs_field_field_paren_rebind();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_plain_rhs_clear()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_plain()) = rhs_field_field_paren_clear();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_grow_rhs_plain()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_grow()) = rhs_field_field_paren_plain();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_grow_rhs_grow()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_grow()) = rhs_field_field_paren_grow();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_grow_rhs_shrink()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_grow()) = rhs_field_field_paren_shrink();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_grow_rhs_rebind()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_grow()) = rhs_field_field_paren_rebind();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_grow_rhs_clear()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_grow()) = rhs_field_field_paren_clear();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_shrink_rhs_plain()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_shrink()) = rhs_field_field_paren_plain();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_shrink_rhs_grow()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_shrink()) = rhs_field_field_paren_grow();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_shrink_rhs_shrink()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_shrink()) = rhs_field_field_paren_shrink();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_shrink_rhs_rebind()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_shrink()) = rhs_field_field_paren_rebind();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_shrink_rhs_clear()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_shrink()) = rhs_field_field_paren_clear();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_rebind_rhs_plain()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_rebind()) = rhs_field_field_paren_plain();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_rebind_rhs_grow()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_rebind()) = rhs_field_field_paren_grow();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_rebind_rhs_shrink()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_rebind()) = rhs_field_field_paren_shrink();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_rebind_rhs_rebind()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_rebind()) = rhs_field_field_paren_rebind();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_rebind_rhs_clear()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_rebind()) = rhs_field_field_paren_clear();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_clear_rhs_plain()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_clear()) = rhs_field_field_paren_plain();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_clear_rhs_grow()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_clear()) = rhs_field_field_paren_grow();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_clear_rhs_shrink()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_clear()) = rhs_field_field_paren_shrink();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_clear_rhs_rebind()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_clear()) = rhs_field_field_paren_rebind();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_sub_clear_rhs_clear()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(idx_field_field_paren_clear()) = rhs_field_field_paren_clear();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_end_rhs_grow()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(end) = rhs_field_field_paren_grow();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_end_rhs_shrink()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(end) = rhs_field_field_paren_shrink();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_end_rhs_rebind()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(end) = rhs_field_field_paren_rebind();
s = logged(show(gT.a.b));
end

function s = w_field_field_paren_end_rhs_clear()
global gT
gT = struct('a', struct('b', [1 2 3]));
gT.a.b(end) = rhs_field_field_paren_clear();
s = logged(show(gT.a.b));
end

function s = w_dynfield_sub_plain_rhs_plain()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_plain()) = rhs_dynfield_plain();
s = logged(show(gT));
end

function s = w_dynfield_sub_plain_rhs_grow()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_plain()) = rhs_dynfield_grow();
s = logged(show(gT));
end

function s = w_dynfield_sub_plain_rhs_shrink()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_plain()) = rhs_dynfield_shrink();
s = logged(show(gT));
end

function s = w_dynfield_sub_plain_rhs_rebind()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_plain()) = rhs_dynfield_rebind();
s = logged(show(gT));
end

function s = w_dynfield_sub_plain_rhs_clear()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_plain()) = rhs_dynfield_clear();
s = logged(show(gT));
end

function s = w_dynfield_sub_grow_rhs_plain()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_grow()) = rhs_dynfield_plain();
s = logged(show(gT));
end

function s = w_dynfield_sub_grow_rhs_grow()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_grow()) = rhs_dynfield_grow();
s = logged(show(gT));
end

function s = w_dynfield_sub_grow_rhs_shrink()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_grow()) = rhs_dynfield_shrink();
s = logged(show(gT));
end

function s = w_dynfield_sub_grow_rhs_rebind()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_grow()) = rhs_dynfield_rebind();
s = logged(show(gT));
end

function s = w_dynfield_sub_grow_rhs_clear()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_grow()) = rhs_dynfield_clear();
s = logged(show(gT));
end

function s = w_dynfield_sub_shrink_rhs_plain()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_shrink()) = rhs_dynfield_plain();
s = logged(show(gT));
end

function s = w_dynfield_sub_shrink_rhs_grow()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_shrink()) = rhs_dynfield_grow();
s = logged(show(gT));
end

function s = w_dynfield_sub_shrink_rhs_shrink()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_shrink()) = rhs_dynfield_shrink();
s = logged(show(gT));
end

function s = w_dynfield_sub_shrink_rhs_rebind()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_shrink()) = rhs_dynfield_rebind();
s = logged(show(gT));
end

function s = w_dynfield_sub_shrink_rhs_clear()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_shrink()) = rhs_dynfield_clear();
s = logged(show(gT));
end

function s = w_dynfield_sub_rebind_rhs_plain()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_rebind()) = rhs_dynfield_plain();
s = logged(show(gT));
end

function s = w_dynfield_sub_rebind_rhs_grow()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_rebind()) = rhs_dynfield_grow();
s = logged(show(gT));
end

function s = w_dynfield_sub_rebind_rhs_shrink()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_rebind()) = rhs_dynfield_shrink();
s = logged(show(gT));
end

function s = w_dynfield_sub_rebind_rhs_rebind()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_rebind()) = rhs_dynfield_rebind();
s = logged(show(gT));
end

function s = w_dynfield_sub_rebind_rhs_clear()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_rebind()) = rhs_dynfield_clear();
s = logged(show(gT));
end

function s = w_dynfield_sub_clear_rhs_plain()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_clear()) = rhs_dynfield_plain();
s = logged(show(gT));
end

function s = w_dynfield_sub_clear_rhs_grow()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_clear()) = rhs_dynfield_grow();
s = logged(show(gT));
end

function s = w_dynfield_sub_clear_rhs_shrink()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_clear()) = rhs_dynfield_shrink();
s = logged(show(gT));
end

function s = w_dynfield_sub_clear_rhs_rebind()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_clear()) = rhs_dynfield_rebind();
s = logged(show(gT));
end

function s = w_dynfield_sub_clear_rhs_clear()
global gT
gT = struct('f', 1);
gT.(idx_dynfield_clear()) = rhs_dynfield_clear();
s = logged(show(gT));
end
