% value_isolation_gen_scope_5.m -- GENERATED by tools/parity/gen-value-isolation.py; do not edit.
% The scope matrix of the value-ownership plan (rule M5) at size 5: a global of every payload
% kind held by every scope kind -- an operand, a literal, a builtin's, a user function's, a
% method's, a handle's and feval's argument, a whole-call builtin, a loop's source, an index
% target -- while a call writes the global's first element; each line shows what the scope
% held and the global afterwards.

run_case('s_binary_real', @s_binary_real);
run_case('s_bracket_real', @s_bracket_real);
run_case('s_cell_literal_real', @s_cell_literal_real);
run_case('s_builtin_arg_real', @s_builtin_arg_real);
run_case('s_user_arg_real', @s_user_arg_real);
run_case('s_method_arg_real', @s_method_arg_real);
run_case('s_handle_arg_real', @s_handle_arg_real);
run_case('s_feval_arg_real', @s_feval_arg_real);
run_case('s_wholecall_cellfun_real', @s_wholecall_cellfun_real);
run_case('s_loop_source_real', @s_loop_source_real);
run_case('s_index_target_real', @s_index_target_real);
run_case('s_binary_complex', @s_binary_complex);
run_case('s_bracket_complex', @s_bracket_complex);
run_case('s_cell_literal_complex', @s_cell_literal_complex);
run_case('s_builtin_arg_complex', @s_builtin_arg_complex);
run_case('s_user_arg_complex', @s_user_arg_complex);
run_case('s_method_arg_complex', @s_method_arg_complex);
run_case('s_handle_arg_complex', @s_handle_arg_complex);
run_case('s_feval_arg_complex', @s_feval_arg_complex);
run_case('s_wholecall_cellfun_complex', @s_wholecall_cellfun_complex);
run_case('s_loop_source_complex', @s_loop_source_complex);
run_case('s_index_target_complex', @s_index_target_complex);
run_case('s_binary_single', @s_binary_single);
run_case('s_bracket_single', @s_bracket_single);
run_case('s_cell_literal_single', @s_cell_literal_single);
run_case('s_builtin_arg_single', @s_builtin_arg_single);
run_case('s_user_arg_single', @s_user_arg_single);
run_case('s_method_arg_single', @s_method_arg_single);
run_case('s_handle_arg_single', @s_handle_arg_single);
run_case('s_feval_arg_single', @s_feval_arg_single);
run_case('s_wholecall_cellfun_single', @s_wholecall_cellfun_single);
run_case('s_loop_source_single', @s_loop_source_single);
run_case('s_index_target_single', @s_index_target_single);
run_case('s_binary_int32', @s_binary_int32);
run_case('s_bracket_int32', @s_bracket_int32);
run_case('s_cell_literal_int32', @s_cell_literal_int32);
run_case('s_builtin_arg_int32', @s_builtin_arg_int32);
run_case('s_user_arg_int32', @s_user_arg_int32);
run_case('s_method_arg_int32', @s_method_arg_int32);
run_case('s_handle_arg_int32', @s_handle_arg_int32);
run_case('s_feval_arg_int32', @s_feval_arg_int32);
run_case('s_wholecall_cellfun_int32', @s_wholecall_cellfun_int32);
run_case('s_loop_source_int32', @s_loop_source_int32);
run_case('s_index_target_int32', @s_index_target_int32);
run_case('s_binary_logical', @s_binary_logical);
run_case('s_bracket_logical', @s_bracket_logical);
run_case('s_cell_literal_logical', @s_cell_literal_logical);
run_case('s_builtin_arg_logical', @s_builtin_arg_logical);
run_case('s_user_arg_logical', @s_user_arg_logical);
run_case('s_method_arg_logical', @s_method_arg_logical);
run_case('s_handle_arg_logical', @s_handle_arg_logical);
run_case('s_feval_arg_logical', @s_feval_arg_logical);
run_case('s_wholecall_cellfun_logical', @s_wholecall_cellfun_logical);
run_case('s_loop_source_logical', @s_loop_source_logical);
run_case('s_index_target_logical', @s_index_target_logical);
run_case('s_cell_literal_char', @s_cell_literal_char);
run_case('s_builtin_arg_char', @s_builtin_arg_char);
run_case('s_user_arg_char', @s_user_arg_char);
run_case('s_method_arg_char', @s_method_arg_char);
run_case('s_handle_arg_char', @s_handle_arg_char);
run_case('s_feval_arg_char', @s_feval_arg_char);
run_case('s_wholecall_cellfun_char', @s_wholecall_cellfun_char);
run_case('s_loop_source_char', @s_loop_source_char);
run_case('s_index_target_char', @s_index_target_char);
run_case('s_bracket_string', @s_bracket_string);
run_case('s_cell_literal_string', @s_cell_literal_string);
run_case('s_builtin_arg_string', @s_builtin_arg_string);
run_case('s_user_arg_string', @s_user_arg_string);
run_case('s_method_arg_string', @s_method_arg_string);
run_case('s_handle_arg_string', @s_handle_arg_string);
run_case('s_feval_arg_string', @s_feval_arg_string);
run_case('s_wholecall_cellfun_string', @s_wholecall_cellfun_string);
run_case('s_loop_source_string', @s_loop_source_string);
run_case('s_index_target_string', @s_index_target_string);
run_case('s_cell_literal_cell', @s_cell_literal_cell);
run_case('s_builtin_arg_cell', @s_builtin_arg_cell);
run_case('s_user_arg_cell', @s_user_arg_cell);
run_case('s_method_arg_cell', @s_method_arg_cell);
run_case('s_handle_arg_cell', @s_handle_arg_cell);
run_case('s_feval_arg_cell', @s_feval_arg_cell);
run_case('s_wholecall_cellfun_cell', @s_wholecall_cellfun_cell);
run_case('s_loop_source_cell', @s_loop_source_cell);
run_case('s_index_target_cell', @s_index_target_cell);
run_case('s_cell_literal_structarr', @s_cell_literal_structarr);
run_case('s_builtin_arg_structarr', @s_builtin_arg_structarr);
run_case('s_user_arg_structarr', @s_user_arg_structarr);
run_case('s_method_arg_structarr', @s_method_arg_structarr);
run_case('s_handle_arg_structarr', @s_handle_arg_structarr);
run_case('s_feval_arg_structarr', @s_feval_arg_structarr);
run_case('s_wholecall_cellfun_structarr', @s_wholecall_cellfun_structarr);
run_case('s_loop_source_structarr', @s_loop_source_structarr);
run_case('s_index_target_structarr', @s_index_target_structarr);
run_case('s_cell_literal_struct', @s_cell_literal_struct);
run_case('s_builtin_arg_struct', @s_builtin_arg_struct);
run_case('s_user_arg_struct', @s_user_arg_struct);
run_case('s_method_arg_struct', @s_method_arg_struct);
run_case('s_handle_arg_struct', @s_handle_arg_struct);
run_case('s_feval_arg_struct', @s_feval_arg_struct);
run_case('s_wholecall_cellfun_struct', @s_wholecall_cellfun_struct);
run_case('s_cell_literal_object', @s_cell_literal_object);
run_case('s_builtin_arg_object', @s_builtin_arg_object);
run_case('s_user_arg_object', @s_user_arg_object);
run_case('s_method_arg_object', @s_method_arg_object);
run_case('s_handle_arg_object', @s_handle_arg_object);
run_case('s_feval_arg_object', @s_feval_arg_object);
run_case('s_wholecall_cellfun_object', @s_wholecall_cellfun_object);
run_case('s_cell_literal_dict', @s_cell_literal_dict);
run_case('s_builtin_arg_dict', @s_builtin_arg_dict);
run_case('s_user_arg_dict', @s_user_arg_dict);
run_case('s_method_arg_dict', @s_method_arg_dict);
run_case('s_handle_arg_dict', @s_handle_arg_dict);
run_case('s_feval_arg_dict', @s_feval_arg_dict);
run_case('s_wholecall_cellfun_dict', @s_wholecall_cellfun_dict);

function run_case(name, fn)
global vlog_text
vlog_text = '';
try
    fprintf('CHK|%s|%s|exact\n', name, clean(fn()));
catch err
    fprintf('CHK|%s|ERR %s|exact\n', name, clean(err.message));
end
end

function s = clean(s)
if isnumeric(s) || islogical(s)
    s = mat2str(s);
end
s = char(s);
s = strrep(s, char(13), '');
s = strrep(s, char(10), ' ');
s = strrep(s, '|', '/');
end

function s = show(x)
% class, size and contents as text; a large array by its first two elements, its last and its sum.
sz = mat2str(size(x));
if isa(x, 'dictionary')
    ks = keys(x);
    parts = cell(1, numel(ks));
    for k = 1:numel(ks)
        parts{k} = sprintf('%s=%s', show(ks(k)), show(x(ks(k))));
    end
    s = sprintf('dictionary %d {%s}', numEntries(x), strjoin(parts, ' '));
elseif isa(x, 'ValueBox')
    s = sprintf('ValueBox p=%s', show(x.p));
elseif isstruct(x)
    if isscalar(x)
        fn = fieldnames(x);
        parts = cell(1, numel(fn));
        for k = 1:numel(fn)
            parts{k} = sprintf('%s=%s', fn{k}, show(x.(fn{k})));
        end
        s = sprintf('struct %s {%s}', sz, strjoin(parts, ' '));
    else
        fn = strjoin(fieldnames(x)', ',');
        if numel(x) <= 8
            parts = arrayfun(@(e) show_fields(e), x, 'UniformOutput', false);
            s = sprintf('struct %s [%s] {%s}', sz, fn, strjoin(parts(:)', ' '));
        else
            s = sprintf('struct %s [%s] {%s %s .. %s}', sz, fn, show_fields(x(1)), show_fields(x(2)), show_fields(x(end)));
        end
    end
elseif iscell(x)
    if numel(x) <= 8
        parts = cellfun(@show, x, 'UniformOutput', false);
        s = sprintf('cell %s {%s}', sz, strjoin(parts(:)', ' '));
    else
        s = sprintf('cell %s {%s %s .. %s}', sz, show(x{1}), show(x{2}), show(x{end}));
    end
elseif isstring(x)
    if numel(x) <= 8
        s = sprintf('string %s {%s}', sz, strjoin(cellstr(x(:)'), ' '));
    else
        s = sprintf('string %s {%s %s .. %s}', sz, x(1), x(2), x(end));
    end
elseif ischar(x)
    if numel(x) <= 16
        s = sprintf('char %s {%s}', sz, x(:)');
    else
        s = sprintf('char %s {%s%s..%s}', sz, x(1), x(2), x(end));
    end
elseif islogical(x)
    if numel(x) <= 8
        s = sprintf('logical %s %s', sz, mat2str(x));
    else
        d = double(x(:));
        s = sprintf('logical %s [%s %s .. %s] sum=%s', sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
elseif isnumeric(x) && ~isreal(x)
    % real and imaginary planes apart: mat2str's spelling of a complex array is its own line (#61)
    if numel(x) <= 8
        s = sprintf('%s %s re=%s im=%s', class(x), sz, mat2str(double(real(x))), mat2str(double(imag(x))));
    else
        d = double(real(x(:))); e = double(imag(x(:)));
        s = sprintf('%s %s re=[%s %s .. %s] sum=%s im=[%s %s .. %s] sum=%s', class(x), sz, ...
            mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)), ...
            mat2str(e(1)), mat2str(e(2)), mat2str(e(end)), mat2str(sum(e)));
    end
elseif isnumeric(x)
    if numel(x) <= 8
        s = sprintf('%s %s %s', class(x), sz, mat2str(double(x)));
    else
        d = double(x(:));
        s = sprintf('%s %s [%s %s .. %s] sum=%s', class(x), sz, mat2str(d(1)), mat2str(d(2)), mat2str(d(end)), mat2str(sum(d)));
    end
else
    s = sprintf('%s %s', class(x), sz);
end
end

function s = show_fields(e)
fn = fieldnames(e);
parts = cell(1, numel(fn));
for k = 1:numel(fn)
    parts{k} = show(e.(fn{k}));
end
s = strjoin(parts, ',');
end

function a = pass_first(a, ~)
end

function r = bump_then(x, b)
b();
r = x;
end

function z = bump_real()
global gS_real
gS_real(3) = 9;
z = 0;
end

function k = bumpi_real()
global gS_real
gS_real(3) = 9;
k = 3;
end

function s = s_binary_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
r = gS_real + bump_real();
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function s = s_bracket_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
r = [gS_real, bump_real()];
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function s = s_cell_literal_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
r = {gS_real, bump_real()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function s = s_builtin_arg_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
[r, ~] = deal(gS_real, bump_real());
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function s = s_user_arg_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
r = pass_first(gS_real, bump_real());
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function s = s_method_arg_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
rd = ValueReader(); r = rd.keep(gS_real, bump_real());
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function s = s_handle_arg_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
h = @pass_first; r = h(gS_real, bump_real());
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function s = s_feval_arg_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
r = feval(@pass_first, gS_real, bump_real());
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function s = s_wholecall_cellfun_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
r = cellfun(@(x) bump_then(x, @bump_real), {gS_real}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function s = s_loop_source_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
r = {}; for e = gS_real, r{end + 1} = e; bump_real(); end
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function s = s_index_target_real()
global gS_real
v = (1:5) * 1;
gS_real = v;
r = gS_real(bumpi_real());
s = sprintf('held=%s global=%s', show(r), show(gS_real));
end

function z = bump_complex()
global gS_complex
gS_complex(3) = 9;
z = 0;
end

function k = bumpi_complex()
global gS_complex
gS_complex(3) = 9;
k = 3;
end

function s = s_binary_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
r = gS_complex + bump_complex();
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function s = s_bracket_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
r = [gS_complex, bump_complex()];
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function s = s_cell_literal_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
r = {gS_complex, bump_complex()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function s = s_builtin_arg_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
[r, ~] = deal(gS_complex, bump_complex());
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function s = s_user_arg_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
r = pass_first(gS_complex, bump_complex());
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function s = s_method_arg_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
rd = ValueReader(); r = rd.keep(gS_complex, bump_complex());
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function s = s_handle_arg_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
h = @pass_first; r = h(gS_complex, bump_complex());
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function s = s_feval_arg_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
r = feval(@pass_first, gS_complex, bump_complex());
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function s = s_wholecall_cellfun_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
r = cellfun(@(x) bump_then(x, @bump_complex), {gS_complex}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function s = s_loop_source_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
r = {}; for e = gS_complex, r{end + 1} = e; bump_complex(); end
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function s = s_index_target_complex()
global gS_complex
v = (1:5) + 1i;
gS_complex = v;
r = gS_complex(bumpi_complex());
s = sprintf('held=%s global=%s', show(r), show(gS_complex));
end

function z = bump_single()
global gS_single
gS_single(3) = 9;
z = 0;
end

function k = bumpi_single()
global gS_single
gS_single(3) = 9;
k = 3;
end

function s = s_binary_single()
global gS_single
v = single(1:5);
gS_single = v;
r = gS_single + bump_single();
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function s = s_bracket_single()
global gS_single
v = single(1:5);
gS_single = v;
r = [gS_single, bump_single()];
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function s = s_cell_literal_single()
global gS_single
v = single(1:5);
gS_single = v;
r = {gS_single, bump_single()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function s = s_builtin_arg_single()
global gS_single
v = single(1:5);
gS_single = v;
[r, ~] = deal(gS_single, bump_single());
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function s = s_user_arg_single()
global gS_single
v = single(1:5);
gS_single = v;
r = pass_first(gS_single, bump_single());
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function s = s_method_arg_single()
global gS_single
v = single(1:5);
gS_single = v;
rd = ValueReader(); r = rd.keep(gS_single, bump_single());
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function s = s_handle_arg_single()
global gS_single
v = single(1:5);
gS_single = v;
h = @pass_first; r = h(gS_single, bump_single());
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function s = s_feval_arg_single()
global gS_single
v = single(1:5);
gS_single = v;
r = feval(@pass_first, gS_single, bump_single());
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function s = s_wholecall_cellfun_single()
global gS_single
v = single(1:5);
gS_single = v;
r = cellfun(@(x) bump_then(x, @bump_single), {gS_single}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function s = s_loop_source_single()
global gS_single
v = single(1:5);
gS_single = v;
r = {}; for e = gS_single, r{end + 1} = e; bump_single(); end
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function s = s_index_target_single()
global gS_single
v = single(1:5);
gS_single = v;
r = gS_single(bumpi_single());
s = sprintf('held=%s global=%s', show(r), show(gS_single));
end

function z = bump_int32()
global gS_int32
gS_int32(3) = 9;
z = 0;
end

function k = bumpi_int32()
global gS_int32
gS_int32(3) = 9;
k = 3;
end

function s = s_binary_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
r = gS_int32 + bump_int32();
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function s = s_bracket_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
r = [gS_int32, bump_int32()];
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function s = s_cell_literal_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
r = {gS_int32, bump_int32()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function s = s_builtin_arg_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
[r, ~] = deal(gS_int32, bump_int32());
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function s = s_user_arg_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
r = pass_first(gS_int32, bump_int32());
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function s = s_method_arg_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
rd = ValueReader(); r = rd.keep(gS_int32, bump_int32());
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function s = s_handle_arg_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
h = @pass_first; r = h(gS_int32, bump_int32());
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function s = s_feval_arg_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
r = feval(@pass_first, gS_int32, bump_int32());
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function s = s_wholecall_cellfun_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
r = cellfun(@(x) bump_then(x, @bump_int32), {gS_int32}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function s = s_loop_source_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
r = {}; for e = gS_int32, r{end + 1} = e; bump_int32(); end
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function s = s_index_target_int32()
global gS_int32
v = int32(1:5);
gS_int32 = v;
r = gS_int32(bumpi_int32());
s = sprintf('held=%s global=%s', show(r), show(gS_int32));
end

function z = bump_logical()
global gS_logical
gS_logical(3) = true;
z = 0;
end

function k = bumpi_logical()
global gS_logical
gS_logical(3) = true;
k = 3;
end

function s = s_binary_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
r = gS_logical + bump_logical();
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function s = s_bracket_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
r = [gS_logical, bump_logical()];
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function s = s_cell_literal_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
r = {gS_logical, bump_logical()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function s = s_builtin_arg_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
[r, ~] = deal(gS_logical, bump_logical());
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function s = s_user_arg_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
r = pass_first(gS_logical, bump_logical());
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function s = s_method_arg_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
rd = ValueReader(); r = rd.keep(gS_logical, bump_logical());
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function s = s_handle_arg_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
h = @pass_first; r = h(gS_logical, bump_logical());
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function s = s_feval_arg_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
r = feval(@pass_first, gS_logical, bump_logical());
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function s = s_wholecall_cellfun_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
r = cellfun(@(x) bump_then(x, @bump_logical), {gS_logical}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function s = s_loop_source_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
r = {}; for e = gS_logical, r{end + 1} = e; bump_logical(); end
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function s = s_index_target_logical()
global gS_logical
v = mod(1:5, 2) == 0;
gS_logical = v;
r = gS_logical(bumpi_logical());
s = sprintf('held=%s global=%s', show(r), show(gS_logical));
end

function z = bump_char()
global gS_char
gS_char(3) = 'z';
z = 0;
end

function k = bumpi_char()
global gS_char
gS_char(3) = 'z';
k = 3;
end

function s = s_cell_literal_char()
global gS_char
t0 = repmat('ab', 1, 5); v = t0(1:5);
gS_char = v;
r = {gS_char, bump_char()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_char));
end

function s = s_builtin_arg_char()
global gS_char
t0 = repmat('ab', 1, 5); v = t0(1:5);
gS_char = v;
[r, ~] = deal(gS_char, bump_char());
s = sprintf('held=%s global=%s', show(r), show(gS_char));
end

function s = s_user_arg_char()
global gS_char
t0 = repmat('ab', 1, 5); v = t0(1:5);
gS_char = v;
r = pass_first(gS_char, bump_char());
s = sprintf('held=%s global=%s', show(r), show(gS_char));
end

function s = s_method_arg_char()
global gS_char
t0 = repmat('ab', 1, 5); v = t0(1:5);
gS_char = v;
rd = ValueReader(); r = rd.keep(gS_char, bump_char());
s = sprintf('held=%s global=%s', show(r), show(gS_char));
end

function s = s_handle_arg_char()
global gS_char
t0 = repmat('ab', 1, 5); v = t0(1:5);
gS_char = v;
h = @pass_first; r = h(gS_char, bump_char());
s = sprintf('held=%s global=%s', show(r), show(gS_char));
end

function s = s_feval_arg_char()
global gS_char
t0 = repmat('ab', 1, 5); v = t0(1:5);
gS_char = v;
r = feval(@pass_first, gS_char, bump_char());
s = sprintf('held=%s global=%s', show(r), show(gS_char));
end

function s = s_wholecall_cellfun_char()
global gS_char
t0 = repmat('ab', 1, 5); v = t0(1:5);
gS_char = v;
r = cellfun(@(x) bump_then(x, @bump_char), {gS_char}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_char));
end

function s = s_loop_source_char()
global gS_char
t0 = repmat('ab', 1, 5); v = t0(1:5);
gS_char = v;
r = {}; for e = gS_char, r{end + 1} = e; bump_char(); end
s = sprintf('held=%s global=%s', show(r), show(gS_char));
end

function s = s_index_target_char()
global gS_char
t0 = repmat('ab', 1, 5); v = t0(1:5);
gS_char = v;
r = gS_char(bumpi_char());
s = sprintf('held=%s global=%s', show(r), show(gS_char));
end

function z = bump_string()
global gS_string
gS_string(3) = "z";
z = 0;
end

function k = bumpi_string()
global gS_string
gS_string(3) = "z";
k = 3;
end

function s = s_bracket_string()
global gS_string
v = "s" + (1:5);
gS_string = v;
r = [gS_string, bump_string()];
s = sprintf('held=%s global=%s', show(r), show(gS_string));
end

function s = s_cell_literal_string()
global gS_string
v = "s" + (1:5);
gS_string = v;
r = {gS_string, bump_string()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_string));
end

function s = s_builtin_arg_string()
global gS_string
v = "s" + (1:5);
gS_string = v;
[r, ~] = deal(gS_string, bump_string());
s = sprintf('held=%s global=%s', show(r), show(gS_string));
end

function s = s_user_arg_string()
global gS_string
v = "s" + (1:5);
gS_string = v;
r = pass_first(gS_string, bump_string());
s = sprintf('held=%s global=%s', show(r), show(gS_string));
end

function s = s_method_arg_string()
global gS_string
v = "s" + (1:5);
gS_string = v;
rd = ValueReader(); r = rd.keep(gS_string, bump_string());
s = sprintf('held=%s global=%s', show(r), show(gS_string));
end

function s = s_handle_arg_string()
global gS_string
v = "s" + (1:5);
gS_string = v;
h = @pass_first; r = h(gS_string, bump_string());
s = sprintf('held=%s global=%s', show(r), show(gS_string));
end

function s = s_feval_arg_string()
global gS_string
v = "s" + (1:5);
gS_string = v;
r = feval(@pass_first, gS_string, bump_string());
s = sprintf('held=%s global=%s', show(r), show(gS_string));
end

function s = s_wholecall_cellfun_string()
global gS_string
v = "s" + (1:5);
gS_string = v;
r = cellfun(@(x) bump_then(x, @bump_string), {gS_string}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_string));
end

function s = s_loop_source_string()
global gS_string
v = "s" + (1:5);
gS_string = v;
r = {}; for e = gS_string, r{end + 1} = e; bump_string(); end
s = sprintf('held=%s global=%s', show(r), show(gS_string));
end

function s = s_index_target_string()
global gS_string
v = "s" + (1:5);
gS_string = v;
r = gS_string(bumpi_string());
s = sprintf('held=%s global=%s', show(r), show(gS_string));
end

function z = bump_cell()
global gS_cell
gS_cell{3} = 9;
z = 0;
end

function k = bumpi_cell()
global gS_cell
gS_cell{3} = 9;
k = 3;
end

function s = s_cell_literal_cell()
global gS_cell
v = num2cell(1:5);
gS_cell = v;
r = {gS_cell, bump_cell()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_cell));
end

function s = s_builtin_arg_cell()
global gS_cell
v = num2cell(1:5);
gS_cell = v;
[r, ~] = deal(gS_cell, bump_cell());
s = sprintf('held=%s global=%s', show(r), show(gS_cell));
end

function s = s_user_arg_cell()
global gS_cell
v = num2cell(1:5);
gS_cell = v;
r = pass_first(gS_cell, bump_cell());
s = sprintf('held=%s global=%s', show(r), show(gS_cell));
end

function s = s_method_arg_cell()
global gS_cell
v = num2cell(1:5);
gS_cell = v;
rd = ValueReader(); r = rd.keep(gS_cell, bump_cell());
s = sprintf('held=%s global=%s', show(r), show(gS_cell));
end

function s = s_handle_arg_cell()
global gS_cell
v = num2cell(1:5);
gS_cell = v;
h = @pass_first; r = h(gS_cell, bump_cell());
s = sprintf('held=%s global=%s', show(r), show(gS_cell));
end

function s = s_feval_arg_cell()
global gS_cell
v = num2cell(1:5);
gS_cell = v;
r = feval(@pass_first, gS_cell, bump_cell());
s = sprintf('held=%s global=%s', show(r), show(gS_cell));
end

function s = s_wholecall_cellfun_cell()
global gS_cell
v = num2cell(1:5);
gS_cell = v;
r = cellfun(@(x) bump_then(x, @bump_cell), {gS_cell}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_cell));
end

function s = s_loop_source_cell()
global gS_cell
v = num2cell(1:5);
gS_cell = v;
r = {}; for e = gS_cell, r{end + 1} = e; bump_cell(); end
s = sprintf('held=%s global=%s', show(r), show(gS_cell));
end

function s = s_index_target_cell()
global gS_cell
v = num2cell(1:5);
gS_cell = v;
r = gS_cell(bumpi_cell());
s = sprintf('held=%s global=%s', show(r), show(gS_cell));
end

function z = bump_structarr()
global gS_structarr
gS_structarr(3).f = 9;
z = 0;
end

function k = bumpi_structarr()
global gS_structarr
gS_structarr(3).f = 9;
k = 3;
end

function s = s_cell_literal_structarr()
global gS_structarr
v = struct('f', num2cell(1:5));
gS_structarr = v;
r = {gS_structarr, bump_structarr()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_structarr));
end

function s = s_builtin_arg_structarr()
global gS_structarr
v = struct('f', num2cell(1:5));
gS_structarr = v;
[r, ~] = deal(gS_structarr, bump_structarr());
s = sprintf('held=%s global=%s', show(r), show(gS_structarr));
end

function s = s_user_arg_structarr()
global gS_structarr
v = struct('f', num2cell(1:5));
gS_structarr = v;
r = pass_first(gS_structarr, bump_structarr());
s = sprintf('held=%s global=%s', show(r), show(gS_structarr));
end

function s = s_method_arg_structarr()
global gS_structarr
v = struct('f', num2cell(1:5));
gS_structarr = v;
rd = ValueReader(); r = rd.keep(gS_structarr, bump_structarr());
s = sprintf('held=%s global=%s', show(r), show(gS_structarr));
end

function s = s_handle_arg_structarr()
global gS_structarr
v = struct('f', num2cell(1:5));
gS_structarr = v;
h = @pass_first; r = h(gS_structarr, bump_structarr());
s = sprintf('held=%s global=%s', show(r), show(gS_structarr));
end

function s = s_feval_arg_structarr()
global gS_structarr
v = struct('f', num2cell(1:5));
gS_structarr = v;
r = feval(@pass_first, gS_structarr, bump_structarr());
s = sprintf('held=%s global=%s', show(r), show(gS_structarr));
end

function s = s_wholecall_cellfun_structarr()
global gS_structarr
v = struct('f', num2cell(1:5));
gS_structarr = v;
r = cellfun(@(x) bump_then(x, @bump_structarr), {gS_structarr}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_structarr));
end

function s = s_loop_source_structarr()
global gS_structarr
v = struct('f', num2cell(1:5));
gS_structarr = v;
r = {}; for e = gS_structarr, r{end + 1} = e; bump_structarr(); end
s = sprintf('held=%s global=%s', show(r), show(gS_structarr));
end

function s = s_index_target_structarr()
global gS_structarr
v = struct('f', num2cell(1:5));
gS_structarr = v;
r = gS_structarr(bumpi_structarr());
s = sprintf('held=%s global=%s', show(r), show(gS_structarr));
end

function z = bump_struct()
global gS_struct
gS_struct.f(3) = 9;
z = 0;
end

function k = bumpi_struct()
global gS_struct
gS_struct.f(3) = 9;
k = 3;
end

function s = s_cell_literal_struct()
global gS_struct
v = struct('f', 1:5);
gS_struct = v;
r = {gS_struct, bump_struct()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_struct));
end

function s = s_builtin_arg_struct()
global gS_struct
v = struct('f', 1:5);
gS_struct = v;
[r, ~] = deal(gS_struct, bump_struct());
s = sprintf('held=%s global=%s', show(r), show(gS_struct));
end

function s = s_user_arg_struct()
global gS_struct
v = struct('f', 1:5);
gS_struct = v;
r = pass_first(gS_struct, bump_struct());
s = sprintf('held=%s global=%s', show(r), show(gS_struct));
end

function s = s_method_arg_struct()
global gS_struct
v = struct('f', 1:5);
gS_struct = v;
rd = ValueReader(); r = rd.keep(gS_struct, bump_struct());
s = sprintf('held=%s global=%s', show(r), show(gS_struct));
end

function s = s_handle_arg_struct()
global gS_struct
v = struct('f', 1:5);
gS_struct = v;
h = @pass_first; r = h(gS_struct, bump_struct());
s = sprintf('held=%s global=%s', show(r), show(gS_struct));
end

function s = s_feval_arg_struct()
global gS_struct
v = struct('f', 1:5);
gS_struct = v;
r = feval(@pass_first, gS_struct, bump_struct());
s = sprintf('held=%s global=%s', show(r), show(gS_struct));
end

function s = s_wholecall_cellfun_struct()
global gS_struct
v = struct('f', 1:5);
gS_struct = v;
r = cellfun(@(x) bump_then(x, @bump_struct), {gS_struct}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_struct));
end

function z = bump_object()
global gS_object
gS_object.p(3) = 9;
z = 0;
end

function k = bumpi_object()
global gS_object
gS_object.p(3) = 9;
k = 3;
end

function s = s_cell_literal_object()
global gS_object
v = ValueBox(); v.p = 1:5;
gS_object = v;
r = {gS_object, bump_object()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_object));
end

function s = s_builtin_arg_object()
global gS_object
v = ValueBox(); v.p = 1:5;
gS_object = v;
[r, ~] = deal(gS_object, bump_object());
s = sprintf('held=%s global=%s', show(r), show(gS_object));
end

function s = s_user_arg_object()
global gS_object
v = ValueBox(); v.p = 1:5;
gS_object = v;
r = pass_first(gS_object, bump_object());
s = sprintf('held=%s global=%s', show(r), show(gS_object));
end

function s = s_method_arg_object()
global gS_object
v = ValueBox(); v.p = 1:5;
gS_object = v;
rd = ValueReader(); r = rd.keep(gS_object, bump_object());
s = sprintf('held=%s global=%s', show(r), show(gS_object));
end

function s = s_handle_arg_object()
global gS_object
v = ValueBox(); v.p = 1:5;
gS_object = v;
h = @pass_first; r = h(gS_object, bump_object());
s = sprintf('held=%s global=%s', show(r), show(gS_object));
end

function s = s_feval_arg_object()
global gS_object
v = ValueBox(); v.p = 1:5;
gS_object = v;
r = feval(@pass_first, gS_object, bump_object());
s = sprintf('held=%s global=%s', show(r), show(gS_object));
end

function s = s_wholecall_cellfun_object()
global gS_object
v = ValueBox(); v.p = 1:5;
gS_object = v;
r = cellfun(@(x) bump_then(x, @bump_object), {gS_object}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_object));
end

function z = bump_dict()
global gS_dict
gS_dict(3) = 9;
z = 0;
end

function k = bumpi_dict()
global gS_dict
gS_dict(3) = 9;
k = 3;
end

function s = s_cell_literal_dict()
global gS_dict
v = dictionary(1:5, 1:5);
gS_dict = v;
r = {gS_dict, bump_dict()}; r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_dict));
end

function s = s_builtin_arg_dict()
global gS_dict
v = dictionary(1:5, 1:5);
gS_dict = v;
[r, ~] = deal(gS_dict, bump_dict());
s = sprintf('held=%s global=%s', show(r), show(gS_dict));
end

function s = s_user_arg_dict()
global gS_dict
v = dictionary(1:5, 1:5);
gS_dict = v;
r = pass_first(gS_dict, bump_dict());
s = sprintf('held=%s global=%s', show(r), show(gS_dict));
end

function s = s_method_arg_dict()
global gS_dict
v = dictionary(1:5, 1:5);
gS_dict = v;
rd = ValueReader(); r = rd.keep(gS_dict, bump_dict());
s = sprintf('held=%s global=%s', show(r), show(gS_dict));
end

function s = s_handle_arg_dict()
global gS_dict
v = dictionary(1:5, 1:5);
gS_dict = v;
h = @pass_first; r = h(gS_dict, bump_dict());
s = sprintf('held=%s global=%s', show(r), show(gS_dict));
end

function s = s_feval_arg_dict()
global gS_dict
v = dictionary(1:5, 1:5);
gS_dict = v;
r = feval(@pass_first, gS_dict, bump_dict());
s = sprintf('held=%s global=%s', show(r), show(gS_dict));
end

function s = s_wholecall_cellfun_dict()
global gS_dict
v = dictionary(1:5, 1:5);
gS_dict = v;
r = cellfun(@(x) bump_then(x, @bump_dict), {gS_dict}, 'UniformOutput', false); r = r{1};
s = sprintf('held=%s global=%s', show(r), show(gS_dict));
end
