% Sweep 2: every catalog name that carries ANY @class method, shadowed one at a time, called with
% the fundamental-class patterns and with library-class arguments in first and second position.
root = fileparts(mfilename('fullpath'));
work = fullfile(root, 'dispatch_work3');
if ~isfolder(work), mkdir(work); end
cd(work);
skip = {'fopen','fprintf','fclose','rehash','feval','system','builtin','strsplit','fgetl','ischar', ...
        'isempty','numel','strcmp','isequal','mkdir','isfolder','cd','delete','fileparts','mfilename', ...
        'fullfile','disp','size','class','isa','error','true','false','struct','cell','string','double', ...
        'int8','table','datetime','duration','categorical','containers.Map','any','strjoin','regexp'};
rows = {'fgetl', 'ischar', 'isempty', 'numel', 'strcmp', 'isequal', 'delete', 'disp', 'size', 'class', 'isa', 'true', 'false', 'struct', 'cell', 'string', 'double', 'table', 'datetime', 'duration', 'categorical', 'any'};
tbl = table([1;2], [3;4], 'VariableNames', {'a','b'});
dt = datetime(2020,1,1); du = seconds(5); ct = categorical({'x'}); mp = containers.Map({'a'},{1});
patterns = { ...
    'none', {}; ...
    'double', {1.5}; ...
    'string', {"x"}; ...
    'cell', {{1}}; ...
    'struct', {struct('a',1)}; ...
    'fh', {@sin}; ...
    'char', {'x'}; ...
    'logical', {true}; ...
    'int8', {int8(1)}; ...
    'table', {tbl}; ...
    'datetime', {dt}; ...
    'duration', {du}; ...
    'categorical', {ct}; ...
    'map', {mp}; ...
    'double,double', {1.5, 2.5}; ...
    'double,string', {1.5, "x"}; ...
    'string,double', {"x", 1.5}; ...
    'double,cell', {1.5, {1}}; ...
    'cell,double', {{1}, 1.5}; ...
    'double,struct', {1.5, struct('a',1)}; ...
    'double,fh', {1.5, @sin}; ...
    'int8,double', {int8(1), 1.5}; ...
    'double,char', {1.5, 'x'}; ...
    'char,double', {'x', 1.5}; ...
    'string,string', {"x", "y"}; ...
    'double,table', {1.5, tbl}; ...
    'table,double', {tbl, 1.5}; ...
    'double,datetime', {1.5, dt}; ...
    'datetime,double', {dt, 1.5}; ...
    'double,duration', {1.5, du}; ...
    'double,categorical', {1.5, ct}; ...
    'double,map', {1.5, mp}; ...
    'map,double', {mp, 1.5}; ...
    'string,cell', {"x", {1}}; ...
    'cell,string', {{1}, "x"}; ...
    'double,double,string', {1.5, 2.5, "x"}; ...
    'double,double,cell', {1.5, 2.5, {1}}; ...
    };
out = fopen(fullfile(root, 'dispatch-probe3.csv'), 'w');
fprintf(out, 'name');
for p = 1:size(patterns, 1), fprintf(out, ',"%s"', patterns{p, 1}); end
fprintf(out, '\n');
sentinel = -12345;
for k = 1:numel(rows)
    name = rows{k};
    file = fullfile(work, [name '.m']);
    try
        f = fopen(file, 'w'); fprintf(f, 'function y = %s(varargin)\ny = %d;\nend\n', name, sentinel); fclose(f);
        rehash;
    catch
        fprintf(out, '%s', name); for p = 1:size(patterns, 1), fprintf(out, ',harness'); end; fprintf(out, '\n');
        continue;
    end
    fprintf(out, '%s', name);
    for p = 1:size(patterns, 1)
        args = patterns{p, 2};
        verdict = 'builtin';
        try
            r = feval(name, args{:});
            if builtin('isequal', r, sentinel), verdict = 'file'; end
        catch e
            id = e.identifier;
            if builtin('strcmp', id, 'MATLAB:UndefinedFunction'), verdict = 'undefined'; else, verdict = 'builtin-err'; end
        end
        fprintf(out, ',%s', verdict);
    end
    fprintf(out, '\n');
    try, system(['del /q "' file '"']); rehash; catch, end
end
fclose(out);
cd(root);
disp('dispatch probe 3 done');
