// Generated by tools/make-v73-fixtures.py — do not edit by hand.
using System.IO;
using System.IO.Compression;

namespace JGraph.Tests.Scripting;

/// <summary>
/// Real version 7.3 MAT-files for the reader tests, each written by an HDF5 library and kept here
/// deflated and base64-encoded so the repository carries no binary assets.
/// </summary>
/// <remarks>
/// Hand-building these the way the version 5 tests hand-build their big-endian files was the
/// alternative, and was rejected: a hand-rolled writer agreeing with a hand-rolled reader proves
/// only that the two share an opinion. These bytes were laid out by something that had never heard
/// of this reader.
/// </remarks>
internal static class MatV73Fixture
{
    /// <summary>Every plain kind: double, scalar, int32, single, logical, char, a char matrix, a three-dimensional array, and an empty.</summary>
    private const string Plain =
        "eNrtWM1u2kAQ3jWQrGgikZ8WFFXqqqqqHNLIISSNuMQ0UCUSUNQgteolccD8SAYqIFJy6jV9kx77CD31efoGdPHOUnsbbCBGTVQPSB8znv2Z2Z" +
        "lh1oVMOZ95Q19v79JCpvyq1jSNLVoy9X6t022laenow0lxP7VFj7qG3jeqtNNO01O9TzOXdbqzR3eSaVVlX5pUk/v0OPt2j/YqDaOl051tJt1G" +
        "bqSgkwIK6J/SV3Zmy9GNqMUQgsIoJg7HogHQxw0nL8afA2LAG8BvipBj61kC5Cswv6xXfp/LDRcdSCTWUcMcD4CPxUEeHOF/Qce5TGmI34Evif" +
        "h7Mt91MVrgsY0Fv8lR4YIQcqTLLXzCGrpCDxGxJBpKPUKpAShGmHT4XFH4hAQyJYRBXYrwJeAxWmYKBBWs+n1WMfVebyhfY7Ms2PKx2rm8MA2+" +
        "rh90WnyXxdauOdGQx7mJ83rsrrcp8nrFXU9Yoa2764k6oa7dz3j2iiss1VUZZ48rFY6O3Ku4mjTPsJRnf/iY9TvGzOJ/FdTDDwdEWD6tHyK2dZ" +
        "vt/m7SEekPkX4dQvZpzjRbBySACY5aTsNQ4/g5/GDj6VCGG8hAJvt0kI4uUJVxV+haWuWpNOtzabWX0i6o5tzdC+du0KaGAgoooIACCiggH/su" +
        "ReqzlLF96LNR3xUnKP4FefWhWV/60F6zXfe3D12cyB/jcNSHjqYgHn7IgwPCU/th0eYHs1NvVnSTjdNg3Cr7PRrH2tSzqlHpVA1xz5L6ZPl+Md" +
        "4ffN8YY7ALOdBuP/dJzMP+Etgfndr+sG2/lYbe5ePuZr8y2kFspvjwfh8wrX8+zXxPma9/xtUPfvPGIezqB//fl9SI843kXe+1qk/1w5kvbvWC" +
        "2C494+38SW6Lz1ntXBLnxcbZ4sFofe5fT1YnEhP5JSPqNWAbsA6YB+wDlgGLgDlp3fM5/R/y91thsHZsGfjL+psFdz0xzVXEXU9EHV192I3Fb2" +
        "LWxlI=";

    /// <summary>Two chunked datasets, one deflated and one shuffled, deflated and checksummed, each spanning several chunks in both directions.</summary>
    private const string Deflate =
        "eNrtWn1UE1cWn4RQElAIAVvXIBkJkrYUCWDBFUkIfkBRhKoVuiKRCgT8Cn6gtI4JrVqFqsixrrIK0eNu2131oHYFlJJA6gdEBKxVQSsQRakokA" +
        "Q/ZiSEfclMrM5KPdt/tnt2fifJzbvvvnfvu/e+y3sT4iTzZkmi4LAJIXCcZF5ARtay9HfghGWpazLkq5ZPhhOmJr43O3TiO/DUVempa9LTYPmK" +
        "yfDc1DWwJEcGB70LBwVPFgrBCw4WBofCMdNmvAuvXpyZvjwVDpoAuBOgXwMdei8OovBfRT6I2UjnMc62BpMJMSC2PTg2DBHwDnixbR+/iKA0gm" +
        "4l6Dd0O59m6xtN8N2J+cly8+ZMn26VHiLBrkfIwCmbCtn/JWKmSxKsNIlo2/Opjv6iXBRB55LyMvI36qVBTvgcNHv7TZzScYY3yR5y2wF8s0q6" +
        "w2KISVgy0QWaOOSA9zsCrrWf7oBP6ALBtjbtmT6mbQelpWeAopwOsYh5mYQGB7pDriPOcrax8Tc0AhIS40cCBhOKs9V56eJlqatXW/keYP7Xnv" +
        "NPmjzno2Xpz1v+csydHT+NBooDk2jDDr/uP/t+PeZG5fDzsNY7Gogmud5Vv2IcOganVSQ+k9Q+ycXpqWHiYUe2F05PQ78k0cvw1tgX53MeRu/t" +
        "sS+fj6x3P7FRKom25zB65/NwWkGSI+t1hXH6LUmOrPcs/GLbk7RfmVRqUqBAgQIFChR+Z6AR94Xh7iMjCLnh6H9+H0nA7yMO9scC+H1kdWZORg" +
        "a4MDChl99TGM/04ScwILsGPBhaFRL8b/eXGrZdNf5m4uc2nIv64J2ThjnpDneODnqFH3PHEc8VSHxHUvvvhNxbJD75nNxKms9xGL10Yj3vkOTI" +
        "8sHDyJH1phByglec3wsIOT+SHFnv8WHkyPOib7/cH27UOZoCBQoUKFCg8DtF7vV3G6riGEGen1/icjhsNjspc6DlAv+1UH1RniPzrzf9knVf3p" +
        "rzFSMWunp+F3LifFchOqQoP38mtDBr3aHBlROl0deeXLqz9J+90UMpW9vu74oQiR6Ylj/1kKmN9evUBn/NLOU/Ep8u2lIYth5BbpRYGtaLsEaB" +
        "FNOWXVbdPzlWVFqCnRPwnKoNqj7EVCJFdXvufdH2c6M374prO7rf8kOECuly0ZhcpF+3/3x0rCjlgdGYtUe+xezoPjOmEBh/aeZK8Cjz8/d9p9" +
        "E5PjRWEdsxYIP47oSdbFZMJJ2zM3s8fLAnW3d3QYlextQ/ObPl4R5hf3duyvKyw9cGlliSI9SJT24sufX95e6SPuSOi9KUL8a2q8wdXKWxWIxq" +
        "o0XftdSuU5s2izFdn/lcvMKwXYM2rBMZi9zkaw0lZYi+z1z7rMPwcwRyi88T/fQ9GFLUZO/pGRrCtCprj/pBx0DAIHRyckpJ7vWAC+M+0QqhvE" +
        "t1ujpdbNr4E9Et7pPogpa8keI/5k/z8QfgA/hXbPhYg11x0ZehosHAHwsfr8qKv/b40VWRslysua7s7XHgVXYXt6OblUY3RWf4iidageKOzFIf" +
        "j3TSEyP6uRpDoGV7H7bjRrUhX4oVi40OvFM1HzSZzwWai8WGiPaVVW+IjP5KfbSig/+GbSa5pY6HlvZV3nRRoU5iI19sKHJJfoSoFLRZE2SfAZ" +
        "9frIpzDPKcfmlBAX8TO8rsXEmbAnfugvKLIvNyp1d67gn+W6UnI6U0bemUb3fwLaUbzfFVf7nZK+v/uPxqq0kULpINNC3z6j4parnNVSHIKRnG" +
        "HzLWy5Eufyl63Hy894HB+NEWOWI6fs2jHdsOHAj8/KFlnvzhJW+efC12rsska8Q6w9SGjX3IQkuyvMdgXFJY6FaFLLBowzXG+kRrzwVpd4mo1a" +
        "agSqbSKKNia4DLG9/HUz32m02xo1m7hZzuvF76OJdlc1i7E1j8g5wZdPDaWTpgiijZJ96k8Q/ExAfb59+/321Rn95w5Nz57kenPlGUhYJoByJ3" +
        "PXjq+Uq0lgcM1/RzedgXKnOnUzuqlYmM+iwnpcmp3ZY00aJ5SrTeTW3c3ARyQGkUKMGCzI1y5Nb3N10Vpo1yRB+iMRZp0F1itDFR0RWiQg0ZTm" +
        "KsNkw9pT+wR7xwrdXwgDlnhdBmkCs6XR0O8E339QFzteSE559rOEl0Tj7C2bt/qSgnYwVTuV5zeIjV4xXgdujeyjUfjykpjZY/HQx+as3l4kJz" +
        "g2NvtBjbDTR7aAwe6y4HKm6HS7GGaMVd7RU3RVcisDXerI1HKnkR6HawL0J4WLEKc9H0+4PlCRR6PlicxgjCcpevwhIt2j6zDoQjv8zMtXeor0" +
        "o9PvmgxZos9XFnhcDlCwr2LfJeU2HIG3UsdaeEzmL82DEnOTZ25VtMZP9FgUCk9LGUVoNM2XvxRmtParmm4WpFqykoXJ2xWBoIIpxpzQjjUSd1" +
        "PxdsT2DtCfPB3oegTpTZMiK6rR9kkB64/LT5eEqr/na9N69vLVZuzg95lhGq7pNtN2wZ8bTJJOv9JeVOtbXob7eCetN5W6Ck9YfPrLd6fOFyxj" +
        "ho8/u+2xi+MI3Fp7HSLrcvr5CADNHGjGbFJLFiMrmNG7DS2aumojdS+pVRp4+uCDzcn5PzXVmp6vDg0pOi+S4qrG5LxRWB0gjyQteH3AoD8RZj" +
        "jcBZxYUIatioQUEO3wH1hAvirTLX4h2VA7VSM6iepnAVai1GgZYOrhRtiBYhA7Vulk6w+JJ4UFks9VL7CLReo/owZa+1qBxeu0kIRUpEhzmnOK" +
        "CMFK2Mk673AXWkqCimMzbtjiK2QrD64gchI8q+emJUTs0fvHdIjDwukw72rxvq+Xqop01j2N2EdIYp9AIF+OwCNaCmzNzQjtaF2VIHlI0zMksH" +
        "KO35bmZdE3InXm0kBnCHOtzsA4Bp9cQAqTnwWYcYA74QAF/IRG3nxfEuWbTclMWLRic1N+dtfyS58EP9Rsl5XeuuqU3XW+fW1Jw7O/NM89WzF9" +
        "poThBkHOvmxz7S5GcbENncATFGjISzIWbNR/A4J82B5q2ZyknubK/X/+DgV3OiBYIOznr9msOf/Ktx+Y5jUMxEL4jj5F1z1jNvWjLd2V3F5Ht5" +
        "ZbOhiwLnBeXzTqA2QcaBg7TGvGO+2x4kV6dv61lYPWqW10/Il7M+3VRQfKiqzAH8I49mj2tOyNqGBMIQiO4UCTXkQLRjSZHZSWkj9jJHsAoLpr" +
        "MXjQdGjJKMLp/75tHQZ0b7uvrmFUceAdZMAtYY84U+tN3Z0L2aGRCk3eecllVw/YFNNqEZuGQCg77k7o5e9ZjXZ3srMjmu2Xl+4Gfs8a8tTT6t" +
        "OYRPmQ0xmh0lsNB3ytuhb070mewap6W5NvtCeg/WEWiUX+wr//7/9t/HKVCgQIECBQr/s/d/2zFipwEcjw6wPouM8tkaE/VGxqLs7Dz3TAi6eZ" +
        "wxjRurKvgXPinmKw==";

    /// <summary>A complex row vector, stored as the two-member compound MATLAB uses.</summary>
    private const string Complex =
        "eNrzdQzxcXRSMNczVvB1DNFNy8xJ1VEIyEksScsvyrVSCHAO9/QzM9FRcC5KTSxJTVHIz7NSCE4sUXAsTVcwNFUwNLIyMAAiBSMDIzMFDxc3U4" +
        "Xi5IzU3EQFQz2gqB4DPsDE4OnLMAoGFHQC44yXS4oLzOHgYGBhEIBFDhj8hwIFLlQ+TH8ClGaE0h1QegUTTJwRLCcBFReEmo+uLiTI1RWk+j8a" +
        "gNljwAKhOUajbEQCD1fHABAdAeVDUynDCSZUdVVo6dGDQnsZgSmOEclARmhKZmRkRM4mcJqZoQGsVIwJ4kZgsZlDjD2CCvbQtO3AYMLNYPKfmY" +
        "EhMzcxnZg0j00vK9TdTExMjBAzIO5mZoQZp4BihgA0RCtYIfwKuAyq7cF+/i6MDHBDGBSYR9MmOYCHwQCanniBYcnB4Auuh+OTcxKLi0HiwsBY" +
        "Y0NKxyn5pUk5qSB9FlB9/EA2Ql9+bkFOKjDSBIARw4IUv4xo+WEUjAJM8MEeynCA5nkoLXAAAHQEXl8=";

    /// <summary>A cell array of references, a scalar struct, and a two-element struct array.</summary>
    private const string Nested =
        "eNrtWs1PE0EUn9m2sCBogQiFeJgED8ZAbWtBw4XWgpaEj0ZI5AZLu7VNFkraBa8c8WI4cjIeORnjyXginvgTPHL06H+Au903dWcspa00fPT90u" +
        "Tt27752De/mXnzdhfiK/PxF+xZ8ClbiK+MZ/OGPsZShmZmC8XNKZZKvJlbnIyOsURR10w9wwpbU2xZM1l85y0LT7BwZCoUsn4sEopMsuTMywlW" +
        "Suf0TY2Fg9bdIKkFhcwtEMSV4r01Zr3dI91lRVWJl/j54JRxBjiIijovvw6SgtwHeaTw+7T8XwDu90H9st3K69lZ2/pMAm/n1OfIAA5ZWyI5G0" +
        "/ZchX0RyBPFNFutKhnS6OEJEBfNkFqIk9DdbZ7Hn+THkfP+erj73PVkQyHEvnr4u++T7QDmpINkDoQVQ83x9/lxaUZaq3qQD/CPGI9Mo9h9ScH" +
        "/bXr5Tw+fCzWdwz66Zi4Xn8aEO1OQP91/2aMHyUdTt8p150RpAoVnus86bE8YV/3sWkYixiJ3iHRM/C/z7pr/68oToUqeM5D97ocC1XoTw8wgJ" +
        "Je6x+VLJTjuLW0oZVK9v0Bq5YOV/uZws6GoTvtXgZkXj3qrG3PebXXV9uO8+VovD7+fQvehtXhQcwk70ih4kXRS7+n4SKWI3m4fAjDGI1xT90O" +
        "TyAQCAQC0Q6gpFOKK50IiFIKcSORpL9s6q+kaPwXxI/7ED92NBw/el3xYzqnFZ1yMSjXb11XyuW3zLWMni5kdB7vqU55HqlRIqSVXBHhRXG26A" +
        "9FqscDzz0EEfL5fvjQVa3dhv2gGwYRMl+t5odPyD/4of/rg46eIvXlH46Hankd0W75B84ndVDKPxjbOTsHsaGbmnveNntq5HwNjMDJpsnza8ks" +
        "7qTNi8/hinTuVi7tHP6x6fWj9edwpXIO/zJY3zlcHcY50cg+/O++0+g+/Bn4470R+zDPc8t5uh7Y9yi5a1kEeLvZvG5k7A4PQ412v2kN/9npxs" +
        "ORv3PT69Jtm1eJpXnq6h51lXOvU7w+7lW+bnmkeb8rPd/RPeQ8AoFAIBAIBAKBQCAQ5MrzMdXz3qvjjeW9f4aqfT2DIG2a965ku6Tvi3alfFHy" +
        "P9vlfGURR98mrc17t+77s6/X8vuzq/PH92vqD1+L3pv+6KqeJz681vPeeS9CK6N08gTXwmbA3wPI3/X2wA7c6HuAavOR5/3tqfcHijIeXw==";

    /// <summary>The newer HDF5 layout: a version 3 superblock, version 2 object headers, and links held as header messages rather than in a symbol table.</summary>
    private const string Latest =
        "eNrzdQzxcXRSMNczVvB1DNFNy8xJ1VEIyEksScsvyrVSCHAO9/QzM9FRcC5KTSxJTVHIz7NSCE4sUXAsTVcwNFUwNLIyMAAiBSMDIzMFDxc3U4" +
        "Xi5IzU3EQFQz2gqB4DPsDE4OnLMAoGFHQC44yXS4qLmYMDFCFg8B8K1LggfAOoWgXb6/L+Hi5BTAwVTELICmGAi4mBkYGBjYcBSDE6boZqg/JL" +
        "9jNCBSzId672Y982sBOABjKqAF3MxMjIBE9O2GlmEQZGQQV7Bg4wz4HBhJvB5D8zAwMr0LXMXBxAnzAzQiUZFKB6RIUYWDD9x6MBVMvAC1QMlP" +
        "QF55z45JzE4mIGYZC/oXam5Jcm5aQyxNE66uSDWBXhYSECtJuRkZEZ5mcYzcPAKAAPCwEUPytA/cyG389q+PzMAjU7OSOxiEcfpFKIgQdJZWZe" +
        "SXxKanJ+SiqDAAdEOSiQmWBOcqVSWDTNUuoazcyjYBSMglFAMvhgD6E5HKACUFrAIY8hlaGcAQCVYHxS";

    /// <summary>Two classes with no representation here and one ordinary double beside them, so that a named load can step over what it was not asked for.</summary>
    private const string Object =
        "eNrzdQzxcXRSMNczVvB1DNFNy8xJ1VEIyEksScsvyrVSCHAO9/QzM9FRcC5KTSxJTVHIz7NSCE4sUXAsTVcwNFUwNLIyMAAiBSMDIzMFDxc3U4" +
        "Xi5IzU3EQFQz2gqB4DPsDE4OnLMAoGFHQC44yXS4oLzOHgYGBhEIBFDhj8hwIJLlQ+TH8ClGaE0h1QegUTTJwRLCcBFReEmo+uLiTI1RWk+j8a" +
        "gNljwAKhBUajbEQCD1fHABAdAeUrQOkTTKjq8pOywHRxSRGEn42aPi1ItJeRgQ2ilxHG14DQTIwo5uKimYEpH8QWVLBn4ACLODCYcDOY/GeGyL" +
        "MCRUHyTEwQAzmgOYWZEaocRkEBD4MB1HxeoAwHgy+4/I5PzkksLgaJCwNNYUeyP7cSJuVAlXgI9vN3YQT6CuYqBWb86mH5voMNvzpYvq5gHRnp" +
        "eeDSFQfZ6YoNyX5g/srMS2egWroauPAQoEp4pOSXJuWkUi886As+2KPSIg4An1RrEg==";

    /// <summary>Writes one fixture into <paramref name="folder"/> and returns its path.</summary>
    public static string Write(string folder, string name)
    {
        string packed = name switch
        {
            "v73_plain.mat" => Plain,
            "v73_deflate.mat" => Deflate,
            "v73_complex.mat" => Complex,
            "v73_nested.mat" => Nested,
            "v73_latest.mat" => Latest,
            "v73_object.mat" => Object,
            _ => throw new ArgumentException($"There is no fixture named {name}.", nameof(name)),
        };

        string path = Path.Combine(folder, name);
        using var source = new MemoryStream(Convert.FromBase64String(packed));
        using var zlib = new ZLibStream(source, CompressionMode.Decompress);
        using var file = new FileStream(path, FileMode.Create);
        zlib.CopyTo(file);
        return path;
    }
}
