"""Writes tests/Interop/JGraph.Interop.TestAssembly/Overloads.g.cs (interop plan, step 0).

MATLAB picks a .NET overload by a fitness order between each MATLAB class and each .NET parameter
type. The order is not fully documented, so it is recorded, not guessed. The generated class gives
the probes two families:

  JGTest.Overloads.Only_<T>(T x)        one overload each: does a MATLAB value convert to T at all?
  JGTest.Overloads.Pair_<A>_<B>(A | B)  two overloads: which of A and B does MATLAB prefer?

Every method returns the name of the .NET type it received, so the probe reads the choice
straight off the answer. The pairwise table orders the types for each MATLAB class. If the order
is not transitive, the probe shows that too.

Run: python tools/interop/gen-overloads.py
"""

from itertools import combinations
from pathlib import Path

# (identifier used in method names, C# type)
TYPES = [
    ("Boolean", "bool"),
    ("Byte", "byte"),
    ("SByte", "sbyte"),
    ("Int16", "short"),
    ("UInt16", "ushort"),
    ("Int32", "int"),
    ("UInt32", "uint"),
    ("Int64", "long"),
    ("UInt64", "ulong"),
    ("Single", "float"),
    ("Double", "double"),
    ("Char", "char"),
    ("String", "string"),
    ("Object", "object"),
    ("Decimal", "decimal"),
    ("DoubleArr", "double[]"),
    ("Int32Arr", "int[]"),
    ("StringArr", "string[]"),
    ("ObjectArr", "object[]"),
    ("BooleanArr", "bool[]"),
    ("CharArr", "char[]"),
    ("Double2D", "double[,]"),
    ("Array", "System.Array"),
    ("DayOfWeek", "System.DayOfWeek"),
    ("NullableInt32", "int?"),
]


def method(name: str, ident: str, cs: str) -> str:
    return f'        public static string {name}({cs} x) => "{ident}";\n'


def main() -> None:
    root = Path(__file__).resolve().parents[2]
    out = root / "tests" / "Interop" / "JGraph.Interop.TestAssembly" / "Overloads.g.cs"
    parts = [
        "// <auto-generated>\n",
        "// Written by tools/interop/gen-overloads.py. Edit the generator, not this file.\n",
        "// </auto-generated>\n\n",
        "namespace JGTest\n{\n",
        "    public static class Overloads\n    {\n",
        "        /// <summary>The type identifiers, in generator order, for the probes to iterate.</summary>\n",
        "        public static string[] Types => new[] { "
        + ", ".join(f'"{i}"' for i, _ in TYPES)
        + " };\n\n",
    ]
    for ident, cs in TYPES:
        parts.append(method(f"Only_{ident}", ident, cs))
    parts.append("\n")
    for (ia, ca), (ib, cb) in combinations(TYPES, 2):
        name = f"Pair_{ia}_{ib}"
        parts.append(method(name, ia, ca))
        parts.append(method(name, ib, cb))
    parts.append("    }\n}\n")
    out.write_text("".join(parts), encoding="utf-8", newline="\n")
    print(f"wrote {out} ({len(TYPES)} types, {len(TYPES) * (len(TYPES) - 1) // 2} pairs)")


if __name__ == "__main__":
    main()
