<#
.SYNOPSIS
    Fills tests/JGraph.Tests/MatlabParity/fixtures/interop/ with the interop test assets, so R2025b
    can record the net_* and shrlib_* fixtures from the source tree (interop plan, step 0).

.DESCRIPTION
    Copies into fixtures/interop/:
      - JGraph.Interop.TestAssembly.dll, after building it (Release, netstandard2.0)
      - tests/Interop/native/win-x64/jgtestlib.dll, the committed MSVC build
      - jgtestlib.h and jgtestlib_win.h
      - jgtestlib_proto.m, the prototype file R2025b wrote, when it has been committed

    The folder is gitignored. The test project copies the same files next to the fixtures in its
    build output, so both engines load identical assets by the same relative path
    (helpers/interop_paths.m).

    MATLAB's 64-bit loadlibrary also needs the thunk library it compiled when it wrote the
    prototype file (jgtestlib_thunk_pcwin64.dll). That file is MATLAB's own build product, is
    regenerated by the shrlib probe, and is left in place here. JGraph does not use it.

.EXAMPLE
    powershell -File tools/interop/stage-assets.ps1
#>
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$dest = Join-Path $repo 'tests\JGraph.Tests\MatlabParity\fixtures\interop'
$native = Join-Path $repo 'tests\Interop\native'
$proj = Join-Path $repo 'tests\Interop\JGraph.Interop.TestAssembly\JGraph.Interop.TestAssembly.csproj'

New-Item -ItemType Directory -Force -Path $dest | Out-Null

dotnet build $proj -c Release -nologo -v q
if ($LASTEXITCODE -ne 0) { Write-Error 'the test assembly did not build.' }
dotnet build-server shutdown | Out-Null

$items = @(
    (Join-Path $repo 'tests\Interop\JGraph.Interop.TestAssembly\bin\Release\netstandard2.0\JGraph.Interop.TestAssembly.dll'),
    (Join-Path $native 'win-x64\jgtestlib.dll'),
    (Join-Path $native 'jgtestlib.h'),
    (Join-Path $native 'jgtestlib_win.h')
)
$proto = Join-Path $native 'jgtestlib_proto.m'
if (Test-Path -LiteralPath $proto) { $items += $proto }

foreach ($item in $items) {
    if (-not (Test-Path -LiteralPath $item)) { Write-Error "missing asset '$item' (run tools/interop/build-testlib.ps1 first?)" }
    Copy-Item -LiteralPath $item -Destination $dest -Force
    Write-Host ('staged ' + (Split-Path -Leaf $item))
}
