#!/usr/bin/env python3
"""Writes src/JGraph.Devices/Bluetooth/GattNames.Table.cs from R2025b's blelib name tables.

    python tools/devices/gen-gatt-names.py [R2025b root]

R2025b resolves a service, characteristic or descriptor name through three JSON tables under
toolbox/shared/blelib/+matlabshared/+blelib/+internal (StandardServicesCharacteristics.json,
CustomServicesCharacteristics.json, StandardDescriptors.json): names and UUIDs, which are the Bluetooth
SIG's assigned numbers plus a few vendor services. The generated table keeps their order, because
R2025b matches a written name against them in that order (device classes plan, stage D3).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "src/JGraph.Devices/Bluetooth/GattNames.Table.cs"
ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(r"C:\Program Files\MATLAB\R2025b")
TABLES = ROOT / "toolbox/shared/blelib/+matlabshared/+blelib/+internal"


def quote(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def services(path: Path) -> list[str]:
    lines = []
    for service in json.loads(path.read_text(encoding="utf-8")):
        characteristics = ", ".join(
            f"new({quote(c['Name'])}, {quote(c['UUID'].upper())})" for c in service.get("Characteristics", [])
        )
        lines.append(
            f"        new({quote(service['Name'])}, {quote(service['UUID'].upper())}, [{characteristics}]),"
        )
    return lines


def main() -> int:
    standard = services(TABLES / "StandardServicesCharacteristics.json")
    custom = services(TABLES / "CustomServicesCharacteristics.json")
    descriptors = [
        f"        new({quote(d['Name'])}, {quote(d['UUID'].upper())}),"
        for d in json.loads((TABLES / "StandardDescriptors.json").read_text(encoding="utf-8"))
    ]
    text = "\n".join(
        [
            "// <auto-generated> tools/devices/gen-gatt-names.py from R2025b's blelib name tables; do not edit. </auto-generated>",
            "namespace JGraph.Devices.Bluetooth;",
            "",
            "public static partial class GattNames",
            "{",
            "    /// <summary>The standard services and their characteristics, in R2025b's order.</summary>",
            "    private static readonly GattService[] StandardServices =",
            "    [",
            *standard,
            "    ];",
            "",
            "    /// <summary>The vendor services R2025b names.</summary>",
            "    private static readonly GattService[] CustomServices =",
            "    [",
            *custom,
            "    ];",
            "",
            "    /// <summary>The standard descriptors, in R2025b's order.</summary>",
            "    private static readonly GattName[] StandardDescriptors =",
            "    [",
            *descriptors,
            "    ];",
            "}",
            "",
        ]
    )
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"{len(standard)} standard, {len(custom)} custom services, {len(descriptors)} descriptors -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
