% PROBE_AUDIO_RECORDER  audiorecorder's validation and error paths in R2025b (device classes plan,
%   stage D10). Nothing records: every call that would start the microphone is one that fails first.
dv_pr('c_one', 'audiorecorder(8000)')
dv_pr('c_two', 'audiorecorder(8000, 16)')
dv_pr('c_five', 'audiorecorder(8000, 16, 1, -1, 5)')
dv_px('c_three', 'r3 = audiorecorder(22050, 16, 2); disp(r3)')
dv_pr('c_fs_low', 'audiorecorder(80, 16, 1)')
dv_pr('c_fs_81', 'get(audiorecorder(81, 16, 1), ''SampleRate'')')
dv_pr('c_fs_high', 'audiorecorder(1e6+1, 16, 1)')
dv_pr('c_fs_vec', 'audiorecorder([8000 8000], 16, 1)')
dv_pr('c_fs_inf', 'audiorecorder(Inf, 16, 1)')
dv_pr('c_fs_char', 'audiorecorder(''a'', 16, 1)')
dv_pr('c_bits', 'audiorecorder(8000, 12, 1)')
dv_pr('c_bits_vec', 'audiorecorder(8000, [8 16], 1)')
dv_pr('c_ch3', 'audiorecorder(8000, 16, 3)')
dv_pr('c_ch0', 'audiorecorder(8000, 16, 0)')
dv_pr('c_ch_vec', 'audiorecorder(8000, 16, [1 2])')
dv_pr('c_dev_bad', 'audiorecorder(8000, 16, 1, 99)')
dv_pr('c_dev_out', 'audiorecorder(8000, 16, 1, 3)')
dv_pr('c_dev_vec', 'audiorecorder(8000, 16, 1, [0 1])')
dv_pr('c_dev_in', 'get(audiorecorder(8000, 16, 1, 1), ''DeviceID'')')
dv_pr('c_24', 'get(audiorecorder(8000, 24, 1), ''BitsPerSample'')')
dv_pr('c_frac', 'get(audiorecorder(8000.5, 16, 1), ''SampleRate'')')
r = audiorecorder(8000, 16, 1);
dv_px('disp', 'r')
dv_px('disp_set', 'set(r)')
dv_pr('empty_get', 'getaudiodata(r)')
dv_pr('empty_get_type', 'getaudiodata(r, ''int32'')')
dv_pr('empty_get_num', 'getaudiodata(r, 5)')
dv_pr('empty_get_str', 'getaudiodata(r, "int16")')
dv_pr('empty_get_three', 'getaudiodata(r, ''double'', 1)')
dv_pr('empty_player', 'getplayer(r)')
dv_pr('empty_play', 'play(r)')
dv_pr('player_from_rec', 'audioplayer(r, 3)')
dv_pr('player_from_rec_bad', 'audioplayer(r, ''a'')')
dv_pr('player_from_rec3', 'audioplayer(r, 3, 4)')
dv_px('rec_neg', 'record(r, -1)')
dv_px('rec_zero', 'record(r, 0)')
dv_px('rec_nan', 'record(r, NaN)')
dv_px('rec_char', 'record(r, ''a'')')
dv_px('rec_empty', 'record(r, [])')
dv_px('rec_three', 'record(r, 1, 2)')
dv_px('recb_none', 'recordblocking(r)')
dv_px('recb_neg', 'recordblocking(r, -1)')
dv_pr('isrec', 'isrecording(r)')
dv_pr('running', 'r.Running')
dv_pr('cur', 'r.CurrentSample')
dv_pr('total', 'r.TotalSamples')
dv_px('stop_idle', 'stop(r); pause(r); resume_is_record = 0; disp(r.Running)')
dv_px('set_fs', 'r.SampleRate = 16000;')
dv_px('set_bits', 'r.BitsPerSample = 8;')
dv_px('set_period', 'r.TimerPeriod = 0.0001;')
dv_px('set_period_ok', 'r.TimerPeriod = 0.2; disp(r.TimerPeriod)')
dv_px('set_tag_num', 'r.Tag = 1;')
dv_px('set_fcn_num', 'r.TimerFcn = 1;')
dv_px('horz', '[r r]')
dv_pr('class_impl', 'class(r)')
delete(r);
dv_pr('deleted_valid', 'isvalid(r)')
