I = 'matlabshared.blelib.internal.ServicesCharacteristicsDescriptorsInfo.getInstance';
dv_pr('c_name', [I '.getCharacteristicUUID("180D", "Heart Rate Measurement")']);
dv_pr('c_name_lower_prefix', [I '.getCharacteristicUUID("180D", "heart rate m")']);
dv_pr('c_short', [I '.getCharacteristicUUID("180D", "2A37")']);
dv_pr('c_num', [I '.getCharacteristicUUID("180D", 0x2A37)']);
dv_pr('c_long', [I '.getCharacteristicUUID("180D", "00002A37-0000-1000-8000-00805F9B34FB")']);
dv_pr('c_name_other_service', [I '.getCharacteristicUUID("180F", "Heart Rate Measurement")']);
dv_pr('c_name_custom_service', [I '.getCharacteristicUUID("FFE0", "Heart Rate Measurement")']);
dv_pr('c_custom', [I '.getCharacteristicUUID("180D", "Custom")']);
dv_pr('c_bad', [I '.getCharacteristicUUID("180D", "zz")']);
dv_pr('c_badtype', [I '.getCharacteristicUUID("180D", {1})']);
dv_pr('c_num_bad', [I '.getCharacteristicUUID("180D", 1.5)']);
dv_pr('s_custom', [I '.getServiceUUID("Custom")']);
dv_pr('s_badtype', [I '.getServiceUUID({1})']);
dv_pr('s_logical', [I '.getServiceUUID(true)']);
dv_pr('s_empty', [I '.getServiceUUID("")']);
dv_pr('s_vector', [I '.getServiceUUID([0x180D 0x180F])']);
dv_pr('d_short', [I '.getDescriptorUUID("2902")']);
dv_pr('d_custom', [I '.getDescriptorUUID("Custom")']);
dv_pr('d_prefix', [I '.getDescriptorUUID("client")']);
dv_pr('d_badtype', [I '.getDescriptorUUID({1})']);
dv_pr('s_ambig_char', [I '.getCharacteristicUUID("1800", "Peripheral")']);
