% PROBE_AUDIO_NAMES  How audioplayer's CaseInsensitiveProperties and TruncatedProperties read names in
%   R2025b (device classes plan, stage D10). Nothing plays.
p = audioplayer(zeros(100, 1), 8000);
dv_pr('dot_trunc', 'p.samp')
dv_pr('dot_upper', 'p.SAMPLERATE')
dv_pr('dot_ambig', 'p.S')
dv_pr('dot_ambig2', 'p.St')
dv_pr('dot_trunc_t', 'p.T')
dv_pr('get_ambig', 'get(p, ''S'')')
dv_px('set_dot_trunc', 'p.samp = 16000; disp(p.SampleRate)')
dv_px('set_dot_upper', 'p.TAG = ''x''; disp(p.Tag)')
dv_px('set_trunc', 'set(p, ''ta'', ''y''); disp(p.Tag)')
dv_px('set_ambig', 'set(p, ''S'', 1)')
dv_px('set_ambig_dot', 'p.S = 1;')
dv_pr('method_upper', 'ISPLAYING(p)')
dv_pr('method_dot', 'p.isplaying')
dv_pr('method_dot_call', 'p.isplaying()')
dv_pr('hidden_noc', 'p.NumberOfChannels')
dv_pr('props', 'properties(p)')
dv_pr('isprop_trunc', 'isprop(p, ''samp'')')
dv_pr('isprop_upper', 'isprop(p, ''SAMPLERATE'')')
dv_pr('fieldnames', 'fieldnames(p)')
dv_pr('isa_setget', 'isa(p, ''matlab.mixin.SetGet'')')
dv_pr('isobject', 'isobject(p)')
dv_pr('struct_of', 'struct(p)')
r = audiorecorder;
dv_pr('rec_dot_trunc', 'r.samp')
dv_pr('rec_hidden', 'r.BufferLength')
dv_px('rec_set_hidden', 'r.BufferLength = 5; disp(r.BufferLength)')
dv_pr('rec_props', 'properties(r)')
dv_pr('rec_noc', 'r.NumberOfChannels')
