% probe_visa_misc: what visadevlist asks a serial peer, a service request's visastatus, the texts of
% a few refusals, enum setters' matching, and the terminator a failed read leaves.
visa_peer();
s = serialport("COM20", 9600, "Timeout", 1);
dp(s, 'reset');
clear s
L = visadevlist("Timeout", 2);
s = serialport("COM20", 9600, "Timeout", 1);
dv_pr('list_sent_to_serial', 'dp(s, ''recv'')');
clear s
L = visadevlist("Timeout", 2, "Identification", ["ASRL20::INSTR" "*IDN?"]);
dv_pr('list_custom_vendor', 'L.Vendor');
s = serialport("COM20", 9600, "Timeout", 1);
dv_pr('list_custom_sent', 'dp(s, ''recv'')');
clear s
dv_pr('list_id_true', 'visadevlist("Timeout", 2, "Identification", true).Alias');

v = visadev("TCPIP0::127.0.0.1::hislip0::INSTR");
dp(v, 'stb 41');
dp(v, 'srq');
pause(0.3);
[ready, status] = visastatus(v);
dv_pr('srq_ready', 'ready');
dv_pr('srq_status', 'status');
[ready, status] = visastatus(v);
dv_pr('srq_ready_again', 'ready');
dv_pr('srq_status_again', 'status');
dv_pr('visastatus_class', 'class(visastatus(v))');
dp(v, 'reset');
flush(v);
dv_pr('inst_after_flush', 'dp(v, ''inst'')');
dv_pr('clrdevice', 'dv_err(@() clrdevice(v))');
dv_pr('inst_after_clrdevice', 'dp(v, ''inst'')');
flush(v, "input");
dv_pr('inst_after_flush_input', 'dp(v, ''inst'')');
v.Timeout = 1;
dp(v, 'reset');
dp(v, 'send 010203');
pause(0.3);
dv_pr('readfailed', 'dv_err(@() read(v, 2, "uint16"))');
dp(v, 'send 2341');
pause(0.3);
dv_pr('rbb_bad', 'dv_err(@() readbinblock(v))');
dp(v, 'send 2330');
pause(0.3);
dv_pr('rbb_zero', 'dv_err(@() readbinblock(v))');
dv_pr('read_vec', 'dv_err(@() read(v, [1 2]))');
dv_pr('read_str_count', 'dv_err(@() read(v, "2"))');
dv_pr('read_prec_num', 'dv_err(@() read(v, 1, 5))');
dv_pr('read_prec_upper', 'dv_err(@() read(v, 1, "UINT8"))');
dv_pr('rbb_prec_bad', 'dv_err(@() readbinblock(v, "uint9"))');
dv_pr('writeread_num', 'dv_err(@() writeread(v, 5))');
dv_pr('writeread_two', 'dv_err(@() writeread(v, "a", "b"))');
dv_pr('eoi_of', 'dv_err(@() set(v, ''EOIMode'', "of"))');
dv_pr('eoi_after_of', 'char(v.EOIMode)');
dv_pr('eoi_two', 'dv_err(@() set(v, ''EOIMode'', 2))');
dv_pr('eoi_after_two', 'char(v.EOIMode)');
v.EOIMode = "on";
dv_pr('timeout_warn', 'dv_err(@() set(v, ''Timeout'', 0.0004))');
[m, id] = lastwarn;
dv_pr('timeout_warn_text', 'sprintf(''%s ## %s'', id, m)');
dv_pr('timeout_after_warn', 'v.Timeout');
dv_pr('attr_after_warn', 'dv_vattr(v)');
v.Timeout = 1;
dv_pr('timeout_single', 'dv_err(@() set(v, ''Timeout'', single(1)))');
dv_pr('timeout_int', 'dv_err(@() set(v, ''Timeout'', int8(1)))');
dv_pr('timeout_nan', 'dv_err(@() set(v, ''Timeout'', NaN))');
dv_pr('timeout_vec', 'dv_err(@() set(v, ''Timeout'', [1 2]))');
dv_pr('timeout_1_2345', 'dv_err(@() set(v, ''Timeout'', 1.2345))');
dv_pr('timeout_after', 'v.Timeout');
dv_pr('attr_1_2345', 'dv_vattr(v)');
v.Timeout = 1;
dv_pr('byteorder_partial', 'dv_err(@() set(v, ''ByteOrder'', "big"))');
dv_pr('byteorder_after', 'v.ByteOrder');
dv_pr('tag_char', 'dv_err(@() set(v, ''Tag'', ''abc''))');
dv_pr('tag_after', 'v.Tag');
dv_pr('tag_class', 'class(v.Tag)');
dv_pr('tag_cell', 'dv_err(@() set(v, ''Tag'', {''a''}))');
dv_pr('userdata_after', 'class(v.UserData)');
dv_pr('type_eq', 'v.Type == "tcpip"');
dv_pr('type_eq_char', 'v.Type == ''tcpip''');
dv_pr('type_char', 'char(v.Type)');
dv_pr('type_string', 'string(v.Type)');
dv_pr('type_isequal', 'isequal(v.Type, "tcpip")');
dv_px('type_disp', 'disp(v.Type)');
dv_px('type_echo', 't = v.Type');
dv_px('eoi_echo', 'e = v.EOIMode');
dv_pr('eoi_logical', 'logical(v.EOIMode)');
dv_pr('eoi_eq', 'v.EOIMode == "on"');
dv_pr('eoi_if', 'double(v.EOIMode == true)');
clear v

v = visadev("ASRL20::INSTR");
v.Timeout = 1;
dv_pr('parity_partial', 'dv_err(@() set(v, ''Parity'', "ev"))');
dv_pr('parity_after', 'char(v.Parity)');
dv_pr('parity_upper', 'dv_err(@() set(v, ''Parity'', "ODD"))');
dv_pr('parity_after_upper', 'char(v.Parity)');
v.Parity = "none";
dv_pr('flow_partial', 'dv_err(@() set(v, ''FlowControl'', "hard"))');
dv_pr('flow_after', 'char(v.FlowControl)');
v.FlowControl = "none";
dv_pr('baud_char', 'dv_err(@() set(v, ''BaudRate'', ''x''))');
dv_pr('baud_after_char', 'v.BaudRate');
v.BaudRate = 9600;
dv_pr('databits_str', 'dv_err(@() set(v, ''DataBits'', "7"))');
dv_pr('databits_after', 'v.DataBits');
v.DataBits = 8;
dv_pr('stopbits_15_msg', 'dv_err(@() set(v, ''StopBits'', 1.5))');
dv_pr('stopbits_after', 'v.StopBits');
v.DataBits = 5;
dv_pr('stopbits_15_db5', 'dv_err(@() set(v, ''StopBits'', 1.5))');
dv_pr('stopbits_after_db5', 'v.StopBits');
v.StopBits = 1;
v.DataBits = 8;
dp(v, 'reset');
flush(v);
dv_pr('peer_breaks_after_flush', 'dp(v, ''status'')');
dv_pr('peer_recv_after_flush', 'dp(v, ''recv'')');
dp(v, 'send 0102');
pause(0.3);
dv_pr('partial_read', 'dv_err(@() read(v, 5))');
dp(v, 'send 68690A');
pause(0.3);
dv_pr('readline_after_failed_read', 'dv_err(@() readline(v))');
dv_pr('attr_after_failed', 'dv_vattr(v)');
configureTerminator(v, "LF");
dp(v, 'send 68690A');
pause(0.3);
dv_pr('readline_after_reconfig', 'readline(v)');
configureTerminator(v, "CR", "LF");
dp(v, 'send 410D420A');
pause(0.3);
dv_pr('readline_cr_lf', 'dv_err(@() readline(v))');
flush(v);
dv_pr('ps_class', 'class(getpinstatus(v))');
dv_pr('ps_fields', 'fieldnames(getpinstatus(v))');
dv_pr('ps_cts_eq', 'getpinstatus(v).ClearToSend == "off"');
clear v
dv_pr('ctor_lower', 'dv_err(@() visadev("asrl20::instr"))');
v = visadev("asrl20::instr");
dv_pr('ctor_lower_name', 'v.ResourceName');
dv_pr('ctor_lower_port', 'v.Port');
clear v
v = visadev("tcpip0::127.0.0.1::hislip0::instr");
dv_pr('ctor_lower_tcpip', 'v.ResourceName');
clear v
v = visadev("TCPIP::127.0.0.1::hislip0::INSTR");
dv_pr('ctor_noboard_tcpip', 'v.ResourceName');
clear v
v = visadev("TCPIP0::127.0.0.1::5025::SOCKET");
dv_pr('sock_intf', 'v.ResourceName');
t0 = tic;
clear v
v = visadev("TCPIP0::localhost::5025::SOCKET");
dv_pr('sock_localhost', 'v.IPAddress');
clear v
dv_pr('ctor_took_hislip', 'dv_time(@() visadev("TCPIP0::127.0.0.1::hislip0::INSTR"))');
dv_pr('ctor_took_sock', 'dv_time(@() visadev("TCPIP0::127.0.0.1::5025::SOCKET"))');
dv_pr('ctor_took_asrl', 'dv_time(@() visadev("ASRL20::INSTR"))');
