% PROBE_MIDI_MSG  midimsg, midimsgtype and midimsg arrays in R2025b (device classes plan, stage D10b).
%   Pure values: no device is opened and nothing is sent.

% --- every constructor form, displayed
dv_px('d_default', 'disp(midimsg)')
dv_px('d_noteon', 'disp(midimsg(''NoteOn'', 1, 60, 64))')
dv_px('d_noteon_ts', 'disp(midimsg(''NoteOn'', 16, 127, 0, 1.25))')
dv_px('d_noteoff', 'disp(midimsg(''NoteOff'', 2, 61, 10, 2))')
dv_px('d_note', 'disp(midimsg(''Note'', 3, 62, 70, 0.5, 1))')
dv_px('d_poly', 'disp(midimsg(''PolyKeyPressure'', 4, 63, 11))')
dv_px('d_cc', 'disp(midimsg(''ControlChange'', 5, 7, 100))')
dv_px('d_aso', 'disp(midimsg(''AllSoundOff'', 6))')
dv_px('d_rac', 'disp(midimsg(''ResetAllControllers'', 7, 3))')
dv_px('d_local_on', 'disp(midimsg(''LocalControl'', 8, true))')
dv_px('d_local_off', 'disp(midimsg(''LocalControl'', 8, false))')
dv_px('d_ano', 'disp(midimsg(''AllNotesOff'', 9))')
dv_px('d_omnioff', 'disp(midimsg(''OmniOff'', 10))')
dv_px('d_omnion', 'disp(midimsg(''OmniOn'', 11))')
dv_px('d_monoon', 'disp(midimsg(''MonoOn'', 12, 4))')
dv_px('d_polyon', 'disp(midimsg(''PolyOn'', 13))')
dv_px('d_pc', 'disp(midimsg(''ProgramChange'', 14, 19))')
dv_px('d_cp', 'disp(midimsg(''ChannelPressure'', 15, 99))')
dv_px('d_pb', 'disp(midimsg(''PitchBend'', 16, 8192))')
dv_px('d_pb_hi', 'disp(midimsg(''PitchBend'', 1, 16383))')
dv_px('d_mtc', 'disp(midimsg(''MIDITimeCodeQuarterFrame'', 5, 9))')
dv_px('d_spp', 'disp(midimsg(''SongPositionPointer'', 300))')
dv_px('d_ss', 'disp(midimsg(''SongSelect'', 12))')
dv_px('d_tune', 'disp(midimsg(''TuneRequest''))')
dv_px('d_clock', 'disp(midimsg(''TimingClock'', 0.25))')
dv_px('d_start', 'disp(midimsg(''Start''))')
dv_px('d_continue', 'disp(midimsg(''Continue''))')
dv_px('d_stop', 'disp(midimsg(''Stop''))')
dv_px('d_as', 'disp(midimsg(''ActiveSensing''))')
dv_px('d_reset', 'disp(midimsg(''SystemReset''))')
dv_px('d_sysex1', 'disp(midimsg(''SystemExclusive''))')
dv_px('d_sysex', 'disp(midimsg(''SystemExclusive'', [1 2 3 4 5 6 7 8 9 10], 0.5))')
dv_px('d_sysex8', 'disp(midimsg(''SystemExclusive'', 1:8, 0))')
dv_px('d_sysex_nots', 'disp(midimsg(''SystemExclusive'', 1:3))')
dv_px('d_data', 'disp(midimsg(''Data'', [1 2 3]))')
dv_px('d_data9', 'disp(midimsg(''Data'', 1:9, 2))')
dv_px('d_eox', 'disp(midimsg(''EOX''))')
dv_px('d_undef', 'disp(midimsg(''Undefined''))')
dv_px('d_empty', 'disp(midimsg(0))')
dv_px('d_size', 'disp(midimsg([2 3]))')
dv_px('d_three', 'disp(midimsg(3))')
dv_px('d_zero_rows', 'disp(midimsg([0 3]))')
dv_px('d_enum', 'disp(midimsg(midimsgtype.NoteOn, 1, 60, 64))')
dv_px('d_string', 'disp(midimsg("ProgramChange", 1, 5))')
dv_px('d_prefix', 'disp(midimsg(''prog'', 1, 5))')
dv_px('d_lower', 'disp(midimsg(''noteon'', 1, 60, 64))')
dv_px('echo_scalar', 'm = midimsg(''NoteOn'', 1, 60, 64)')
dv_px('echo_array', 'm = midimsg(''Note'', 1, 60, 64, 1)')
dv_px('echo_empty', 'm = midimsg(0)')
dv_px('d_ts_g', 'disp(midimsg(''NoteOn'', 1, 60, 64, 1234567.891))')
dv_px('d_ts_neg', 'disp(midimsg(''NoteOn'', 1, 60, 64, -1))')
dv_px('d_ts_int', 'disp(midimsg(''NoteOn'', 1, 60, 64, int8(3)))')

% --- constructor refusals
dv_pr('e_chan0', 'midimsg(''NoteOn'', 0, 60, 64)')
dv_pr('e_chan17', 'midimsg(''NoteOn'', 17, 60, 64)')
dv_pr('e_chan_frac', 'midimsg(''NoteOn'', 1.5, 60, 64)')
dv_pr('e_note', 'midimsg(''NoteOn'', 1, 128, 64)')
dv_pr('e_vel', 'midimsg(''NoteOn'', 1, 60, -1)')
dv_pr('e_vel_vec', 'midimsg(''NoteOn'', 1, 60, [1 2])')
dv_pr('e_vel_char', 'midimsg(''NoteOn'', 1, 60, ''a'')')
dv_pr('e_vel_nan', 'midimsg(''NoteOn'', 1, 60, NaN)')
dv_pr('e_few', 'midimsg(''NoteOn'', 1, 60)')
dv_pr('e_many', 'midimsg(''NoteOn'', 1, 60, 64, 0, 1)')
dv_pr('e_type', 'midimsg(''Bogus'', 1)')
dv_pr('e_ambig', 'midimsg(''No'', 1)')
dv_pr('e_cell', 'midimsg({1})')
dv_pr('e_neg_size', 'midimsg(-1)')
dv_pr('e_frac_size', 'midimsg(1.5)')
dv_pr('e_3d', 'midimsg(ones(1,3))')
dv_pr('e_cc', 'midimsg(''ControlChange'', 1, 120, 0)')
dv_pr('e_local', 'midimsg(''LocalControl'', 1, 1)')
dv_pr('e_mono', 'midimsg(''MonoOn'', 1, 17)')
dv_pr('e_pb', 'midimsg(''PitchBend'', 1, 16384)')
dv_pr('e_mtc', 'midimsg(''MIDITimeCodeQuarterFrame'', 8, 0)')
dv_pr('e_ts', 'midimsg(''NoteOn'', 1, 60, 64, [1 2])')
dv_pr('e_ts_char', 'midimsg(''NoteOn'', 1, 60, 64, ''x'')')
dv_pr('e_ts_cplx', 'midimsg(''NoteOn'', 1, 60, 64, 1i)')
dv_pr('e_dur', 'midimsg(''Note'', 1, 60, 64, [1 2])')
dv_pr('e_data_big', 'midimsg(''Data'', 128)')
dv_pr('e_data_empty', 'midimsg(''Data'', [])')
dv_pr('e_sysex_big', 'midimsg(''SystemExclusive'', 200, 0)')
dv_pr('e_tune_extra', 'midimsg(''TuneRequest'', 1, 2)')

% --- properties and their types
m = midimsg('NoteOn', 2, 60, 64, 0.5);
dv_pr('props', 'properties(m)')
dv_pr('methods', 'methods(m)')
dv_pr('class', 'class(m)')
dv_pr('type', 'm.Type')
dv_px('type_disp', 'disp(m.Type)')
dv_px('type_echo', 't = m.Type')
dv_pr('type_class', 'class(m.Type)')
dv_pr('nbytes', 'm.NumMsgBytes')
dv_pr('bytes', 'm.MsgBytes')
dv_pr('ts', 'm.Timestamp')
dv_pr('chan', 'm.Channel')
dv_pr('note', 'm.Note')
dv_pr('vel', 'm.Velocity')
dv_pr('raw', 'm.RawBytes')
dv_pr('bad_prop', 'm.CCNumber')
dv_pr('bad_prop2', 'm.Program')
dv_pr('no_prop', 'm.Bogus')
dv_pr('lower_prop', 'm.channel')
dv_pr('isa_handle', 'isa(m, ''handle'')')
dv_pr('isobject', 'isobject(m)')
dv_pr('isstruct', 'isstruct(m)')
dv_pr('isequal_same', 'isequal(m, midimsg(''NoteOn'', 2, 60, 64, 0.5))')
dv_pr('isequal_diff', 'isequal(m, midimsg(''NoteOn'', 2, 60, 64, 0.25))')
dv_pr('eq_op', 'm == m')
dv_pr('struct_of', 'struct(m)')
dv_pr('size', 'size(m)')
dv_pr('numel', 'numel(m)')
dv_pr('double_of', 'double(m)')

% --- per-type properties
dv_pr('p_poly', 'midimsg(''PolyKeyPressure'', 4, 63, 11).KeyPressure')
dv_pr('p_cc', '[midimsg(''ControlChange'', 5, 7, 100).CCNumber, midimsg(''ControlChange'', 5, 7, 100).CCValue]')
dv_pr('p_local', 'midimsg(''LocalControl'', 8, true).LocalControl')
dv_pr('p_mono', 'midimsg(''MonoOn'', 12, 4).MonoChannels')
dv_pr('p_pc', 'midimsg(''ProgramChange'', 14, 19).Program')
dv_pr('p_cp', 'midimsg(''ChannelPressure'', 15, 99).ChannelPressure')
dv_pr('p_pb', 'midimsg(''PitchBend'', 16, 8195).PitchChange')
dv_pr('p_mtc', '[midimsg(''MIDITimeCodeQuarterFrame'', 5, 9).TimeCodeSequence, midimsg(''MIDITimeCodeQuarterFrame'', 5, 9).TimeCodeValue]')
dv_pr('p_spp', 'midimsg(''SongPositionPointer'', 300).SongPosition')
dv_pr('p_ss', 'midimsg(''SongSelect'', 12).Song')
dv_pr('p_aso_type', 'midimsg(''AllSoundOff'', 6).Type')
dv_pr('p_sysex_chan', 'midimsg(''SystemExclusive'').Channel')
dv_pr('p_data_type', 'midimsg(''Data'', [1 2 3]).Type')
dv_pr('p_data_bytes', 'midimsg(''Data'', [1 2 3]).MsgBytes')
dv_pr('p_default_type', 'midimsg().Type')
dv_pr('p_default_bytes', 'midimsg().MsgBytes')
dv_pr('p_default_n', 'midimsg().NumMsgBytes')
dv_pr('p_undef_n', 'midimsg(''Undefined'').NumMsgBytes')

% --- setters
m2 = m;
m2.Channel = 16;
dv_pr('set_chan', 'm2.MsgBytes')
m2.Note = 0;
m2.Velocity = 127;
dv_pr('set_note_vel', 'm2.MsgBytes')
m2.Timestamp = 3;
dv_pr('set_ts', 'm2.Timestamp')
dv_pr('orig_unchanged', 'm.MsgBytes')
dv_px('set_bad_chan', 'm2.Channel = 0;')
dv_px('set_bad_prop', 'm2.Program = 3;')
dv_px('set_type', 'm2.Type = 1;')
dv_px('set_bytes', 'm2.MsgBytes = uint8([1 2 3]);')
dv_px('set_raw', 'm2.RawBytes = uint8(1:8);')
dv_px('set_ts_char', 'm2.Timestamp = ''a'';')
dv_px('set_ts_vec', 'm2.Timestamp = [1 2];')
dv_px('set_ts_int', 'm2.Timestamp = int8(4); disp(class(m2.Timestamp)); disp(m2.Timestamp)')
dv_px('set_ts_true', 'm2.Timestamp = true; disp(class(m2.Timestamp))')
dv_px('set_new', 'm2.Bogus = 1;')
pb = midimsg('PitchBend', 1, 0);
pb.PitchChange = 16000;
dv_pr('set_pb', 'pb.MsgBytes')
tc = midimsg('MIDITimeCodeQuarterFrame', 1, 2);
tc.TimeCodeSequence = 7;
tc.TimeCodeValue = 15;
dv_pr('set_mtc', 'tc.MsgBytes')
lc = midimsg('LocalControl', 1, false);
lc.LocalControl = true;
dv_pr('set_local', 'lc.MsgBytes')
dv_px('set_local_num', 'lc.LocalControl = 1;')

% --- arrays
a = midimsg('Note', 1, 60, 64, 0.5, 1);
dv_pr('a_size', 'size(a)')
dv_pr('a_class', 'class(a)')
dv_px('a_disp', 'disp(a)')
dv_pr('a1', 'a(1).MsgBytes')
dv_pr('a2_ts', 'a(2).Timestamp')
dv_pr('a_ts_list', '[a.Timestamp]')
dv_px('a_ts_cs', 'a.Timestamp')
dv_pr('a_nbytes', 'a.NumMsgBytes')
dv_pr('a_bytes', 'a.MsgBytes')
dv_pr('a_type', 'a.Type')
dv_px('a_type_cs', 'a.Type')
dv_pr('a_chan', 'a.Channel')
dv_px('a_chan_cs', 'a.Channel')
dv_pr('a_end', 'a(end).Timestamp')
dv_pr('a_colon', 'size(a(:))')
dv_pr('a_rev', '[a([2 1]).Timestamp]')
dv_pr('a_logical', 'size(a([true false]))')
dv_pr('a_bad_idx', 'a(3)')
dv_pr('a_zero_idx', 'a(0)')
dv_pr('a_two_idx', 'size(a(2, 1))')
dv_pr('a_empty_idx', 'size(a([]))')
dv_pr('a_isempty', 'isempty(a)')
dv_pr('a_numel', 'numel(a)')
dv_pr('a_length', 'length(a)')
dv_pr('a_transpose', 'size(a'')')
dv_pr('a_isequal', 'isequal(a, a)')
b = [a; midimsg('ProgramChange', 1, 5)];
dv_pr('cat_v', 'size(b)')
dv_pr('cat_h', 'size([midimsg, midimsg, midimsg])')
dv_pr('cat_mix', '[a; 1]')
dv_pr('cat_empty', 'size([midimsg(0); a])')
dv_pr('cat_dbl_empty', 'size([[]; a])')
dv_pr('cat_cell', 'class({a, a})')
dv_pr('cat_bad', '[a, midimsg]')
c = a;
c(2).Timestamp = 9;
dv_pr('ix_set', '[c.Timestamp]')
dv_pr('ix_set_orig', '[a.Timestamp]')
c(4) = midimsg('Start');
dv_pr('grow', 'size(c)')
dv_pr('grow_fill', 'c(3).MsgBytes')
c(end+1) = midimsg('Stop');
dv_pr('grow_end', 'size(c)')
c(2) = [];
dv_pr('delete', 'size(c)')
dv_px('ix_set_bad', 'c(1) = 5;')
dv_px('dot_set_array', 'c.Timestamp = 1;')
dv_px('dot_set_array_cs', '[c.Timestamp] = deal(7); disp([c.Timestamp])')
e = midimsg(0);
dv_pr('e_size', 'size(e)')
e(end+1) = midimsg('Start');
dv_pr('e_grow', 'size(e)')
dv_pr('rep', 'size(repmat(midimsg(''Start''), 2, 2))')
dv_pr('rs', 'size(reshape(midimsg([2 3]), 3, 2))')
dv_px('for_loop', 'for k = a, disp(class(k)), disp(size(k)), end')
dv_px('for_loop_row', 'for k = a'', disp(k.Timestamp), end')
dv_px('arrayfun', 'disp(arrayfun(@(x) x.Timestamp, a))')
dv_pr('cellfun', 'cellfun(@(x) x.Note, {a(1), a(2)})')
z = midimsg([2 3]);
dv_pr('z_bytes', 'z.MsgBytes')
dv_pr('z_ts', '[z.Timestamp]')
dv_pr('z_type', 'z(1).Type')
dv_pr('z_nb', 'z.NumMsgBytes')

% --- midimsgtype
dv_px('t_disp', 'disp(midimsgtype.NoteOn)')
dv_px('t_echo', 't = midimsgtype.PitchBend')
dv_pr('t_class', 'class(midimsgtype.NoteOn)')
dv_pr('t_double', 'double(midimsgtype.PitchBend)')
dv_pr('t_int32', 'int32(midimsgtype.Undefined)')
dv_pr('t_char', 'char(midimsgtype.NoteOn)')
dv_pr('t_string', 'string(midimsgtype.NoteOn)')
dv_pr('t_eq', 'midimsgtype.NoteOn == midimsgtype.NoteOn')
dv_pr('t_ne', 'midimsgtype.NoteOn ~= midimsgtype.NoteOff')
dv_pr('t_eq_char', 'midimsgtype.NoteOn == ''NoteOn''')
dv_pr('t_eq_num', 'midimsgtype.NoteOn == 1')
dv_pr('t_plus', 'midimsgtype.NoteOn + 1')
dv_pr('t_lt', 'midimsgtype.NoteOn < midimsgtype.NoteOff')
dv_pr('t_isequal_char', 'isequal(midimsgtype.NoteOn, ''NoteOn'')')
dv_pr('t_isa', 'isa(midimsgtype.NoteOn, ''int32'')')
dv_pr('t_isenum', 'isenum(midimsgtype.NoteOn)')
dv_pr('t_isnumeric', 'isnumeric(midimsgtype.NoteOn)')
dv_px('t_enumeration', 'enumeration(''midimsgtype'')')
dv_pr('t_enum_out', '[m, s] = enumeration(''midimsgtype''); s')
dv_pr('t_ctor', 'midimsgtype(1)')
dv_pr('t_ctor_name', 'midimsgtype(''NoteOn'')')
dv_pr('t_bad', 'midimsgtype.Bogus')
dv_px('t_switch', 'switch midimsg(''NoteOn'',1,60,64).Type, case midimsgtype.NoteOff, disp(1), case midimsgtype.NoteOn, disp(2), end')
dv_px('t_switch_char', 'switch midimsg(''NoteOn'',1,60,64).Type, case ''NoteOn'', disp(2), otherwise, disp(3), end')
dv_pr('t_arr', 'size([midimsgtype.NoteOn, midimsgtype.Stop])')
dv_px('t_arr_disp', 'disp([midimsgtype.NoteOn, midimsgtype.Stop])')
dv_pr('t_ismember', 'ismember(midimsgtype.NoteOn, [midimsgtype.NoteOn, midimsgtype.Stop])')
dv_pr('t_cellstr', 'cellstr(midimsgtype.NoteOn)')
