% probe_sp_io: read and write -- precisions, byte order, partial reads and their warning, counts,
% argument refusals, NumBytesWritten, flush.
device_peer();
s = serialport("COM20", 9600, "Timeout", 1);
dp(s, 'reset');
% what each precision writes (the peer logs the bytes)
precs = {'uint8','int8','uint16','int16','uint32','int32','uint64','int64','single','double','char','string'};
for k = 1:numel(precs)
    dv_px(['write_' precs{k}], sprintf('write(s, [1 -2 300 2.5], "%s")', precs{k}));
    dv_pr(['wrote_' precs{k}], 'dp(s, ''recv'')');
end
dv_px('write_char_data', 'write(s, ''AZ'', "uint8")');
dv_pr('wrote_char_data', 'dp(s, ''recv'')');
dv_px('write_string_data', 'write(s, "AZ", "uint8")');
dv_pr('wrote_string_data', 'dp(s, ''recv'')');
dv_px('write_string_char', 'write(s, "AZ", "char")');
dv_pr('wrote_string_char', 'dp(s, ''recv'')');
dv_px('write_string_string', 'write(s, "AZ", "string")');
dv_pr('wrote_string_string', 'dp(s, ''recv'')');
dv_px('write_strarr', 'write(s, ["A" "Z"], "string")');
dv_pr('wrote_strarr', 'dp(s, ''recv'')');
dv_px('write_nan', 'write(s, [NaN Inf -Inf], "uint8")');
dv_pr('wrote_nan', 'dp(s, ''recv'')');
dv_px('write_nan_int16', 'write(s, [NaN Inf -Inf 40000], "int16")');
dv_pr('wrote_nan_int16', 'dp(s, ''recv'')');
dv_px('write_int8_uint8', 'write(s, int8([-1 5]), "uint8")');
dv_pr('wrote_int8_uint8', 'dp(s, ''recv'')');
dv_px('write_logical', 'write(s, [true false], "uint8")');
dv_pr('wrote_logical', 'dp(s, ''recv'')');
dv_px('write_column', 'write(s, [1;2;3], "uint8")');
dv_pr('wrote_column', 'dp(s, ''recv'')');
dv_px('write_matrix', 'write(s, [1 2; 3 4], "uint8")');
dv_pr('wrote_matrix', 'dp(s, ''recv'')');
dv_px('write_empty', 'write(s, [], "uint8")');
dv_pr('wrote_empty', 'dp(s, ''recv'')');
dv_px('write_complex', 'write(s, 1+2i, "uint8")');
dv_pr('wrote_complex', 'dp(s, ''recv'')');
dv_px('write_cell', 'write(s, {1}, "uint8")');
dv_px('write_struct', 'write(s, struct(''a'',1), "uint8")');
dv_px('write_unicode', 'write(s, char(955), "char")');
dv_pr('wrote_unicode', 'dp(s, ''recv'')');
dv_px('write_unicode_string', 'write(s, string(char([955 65])), "string")');
dv_pr('wrote_unicode_string', 'dp(s, ''recv'')');
dv_px('write_no_prec', 'write(s, 1)');
dv_px('write_bad_prec', 'write(s, 1, "uint9")');
dv_px('write_prec_upper', 'write(s, 1, "UINT8")');
dv_pr('wrote_prec_upper', 'dp(s, ''recv'')');
dv_px('write_prec_char', 'write(s, 1, ''uint8'')');
dv_px('write_prec_num', 'write(s, 1, 8)');
dv_px('write_prec_partial', 'write(s, 1, "uint")');
dv_px('write_too_many', 'write(s, 1, "uint8", 2)');
dv_px('write_one_arg', 'write(s)');
s.ByteOrder = "big-endian";
dv_px('write_be_uint16', 'write(s, [1 258], "uint16")');
dv_pr('wrote_be_uint16', 'dp(s, ''recv'')');
dv_px('write_be_double', 'write(s, 1.5, "double")');
dv_pr('wrote_be_double', 'dp(s, ''recv'')');
dv_px('write_be_single', 'write(s, -2, "single")');
dv_pr('wrote_be_single', 'dp(s, ''recv'')');
s.ByteOrder = "little-endian";
% NumBytesWritten
dp(s, 'reset');
before = s.NumBytesWritten;
write(s, 1:5, "uint8");
dv_pr('nbw_delta', 's.NumBytesWritten - before');
dv_pr('nbw_class', 'class(s.NumBytesWritten)');
dp(s, 'recv');
% reading
flush(s);
dp(s, sprintf('send %s', dp_hex(0:9)));
pause(0.3);
dv_pr('nba', 's.NumBytesAvailable');
dv_pr('read_uint8', 'read(s, 3, "uint8")');
dv_pr('nba_after', 's.NumBytesAvailable');
dv_pr('read_char', 'read(s, 2, "char")');
dv_pr('read_string', 'read(s, 2, "string")');
dv_pr('read_rest', 'read(s, s.NumBytesAvailable, "uint8")');
bytes = [1 0 255 255 0 1 0 0 0 0 0 0 248 63];
dp(s, sprintf('send %s', dp_hex(bytes)));
pause(0.3);
dv_pr('read_uint16', 'read(s, 2, "uint16")');
dv_pr('read_int16', 'read(s, 1, "int16")');
dv_pr('read_double', 'read(s, 1, "double")');
dp(s, sprintf('send %s', dp_hex([0 1 255 254])));
pause(0.3);
s.ByteOrder = "big-endian";
dv_pr('read_be_uint16', 'read(s, 1, "uint16")');
dv_pr('read_be_int16', 'read(s, 1, "int16")');
s.ByteOrder = "little-endian";
precs = {'int8','uint32','int32','uint64','int64','single'};
for k = 1:numel(precs)
    dp(s, sprintf('send %s', dp_hex([255 255 255 255 255 255 255 255])));
    pause(0.2);
    dv_pr(['read_' precs{k}], sprintf('read(s, 1, "%s")', precs{k}));
    flush(s, "input");
end
dp(s, sprintf('send %s', dp_hex([0 0 192 127 0 0 128 255])));
pause(0.2);
dv_pr('read_single_nan', 'read(s, 2, "single")');
dp(s, sprintf('send %s', dp_hex(double('héllo'))));
pause(0.2);
dv_pr('read_char_high', 'double(read(s, 6, "char"))');
flush(s);
% partial reads and the warning
dp(s, sprintf('send %s', dp_hex(1:3)));
pause(0.3);
lastwarn('');
t0 = tic;
dv_pr('read_partial', 'read(s, 5, "uint8")');
dv_pr('read_partial_took', 'round(toc(t0))');
[msg, id] = lastwarn;
dv_pr('read_partial_warn_id', 'id');
dv_pr('read_partial_warn_msg', 'msg');
lastwarn('');
dv_pr('read_none', 'read(s, 2, "uint8")');
[msg, id] = lastwarn;
dv_pr('read_none_warn_id', 'id');
dv_pr('read_none_warn_msg', 'msg');
dv_px('read_none_disp', 'x = read(s, 2, "uint8")');
dv_pr('read_none_char', 'read(s, 2, "char")');
dv_pr('read_none_string', 'read(s, 2, "string")');
dp(s, sprintf('send %s', dp_hex(1:3)));
pause(0.3);
dv_pr('read_partial_uint16', 'read(s, 2, "uint16")');
dv_pr('read_partial_uint16_left', 's.NumBytesAvailable');
flush(s);
dp(s, sprintf('send %s', dp_hex(double('ab'))));
pause(0.3);
dv_pr('read_partial_string', 'read(s, 3, "string")');
% the arguments
dv_pr('read_zero', 'read(s, 0, "uint8")');
dv_pr('read_neg', 'read(s, -1, "uint8")');
dv_pr('read_frac', 'read(s, 1.5, "uint8")');
dv_pr('read_inf', 'read(s, Inf, "uint8")');
dv_pr('read_nan', 'read(s, NaN, "uint8")');
dv_pr('read_str_count', 'read(s, "2", "uint8")');
dv_pr('read_vec_count', 'read(s, [1 2], "uint8")');
dv_pr('read_no_prec', 'read(s, 2)');
dv_pr('read_no_count', 'read(s)');
dv_pr('read_bad_prec', 'read(s, 1, "uint9")');
dv_pr('read_prec_num', 'read(s, 1, 8)');
dv_pr('read_too_many', 'read(s, 1, "uint8", 3)');
dv_pr('read_int_count', 'class(read(s, int8(1), "uint8"))');
% delayed data arrives within the timeout
flush(s);
dp(s, sprintf('later 300 %s', dp_hex(7:9)));
t0 = tic;
dv_pr('read_later', 'read(s, 3, "uint8")');
dv_pr('read_later_fast', 'toc(t0) < 0.9');
% flush
dp(s, sprintf('send %s', dp_hex(1:4)));
pause(0.3);
flush(s, "input");
dv_pr('flush_input', 's.NumBytesAvailable');
dp(s, sprintf('send %s', dp_hex(1:4)));
pause(0.3);
flush(s, "output");
dv_pr('flush_output_keeps_input', 's.NumBytesAvailable');
flush(s);
dv_pr('flush_both', 's.NumBytesAvailable');
dv_px('flush_bad', 'flush(s, "bogus")');
dv_px('flush_partial', 'flush(s, "in")');
dv_px('flush_num', 'flush(s, 1)');
dv_px('flush_too_many', 'flush(s, "input", "output")');
dv_px('flush_upper', 'flush(s, "INPUT")');
% timeout and a big transfer
s.Timeout = 5;
data = mod(0:9999, 256);
write(s, data, "uint8");
got = dp(s, 'recv');
dv_pr('big_write', 'isequal(got, data)');
dp(s, sprintf('send %s', dp_hex(data)));
dv_pr('big_read', 'isequal(read(s, 10000, "uint8"), data)');
% method call forms
dv_pr('dot_read', 'class(s.NumBytesAvailable)');
dp(s, sprintf('send %s', dp_hex(1:2)));
pause(0.3);
dv_pr('dot_method', 's.read(2, "uint8")');
