% PROBE_MIDI_CONTROLS  midicontrols, midiread, midisync, midicallback and midiid in R2025b with no
%   MIDI input attached (device classes plan, stage D10b). Nothing is sent to an output.
dv_px('mc_default', 'mc = midicontrols')
dv_px('mc_one', 'mc = midicontrols(1081, 0.5)')
dv_px('mc_range', 'disp(midicontrols([1 2 3 4]))')
dv_px('mc_list', 'disp(midicontrols([1 5 9]))')
dv_px('mc_rawmidi', 'disp(midicontrols(7, 64, ''OutputMode'', ''rawmidi''))')
dv_px('mc_device', 'disp(midicontrols(7, ''MIDIDevice'', ''nothing here''))')
dv_px('mc_string', 'disp(midicontrols(7, "MIDIDevice", "nothing here"))')
dv_pr('mc_class', 'class(midicontrols(7))')
dv_pr('mc_props', 'properties(midicontrols(7))')
dv_pr('mc_methods', 'methods(midicontrols(7))')
dv_pr('mc_isa', 'isa(midicontrols(7), ''handle'')')
dv_pr('e_ctl_neg', 'midicontrols(-1)')
dv_pr('e_ctl_frac', 'midicontrols(1.5)')
dv_pr('e_ctl_128', 'midicontrols(128)')
dv_pr('e_ctl_chan', 'midicontrols(17001)')
dv_pr('e_ctl_char', 'midicontrols(''abc'')')
dv_pr('e_init_big', 'midicontrols(7, 2)')
dv_pr('e_init_raw_big', 'midicontrols(7, 200, ''OutputMode'', ''rawmidi'')')
dv_pr('e_init_raw_frac', 'midicontrols(7, 2.5, ''OutputMode'', ''rawmidi'')')
dv_pr('e_init_size', 'midicontrols([1 2], [0.1 0.2 0.3])')
dv_pr('e_mode', 'midicontrols(7, ''OutputMode'', ''loud'')')
dv_pr('e_dev', 'midicontrols(7, ''MIDIDevice'', 5)')
dv_pr('e_param', 'midicontrols(7, ''Bogus'', 5)')
dv_pr('e_many', 'midicontrols(1, 2, 3)')
mc = midicontrols(1081, 0.5);
dv_pr('read_one', 'midiread(mc)')
dv_pr('read_method', 'read(mc)')
dv_pr('read_two', '[v, c] = midiread(mc); c')
mc2 = midicontrols([1 2 3], [0 0.25 1]);
dv_pr('read_vec', 'midiread(mc2)')
mc3 = midicontrols([1 2], [3 127], 'OutputMode', 'rawmidi');
dv_pr('read_raw', 'midiread(mc3)')
mc4 = midicontrols([1 2; 3 4], 0.1);
dv_pr('read_mat', 'midiread(mc4)')
mc5 = midicontrols;
dv_pr('read_any', 'midiread(mc5)')
dv_pr('read_any_last', '[v, c] = midiread(mc5); c')
dv_px('sync_none', 'midisync(mc)')
dv_px('sync_val', 'midisync(mc, 0.75); disp(midiread(mc))')
dv_pr('sync_bad', 'midisync(mc, 2)')
dv_pr('sync_bad_size', 'midisync(mc2, [0.1 0.2])')
dv_px('sync_many', 'midisync(mc, 0.1, 0.2)')
dv_pr('cb_get', 'midicallback(mc)')
dv_pr('cb_set', 'midicallback(mc, @(h) disp(1))')
dv_pr('cb_get2', 'func2str(midicallback(mc))')
dv_pr('cb_clear', 'func2str(midicallback(mc, []))')
dv_pr('cb_get3', 'midicallback(mc)')
dv_pr('cb_bad', 'midicallback(mc, 5)')
dv_pr('cb_many', 'midicallback(mc, [], [])')
dv_px('cb_noout', 'midicallback(mc, @(h) disp(2))')
dv_pr('read_bad', 'midiread(5)')
dv_pr('sync_bad_obj', 'midisync(5)')
dv_pr('info_hidden', '[c, d] = midiinfo(mc); c')
dv_pr('info_hidden_dev', '[c, d] = midiinfo(mc); d')
dv_pr('info_any', 'midiinfo(mc5)')
dv_px('midiid', '[c, d] = midiid; disp(size(c)); disp(class(d)); disp(size(d))')
dv_pr('trace', 'midicontrols.trace')
dv_pr('trace_bad', 'midicontrols.trace(1)')
dv_pr('scale_q', 'midiread(midicontrols(1, 0.3))')
dv_pr('scale_q2', 'midiread(midicontrols(1, 0.001))')
dv_pr('scale_q3', 'midiread(midicontrols(1, 1))')
dv_pr('scale_many', 'midiread(midicontrols(1:11, 0:0.1:1))')
