% probe_sp_lines: terminators, readline, writeline, writeread, binblock.
device_peer();
s = serialport("COM20", 9600, "Timeout", 1);
dp(s, 'reset');
% writeline and the write terminator
writeline(s, "abc");
dv_pr('writeline_lf', 'dp(s, ''recv'')');
writeline(s, 'chars');
dv_pr('writeline_char', 'dp(s, ''recv'')');
dv_px('writeline_num', 'writeline(s, 65)');
dv_pr('writeline_num_sent', 'dp(s, ''recv'')');
dv_px('writeline_strarr', 'writeline(s, ["a" "b"])');
dv_pr('writeline_strarr_sent', 'dp(s, ''recv'')');
dv_px('writeline_cell', 'writeline(s, {''a''})');
dv_px('writeline_none', 'writeline(s)');
dv_px('writeline_two', 'writeline(s, "a", "b")');
dv_px('writeline_empty', 'writeline(s, "")');
dv_pr('writeline_empty_sent', 'dp(s, ''recv'')');
dv_px('writeline_charmat', 'writeline(s, [''ab''; ''cd''])');
dv_pr('writeline_charmat_sent', 'dp(s, ''recv'')');
configureTerminator(s, "CR");
dv_pr('term_cr', 's.Terminator');
writeline(s, "x");
dv_pr('writeline_cr', 'dp(s, ''recv'')');
configureTerminator(s, "CR/LF");
dv_pr('term_crlf', 's.Terminator');
writeline(s, "x");
dv_pr('writeline_crlf', 'dp(s, ''recv'')');
configureTerminator(s, 0);
dv_pr('term_zero', 's.Terminator');
dv_pr('term_zero_class', 'class(s.Terminator)');
writeline(s, "x");
dv_pr('writeline_zero', 'dp(s, ''recv'')');
configureTerminator(s, "LF", "CR");
dv_pr('term_pair', 's.Terminator');
writeline(s, "x");
dv_pr('writeline_pair', 'dp(s, ''recv'')');
configureTerminator(s, 13, "LF");
dv_pr('term_pair_num', 's.Terminator');
configureTerminator(s, "cr");
dv_pr('term_lower', 's.Terminator');
configureTerminator(s, 'C');
dv_pr('term_partial', 's.Terminator');
dv_px('term_bad', 'configureTerminator(s, "TAB")');
dv_px('term_256', 'configureTerminator(s, 256)');
dv_px('term_neg', 'configureTerminator(s, -1)');
dv_px('term_frac', 'configureTerminator(s, 1.5)');
dv_px('term_vec', 'configureTerminator(s, [10 13])');
dv_px('term_none', 'configureTerminator(s)');
dv_px('term_three', 'configureTerminator(s, "LF", "LF", "LF")');
dv_px('term_lfcr', 'configureTerminator(s, "LF/CR")');
dv_px('term_int8', 'configureTerminator(s, int8(10))');
dv_pr('term_int8_value', 's.Terminator');
dv_pr('term_int8_class', 'class(s.Terminator)');
dv_px('term_char_num', 'configureTerminator(s, ''10'')');
% readline
configureTerminator(s, "LF");
flush(s);
dp(s, sprintf('send %s', dp_hex(['one' 10 'two' 10 'three'])));
pause(0.3);
dv_pr('readline_1', 'readline(s)');
dv_pr('readline_2', 'readline(s)');
lastwarn('');
dv_pr('readline_partial', 'readline(s)');
[msg, id] = lastwarn;
dv_pr('readline_warn_id', 'id');
dv_pr('readline_warn_msg', 'msg');
dv_pr('readline_partial_left', 's.NumBytesAvailable');
flush(s);
lastwarn('');
dv_pr('readline_none', 'readline(s)');
[msg, id] = lastwarn;
dv_pr('readline_none_warn_msg', 'msg');
dv_px('readline_none_disp', 'x = readline(s)');
dv_px('readline_arg', 'readline(s, 1)');
dp(s, sprintf('send %s', dp_hex([10 10 'a' 13 10])));
pause(0.3);
dv_pr('readline_empty_line', 'readline(s)');
dv_pr('readline_empty_class', 'class(readline(s))');
dv_pr('readline_cr_kept', 'double(char(readline(s)))');
configureTerminator(s, "CR/LF");
flush(s);
dp(s, sprintf('send %s', dp_hex(['a' 10 'b' 13 'c' 13 10 'd' 13 10])));
pause(0.3);
dv_pr('readline_crlf_1', 'double(char(readline(s)))');
dv_pr('readline_crlf_2', 'double(char(readline(s)))');
configureTerminator(s, 13);
flush(s);
dp(s, sprintf('send %s', dp_hex(['p' 13 'q' 10 13])));
pause(0.3);
dv_pr('readline_int_1', 'double(char(readline(s)))');
dv_pr('readline_int_2', 'double(char(readline(s)))');
configureTerminator(s, "CR", "LF");
flush(s);
dp(s, sprintf('send %s', dp_hex(['r' 13 's' 10])));
pause(0.3);
dv_pr('readline_pair_read_cr', 'double(char(readline(s)))');
configureTerminator(s, 0);
flush(s);
dp(s, sprintf('send %s', dp_hex(['z' 0 'y' 0])));
pause(0.3);
dv_pr('readline_nul', 'double(char(readline(s)))');
configureTerminator(s, "LF");
flush(s);
dp(s, sprintf('send %s', dp_hex([double('héllo') 10])));
pause(0.3);
dv_pr('readline_high', 'double(char(readline(s)))');
dp(s, sprintf('send %s', dp_hex([195 169 10])));
pause(0.3);
dv_pr('readline_utf8', 'double(char(readline(s)))');
% read after readline sees what is left
dp(s, sprintf('send %s', dp_hex(['ab' 10 'cd'])));
pause(0.3);
readline(s);
dv_pr('read_after_readline', 'read(s, 2, "char")');
% writeread with the echo turned on
flush(s);
dp(s, 'echo on');
dv_pr('writeread', 'writeread(s, "hello")');
dv_pr('writeread_char', 'writeread(s, ''abc'')');
dv_px('writeread_none', 'writeread(s)');
dv_px('writeread_num', 'writeread(s, 5)');
dp(s, 'echo off');
lastwarn('');
dv_pr('writeread_timeout', 'writeread(s, "q")');
[msg, id] = lastwarn;
dv_pr('writeread_timeout_warn', 'id');
flush(s);
dp(s, 'recv');
% binblock
dp(s, 'reset');
writebinblock(s, 1:5, "uint8");
dv_pr('wbb_uint8', 'char(dp(s, ''recv''))');
writebinblock(s, [1 2], "uint16");
dv_pr('wbb_uint16', 'dp(s, ''recv'')');
writebinblock(s, 1:12, "uint8", "HDR");
dv_pr('wbb_header', 'dp(s, ''recv'')');
writebinblock(s, 'hi', "char");
dv_pr('wbb_char', 'dp(s, ''recv'')');
dv_px('wbb_empty', 'writebinblock(s, [], "uint8")');
dv_pr('wbb_empty_sent', 'dp(s, ''recv'')');
writebinblock(s, 1:300, "uint16");
got = dp(s, 'recv');
dv_pr('wbb_long_head', 'char(got(1:6))');
dv_px('wbb_no_prec', 'writebinblock(s, 1:3)');
dv_px('wbb_bad_prec', 'writebinblock(s, 1:3, "uint9")');
dv_px('wbb_num_header', 'writebinblock(s, 1:3, "uint8", 5)');
dp(s, 'recv');
flush(s);
dp(s, sprintf('send %s', dp_hex(['#15' 1 2 3 4 5])));
pause(0.3);
dv_pr('rbb_uint8', 'readbinblock(s)');
dp(s, sprintf('send %s', dp_hex(['#14' 1 0 2 0])));
pause(0.3);
dv_pr('rbb_uint16', 'readbinblock(s, "uint16")');
dp(s, sprintf('send %s', dp_hex(['junk#13abc' 10])));
pause(0.3);
dv_pr('rbb_junk_char', 'readbinblock(s, "char")');
dv_pr('rbb_after_left', 's.NumBytesAvailable');
flush(s);
dp(s, sprintf('send %s', dp_hex('#0abc')));
pause(0.3);
dv_pr('rbb_indefinite', 'readbinblock(s)');
flush(s);
dp(s, sprintf('send %s', dp_hex('#15ab')));
pause(0.3);
lastwarn('');
dv_pr('rbb_short', 'readbinblock(s)');
[msg, id] = lastwarn;
dv_pr('rbb_short_warn', 'id');
dv_pr('rbb_short_msg', 'msg');
flush(s);
lastwarn('');
dv_pr('rbb_none', 'readbinblock(s)');
[msg, id] = lastwarn;
dv_pr('rbb_none_warn', 'id');
dv_pr('rbb_none_msg', 'msg');
dp(s, sprintf('send %s', dp_hex('#x5abcde')));
pause(0.3);
dv_pr('rbb_bad_digit', 'readbinblock(s)');
flush(s);
dp(s, sprintf('send %s', dp_hex('#15abcde')));
pause(0.3);
dv_pr('rbb_string', 'readbinblock(s, "string")');
dv_pr('rbb_too_many', 'readbinblock(s, "uint8", 1)');
dp(s, sprintf('send %s', dp_hex(['#210' 0:9])));
pause(0.3);
dv_pr('rbb_two_digits', 'readbinblock(s)');
