% probe_visa_serial2: what visadev asks of the VISA driver on an ASRL resource, read back through
% getAttributeByType after each step -- why readline waits on a fresh object -- and the refusals of
% methods that answer nothing (called through dv_err).
device_peer();
v = visadev("ASRL20::INSTR");
v.Timeout = 1;
dv_pr('attr_fresh', 'dv_vattr(v)');
dp(v, 'reset');
dv_pr('attr_after_dp', 'dv_vattr(v)');
dp(v, 'send 68690A');
pause(0.3);
t0 = tic;
dv_pr('readline_fresh', 'readline(v)');
dv_pr('readline_fresh_took', 'round(toc(t0), 1)');
dv_pr('attr_after_readline', 'dv_vattr(v)');
dv_pr('read_leftover', 'read(v, 3)');
dp(v, 'send 68690A');
pause(0.3);
dv_pr('read_all3', 'read(v, 3)');
dv_pr('attr_after_read', 'dv_vattr(v)');
dp(v, 'send 68690A');
pause(0.3);
dv_pr('readline_after_read', 'readline(v)');
configureTerminator(v, "LF");
dv_pr('attr_after_cfg_lf', 'dv_vattr(v)');
dp(v, 'send 68690A');
pause(0.3);
dv_pr('readline_after_cfg', 'readline(v)');
dp(v, 'send 6120620A6320640A');
pause(0.3);
dv_pr('readline_two_1', 'readline(v)');
dv_pr('readline_two_2', 'readline(v)');
dp(v, 'send 01020A0304');
pause(0.3);
dv_pr('read_across_lf', 'read(v, 5)');
dv_pr('attr_after_read2', 'dv_vattr(v)');
dp(v, 'send 7A7A0A');
pause(0.3);
dv_pr('readline_after_read2', 'readline(v)');
% partial reads: what arrives before the timeout, and whether it is kept
dp(v, 'send 0102');
pause(0.3);
t0 = tic;
dv_pr('read_partial', 'read(v, 5)');
dv_pr('read_partial_took', 'round(toc(t0), 1)');
dp(v, 'send 03');
pause(0.3);
dv_pr('read_after_partial', 'read(v, 1)');
dp(v, 'send 6869');
pause(0.3);
t0 = tic;
dv_pr('readline_partial', 'readline(v)');
dv_pr('readline_partial_took', 'round(toc(t0), 1)');
dp(v, 'send 0A');
pause(0.3);
lastwarn('');
dv_pr('readline_after_partial', 'readline(v)');
[m, id] = lastwarn;
dv_pr('readline_after_partial_warn', 'id');
t0 = tic;
lastwarn('');
dv_pr('read_nothing', 'read(v, 2)');
dv_pr('read_nothing_took', 'round(toc(t0), 1)');
[m, id] = lastwarn;
dv_pr('read_nothing_warn', 'id');
v.Timeout = 2;
t0 = tic;
dv_pr('read_nothing_t2', 'read(v, 2)');
dv_pr('read_nothing_t2_took', 'round(toc(t0), 1)');
t0 = tic;
dv_pr('readline_nothing_t2', 'readline(v)');
dv_pr('readline_nothing_t2_took', 'round(toc(t0), 1)');
v.Timeout = 1;
dv_pr('attr_t1', 'dv_vattr(v)');
dp(v, 'later 1500 41420A');
t0 = tic;
dv_pr('readline_late', 'readline(v)');
dv_pr('readline_late_took', 'round(toc(t0), 1)');
pause(1);
flush(v);
dp(v, 'later 1500 0102');
t0 = tic;
dv_pr('read_late', 'read(v, 2)');
dv_pr('read_late_took', 'round(toc(t0), 1)');
pause(1);
flush(v);
dp(v, 'later 300 0102');
t0 = tic;
dv_pr('read_soon', 'read(v, 2)');
dv_pr('read_soon_took', 'round(toc(t0), 1)');
configureTerminator(v, "off");
dv_pr('attr_off', 'dv_vattr(v)');
configureTerminator(v, "CR/LF");
dv_pr('attr_crlf', 'dv_vattr(v)');
configureTerminator(v, "CR", "LF");
dv_pr('attr_cr_lf', 'dv_vattr(v)');
configureTerminator(v, "LF", "CR");
dv_pr('attr_lf_cr', 'dv_vattr(v)');
configureTerminator(v, 0);
dv_pr('attr_zero', 'dv_vattr(v)');
configureTerminator(v, "LF");
v.Timeout = 3.5;
dv_pr('attr_t35', 'dv_vattr(v)');
v.Timeout = 1;

% refusals of methods with no output
dv_pr('write_300', 'dv_err(@() write(v, 300))');
dv_pr('write_neg', 'dv_err(@() write(v, -1))');
dv_pr('write_frac', 'dv_err(@() write(v, 1.5))');
dv_pr('write_none', 'dv_err(@() write(v))');
dv_pr('write_cell', 'dv_err(@() write(v, {1}))');
dv_pr('write_prec_bad', 'dv_err(@() write(v, 1, "uint9"))');
dv_pr('write_four', 'dv_err(@() write(v, 1, "uint8", 3))');
dv_pr('write_logical', 'dv_err(@() write(v, true))');
dv_pr('write_empty', 'dv_err(@() write(v, []))');
dv_pr('write_matrix', 'dv_err(@() write(v, [1 2; 3 4]))');
dv_pr('writeline_none', 'dv_err(@() writeline(v))');
dv_pr('writeline_num', 'dv_err(@() writeline(v, 5))');
dv_pr('writeline_two', 'dv_err(@() writeline(v, "a", "b"))');
dv_pr('term_bad', 'dv_err(@() configureTerminator(v, "XY"))');
dv_pr('term_256', 'dv_err(@() configureTerminator(v, 256))');
dv_pr('term_none', 'dv_err(@() configureTerminator(v))');
dv_pr('term_four', 'dv_err(@() configureTerminator(v, "LF", "LF", "LF"))');
dv_pr('term_off_off', 'dv_err(@() configureTerminator(v, "off", "off"))');
dv_pr('term_lower_off', 'dv_err(@() configureTerminator(v, "OFF"))');
dv_pr('term_after', 'v.Terminator');
configureTerminator(v, "LF");
dv_pr('term_empty', 'dv_err(@() configureTerminator(v, ""))');
dv_pr('term_after_empty', 'v.Terminator');
configureTerminator(v, "LF");
dv_pr('term_lower', 'dv_err(@() configureTerminator(v, "lf"))');
dv_pr('term_after_lower', 'v.Terminator');
configureTerminator(v, "LF");
dv_pr('cc_off', 'dv_err(@() configureCallback(v, "off"))');
dv_pr('cc_none', 'dv_err(@() configureCallback(v))');
dv_pr('setdtr_bad', 'dv_err(@() setDTR(v, "on"))');
dv_pr('setdtr_none', 'dv_err(@() setDTR(v))');
dv_pr('setrts_num', 'dv_err(@() setRTS(v, 1))');
dv_pr('setrts_two', 'dv_err(@() setRTS(v, 1, 2))');
dv_pr('setrts_vec', 'dv_err(@() setRTS(v, [true false]))');
dv_pr('flush_bad', 'dv_err(@() flush(v, "both"))');
dv_pr('flush_output', 'dv_err(@() flush(v, "output"))');
dv_pr('flush_three', 'dv_err(@() flush(v, "input", "x"))');
dv_pr('flush_partial', 'dv_err(@() flush(v, "in"))');
dv_pr('clrdevice', 'dv_err(@() clrdevice(v))');
dv_pr('fopen', 'dv_err(@() fopen(v))');
dv_pr('fclose', 'dv_err(@() fclose(v))');
dv_pr('fwrite', 'dv_err(@() fwrite(v, [1 2]))');
dv_pr('fwrite_recv', 'dp(v, ''recv'')');
dv_pr('binblockwrite', 'dv_err(@() binblockwrite(v, [1 2]))');
dv_pr('binblockwrite_recv', 'dp(v, ''recv'')');
dv_pr('flushinput', 'dv_err(@() flushinput(v))');
dv_pr('flushoutput', 'dv_err(@() flushoutput(v))');
dv_pr('record', 'dv_err(@() record(v))');
dv_pr('readasync', 'dv_err(@() readasync(v))');
dv_pr('stopasync', 'dv_err(@() stopasync(v))');
dv_pr('wbb_none', 'dv_err(@() writebinblock(v))');
dv_pr('wbb_one', 'dv_err(@() writebinblock(v, 1:3))');
dv_pr('wbb_hdr_num', 'dv_err(@() writebinblock(v, 1:3, "uint8", 5))');
dv_pr('visastatus_none', 'dv_err(@() visastatus(v, 1))');
dv_pr('set_errfcn_empty', 'dv_err(@() set(v, ''ErrorOccurredFcn'', []))');
dv_pr('errfcn_after_empty', 'class(v.ErrorOccurredFcn)');
dv_pr('set_userdata', 'dv_err(@() set(v, ''UserData'', 5))');
% legacy reads with a line waiting
dp(v, 'send 31320A');
pause(0.3);
dv_pr('fscanf', 'fscanf(v)');
dp(v, 'send 7A0A');
pause(0.3);
dv_pr('fgetl', 'fgetl(v)');
dp(v, 'send 7A0A');
pause(0.3);
dv_pr('fgets', 'fgets(v)');
dp(v, 'on 513F0A 410A');
dv_pr('query', 'query(v, ''Q?'')');
dp(v, 'send 010203');
pause(0.3);
dv_pr('fread', 'fread(v, 3)');
dp(v, 'send 2331330102030A');
pause(0.3);
dv_pr('binblockread', 'binblockread(v)');
dv_pr('fread_none', 'fread(v)');
lastwarn('');
dv_pr('props_legacy_ValuesReceived', 'v.ValuesReceived');
[m, id] = lastwarn;
dv_pr('props_legacy_warn', 'sprintf(''%s ## %s'', id, m)');
dv_pr('props_legacy_InputBufferSize', 'v.InputBufferSize');
dv_pr('props_legacy_Name', 'v.Name');
dv_pr('props_legacy_Type', 'v.Type');
dv_pr('props_legacy_TimerFcn', 'v.TimerFcn');
dv_pr('props_legacy_ReadAsyncMode', 'v.ReadAsyncMode');
