% probe_sp_object: the serialport object itself -- class, bases, properties and their defaults,
% display, methods, handle semantics, lists and find, preferences, delete, save and load.
% Needs com0com COM20<->COM21 and peer-sim (device_peer starts it on COM21).
device_peer();
try, internal.Serialport.clearPreferences(); catch, end
s = serialport("COM20", 9600);
dv_pr('class', 'class(s)');
dv_pr('isa_handle', 'isa(s, ''handle'')');
dv_pr('isa_serialport', 'isa(s, ''serialport'')');
dv_pr('isa_internal', 'isa(s, ''internal.Serialport'')');
dv_pr('isobject', 'isobject(s)');
dv_pr('isstruct', 'isstruct(s)');
dv_pr('superclasses', 'superclasses(s)');
dv_pr('properties', 'properties(s)');
dv_pr('fieldnames', 'fieldnames(s)');
dv_pr('methods', 'methods(s)');
dv_px('methods_disp', 'methods(s)');
dv_pr('size', 'size(s)');
dv_pr('numel', 'numel(s)');
dv_pr('isvalid', 'isvalid(s)');
dv_pr('isequal_self', 'isequal(s, s)');
dv_pr('eq_self', 's == s');
props = {'Port','BaudRate','Parity','DataBits','StopBits','FlowControl','ByteOrder','Timeout','Tag', ...
    'NumBytesAvailable','NumBytesWritten','Terminator','BytesAvailableFcnMode','BytesAvailableFcnCount', ...
    'BytesAvailableFcn','ErrorOccurredFcn','UserData'};
for k = 1:numel(props)
    dv_pr(['prop_' props{k}], ['s.' props{k}]);
end
dv_px('echo', 's');
dv_px('disp', 'disp(s)');
dv_px('display', 'display(s)');
dv_pr('get_all', 'get(s)');
dv_px('get_disp', 'get(s)');
dv_pr('get_one', 'get(s, ''BaudRate'')');
dv_pr('get_cell', 'get(s, {''BaudRate'', ''Parity''})');
dv_px('set_disp', 'set(s)');
dv_pr('isprop_baud', 'isprop(s, ''BaudRate'')');
dv_pr('isprop_bogus', 'isprop(s, ''Bogus'')');
dv_pr('isprop_bytesavailable', 'isprop(s, ''BytesAvailable'')');
dv_pr('status', 'dp(s, ''status'')');
dv_pr('pins', 'getpinstatus(s)');
p = getpinstatus(s);
dv_pr('pins_values', '[p.ClearToSend p.DataSetReady p.CarrierDetect p.RingIndicator]');
dv_pr('pins_class', 'class(p.ClearToSend)');
dv_px('pins_disp', 'getpinstatus(s)');
% lists and find
dv_pr('list', 'serialportlist');
dv_pr('list_all', 'serialportlist("all")');
dv_pr('list_available', 'serialportlist("available")');
dv_pr('list_char', 'serialportlist(''available'')');
dv_pr('list_partial', 'serialportlist("avail")');
dv_pr('list_upper', 'serialportlist("ALL")');
dv_pr('list_two', 'serialportlist("all", "available")');
dv_pr('list_number', 'serialportlist(1)');
s.Tag = "probe";
dv_pr('find_all', 'serialportfind');
f = serialportfind;
dv_pr('find_isequal', 'isequal(f, s)');
dv_pr('find_tag', 'serialportfind("Tag", "probe")');
dv_pr('find_tag_nv', 'serialportfind(Tag="probe")');
dv_pr('find_port', 'serialportfind("Port", "COM20")');
dv_pr('find_port_char', 'serialportfind(''Port'', ''COM20'')');
dv_pr('find_baud', 'serialportfind("BaudRate", 9600)');
dv_pr('find_none', 'serialportfind("Tag", "nothing")');
dv_pr('find_bogus', 'serialportfind("Bogus", 1)');
dv_pr('find_odd', 'serialportfind("Tag")');
dv_pr('find_case', 'serialportfind("tag", "probe")');
dv_pr('find_two', 'serialportfind("Tag", "probe", "Port", "COM20")');
% a second object on the same port
dv_pr('second_open', 'serialport("COM20", 9600)');
% handle semantics
s2 = s;
s2.Tag = "changed";
dv_pr('handle_tag', 's.Tag');
dv_pr('eq_alias', 's == s2');
% setters
s.BaudRate = 115200;
dv_pr('baud_set', 's.BaudRate');
dv_pr('baud_class', 'class(s.BaudRate)');
s.Parity = 'even';
dv_pr('parity_set', 's.Parity');
s.Parity = "ODD";
dv_pr('parity_upper', 's.Parity');
s.Parity = "n";
dv_pr('parity_partial', 's.Parity');
s.FlowControl = "hard";
dv_pr('flow_partial', 's.FlowControl');
s.FlowControl = "none";
s.ByteOrder = "big";
dv_pr('byteorder_partial', 's.ByteOrder');
s.ByteOrder = "little-endian";
s.StopBits = 2;
dv_pr('stopbits_2', 's.StopBits');
s.StopBits = 1;
s.DataBits = int8(7);
dv_pr('databits_int8', 's.DataBits');
dv_pr('databits_int8_class', 'class(s.DataBits)');
s.DataBits = 8;
s.Timeout = 2.5;
dv_pr('timeout_set', 's.Timeout');
dv_px('timeout_int', 's.Timeout = int32(3)');
dv_pr('timeout_after_int', 's.Timeout');
dv_px('timeout_zero', 's.Timeout = 0');
dv_pr('timeout_zero_value', 's.Timeout');
dv_px('timeout_inf', 's.Timeout = Inf');
dv_pr('timeout_inf_value', 's.Timeout');
dv_px('timeout_neg', 's.Timeout = -1');
dv_px('timeout_nan', 's.Timeout = NaN');
dv_px('timeout_vec', 's.Timeout = [1 2]');
dv_px('timeout_str', 's.Timeout = "5"');
dv_px('timeout_empty', 's.Timeout = []');
dv_px('timeout_single', 's.Timeout = single(2)');
dv_px('timeout_logical', 's.Timeout = true');
s.Timeout = 10;
dv_px('baud_neg', 's.BaudRate = -1');
dv_px('baud_zero', 's.BaudRate = 0');
dv_px('baud_frac', 's.BaudRate = 9600.5');
dv_px('baud_str', 's.BaudRate = "9600"');
dv_px('baud_vec', 's.BaudRate = [1 2]');
dv_px('baud_int32', 's.BaudRate = int32(19200)');
dv_pr('baud_int32_value', 's.BaudRate');
dv_pr('baud_int32_class', 'class(s.BaudRate)');
dv_px('baud_inf', 's.BaudRate = Inf');
dv_px('baud_huge', 's.BaudRate = 5e9');
dv_pr('baud_huge_value', 's.BaudRate');
s.BaudRate = 9600;
dv_px('parity_bad', 's.Parity = "bogus"');
dv_px('parity_num', 's.Parity = 1');
dv_px('parity_empty', 's.Parity = ""');
dv_px('parity_mark', 's.Parity = "mark"');
dv_px('parity_cell', 's.Parity = {''none''}');
s.Parity = "none";
dv_px('databits_9', 's.DataBits = 9');
dv_px('databits_4', 's.DataBits = 4');
dv_px('databits_frac', 's.DataBits = 7.5');
dv_px('databits_str', 's.DataBits = "8"');
dv_px('databits_vec', 's.DataBits = [7 8]');
dv_px('databits_5', 's.DataBits = 5');
dv_pr('databits_5_value', 's.DataBits');
dv_px('databits_6', 's.DataBits = 6');
dv_px('databits_7', 's.DataBits = 7');
s.DataBits = 8;
dv_px('stopbits_3', 's.StopBits = 3');
dv_px('stopbits_0', 's.StopBits = 0');
dv_px('stopbits_15', 's.StopBits = 1.5');
dv_pr('stopbits_15_value', 's.StopBits');
dv_px('stopbits_str', 's.StopBits = "1"');
dv_px('stopbits_2_again', 's.StopBits = 2');
s.StopBits = 1;
dv_px('flow_bad', 's.FlowControl = "rts"');
dv_px('flow_num', 's.FlowControl = 0');
dv_px('flow_software', 's.FlowControl = "software"');
dv_pr('flow_software_value', 's.FlowControl');
s.FlowControl = "none";
dv_px('order_bad', 's.ByteOrder = "middle"');
dv_px('order_num', 's.ByteOrder = 1');
dv_px('tag_num', 's.Tag = 5');
dv_px('tag_cell', 's.Tag = {''a''}');
dv_px('tag_strarr', 's.Tag = ["a" "b"]');
dv_px('port_set', 's.Port = "COM21"');
dv_px('nba_set', 's.NumBytesAvailable = 3');
dv_px('nbw_set', 's.NumBytesWritten = 3');
dv_px('term_set', 's.Terminator = "CR"');
dv_px('bafm_set', 's.BytesAvailableFcnMode = "byte"');
dv_px('bafc_set', 's.BytesAvailableFcnCount = 5');
dv_px('baf_set', 's.BytesAvailableFcn = @disp');
dv_px('errfcn_bad', 's.ErrorOccurredFcn = 5');
dv_px('errfcn_str', 's.ErrorOccurredFcn = "disp"');
dv_px('bogus_set', 's.Bogus = 1');
dv_pr('bogus_get', 's.Bogus');
dv_px('set_fn_bad', 'set(s, ''Parity'', ''bogus'')');
dv_px('set_fn_odd', 'set(s, ''Parity'')');
dv_px('set_fn_multi', 'set(s, ''Parity'', ''even'', ''DataBits'', 7)');
dv_pr('set_fn_multi_value', 'get(s, {''Parity'', ''DataBits''})');
dv_px('set_fn_readonly', 'set(s, ''Port'', ''COM1'')');
dv_px('set_fn_lower', 'set(s, ''parity'', ''odd'')');
dv_pr('set_fn_lower_value', 's.Parity');
dv_pr('get_fn_lower', 'get(s, ''baudrate'')');
dv_pr('get_fn_bogus', 'get(s, ''Bogus'')');
dv_pr('dot_lower', 's.baudrate');
s.Parity = "none";
s.DataBits = 8;
s.UserData = {1, 'two'};
dv_pr('userdata', 's.UserData');
s.Tag = 'charTag';
dv_pr('tag_char', 's.Tag');
s.ErrorOccurredFcn = @(varargin) disp('err');
dv_pr('errfcn', 'class(s.ErrorOccurredFcn)');
s.ErrorOccurredFcn = [];
dv_pr('errfcn_empty', 's.ErrorOccurredFcn');
% save and load
f = [tempname '.mat'];
s.Tag = "saved";
configureTerminator(s, "CR", 10);
save(f, 's');
w = whos('-file', f);
dv_pr('save_whos_class', 'w.class');
clear s s2
dv_pr('after_clear_list', 'serialportlist("available")');
S = load(f);
dv_pr('load_class', 'class(S.s)');
dv_pr('load_port', 'S.s.Port');
dv_pr('load_tag', 'S.s.Tag');
dv_pr('load_baud', 'S.s.BaudRate');
dv_pr('load_term', 'S.s.Terminator');
dv_pr('load_valid', 'isvalid(S.s)');
delete(S.s);
dv_pr('deleted_valid', 'isvalid(S.s)');
dv_pr('deleted_prop', 'S.s.BaudRate');
dv_pr('deleted_port', 'S.s.Port');
dv_px('deleted_echo', 'S.s');
dv_pr('deleted_read', 'read(S.s, 1, "uint8")');
dv_pr('deleted_write', 'write(S.s, 1, "uint8")');
dv_pr('deleted_set', 'set(S.s, ''BaudRate'', 9600)');
dv_pr('deleted_find', 'serialportfind');
clear S
delete(f);
% the no-argument constructor: the last cleared object's settings
s = serialport();
dv_pr('noarg_port', 's.Port');
dv_pr('noarg_baud', 's.BaudRate');
dv_pr('noarg_tag', 's.Tag');
dv_pr('noarg_term', 's.Terminator');
dv_pr('noarg_parity', 's.Parity');
clear s
try, internal.Serialport.clearPreferences(); catch, end
dv_pr('noarg_after_clearprefs', 'serialport()');
% the constructor's forms
dv_pr('ctor_one', 'serialport("COM20")');
dv_pr('ctor_missing', 'serialport("COM99", 9600)');
dv_pr('ctor_peer_port', 'serialport("COM21", 9600)');
dv_pr('ctor_neg_baud', 'serialport("COM20", -5)');
dv_pr('ctor_zero_baud', 'serialport("COM20", 0)');
dv_pr('ctor_frac_baud', 'serialport("COM20", 9600.5)');
dv_pr('ctor_str_baud', 'serialport("COM20", "9600")');
dv_pr('ctor_int_baud', 'serialport("COM20", int32(9600))');
dv_pr('ctor_vec_baud', 'serialport("COM20", [9600 9600])');
dv_pr('ctor_empty_port', 'serialport("", 9600)');
dv_pr('ctor_num_port', 'serialport(20, 9600)');
dv_pr('ctor_cell_port', 'serialport({''COM20''}, 9600)');
dv_pr('ctor_lower_port', 'serialport("com20", 9600)');
dv_pr('ctor_odd_nv', 'serialport("COM20", 9600, "Parity")');
dv_pr('ctor_bad_nv', 'serialport("COM20", 9600, "Bogus", 1)');
dv_pr('ctor_partial_nv', 'get(serialport("COM20", 9600, "Par", "even"), ''Parity'')');
dv_pr('ctor_bad_parity', 'serialport("COM20", 9600, "Parity", "bogus")');
dv_pr('ctor_num_parity', 'serialport("COM20", 9600, "Parity", 1)');
dv_pr('ctor_bad_databits', 'serialport("COM20", 9600, "DataBits", 9)');
dv_pr('ctor_vec_databits', 'serialport("COM20", 9600, "DataBits", [7 8])');
dv_pr('ctor_bad_stopbits', 'serialport("COM20", 9600, "StopBits", 3)');
dv_pr('ctor_15_stopbits', 'get(serialport("COM20", 9600, "StopBits", 1.5), ''StopBits'')');
dv_pr('ctor_bad_flow', 'serialport("COM20", 9600, "FlowControl", "rts")');
dv_pr('ctor_bad_order', 'serialport("COM20", 9600, "ByteOrder", "middle")');
dv_pr('ctor_bad_timeout', 'serialport("COM20", 9600, "Timeout", -1)');
dv_pr('ctor_timeout_zero', 'get(serialport("COM20", 9600, "Timeout", 0), ''Timeout'')');
dv_pr('ctor_timeout_inf', 'get(serialport("COM20", 9600, "Timeout", Inf), ''Timeout'')');
dv_pr('ctor_bad_tag', 'serialport("COM20", 9600, "Tag", 5)');
dv_pr('ctor_userdata_nv', 'serialport("COM20", 9600, "UserData", 5)');
dv_pr('ctor_terminator_nv', 'serialport("COM20", 9600, "Terminator", "CR")');
dv_pr('ctor_nv_struct', 'get(serialport("COM20", 9600, Parity="odd", DataBits=7), {''Parity'',''DataBits''})');
dv_pr('ctor_parity_mark', 'get(serialport("COM20", 9600, "Parity", "mark"), ''Parity'')');
dv_pr('ctor_parity_space', 'get(serialport("COM20", 9600, "Parity", "space"), ''Parity'')');
dv_pr('ctor_databits_5', 'get(serialport("COM20", 9600, "DataBits", 5), ''DataBits'')');
dv_pr('ctor_databits_5_stop15', 'get(serialport("COM20", 9600, "DataBits", 5, "StopBits", 1.5), {''DataBits'',''StopBits''})');
dv_pr('ctor_databits_4', 'serialport("COM20", 9600, "DataBits", 4)');
dv_pr('ctor_huge_baud', 'get(serialport("COM20", 1e9), ''BaudRate'')');
dv_pr('ctor_odd_baud', 'get(serialport("COM20", 12345), ''BaudRate'')');
serialport("COM20", 9600);
dv_pr('ctor_ans', 'class(ans)');
dv_pr('ctor_ans_port', 'ans.Port');
