% PROBE_NET_ECHO  echotcpip and echoudp edges, resolvehost refusals, udpport write refusals and
% datagram edges (device classes plan, stage D2).
dv_px('tcp_on_only', 'echotcpip("on")');
dv_px('tcp_three', 'echotcpip("on", 50250, 1)');
dv_px('tcp_port_zero', 'echotcpip("on", 0)');
dv_px('tcp_port_big', 'echotcpip("on", 70000)');
dv_px('tcp_port_frac', 'echotcpip("on", 5.5)');
dv_px('tcp_port_str', 'echotcpip("on", "50250")');
dv_px('tcp_state_num', 'echotcpip(1, 50250)');
dv_px('tcp_prefix', 'echotcpip("of")');
dv_px('tcp_off_idle', 'echotcpip("off")');
dv_px('tcp_on', 'echotcpip("On", 50250)');
dv_px('tcp_on_again', 'echotcpip("on", 50250)');
dv_px('tcp_on_other', 'echotcpip("on", 50251)');
t = tcpclient("127.0.0.1", 50250);
write(t, uint8(1:3)); pause(0.3);
dv_pr('tcp_echoed', 'read(t)');
clear t
dv_px('tcp_off', 'echotcpip("off")');
dv_px('tcp_off_twice', 'echotcpip("off")');

dv_px('udp_on_only', 'echoudp("on")');
dv_px('udp_three', 'echoudp("on", 50252, 1)');
dv_px('udp_off_port', 'echoudp("off", 5)');
dv_px('udp_port_zero', 'echoudp("on", 0)');
dv_px('udp_port_frac', 'echoudp("on", 5.5)');
dv_px('udp_off_idle', 'echoudp("off")');
dv_px('udp_on', 'echoudp("on", 50252)');
dv_px('udp_on_again', 'echoudp("on", 50252)');
dv_px('udp_on_other', 'echoudp("on", 50253)');
dv_px('udp_off', 'echoudp("off")');

dv_px('rh_none', 'resolvehost');
dv_px('rh_three', 'resolvehost("a", "name", 1)');
dv_px('rh_num', 'resolvehost(5)');
dv_px('rh_flag_num', 'resolvehost("localhost", 5)');
dv_px('rh_flag_bad', 'resolvehost("localhost", "who")');
dv_pr('rh_flag_addr', 'resolvehost("localhost", "address")');
dv_pr('rh_flag_prefix', 'resolvehost("localhost", "n")');
dv_pr('rh_empty', 'resolvehost("")');
dv_pr('rh_blank', 'resolvehost("  ")');
dv_pr('rh_upper', 'resolvehost("LOCALHOST")');
dv_pr('rh_badip', 'resolvehost("300.1.1.1")');
dv_pr('rh_badip_warn', 'lastwarn');
dv_pr('rh_three_dots', 'resolvehost("1.2.3")');
dv_pr('rh_ip_addr', 'resolvehost("127.0.0.1", "address")');
[n, a] = resolvehost("no.such.host.invalid");
dv_pr('rh_bad_two', 'a');
[n, a] = resolvehost("127.0.0.1");
dv_pr('rh_ip_two_n', 'n');
dv_pr('rh_ip_two_a', 'a');
dv_px('rh_three_out', '[a, b, c] = resolvehost("localhost")');

% udpport writes without a destination, destinations, and datagram edges
echoudp("on", 50254);
u = udpport;
dv_px('u_write_nodest', 'write(u, 1:3)');
dv_px('u_writeline_nodest', 'writeline(u, "hi")');
dv_px('u_write_badhost', 'write(u, 1:3, "no.such.host.invalid", 50254)');
dv_px('u_write_portstr', 'write(u, 1:3, "127.0.0.1", "50254")');
dv_px('u_write_portbig', 'write(u, 1:3, "127.0.0.1", 70000)');
dv_px('u_write_five', 'write(u, 1:3, "uint8", "127.0.0.1", 50254, 1)');
dv_px('u_write_none', 'write(u)');
dv_px('u_writeline_two', 'writeline(u, "a", "127.0.0.1")');
write(u, 1:3, "127.0.0.1", 50254); pause(0.3);
dv_pr('u_nba', 'u.NumBytesAvailable');
write(u, 4:5); pause(0.3);
dv_pr('u_read_kept_dest', 'read(u, u.NumBytesAvailable)');
writeline(u, "abc", "127.0.0.1", 50254); pause(0.3);
dv_pr('u_readline', 'readline(u)');
dv_pr('u_written', 'u.NumBytesWritten');
dv_px('u_mc_bad', 'configureMulticast(u, "10.0.0.1")');
dv_px('u_mc_none', 'configureMulticast(u)');
dv_px('u_mc_num', 'configureMulticast(u, 5)');
dv_px('u_mc_loop_num', 'configureMulticast(u, "239.1.1.1", 1)');
dv_pr('u_mc_state', '{u.EnableMulticast, u.MulticastGroup}');
dv_px('u_mc_off', 'configureMulticast(u, "off")');
dv_px('u_set_group', 'u.MulticastGroup = "239.1.1.1"');
dv_px('u_set_enable_mc', 'u.EnableMulticast = true');
dv_px('u_set_host', 'u.LocalHost = "1.2.3.4"');
dv_px('u_set_ver', 'u.IPAddressVersion = "IPV6"');
dv_px('u_set_share', 'u.EnablePortSharing = true');
dv_px('u_set_term', 'u.Terminator = "CR"');
clear u

d = udpport("datagram");
dv_px('d_show', 'd');
dv_px('d_read_none', 'read(d)');
dv_px('d_read_zero', 'read(d, 0)');
dv_px('d_read_str', 'read(d, "a")');
dv_px('d_read_badprec', 'read(d, 1, "int3")');
dv_px('d_readline', 'readline(d)');
dv_px('d_write_nodest', 'write(d, 1:3)');
write(d, 1:3, "127.0.0.1", 50254);
write(d, uint16([1 2]), "uint16", "127.0.0.1", 50254);
pause(0.3);
dv_pr('d_nda', 'd.NumDatagramsAvailable');
dv_pr('d_ndw', 'd.NumDatagramsWritten');
dv_pr('d_read_bad_multiple', 'read(d, 1, "uint16")');
dv_pr('d_nda_after_bad', 'd.NumDatagramsAvailable');
flush(d);
write(d, uint16([1 2]), "uint16", "127.0.0.1", 50254); pause(0.3);
x = read(d, 2, "uint16");
dv_pr('d_read_class', 'class(x)');
dv_pr('d_read_size', 'size(x)');
dv_pr('d_read_data1', 'x(1).Data');
dv_pr('d_read_data2', 'x(2).Data');
dv_pr('d_read_addr', 'x(1).SenderAddress');
dv_pr('d_read_port', 'x(1).SenderPort == 50254');
dv_px('d_read_show', 'x(1)');
dv_pr('d_read_fields', 'properties(x)');
write(d, 65:67, "127.0.0.1", 50254); pause(0.3);
y = read(d, 1, "char");
dv_pr('d_read_char', 'y.Data');
write(d, 65:67, "127.0.0.1", 50254); pause(0.3);
y = read(d, 1, "string");
dv_pr('d_read_string', 'y.Data');
write(d, 1:3, "127.0.0.1", 50254); pause(0.3);
dv_px('d_read_odd_err', 'y = read(d, 1, "uint16")');
dv_px('d_read_odd', 'y.Data');
d.Timeout = 1;
dv_pr('d_read_timeout', 'read(d, 1)');
dv_pr('d_read_timeout_warn', 'lastwarn');
dv_px('d_cb_bad', 'configureCallback(d, "byte", 1, @disp)');
dv_px('d_cb_nofcn', 'configureCallback(d, "datagram", 1)');
dv_px('d_cb_zero', 'configureCallback(d, "datagram", 0, @disp)');
dv_px('d_cb_notfcn', 'configureCallback(d, "datagram", 1, 5)');
dv_px('d_flush_out', 'flush(d, "output")');
dv_px('d_flush_bad', 'flush(d, "sideways")');
dv_px('d_set_count', 'd.DatagramsAvailableFcnCount = 2');
dv_pr('d_methods', 'methods(d)');
dv_pr('d_props', 'properties(d)');
clear d
echoudp("off");
