% probe_visa_serial: visadev on ASRL20::INSTR with the peer engine on COM21 -- the object, every
% property and setter, reads and writes through VISA's synchronous reads, terminators, pins, the
% refusals of the dropped asynchronous surface, legacy methods, and lifetime.
device_peer();
v = visadev("ASRL20::INSTR");
dv_pr('class', 'class(v)');
dv_pr('superclasses', 'superclasses(v)');
dv_pr('isa_handle', 'isa(v, ''handle'')');
dv_pr('isa_resource', 'isa(v, ''visalib.Resource'')');
dv_pr('properties', 'properties(v)');
dv_pr('methods', 'methods(v)');
dv_px('echo', 'v');
dv_px('disp', 'disp(v)');
dv_px('get', 'get(v)');
props = {'ResourceName','Alias','Vendor','Model','SerialNumber','Type','PreferredVisa','Port', ...
    'BaudRate','DataBits','StopBits','Parity','FlowControl','ByteOrder','Timeout','Terminator', ...
    'NumBytesWritten','ErrorOccurredFcn','UserData','Tag'};
for k = 1:numel(props)
    dv_pr(['prop_' props{k}], ['v.' props{k}]);
end
dv_pr('class_Type', 'class(v.Type)');
dv_pr('class_Parity', 'class(v.Parity)');
dv_pr('class_FlowControl', 'class(v.FlowControl)');
hidden = {'NumBytesAvailable','BytesAvailableFcn','BytesAvailableFcnMode','BytesAvailableFcnCount', ...
    'TransferPeriod','TransferSize','Connected','ResourceClass','EOSMode','EOSCharCode','RsrcName', ...
    'ObjectType','KeepAlive','EOIMode'};
for k = 1:numel(hidden)
    dv_pr(['hidden_' hidden{k}], ['v.' hidden{k}]);
end
dv_pr('set_nba', 'set(v, ''NumBytesAvailable'', 1)');
dv_pr('set_bafcn', 'set(v, ''BytesAvailableFcn'', @disp)');
dv_pr('configureCallback', 'configureCallback(v, "off")');
dv_pr('isprop_nba', 'isprop(v, ''NumBytesAvailable'')');
dv_pr('ismethod_cc', 'ismethod(v, ''configureCallback'')');

% setters
dv_px('set_baud', 'v.BaudRate = 115200; disp(v.BaudRate)');
dv_pr('set_baud_neg', 'set(v, ''BaudRate'', -1)');
dv_pr('set_baud_frac', 'set(v, ''BaudRate'', 1.5)');
dv_pr('set_baud_str', 'set(v, ''BaudRate'', "x")');
dv_pr('set_baud_vec', 'set(v, ''BaudRate'', [1 2])');
dv_px('set_baud_odd', 'v.BaudRate = 12345; disp(v.BaudRate)');
dv_px('set_baud_huge', 'v.BaudRate = 5e7; disp(v.BaudRate)');
v.BaudRate = 9600;
dv_px('set_databits', 'v.DataBits = 7; disp(v.DataBits)');
dv_pr('set_databits_bad', 'set(v, ''DataBits'', 9)');
dv_px('set_databits_5', 'v.DataBits = 5; disp(v.DataBits)');
v.DataBits = 8;
dv_px('set_stopbits', 'v.StopBits = 2; disp(v.StopBits)');
dv_px('set_stopbits_15', 'v.StopBits = 1.5; disp(v.StopBits)');
dv_pr('set_stopbits_bad', 'set(v, ''StopBits'', 3)');
v.StopBits = 1;
dv_px('set_parity', 'v.Parity = "even"; disp(v.Parity)');
dv_px('set_parity_char', 'v.Parity = ''odd''; disp(v.Parity)');
dv_pr('set_parity_bad', 'set(v, ''Parity'', "mark")');
dv_pr('set_parity_num', 'set(v, ''Parity'', 1)');
dv_pr('set_parity_partial', 'set(v, ''Parity'', "ev")');
v.Parity = "none";
dv_px('set_flow', 'v.FlowControl = "hardware"; disp(v.FlowControl)');
dv_px('set_flow_sw', 'v.FlowControl = "software"; disp(v.FlowControl)');
dv_pr('set_flow_bad', 'set(v, ''FlowControl'', "both")');
v.FlowControl = "none";
dv_px('set_timeout', 'v.Timeout = 2; disp(v.Timeout)');
dv_px('set_timeout_frac', 'v.Timeout = 0.25; disp(v.Timeout)');
dv_px('set_timeout_tiny', 'v.Timeout = 0.0001; disp(v.Timeout)');
dv_pr('set_timeout_neg', 'set(v, ''Timeout'', -1)');
dv_pr('set_timeout_zero', 'set(v, ''Timeout'', 0)');
dv_px('set_timeout_inf', 'v.Timeout = Inf; disp(v.Timeout)');
dv_pr('set_timeout_str', 'set(v, ''Timeout'', "1")');
v.Timeout = 1;
dv_px('set_byteorder', 'v.ByteOrder = "big-endian"; disp(v.ByteOrder)');
dv_pr('set_byteorder_bad', 'set(v, ''ByteOrder'', "middle")');
v.ByteOrder = "little-endian";
dv_pr('set_terminator', 'set(v, ''Terminator'', "CR")');
dv_pr('set_port', 'set(v, ''Port'', "ASRL1")');
dv_pr('set_resname', 'set(v, ''ResourceName'', "x")');
dv_pr('set_type', 'set(v, ''Type'', "usb")');
dv_px('set_tag', 'v.Tag = "dev1"; disp(v.Tag)');
dv_pr('set_tag_num', 'set(v, ''Tag'', 5)');
dv_px('set_userdata', 'v.UserData = {1}; disp(class(v.UserData))');
dv_px('set_eofcn', 'v.ErrorOccurredFcn = @disp; disp(class(v.ErrorOccurredFcn))');
dv_pr('set_eofcn_bad', 'set(v, ''ErrorOccurredFcn'', 5)');
dv_pr('find_tag', 'class(visadevfind("Tag", "dev1"))');
dv_pr('find_all', 'size(visadevfind)');
dv_pr('find_type', 'size(visadevfind("Type", "serial"))');

% writes and reads
dp(v, 'reset');
flush(v);
write(v, 1:4, "uint8");
dv_pr('written', 'v.NumBytesWritten');
dv_pr('recv', 'dp(v, ''recv'')');
write(v, [1 2]);
dv_pr('recv_default', 'dp(v, ''recv'')');
write(v, 258, "uint16");
dv_pr('recv_u16', 'dp(v, ''recv'')');
write(v, "AB");
dv_pr('recv_string', 'dp(v, ''recv'')');
write(v, 'CD', "char");
dv_pr('recv_char', 'dp(v, ''recv'')');
write(v, -1, "int8");
dv_pr('recv_neg', 'dp(v, ''recv'')');
dv_pr('write_300', 'write(v, 300)');
dv_pr('write_none', 'write(v)');
dv_pr('write_cell', 'write(v, {1})');
dv_pr('write_prec_bad', 'write(v, 1, "uint9")');
dp(v, 'send 0102030405');
pause(0.3);
dv_pr('read2', 'read(v, 2)');
dv_pr('read_u16', 'read(v, 1, "uint16")');
dv_pr('read_rest', 'read(v, 1)');
dp(v, 'send 41420A4344');
pause(0.3);
dv_pr('read_through_lf', 'read(v, 5, "char")');
dp(v, 'send 41420A4344');
pause(0.3);
dv_pr('read_string', 'read(v, 5, "string")');
t0 = tic;
lastwarn('');
dv_pr('read_timeout', 'read(v, 3)');
dv_pr('read_timeout_took', 'round(toc(t0), 1)');
[m, id] = lastwarn;
dv_pr('read_timeout_warn', 'sprintf(''%s ## %s'', id, m)');
dp(v, 'send 0102');
pause(0.3);
lastwarn('');
dv_pr('read_partial', 'read(v, 5)');
[m, id] = lastwarn;
dv_pr('read_partial_warn', 'sprintf(''%s ## %s'', id, m)');
dv_pr('read_none', 'read(v)');
dv_pr('read_zero', 'read(v, 0)');
dv_pr('read_neg', 'read(v, -1)');
dv_pr('read_frac', 'read(v, 1.5)');
dv_pr('read_bad_prec', 'read(v, 1, "uint9")');
dv_pr('read_too_many', 'read(v, 1, "uint8", 3)');

% lines
dp(v, 'send 68690A');
pause(0.3);
dv_pr('readline', 'readline(v)');
dp(v, 'send 6120620A6320640A');
pause(0.3);
dv_pr('readline_1', 'readline(v)');
dv_pr('readline_2', 'readline(v)');
t0 = tic;
lastwarn('');
dv_pr('readline_timeout', 'readline(v)');
dv_pr('readline_timeout_took', 'round(toc(t0), 1)');
[m, id] = lastwarn;
dv_pr('readline_timeout_warn', 'sprintf(''%s ## %s'', id, m)');
dp(v, 'send 7878');
pause(0.3);
lastwarn('');
dv_pr('readline_partial', 'readline(v)');
[m, id] = lastwarn;
dv_pr('readline_partial_warn', 'sprintf(''%s ## %s'', id, m)');
writeline(v, "hello");
dv_pr('writeline_recv', 'dp(v, ''recv'')');
dv_pr('writeline_none', 'writeline(v)');
dv_pr('writeline_num', 'writeline(v, 5)');
configureTerminator(v, "CR");
dv_pr('term_cr', 'v.Terminator');
dp(v, 'send 410D420D');
pause(0.3);
dv_pr('readline_cr', 'readline(v)');
dv_pr('readline_cr2', 'readline(v)');
writeline(v, "x");
dv_pr('writeline_cr', 'dp(v, ''recv'')');
configureTerminator(v, "CR/LF");
dv_pr('term_crlf', 'v.Terminator');
dp(v, 'send 410D0A420A');
pause(0.3);
dv_pr('readline_crlf', 'readline(v)');
dv_pr('readline_crlf_lone_lf', 'readline(v)');
writeline(v, "y");
dv_pr('writeline_crlf', 'dp(v, ''recv'')');
configureTerminator(v, "CR", 10);
dv_pr('term_pair', 'v.Terminator');
configureTerminator(v, 35);
dv_pr('term_num', 'v.Terminator');
dp(v, 'send 41234223');
pause(0.3);
dv_pr('readline_num', 'readline(v)');
flush(v);
configureTerminator(v, "off");
dv_pr('term_off', 'v.Terminator');
dp(v, 'send 410A42');
pause(0.3);
lastwarn('');
dv_pr('readline_off', 'readline(v)');
[m, id] = lastwarn;
dv_pr('readline_off_warn', 'sprintf(''%s ## %s'', id, m)');
flush(v);
configureTerminator(v, "off", "CR");
dv_pr('term_off_cr', 'v.Terminator');
configureTerminator(v, "LF");
dv_pr('term_lf', 'v.Terminator');
dv_pr('term_bad', 'configureTerminator(v, "XY")');
dv_pr('term_256', 'configureTerminator(v, 256)');
dv_pr('term_none', 'configureTerminator(v)');
dv_pr('term_four', 'configureTerminator(v, "LF", "LF", "LF")');
dv_pr('term_off_off', 'configureTerminator(v, "off", "off")');
dv_pr('term_after_offoff', 'v.Terminator');
configureTerminator(v, "LF");
dp(v, 'on 3F0A 4F4B0A');
dv_pr('writeread', 'writeread(v, "?")');
t0 = tic;
dv_pr('writeread_timeout', 'writeread(v, "nope")');
dv_pr('writeread_timeout_took', 'round(toc(t0), 1)');
dv_pr('writeread_none', 'writeread(v)');
flush(v);
dp(v, 'reset');
writebinblock(v, 1:3, "uint8");
dv_pr('binblock_recv', 'dp(v, ''recv'')');
writebinblock(v, [1 2], "uint16", "HDR");
dv_pr('binblock_hdr_recv', 'dp(v, ''recv'')');
dp(v, 'send 2332303301020341');
pause(0.3);
dv_pr('readbinblock', 'readbinblock(v)');
dp(v, 'send 23323034010002000A');
pause(0.3);
dv_pr('readbinblock_u16', 'readbinblock(v, "uint16")');
dv_pr('readbinblock_after', 'read(v, 1)');
dv_pr('readbinblock_timeout', 'readbinblock(v)');

% pins
dp(v, 'reset');
setDTR(v, true);
setRTS(v, false);
dv_pr('peer_status1', 'dp(v, ''status'')');
setRTS(v, true);
dv_pr('peer_status2', 'dp(v, ''status'')');
dp(v, 'pins rts=1 dtr=0');
pause(0.2);
ps = getpinstatus(v);
dv_pr('pinstatus', 'ps');
dv_pr('pinstatus_class', 'class(ps.ClearToSend)');
dv_pr('pinstatus_cts', 'char(ps.ClearToSend)');
dv_pr('pinstatus_dsr', 'char(ps.DataSendReady)');
dv_pr('setdtr_bad', 'setDTR(v, "on")');
dv_pr('setdtr_none', 'setDTR(v)');
dv_pr('setrts_num', 'setRTS(v, 1)');
dv_pr('serialbreak', 'serialbreak(v)');

% VISA methods on a serial resource
dv_pr('visastatus', 'visastatus(v)');
dv_pr('visastatus2', '[r, s] = visastatus(v)');
dv_pr('visatrigger', 'visatrigger(v)');

% flush
dp(v, 'send 010203');
pause(0.3);
flush(v, "input");
dv_pr('after_flush_input', 'read(v, 1)');
dv_pr('flush_bad', 'flush(v, "both")');
dv_pr('flush_output', 'flush(v, "output")');
dp(v, 'send 010203');
pause(0.3);
flush(v);
dv_pr('after_flush', 'read(v, 1)');

% legacy
dp(v, 'reset');
flush(v);
lastwarn('');
dv_px('fprintf', 'fprintf(v, ''AB'')');
dv_pr('fprintf_recv', 'dp(v, ''recv'')');
dp(v, 'send 31320A');
pause(0.3);
dv_pr('fscanf', 'fscanf(v)');
dp(v, 'send 7A0A');
pause(0.3);
dv_pr('fgetl', 'fgetl(v)');
dp(v, 'on 513F0A 410A');
dv_pr('query', 'query(v, ''Q?'')');
dv_pr('clrdevice', 'clrdevice(v)');
dv_pr('fopen', 'fopen(v)');
dv_pr('fclose', 'fclose(v)');
dv_pr('eoscharcode', 'v.EOSCharCode');
configureTerminator(v, "CR", "LF");
dv_pr('eoscharcode_mismatch', 'v.EOSCharCode');
[m, id] = lastwarn;
dv_pr('eoscharcode_warn', 'sprintf(''%s ## %s'', id, m)');
configureTerminator(v, "LF");
dv_pr('bytesavailable', 'v.BytesAvailable');
dv_pr('status_legacy', 'v.Status');

% a second object, save, lifetime
dv_pr('second', 'visadev("ASRL20::INSTR")');
dv_pr('second_alias', 'visadev("COM20")');
f = [tempname '.mat'];
lastwarn('');
dv_px('save', 'save(f, ''v'')');
[m, id] = lastwarn;
dv_pr('save_warn', 'sprintf(''%s ## %s'', id, m)');
dv_px('load', 'S = load(f); disp(class(S.v)); disp(size(S.v))');
delete(f);
v2 = v;
delete(v);
dv_pr('isvalid', 'isvalid(v2)');
dv_pr('after_delete_prop', 'v2.BaudRate');
dv_pr('after_delete_read', 'read(v2, 1)');
dv_px('after_delete_disp', 'disp(v2)');
clear v v2
v = visadev("COM20", "Tag", "again");
dv_pr('by_alias', 'v.ResourceName');
dv_pr('by_alias_tag', 'v.Tag');
dv_pr('by_lower', 'size(visadev("asrl21::instr"))');
clear v
dv_pr('by_partial', 'visadev("ASRL2")');
