function u9b_json
% U9b probe: jsonencode and jsondecode as R2025b has them, which the uihtml bridge runs through.
% Headless.
here = fileparts(mfilename('fullpath'));
addpath(here);
enc = {1, -1, 0, -0, 0.1, 0.5, 1/3, pi, 100, 1e5, 1e15, 1e16, 1e17, 1e21, 1e22, 123456789, 1.5e300, 1e-5, 1e-6, 1e-7, 2^53, 2^53 + 2, ...
    realmin, realmax, eps, 5e-324, NaN, Inf, -Inf, [1 NaN Inf], single(pi), single(0.1), single(1e10), single(16777217), ...
    int8(-5), uint8(200), int16(300), int32(-7), int64(9007199254740993), intmax('int64'), intmin('int64'), intmax('uint64'), ...
    true, false, [true false], true(2), [], zeros(0, 3), zeros(3, 0), 1:3, (1:3)', [1 2; 3 4], magic(3), zeros(2, 2, 2), reshape(1:8, 2, 2, 2), ...
    zeros(1, 1, 2), zeros(2, 1, 2), '', 'a', 'abc', ['ab'; 'cd'], char(zeros(0, 3)), char(zeros(2, 0)), 'a"b\c/d', sprintf('t\tn\nr\r'), ...
    char(1), char(31), char(127), char(233), char(8364), char([55357 56832]), '<>&''', ...
    "", "s", ["a" "b"], ["a"; "b"], string(missing), ["a" missing], strings(0, 1), strings(2, 2), ...
    {}, {1}, {1, 'x'}, {1; 'x'}, {1, 'x'; 2, 'y'}, {[]}, {{}}, {{1, 2}}, cell(0, 3), {[1 2]; [3 4]}, ...
    struct(), struct('a', 1), struct('a', {}), struct('a', {1, 2}), struct('a', {1; 2}), struct('a', {1 2; 3 4}), ...
    struct('a', [1 2; 3 4]), struct('a', {{}}), struct('a', {{1, 2}}), struct('a', struct('b', [])), struct('x_1', 1, 'A', 2), ...
    datetime(2024, 1, 15), datetime(2024, 1, 15, 10, 30, 5), [datetime(2024, 1, 15) datetime(2024, 1, 16)], NaT, ...
    datetime(2024, 1, 15, 'TimeZone', 'UTC'), datetime(2024, 1, 15, 'Format', 'yyyy-MM-dd'), ...
    seconds(90), days(1.5), categorical({'a', 'b'}), categorical({'a'; 'b'}), categorical({'a', 'b'; 'c', 'a'}), ...
    table([1; 2], {'x'; 'y'}), table([1; 2], 'VariableNames', {'n'}), containers.Map({'k1', 'k2'}, {1, 'v'}), containers.Map(), ...
    containers.Map('KeyType', 'double', 'ValueType', 'any'), matlab.lang.OnOffSwitchState.on, ...
    @sin, 1 + 2i, sparse([1 0 2]), 1:0, {1, {2, {3}}}, struct('n', {struct('m', 1), struct('m', 2)})};
for k = 1:numel(enc)
    v = enc{k};
    try
        t = jsonencode(v);
        fprintf('enc %-50s => %s\n', deep(v), t);
    catch e
        fprintf('enc %-50s => ERR %s | %s\n', deep(v), e.identifier, oneline(e.message));
    end
end
% options
opts = {{NaN, 'ConvertInfAndNaN', false}, {[1 Inf -Inf], 'ConvertInfAndNaN', false}, {struct('a', [1 2], 'b', 'x'), 'PrettyPrint', true}, ...
    {{1, {2}}, 'PrettyPrint', true}, {[1 2; 3 4], 'PrettyPrint', true}, {struct(), 'PrettyPrint', true}, {[], 'PrettyPrint', true}, ...
    {1, 'Bogus', true}, {1, 'PrettyPrint'}, {1, 'prettyprint', true}, {1, 'Pretty', true}, {1, 'PrettyPrint', 'yes'}, ...
    {struct('a', {}), 'PrettyPrint', true}, {{}, 'PrettyPrint', true}, {struct('a', {1, 2}), 'PrettyPrint', true}};
for k = 1:numel(opts)
    o = opts{k};
    try
        t = jsonencode(o{:});
        fprintf('encopt %-40s => %s\n', strjoin(cellfun(@deep, o, 'UniformOutput', false), ' '), strrep(t, newline, '\n'));
    catch e
        fprintf('encopt %-40s => ERR %s | %s\n', strjoin(cellfun(@deep, o, 'UniformOutput', false), ' '), e.identifier, oneline(e.message));
    end
end

dec = {'1', '-0', '1.5e3', '1E-2', '123456789012345678', '1e400', '-1e400', '1e-400', 'true', 'null', '"s"', '""', '"a\nb"', '"é"', '"😀"', ...
    '[]', '[1]', '[1,2,3]', '[[1,2],[3,4]]', '[[1],[2]]', '[[1,2]]', '[[1,2],[3]]', '[[1,2],[3,null]]', '[[[1,2],[3,4]],[[5,6],[7,8]]]', ...
    '[[[1,2]],[[3,4]]]', '[[[1],[2]],[[3],[4]]]', '[[],[]]', '[[]]', '[[[]]]', '[1,null]', '[null]', '[null,null]', '[true,false]', ...
    '[true,null]', '[true,1]', '[[true],[false]]', '[[true,false],[1,0]]', '["a","b"]', '["a"]', '["a",null]', '[["a","b"],["c","d"]]', ...
    '[1,"a"]', '[1,[2]]', '[1,[2,3]]', '[[1,2],"a"]', '{}', '[{}]', '[{},{}]', '{"a":1}', '[{"a":1},{"a":2}]', '[{"a":1},{"b":2}]', ...
    '[{"a":1,"b":2},{"b":3,"a":4}]', '[{"a":[1,2]},{"a":[3,4]}]', '[{"a":1},{"a":"x"}]', '[[{"a":1}],[{"a":2}]]', '[[{"a":1},{"a":2}],[{"a":3},{"a":4}]]', ...
    '{"a":[]}', '{"a":{}}', '{"a":null}', '{"1a":1}', '{"a b":1}', '{"":1}', '{"a-b":1}', '{"_a":1}', '{"a":1,"a":2}', ...
    '{"a b c":1}', '{"aB":1,"a b":2}', '{"if":1}', '{"end":1}', '{"x":1,"X":2}', '{"é":1}', '{"a.b":1}', '{" a":1}', '{"a ":1}', ...
    '{"abcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghijabcdefghij":1}', '[1,true]', '[[1,2],[true,false]]', ...
    ' [1, 2] ', '[1,2,]', '{"a":1,}', '', '   ', 'nul', '[1 2]', '{"a"}', 'NaN', '"unterminated', '1 2', '[01]'};
for k = 1:numel(dec)
    t = dec{k};
    try
        v = jsondecode(t);
        fprintf('dec %-40s => %s\n', t, deep(v));
    catch e
        fprintf('dec %-40s => ERR %s | %s\n', t, e.identifier, oneline(e.message));
    end
end
decopts = {{'{"1a":1}', 'makeValidName', false}, {'{"a b":1}', 'makeValidName', false}, {'{"1a":1}', 'MakeValidName', false}, ...
    {'{"a":1}', 'makeValidName', true}, {'{"a":1}', 'Bogus', true}, {'[1,2]', 'makeValidName'}};
for k = 1:numel(decopts)
    o = decopts{k};
    try
        v = jsondecode(o{:});
        fprintf('decopt %-40s => %s\n', strjoin(cellfun(@deep, o, 'UniformOutput', false), ' '), deep(v));
    catch e
        fprintf('decopt %-40s => ERR %s | %s\n', strjoin(cellfun(@deep, o, 'UniformOutput', false), ' '), e.identifier, oneline(e.message));
    end
end
bad = {@() jsonencode(), @() jsondecode(), @() jsondecode(5), @() jsondecode("[1]"), @() jsondecode({'1'}), @() jsondecode(['1'; '2']), ...
    @() jsonencode(1, 2), @() jsondecode('1', 'a'), @() jsonencode(struct('a', @sin)), @() jsonencode({1, @sin})};
for k = 1:numel(bad)
    try
        v = bad{k}();
        fprintf('bad %s => %s\n', func2str(bad{k}), deep(v));
    catch e
        fprintf('bad %s => ERR %s | %s\n', func2str(bad{k}), e.identifier, oneline(e.message));
    end
end
end
