#!/usr/bin/env python3
"""Writes src/JGraph.Scripting/Jgs/JgsBuiltinOutputCounts.cs from nargout-r2025b.tsv (V9, ADR 0170).

    python tools/matlab-checklist/gen-builtin-outputs.py

The TSV is what tools/matlab-checklist/audit-nargout.m recorded in R2025b for every name the
catalog registers: `name<tab>nargout<tab>exist`. A name with a fixed count (nargout >= 0) that
MATLAB holds as a built-in (exist 5, or a MEX file, 3) or as a file (2, or a P-file, 6) gets a row;
a variable count (-1, -2), a name MATLAB does not have, and the measured exception below are left
out, so a call of them is never refused for its output count. The engine applies a row's count only
where it cannot be wrong about its own builtin: when the count is zero, or when the builtin has no
multi-output body (BuiltinFunction.MaxOutputs says why: nargout under-reports fgets, sees the tf
constructor rather than the digitalFilter overload, and cannot see triplot's extra outputs).
"""

from __future__ import annotations

import io
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
TSV = REPO / "tools/matlab-checklist/nargout-r2025b.tsv"
OUT = REPO / "src/JGraph.Scripting/Jgs/JgsBuiltinOutputCounts.cs"

# nargout reports no output for pause, and R2025b still binds `x = pause(0)` (measured, V9's
# probe 3); the table must not refuse what MATLAB accepts.
EXCEPTIONS = {"pause"}

BUILTIN_KINDS = {"5", "3"}
FILE_KINDS = {"2", "6"}


def main() -> int:
    rows: list[tuple[str, int, bool]] = []
    for raw in TSV.read_text(encoding="utf-8").splitlines():
        if not raw.strip():
            continue
        name, count, kind = raw.split("\t")
        if name in EXCEPTIONS or count.startswith("ERR") or int(count) < 0:
            continue
        if kind in BUILTIN_KINDS:
            rows.append((name, int(count), False))
        elif kind in FILE_KINDS:
            rows.append((name, int(count), True))
    rows.sort()

    lines = [
        "// <auto-generated> tools/matlab-checklist/gen-builtin-outputs.py from nargout-r2025b.tsv; do not edit. </auto-generated>",
        "namespace JGraph.Scripting.Jgs;",
        "",
        "/// <summary>",
        "/// R2025b's <c>nargout</c> for every registered builtin whose output count is fixed (V9, ADR 0170):",
        "/// the most outputs a call may ask of it, and whether MATLAB holds the name as a file (which",
        "/// refuses excess outputs as <c>MATLAB:TooManyOutputs</c>) or as a built-in (<c>MATLAB:maxlhs</c>).",
        "/// A name absent here has a variable count, or is not MATLAB's; a call of it is never refused for",
        "/// its output count. A count applies where it cannot be wrong about this build's own builtin: when",
        "/// it is zero, or when the builtin has only a single-output body (<see cref=\"BuiltinFunction.MaxOutputs\"/>).",
        "/// Generated by <c>tools/matlab-checklist/gen-builtin-outputs.py</c> from the audit",
        "/// <c>tools/matlab-checklist/audit-nargout.m</c> recorded, less the measured exception the generator",
        "/// names.",
        "/// </summary>",
        "internal static class JgsBuiltinOutputCounts",
        "{",
        "    /// <summary>The fixed output count and file-ness of <paramref name=\"name\"/>, or false.</summary>",
        "    public static bool TryGet(string name, out int count, out bool isFile)",
        "    {",
        "        if (Table.TryGetValue(name, out (int Count, bool IsFile) entry))",
        "        {",
        "            (count, isFile) = entry;",
        "            return true;",
        "        }",
        "",
        "        count = 0;",
        "        isFile = false;",
        "        return false;",
        "    }",
        "",
        "    private static readonly Dictionary<string, (int Count, bool IsFile)> Table = new(StringComparer.Ordinal)",
        "    {",
    ]
    for name, count, is_file in rows:
        lines.append(f"        [\"{name}\"] = ({count}, {'true' if is_file else 'false'}),")
    lines += ["    };", "}", ""]
    with io.open(OUT, "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(lines))
    zero = sum(1 for _, c, _ in rows if c == 0)
    print(f"{len(rows)} rows ({zero} with no output) -> {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
