#!/usr/bin/env python3
"""Collects every divergence the ADRs record into one index.

Sixty-odd deliberate differences from MATLAB are written down across ADRs 0005–0069, each in the
milestone that introduced it and nowhere else. That is the right place to *decide* one and the wrong
place to *find* one: nothing lists them, so a script author has no page to check and a later
milestone can undo one without noticing.

This reads every ADR, finds the sections whose heading names divergences, and lifts each bullet's
bolded lead — the claim — into `docs/matlab-divergences.md`, with the ADR it came from.

**It harvests, it does not verify.** A row here says an ADR recorded this, not that the build still
behaves that way; `stess_41.m` is where a divergence gets checked against the running interpreter,
and it covers a chosen subset rather than all of them. The generated file says both of those things
in its own text, because an index that looks authoritative and is not is worse than no index.

Usage:
    python harvest-divergences.py [--adr docs/adr] [--out docs/matlab-divergences.md]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# Three ADR generations wrote these three ways, and the harvest has to read all three or the index
# is a claim about the newest milestones dressed up as a claim about the project:
#   * a heading whose text names divergences (M60 onward),
#   * a bolded lead-in paragraph, '**Divergences**, recorded in …:' (M54–M56),
#   * a heading plus plain unbolded bullets (M23).
HEADING = re.compile(r"^#{2,4}\s+.*diverg", re.IGNORECASE)
LEAD_IN = re.compile(r"^\*\*Divergences?\*\*", re.IGNORECASE)
ANY_HEADING = re.compile(r"^#{1,6}\s")
# A bullet whose first sentence is bolded: the house style for one recorded difference.
BULLET = re.compile(r"^\s*[-*]\s+\*\*(.+?)\*\*(.*)$", re.DOTALL)


def sections(text: str) -> list[list[str]]:
    """The line blocks a divergence heading or lead-in opens, up to the next heading or lead-in."""
    found: list[list[str]] = []
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        if HEADING.match(lines[index]) or LEAD_IN.match(lines[index]):
            index += 1
            block: list[str] = []
            while (index < len(lines)
                   and not ANY_HEADING.match(lines[index])
                   # A bolded paragraph that is not a bullet ends the run: '**Found on the way…**'
                   # follows the divergences in the M56-era ADRs and is a different kind of note.
                   and not (lines[index].startswith("**") and not lines[index].lstrip().startswith("-"))):
                block.append(lines[index])
                index += 1
            found.append(block)
        else:
            index += 1
    return found


def claims(block: list[str]) -> list[str]:
    """
    One line per bullet: its bolded lead where it has one, and the whole bullet where it does not.

    M23's divergences are plain bullets with no bold, so reading only bolded leads would drop the
    five oldest recorded differences in the project and report the index as complete without them.
    """
    text = "\n".join(block)
    out: list[str] = []
    for chunk in re.split(r"\n(?=\s*[-*]\s)", text):
        if not chunk.strip().startswith(("-", "*")):
            continue
        if match := BULLET.match(chunk):
            out.append(" ".join(match.group(1).split()))
        else:
            plain = " ".join(chunk.strip().lstrip("-*").split())
            if plain:
                # Trim to the first sentence: the index wants the claim, the ADR holds the reasoning.
                out.append(re.split(r"(?<=[.;])\s", plain)[0])
    return out


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--adr", type=Path, default=REPO / "docs/adr")
    parser.add_argument("--out", type=Path, default=REPO / "docs/matlab-divergences.md")
    args = parser.parse_args()

    rows: list[tuple[str, str, str]] = []
    for path in sorted(args.adr.glob("*.md")):
        number = path.name.split("-", 1)[0]
        title = path.name.split("-", 1)[1].removesuffix(".md").replace("-", " ")
        for block in sections(path.read_text(encoding="utf-8")):
            for claim in claims(block):
                rows.append((number, title, claim))

    lines = [
        "# Recorded divergences from MATLAB",
        "",
        "Generated by `tools/matlab-checklist/harvest-divergences.py` from the ADRs themselves.",
        "Re-run it after writing an ADR that records one.",
        "",
        f"**{len(rows)} divergences** are recorded across "
        f"{len({number for number, _, _ in rows})} ADRs. Each is a difference from MATLAB that was",
        "decided rather than overlooked; the ADR named beside it holds the reasoning.",
        "",
        "## What this list is",
        "",
        "It is a **harvest, not a verification**. A row says an ADR recorded this behaviour when it",
        "was written — not that the build still behaves that way today. `stess_41.m` is where a",
        "divergence is checked against the running interpreter, and it covers a chosen subset of this",
        "list rather than all of it. Anything here that `stess_41.m` does not assert could have been",
        "silently fixed, or silently worsened, since the ADR that recorded it.",
        "",
        "It is also **not every difference**. It collects the ones an ADR wrote under a heading that",
        "names divergences, in the house style of a bolded lead sentence. A limit recorded in prose",
        "elsewhere in an ADR, or in a code comment, or nowhere at all, is not here. M69's syntax-form",
        "probe found gaps recorded in none of the three.",
        "",
        "## The index",
        "",
        "| ADR | Milestone | Divergence |",
        "|---|---|---|",
    ]
    for number, title, claim in rows:
        lines.append(f"| [{number}](adr/{number}-{title.replace(' ', '-')}.md) | {title} | {claim} |")

    lines.append("")
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{args.out.name}: {len(rows)} divergences from "
          f"{len({number for number, _, _ in rows})} ADRs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
